# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Configuration module for CodeWeaver."""

from codeweaver.config.language import CustomDelimiter, CustomLanguage
from codeweaver.config.logging import (
    FilterID,
    FiltersDict,
    FormatterID,
    FormattersDict,
    HandlerID,
    HandlersDict,
    LoggerName,
    LoggersDict,
    LoggingConfigDict,
    LoggingSettings,
    SerializableLoggingFilter,
)
from codeweaver.config.middleware import (
    AVAILABLE_MIDDLEWARE,
    ErrorHandlingMiddlewareSettings,
    LoggingMiddlewareSettings,
    MiddlewareOptions,
    RateLimitingMiddlewareSettings,
    RetryMiddlewareSettings,
)
from codeweaver.config.providers import (
    AgentModelSettings,
    AgentProviderSettings,
    AWSProviderSettings,
    AzureCohereProviderSettings,
    AzureOpenAIProviderSettings,
    DataProviderSettings,
    EmbeddingModelSettings,
    EmbeddingProviderSettings,
    FastembedGPUProviderSettings,
    ModelString,
    ProviderSettingsDict,
    ProviderSettingsView,
    ProviderSpecificSettings,
    RerankingModelSettings,
    RerankingProviderSettings,
)
from codeweaver.config.settings import (
    CodeWeaverSettings,
    CodeWeaverSettingsDict,
    FastMcpServerSettings,
    FileFilterSettings,
    get_settings,
    get_settings_map,
    update_settings,
)
from codeweaver.config.types import (
    ConnectionConfiguration,
    ConnectionRateLimitConfig,
    FastMcpHttpRunArgs,
    FastMcpServerSettingsDict,
    FileFilterSettingsDict,
    RignoreSettings,
    UvicornServerSettings,
    UvicornServerSettingsDict,
    default_config_file_locations,
)


__all__ = (
    "AVAILABLE_MIDDLEWARE",
    "AWSProviderSettings",
    "AgentModelSettings",
    "AgentProviderSettings",
    "AzureCohereProviderSettings",
    "AzureOpenAIProviderSettings",
    "CodeWeaverSettings",
    "CodeWeaverSettingsDict",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "CustomDelimiter",
    "CustomLanguage",
    "DataProviderSettings",
    "EmbeddingModelSettings",
    "EmbeddingProviderSettings",
    "ErrorHandlingMiddlewareSettings",
    "FastMcpHttpRunArgs",
    "FastMcpServerSettings",
    "FastMcpServerSettingsDict",
    "FastembedGPUProviderSettings",
    "FileFilterSettings",
    "FileFilterSettingsDict",
    "FilterID",
    "FiltersDict",
    "FormatterID",
    "FormattersDict",
    "HandlerID",
    "HandlersDict",
    "LoggerName",
    "LoggersDict",
    "LoggingConfigDict",
    "LoggingMiddlewareSettings",
    "LoggingSettings",
    "MiddlewareOptions",
    "ModelString",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "ProviderSpecificSettings",
    "RateLimitingMiddlewareSettings",
    "RerankingModelSettings",
    "RerankingProviderSettings",
    "RetryMiddlewareSettings",
    "RignoreSettings",
    "SerializableLoggingFilter",
    "UvicornServerSettings",
    "UvicornServerSettingsDict",
    "default_config_file_locations",
    "get_settings",
    "get_settings_map",
    "update_settings",
)
