# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
#:tombi schema.strict = false

[tools]
bun = "latest"
node = "24"

[env]

[tasks]
astro = "bun run astro"
build = "bun run build"
dev = "bun run dev"
preview = "bun run preview"
sync = "bun install"

[tasks.gen-api-docs]
tools.uv = "latest"
run = "uvx ../scripts/gen_api_docs.py"

[tasks.gen-cloudflare-types]
tools.bun = "latest"
run = "bunx wrangler types"
dir = "./"
