# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Package-level lazy imports for codeweaver.providers.config."""

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core.utils.lazy_import import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.providers.config.clients import (
        BedrockClientOptions,
        ClientOptions,
        CohereClientOptions,
        FastEmbedClientOptions,
        GoogleClientOptions,
        GrpcParams,
        HFInferenceClientOptions,
        MistralClientOptions,
        OpenAIClientOptions,
        QdrantClientOptions,
        SentenceTransformersClientOptions,
        VoyageClientOptions,
        discriminate_azure_embedding_client_options,
    )
    from codeweaver.providers.config.embedding import (
        DATATYPE_FIELDS,
        DIMENSION_FIELDS,
        INCOMPATIBLE_FIELDS,
        BaseEmbeddingConfig,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingRequestParams,
        BedrockTitanV2ConfigDict,
        EmbeddingConfigT,
        FastEmbedEmbeddingConfig,
        FastEmbedSparseEmbeddingConfig,
        GoogleEmbeddingConfig,
        GoogleEmbeddingRequestParams,
        HuggingFaceEmbeddingConfig,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SentenceTransformersSparseEmbeddingConfig,
        SerializedEmbeddingOptionsDict,
        SparseEmbeddingConfigT,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
    )
    from codeweaver.providers.config.kinds import (
        AgentProviderSettings,
        AzureEmbeddingProviderSettings,
        AzureProviderMixin,
        BaseEmbeddingProviderSettings,
        BaseProviderSettings,
        BaseProviderSettingsDict,
        BedrockEmbeddingProviderSettings,
        BedrockProviderMixin,
        BedrockRerankingProviderSettings,
        CollectionConfig,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        DataProviderSettings,
        EmbeddingProviderSettings,
        FastEmbedEmbeddingProviderSettings,
        FastEmbedProviderMixin,
        FastEmbedRerankingProviderSettings,
        FastEmbedSparseEmbeddingProviderSettings,
        MemoryConfig,
        MemoryVectorStoreProviderSettings,
        QdrantVectorStoreProviderSettings,
        RerankingProviderSettings,
        SparseEmbeddingProviderSettings,
        VectorStoreProviderSettings,
    )
    from codeweaver.providers.config.profiles import HAS_ST, ProviderConfigProfile, ProviderProfile
    from codeweaver.providers.config.providers import (
        HAS_ANTHROPIC,
        AllDefaultProviderSettings,
        DeterminedDefaults,
        ProviderNameMap,
        ProviderSettings,
        ProviderSettingsDict,
        merge_agent_model_settings,
    )
    from codeweaver.providers.config.reranking import (
        BaseRerankingConfig,
        BedrockRerankingConfig,
        BedrockRerankingModelConfig,
        BedrockRerankingOptionsDict,
        CohereRerankingConfig,
        CohereRerankingOptionsDict,
        FastEmbedRerankingConfig,
        FastEmbedRerankingOptionsDict,
        RerankingConfigT,
        SentenceTransformersRerankingConfig,
        SentenceTransformersRerankingOptionsDict,
        SerializedRerankingOptionsDict,
        VoyageRerankingConfig,
        VoyageRerankingOptionsDict,
    )
    from codeweaver.providers.config.root_settings import CodeWeaverProviderSettings
    from codeweaver.providers.config.types import CohereRequestOptionsDict, HttpxClientParams

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "DATATYPE_FIELDS": (__spec__.parent, "embedding"),
    "DIMENSION_FIELDS": (__spec__.parent, "embedding"),
    "HAS_ANTHROPIC": (__spec__.parent, "providers"),
    "HAS_ST": (__spec__.parent, "profiles"),
    "INCOMPATIBLE_FIELDS": (__spec__.parent, "embedding"),
    "AgentProviderSettings": (__spec__.parent, "kinds"),
    "AllDefaultProviderSettings": (__spec__.parent, "providers"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "AzureProviderMixin": (__spec__.parent, "kinds"),
    "BaseEmbeddingConfig": (__spec__.parent, "embedding"),
    "BaseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BaseProviderSettings": (__spec__.parent, "kinds"),
    "BaseProviderSettingsDict": (__spec__.parent, "kinds"),
    "BaseRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockClientOptions": (__spec__.parent, "clients"),
    "BedrockCohereConfigDict": (__spec__.parent, "embedding"),
    "BedrockEmbeddingConfig": (__spec__.parent, "embedding"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "BedrockProviderMixin": (__spec__.parent, "kinds"),
    "BedrockRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockRerankingModelConfig": (__spec__.parent, "reranking"),
    "BedrockRerankingOptionsDict": (__spec__.parent, "reranking"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "embedding"),
    "ClientOptions": (__spec__.parent, "clients"),
    "CodeWeaverProviderSettings": (__spec__.parent, "root_settings"),
    "CohereClientOptions": (__spec__.parent, "clients"),
    "CohereRequestOptionsDict": (__spec__.parent, "types"),
    "CohereRerankingConfig": (__spec__.parent, "reranking"),
    "CohereRerankingOptionsDict": (__spec__.parent, "reranking"),
    "CollectionConfig": (__spec__.parent, "kinds"),
    "ConnectionConfiguration": (__spec__.parent, "kinds"),
    "ConnectionRateLimitConfig": (__spec__.parent, "kinds"),
    "DataProviderSettings": (__spec__.parent, "kinds"),
    "DeterminedDefaults": (__spec__.parent, "providers"),
    "EmbeddingConfigT": (__spec__.parent, "embedding"),
    "EmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedClientOptions": (__spec__.parent, "clients"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedProviderMixin": (__spec__.parent, "kinds"),
    "FastEmbedRerankingConfig": (__spec__.parent, "reranking"),
    "FastEmbedRerankingOptionsDict": (__spec__.parent, "reranking"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "GoogleClientOptions": (__spec__.parent, "clients"),
    "GoogleEmbeddingConfig": (__spec__.parent, "embedding"),
    "GoogleEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "GrpcParams": (__spec__.parent, "clients"),
    "HFInferenceClientOptions": (__spec__.parent, "clients"),
    "HttpxClientParams": (__spec__.parent, "types"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "embedding"),
    "MemoryConfig": (__spec__.parent, "kinds"),
    "MemoryVectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "MistralClientOptions": (__spec__.parent, "clients"),
    "MistralEmbeddingConfig": (__spec__.parent, "embedding"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "OpenAIClientOptions": (__spec__.parent, "clients"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "embedding"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "ProviderConfigProfile": (__spec__.parent, "profiles"),
    "ProviderProfile": (__spec__.parent, "profiles"),
    "ProviderNameMap": (__spec__.parent, "providers"),
    "ProviderSettings": (__spec__.parent, "providers"),
    "ProviderSettingsDict": (__spec__.parent, "providers"),
    "QdrantClientOptions": (__spec__.parent, "clients"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "RerankingConfigT": (__spec__.parent, "reranking"),
    "RerankingProviderSettings": (__spec__.parent, "kinds"),
    "SentenceTransformersClientOptions": (__spec__.parent, "clients"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "embedding"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "embedding"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "reranking"),
    "SentenceTransformersRerankingOptionsDict": (__spec__.parent, "reranking"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "reranking"),
    "SparseEmbeddingConfigT": (__spec__.parent, "embedding"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "VectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "VoyageClientOptions": (__spec__.parent, "clients"),
    "VoyageEmbeddingConfig": (__spec__.parent, "embedding"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "VoyageRerankingConfig": (__spec__.parent, "reranking"),
    "VoyageRerankingOptionsDict": (__spec__.parent, "reranking"),
    "discriminate_azure_embedding_client_options": (__spec__.parent, "clients"),
    "merge_agent_model_settings": (__spec__.parent, "providers"),
})

__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "DATATYPE_FIELDS",
    "DIMENSION_FIELDS",
    "HAS_ANTHROPIC",
    "HAS_ST",
    "INCOMPATIBLE_FIELDS",
    "AgentProviderSettings",
    "AllDefaultProviderSettings",
    "AzureEmbeddingProviderSettings",
    "AzureProviderMixin",
    "BaseEmbeddingConfig",
    "BaseEmbeddingProviderSettings",
    "BaseProviderSettings",
    "BaseProviderSettings",
    "BaseProviderSettingsDict",
    "BaseProviderSettingsDict",
    "BaseRerankingConfig",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingModelConfig",
    "BedrockRerankingOptionsDict",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CohereClientOptions",
    "CohereRequestOptionsDict",
    "CohereRerankingConfig",
    "CohereRerankingOptionsDict",
    "CollectionConfig",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "DataProviderSettings",
    "DeterminedDefaults",
    "EmbeddingConfigT",
    "EmbeddingProviderSettings",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingOptionsDict",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GoogleEmbeddingRequestParams",
    "GrpcParams",
    "HFInferenceClientOptions",
    "HttpxClientParams",
    "HuggingFaceEmbeddingConfig",
    "MemoryConfig",
    "MemoryVectorStoreProviderSettings",
    "MistralClientOptions",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "OpenAIClientOptions",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "ProviderConfigProfile",
    "ProviderNameMap",
    "ProviderProfile",
    "ProviderSettings",
    "ProviderSettingsDict",
    "QdrantClientOptions",
    "QdrantVectorStoreProviderSettings",
    "RerankingConfigT",
    "RerankingProviderSettings",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersRerankingOptionsDict",
    "SentenceTransformersSparseEmbeddingConfig",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingProviderSettings",
    "VectorStoreProviderSettings",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageRerankingConfig",
    "VoyageRerankingOptionsDict",
    "discriminate_azure_embedding_client_options",
    "get_profile",
    "get_profile",
    "get_profile",
    "merge_agent_model_settings",
)


def __dir__() -> list[str]:
    return list(__all__)
