"""Provider configuration exports."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.providers.config.clients import (
        BedrockClientOptions,
        ClientOptions,
        CohereClientOptions,
        FastEmbedClientOptions,
        GeneralEmbeddingClientOptionsType,
        GeneralRerankingClientOptionsType,
        GoogleClientOptions,
        GrpcParams,
        HFInferenceClientOptions,
        HttpxClientParams,
        OpenAIClientOptions,
        QdrantClientOptions,
        SentenceTransformersClientOptions,
        VoyageClientOptions,
    )
    from codeweaver.providers.config.embedding import (
        DATATYPE_FIELDS,
        DIMENSION_FIELDS,
        BaseEmbeddingConfig,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingRequestParams,
        BedrockTitanV2ConfigDict,
        EmbeddingConfigT,
        FastEmbedEmbeddingConfig,
        FastEmbedSparseEmbeddingConfig,
        GoogleEmbeddingConfig,
        HuggingFaceEmbeddingConfig,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SentenceTransformersSparseEmbeddingConfig,
        SerializedEmbeddingOptionsDict,
        SparseEmbeddingConfigT,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
    )
    from codeweaver.providers.config.kinds import (
        AgentProviderSettings,
        AzureEmbeddingProviderSettings,
        BaseProviderSettings,
        BaseProviderSettingsDict,
        BedrockEmbeddingProviderSettings,
        BedrockRerankingProviderSettings,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        DataProviderSettings,
        EmbeddingProviderSettings,
        FastEmbedEmbeddingProviderSettings,
        FastEmbedRerankingProviderSettings,
        FastEmbedSparseEmbeddingProviderSettings,
        ModelString,
        QdrantVectorStoreProviderSettings,
        RerankingProviderSettings,
        SparseEmbeddingProviderSettings,
        VectorConfig,
        VectorStoreProviderSettings,
    )
    from codeweaver.providers.config.profiles import get_profile
    from codeweaver.providers.config.providers import (
        AgentProviderSettingsType,
        AllDefaultProviderSettings,
        DataProviderSettingsType,
        EmbeddingProviderSettingsType,
        ProviderSettings,
        ProviderSettingsDict,
        ProviderSettingsView,
        RerankingProviderSettingsType,
        VectorStoreProviderSettingsType,
    )
    from codeweaver.providers.config.reranking import (
        BaseRerankingConfig,
        BedrockRerankingConfig,
        CohereRerankingConfig,
        FastEmbedRerankingConfig,
        RerankingConfigT,
        SentenceTransformersRerankingConfig,
        SerializedRerankingOptionsDict,
        VoyageRerankingConfig,
    )
    from codeweaver.providers.config.root_settings import CodeWeaverProviderSettings


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AgentProviderSettings": (__spec__.parent, "kinds"),
    "AgentProviderSettingsType": (__spec__.parent, "providers"),
    "AllDefaultProviderSettings": (__spec__.parent, "providers"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BaseEmbeddingConfig": (__spec__.parent, "embedding"),
    "BaseProviderSettings": (__spec__.parent, "kinds"),
    "BaseProviderSettingsDict": (__spec__.parent, "kinds"),
    "BaseRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockClientOptions": (__spec__.parent, "clients"),
    "BedrockCohereConfigDict": (__spec__.parent, "embedding"),
    "BedrockEmbeddingConfig": (__spec__.parent, "embedding"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "BedrockRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "embedding"),
    "ClientOptions": (__spec__.parent, "clients"),
    "CodeWeaverProviderSettings": (__spec__.parent, "root_settings"),
    "CohereClientOptions": (__spec__.parent, "clients"),
    "CohereRerankingConfig": (__spec__.parent, "reranking"),
    "CollectionConfig": (__spec__.parent, "kinds"),
    "ConnectionConfiguration": (__spec__.parent, "kinds"),
    "ConnectionRateLimitConfig": (__spec__.parent, "kinds"),
    "DATATYPE_FIELDS": (__spec__.parent, "embedding"),
    "DIMENSION_FIELDS": (__spec__.parent, "embedding"),
    "DataProviderSettings": (__spec__.parent, "kinds"),
    "DataProviderSettingsType": (__spec__.parent, "providers"),
    "EmbeddingConfigT": (__spec__.parent, "embedding"),
    "EmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "EmbeddingProviderSettingsType": (__spec__.parent, "providers"),
    "FastEmbedClientOptions": (__spec__.parent, "clients"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedRerankingConfig": (__spec__.parent, "reranking"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "GeneralEmbeddingClientOptionsType": (__spec__.parent, "clients"),
    "GeneralRerankingClientOptionsType": (__spec__.parent, "clients"),
    "GoogleClientOptions": (__spec__.parent, "clients"),
    "GoogleEmbeddingConfig": (__spec__.parent, "embedding"),
    "GrpcParams": (__spec__.parent, "clients"),
    "HFInferenceClientOptions": (__spec__.parent, "clients"),
    "HttpxClientParams": (__spec__.parent, "clients"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "embedding"),
    "MemoryConfig": (__spec__.parent, "kinds"),
    "MistralEmbeddingConfig": (__spec__.parent, "embedding"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "ModelString": (__spec__.parent, "kinds"),
    "OpenAIClientOptions": (__spec__.parent, "clients"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "embedding"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "ProviderSettings": (__spec__.parent, "providers"),
    "ProviderSettingsDict": (__spec__.parent, "providers"),
    "ProviderSettingsView": (__spec__.parent, "providers"),
    "QdrantClientOptions": (__spec__.parent, "clients"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "RerankingConfigT": (__spec__.parent, "reranking"),
    "RerankingProviderSettings": (__spec__.parent, "kinds"),
    "RerankingProviderSettingsType": (__spec__.parent, "providers"),
    "SentenceTransformersClientOptions": (__spec__.parent, "clients"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "embedding"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "embedding"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "reranking"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "reranking"),
    "SparseEmbeddingConfigT": (__spec__.parent, "embedding"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "VectorConfig": (__spec__.parent, "kinds"),
    "VectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "VectorStoreProviderSettingsType": (__spec__.parent, "providers"),
    "VoyageClientOptions": (__spec__.parent, "clients"),
    "VoyageEmbeddingConfig": (__spec__.parent, "embedding"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "VoyageRerankingConfig": (__spec__.parent, "reranking"),
    "get_profile": (__spec__.parent, "profiles"),
})


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "DATATYPE_FIELDS",
    "DIMENSION_FIELDS",
    "AgentProviderSettings",
    "AgentProviderSettingsType",
    "AllDefaultProviderSettings",
    "AzureEmbeddingProviderSettings",
    "AzureProviderMixin",
    "BaseEmbeddingConfig",
    "BaseProviderSettings",
    "BaseProviderSettingsDict",
    "BaseRerankingConfig",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CohereClientOptions",
    "CohereProviderEmbeddingConfig",
    "CohereRerankingConfig",
    "CollectionConfig",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "DataProviderSettings",
    "DataProviderSettingsType",
    "EmbeddingConfigT",
    "EmbeddingProviderSettings",
    "EmbeddingProviderSettingsType",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "GeneralEmbeddingClientOptionsType",
    "GeneralRerankingClientOptionsType",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GrpcParams",
    "HFInferenceClientOptions",
    "HttpxClientParams",
    "HuggingFaceEmbeddingConfig",
    "MemoryConfig",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "ModelString",
    "OpenAIClientOptions",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "ProviderSettings",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "QdrantClientOptions",
    "QdrantVectorStoreProviderSettings",
    "RerankingConfigT",
    "RerankingProviderSettings",
    "RerankingProviderSettingsType",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersSparseEmbeddingConfig",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingProviderSettings",
    "VectorConfig",
    "VectorStoreProviderSettings",
    "VectorStoreProviderSettingsType",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageRerankingConfig",
    "get_profile",
)


def __dir__() -> list[str]:
    return list(__all__)
