# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Package-level lazy imports for codeweaver.providers.config package.

## Provider Configuration, Settings, and Options

This package provides comprehensive configuration classes, types, and utilities for managing provider settings across various categories, including:
- **Agent Providers**: Configuration for LLM-based agents.
- **Data Providers**: Configuration for tools and data sources.
- **Embedding Providers**: Configuration for models that generate vector embeddings.
- **Sparse Embedding Providers**: Configuration for models that generate sparse vector embeddings.
- **Reranking Providers**: Configuration for models that perform reranking of results.
- **Vector Store Providers**: Configuration for vector databases and stores.

## Structure and Organization

Each category of provider configuration, and each provider within that category, has three levels of configuration:
1. **Provider Settings**: These are the top-level settings classes for a given category of providers (e.g. `BaseAgentProviderSettings`, `BaseEmbeddingProviderSettings`, etc.) that define the common configuration options for that category, and are subclassed by provider-specific settings classes (e.g. `AnthropicAgentProviderSettings`, `OpenAIEmbeddingProviderSettings`, etc.). The `provider` is the *service provider*, 'who you pay', except for local providers which are more accurately 'what you use'. Another way to consider it is 'who you authenticate with or need an API key for'. The following two configuration levels are contained within a given provider setting class as fields. Defined in `codeweaver.providers.config.categories` package.

2. **Client Options**: These are configuration classes that define the options for using a specific SDK or API client to interact with a provider. This can often be different from the service provider, for example, many providers use the OpenAI SDK or have OpenAI compatible APIs -- the provider is the provider, but the client is the OpenAI client. The parent `ProviderSettings` class will have this configuration in its `client_options` field. For convenience, we differentiate top-level provider settings classes by both provider and SDK, for example `AnthropicAgentProviderSettings` vs `AnthropicAzureAgentProviderSettings`, which both have an `AnthropicClientOptions` field, but the former is for directly using Anthropic as a service provider and the latter is for using Anthropic models with Azure as the service provider, which has some different configuration options and requirements. Defined in `codeweaver.providers.config.clients` package.

3. **SDK Configuration**: These are configuration classes for *principal* method or functions calls to the underlying SDKs, which are not part of the client's constructor (i.e. client options). The field names correspond to a common name for the function or method call, for example `embed` is the field for configuring parameters to the SDK's embedding generation method. Defined in the `codeweaver.providers.config.sdk` package.

### A Special Case: Model Configuration

In most cases, either the ClientOptions or the SDK configuration will cover the configuration options for the model. However, there are some cases where the model configuration is separate or the model has its own constructor.

This is true for *all agent providers*, because it is how PydanticAI structures its agent classes and types, and we use PydanticAI for all agent provider implementations. This is the `agent_config` field in the agent provider settings classes. Since agents have no functional settings with PydanticAI, the classes for `agent_config` are in the `codeweaver.providers.config.sdk.agent` package.

The only other exception is for **Bedrock**, which for both reranking and embedding models, requires a separate model configuration class that is distinct from the client options and SDK configuration and is specific to the model family. For Bedrock, this is the `model_options` field in the top-level provider settings class, such as `BedrockEmbeddingProviderSettings`.
"""

from __future__ import annotations

from types import MappingProxyType

# === MANAGED EXPORTS ===
# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.providers.config.backup_models import (
        ConfigurationError,
        create_backup_embeddings,
        get_backup_embedding_config,
        get_backup_embedding_provider,
        get_backup_model_info,
    )
    from codeweaver.providers.config.categories import MappingProxyType
    from codeweaver.providers.config.categories.agent import (
        AnthropicAgentProviderSettings,
        AnthropicAgentProviderSettingsType,
        AnthropicAzureAgentProviderSettings,
        AnthropicBedrockAgentProviderSettings,
        AnthropicGoogleVertexAgentProviderSettings,
        BaseAgentProviderSettings,
        CerebrasAgentProviderSettings,
        CohereAgentProviderSettings,
        GeneralAgentClientOptionsType,
        GoogleAgentProviderSettings,
        GroqAgentProviderSettings,
        HuggingFaceAgentProviderSettings,
        MistralAgentProviderSettings,
        NonAnthropicAgentProviderSettingsType,
        OpenAIAgentProviderSettings,
        OpenRouterAgentProviderSettings,
        PydanticGatewayProviderSettings,
    )
    from codeweaver.providers.config.categories.base import (
        BaseProviderCategorySettings,
        BaseProviderCategorySettingsDict,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
    )
    from codeweaver.providers.config.categories.data import (
        BaseDataProviderSettings,
        DuckDuckGoProviderSettings,
        ExaProviderSettings,
        GeneralDataClientOptionsType,
        TavilyProviderSettings,
    )
    from codeweaver.providers.config.categories.embedding import (
        AsymmetricEmbeddingProviderSettings,
        AsymmetricEmbeddingProviderSettingsDict,
        AzureClientOptionsType,
        AzureEmbeddingProviderSettings,
        BaseEmbeddingProviderSettings,
        BedrockEmbeddingProviderSettings,
        CohereEmbeddingProviderSettings,
        CoreEmbeddingProviderSettingsType,
        DatatypeMismatchError,
        DimensionMismatchError,
        EmbeddingProviderSettings,
        FastEmbedEmbeddingProviderSettings,
        GeneralEmbeddingClientOptionsType,
        GoogleEmbeddingProviderSettings,
        HuggingFaceEmbeddingProviderSettings,
        MistralEmbeddingProviderSettings,
        SentenceTransformersEmbeddingProviderSettings,
        VoyageEmbeddingProviderSettings,
    )
    from codeweaver.providers.config.categories.mixins import (
        AzureProviderMixin,
        BedrockProviderMixin,
        FastEmbedProviderMixin,
    )
    from codeweaver.providers.config.categories.reranking import (
        BaseRerankingProviderSettings,
        BedrockRerankingProviderSettings,
        CohereRerankingProviderSettings,
        FastEmbedRerankingProviderSettings,
        GeneralRerankingClientOptionsType,
        RerankingProviderSettings,
        SentenceTransformersRerankingProviderSettings,
        VoyageRerankingProviderSettings,
    )
    from codeweaver.providers.config.categories.sparse_embedding import (
        BaseSparseEmbeddingProviderSettings,
        FastEmbedSparseEmbeddingProviderSettings,
        SparseEmbeddingProviderSettings,
    )
    from codeweaver.providers.config.categories.vector_store import (
        BaseVectorStoreProviderSettings,
        MemoryConfig,
        MemoryVectorStoreProviderSettings,
        QdrantCollectionConfig,
        QdrantVectorStoreProviderSettings,
        VectorStoreProviderSettings,
    )
    from codeweaver.providers.config.clients.agent import (
        AnthropicAgentClientOptionsType,
        AnthropicAzureClientOptions,
        AnthropicBedrockClientOptions,
        AnthropicClientOptions,
        AnthropicGoogleVertexClientOptions,
        BaseAnthropicClientOptions,
        GroqClientOptions,
        LiteralProviderType,
        OpenAIAgentClientOptions,
        PydanticGatewayClientOptions,
        SimpleAgentClientOptionsType,
        XAIClientOptions,
    )
    from codeweaver.providers.config.clients.base import ClientOptions
    from codeweaver.providers.config.clients.data import (
        DuckDuckGoClientOptions,
        ExaClientOptions,
        TavilyClientOptions,
    )
    from codeweaver.providers.config.clients.multi import (
        BedrockClientOptions,
        CohereClientOptions,
        FastEmbedClientOptions,
        GoogleClientOptions,
        HuggingFaceClientOptions,
        MistralClientOptions,
        OpenAIClientOptions,
        SentenceTransformersClientOptions,
        SentenceTransformersModelOptions,
        VoyageClientOptions,
    )
    from codeweaver.providers.config.clients.vector_store import GrpcParams, QdrantClientOptions
    from codeweaver.providers.config.profiles import (
        HAS_FASTEMBED,
        HAS_ST,
        AgentProviderSettingsType,
        DataProviderSettingsType,
        EmbeddingProviderSettingsType,
        ProviderConfigProfile,
        ProviderProfile,
        RerankingProviderSettingsType,
        SparseEmbeddingProviderSettingsType,
        VersionedProfile,
        parse_version,
    )
    from codeweaver.providers.config.providers import (
        HAS_ANTHROPIC,
        AgentModelSettings,
        DefaultAgentProviderSettings,
        DefaultEmbeddingProviderSettings,
        DefaultRerankingProviderSettings,
        DefaultSparseEmbeddingProviderSettings,
        DefaultVectorStoreProviderSettings,
        DeterminedDefaults,
        LiteralProviderCategoryType,
        ProviderCategorySettingsType,
        ProviderNameMap,
        ProviderSettings,
        ProviderSettingsDict,
        ProviderSettingsView,
        VectorStoreProviderSettingsType,
        merge_agent_model_settings,
    )
    from codeweaver.providers.config.root_settings import (
        CodeWeaverProviderSettings,
        CodeWeaverProviderSettingsDict,
    )
    from codeweaver.providers.config.sdk.agent import (
        AgentModelConfig,
        AgentModelConfigT,
        CohereAgentModelConfig,
    )
    from codeweaver.providers.config.sdk.data import (
        BaseToolConfig,
        DataToolConfigT,
        DuckDuckGoSearchToolConfig,
        ExaAnswerToolOptions,
        ExaContentsOptions,
        ExaFindSimilarToolOptions,
        ExaGetContentsToolOptions,
        ExaSearchToolOptions,
        ExaToolConfig,
        TavilySearchContextToolConfig,
    )
    from codeweaver.providers.config.sdk.embedding import (
        BaseEmbeddingConfig,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingRequestParams,
        BedrockModelConfig,
        BedrockTitanV2ConfigDict,
        CohereEmbeddingConfig,
        CohereEmbeddingOptionsDict,
        EmbeddingConfigT,
        EmbeddingMixin,
        FastEmbedEmbeddingConfig,
        GoogleEmbeddingConfig,
        GoogleEmbeddingRequestParams,
        HuggingFaceEmbeddingConfig,
        HuggingFaceEmbeddingOptionsDict,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        ScalarType,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SerializedEmbeddingOptionsDict,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
    )
    from codeweaver.providers.config.sdk.reranking import (
        BaseRerankingConfig,
        BedrockRerankingConfig,
        BedrockRerankingModelConfig,
        BedrockRerankingOptionsDict,
        CohereRerankingConfig,
        CohereRerankingOptionsDict,
        FastEmbedRerankingConfig,
        FastEmbedRerankingOptionsDict,
        RerankingConfigT,
        SentenceTransformersRerankingConfig,
        SentenceTransformersRerankingOptionsDict,
        SerializedRerankingOptionsDict,
        VoyageRerankingConfig,
        VoyageRerankingOptionsDict,
    )
    from codeweaver.providers.config.sdk.sparse_embedding import (
        BaseSparseEmbeddingConfig,
        FastEmbedSparseEmbeddingConfig,
        SentenceTransformersSparseEmbeddingConfig,
        SparseEmbeddingConfigT,
    )
    from codeweaver.providers.config.sdk.vector_store import (
        CollectionConfig,
        EmbeddingCapabilityGroupDep,
    )
    from codeweaver.providers.config.types import (
        AgentModelNameString,
        AzureOptions,
        Bm25Config,
        CohereRequestOptionsDict,
        DocumentRepr,
        HttpxClientParams,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "HAS_ANTHROPIC": (__spec__.parent, "providers"),
    "HAS_FASTEMBED": (__spec__.parent, "profiles"),
    "HAS_ST": (__spec__.parent, "profiles"),
    "AgentModelConfig": (__spec__.parent, "sdk.agent"),
    "AgentModelSettings": (__spec__.parent, "providers"),
    "AgentProviderSettingsType": (__spec__.parent, "profiles"),
    "AnthropicAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "AnthropicAzureAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "AnthropicAzureClientOptions": (__spec__.parent, "clients.agent"),
    "AnthropicBedrockAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "AnthropicBedrockClientOptions": (__spec__.parent, "clients.agent"),
    "AnthropicClientOptions": (__spec__.parent, "clients.agent"),
    "AnthropicGoogleVertexAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "AnthropicGoogleVertexClientOptions": (__spec__.parent, "clients.agent"),
    "AsymmetricEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "AsymmetricEmbeddingProviderSettingsDict": (__spec__.parent, "categories.embedding"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "AzureOptions": (__spec__.parent, "types"),
    "AzureProviderMixin": (__spec__.parent, "categories.mixins"),
    "BaseAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "BaseAnthropicClientOptions": (__spec__.parent, "clients.agent"),
    "BaseDataProviderSettings": (__spec__.parent, "categories.data"),
    "BaseEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "BaseEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "BaseProviderCategorySettings": (__spec__.parent, "categories.base"),
    "BaseProviderCategorySettingsDict": (__spec__.parent, "categories.base"),
    "BaseRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "BaseRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "BaseSparseEmbeddingConfig": (__spec__.parent, "sdk.sparse_embedding"),
    "BaseSparseEmbeddingProviderSettings": (__spec__.parent, "categories.sparse_embedding"),
    "BaseToolConfig": (__spec__.parent, "sdk.data"),
    "BaseVectorStoreProviderSettings": (__spec__.parent, "categories.vector_store"),
    "BedrockClientOptions": (__spec__.parent, "clients.multi"),
    "BedrockCohereConfigDict": (__spec__.parent, "sdk.embedding"),
    "BedrockEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "sdk.embedding"),
    "BedrockProviderMixin": (__spec__.parent, "categories.mixins"),
    "BedrockRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "BedrockRerankingModelConfig": (__spec__.parent, "sdk.reranking"),
    "BedrockRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "sdk.embedding"),
    "Bm25Config": (__spec__.parent, "types"),
    "CerebrasAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "ClientOptions": (__spec__.parent, "clients.base"),
    "CodeWeaverProviderSettings": (__spec__.parent, "root_settings"),
    "CodeWeaverProviderSettingsDict": (__spec__.parent, "root_settings"),
    "CohereAgentModelConfig": (__spec__.parent, "sdk.agent"),
    "CohereAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "CohereClientOptions": (__spec__.parent, "clients.multi"),
    "CohereEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "CohereEmbeddingOptionsDict": (__spec__.parent, "sdk.embedding"),
    "CohereEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "CohereRequestOptionsDict": (__spec__.parent, "types"),
    "CohereRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "CohereRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "CohereRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "CollectionConfig": (__spec__.parent, "sdk.vector_store"),
    "ConfigurationError": (__spec__.parent, "backup_models"),
    "ConnectionConfiguration": (__spec__.parent, "categories.base"),
    "ConnectionRateLimitConfig": (__spec__.parent, "categories.base"),
    "DataProviderSettingsType": (__spec__.parent, "profiles"),
    "DatatypeMismatchError": (__spec__.parent, "categories.embedding"),
    "DefaultAgentProviderSettings": (__spec__.parent, "providers"),
    "DefaultEmbeddingProviderSettings": (__spec__.parent, "providers"),
    "DefaultRerankingProviderSettings": (__spec__.parent, "providers"),
    "DefaultSparseEmbeddingProviderSettings": (__spec__.parent, "providers"),
    "DefaultVectorStoreProviderSettings": (__spec__.parent, "providers"),
    "DeterminedDefaults": (__spec__.parent, "providers"),
    "DimensionMismatchError": (__spec__.parent, "categories.embedding"),
    "DocumentRepr": (__spec__.parent, "types"),
    "DuckDuckGoClientOptions": (__spec__.parent, "clients.data"),
    "DuckDuckGoProviderSettings": (__spec__.parent, "categories.data"),
    "DuckDuckGoSearchToolConfig": (__spec__.parent, "sdk.data"),
    "EmbeddingCapabilityGroupDep": (__spec__.parent, "sdk.vector_store"),
    "EmbeddingConfigT": (__spec__.parent, "sdk.embedding"),
    "EmbeddingMixin": (__spec__.parent, "sdk.embedding"),
    "EmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "EmbeddingProviderSettingsType": (__spec__.parent, "profiles"),
    "ExaAnswerToolOptions": (__spec__.parent, "sdk.data"),
    "ExaClientOptions": (__spec__.parent, "clients.data"),
    "ExaContentsOptions": (__spec__.parent, "sdk.data"),
    "ExaFindSimilarToolOptions": (__spec__.parent, "sdk.data"),
    "ExaGetContentsToolOptions": (__spec__.parent, "sdk.data"),
    "ExaProviderSettings": (__spec__.parent, "categories.data"),
    "ExaSearchToolOptions": (__spec__.parent, "sdk.data"),
    "ExaToolConfig": (__spec__.parent, "sdk.data"),
    "FastEmbedClientOptions": (__spec__.parent, "clients.multi"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "FastEmbedProviderMixin": (__spec__.parent, "categories.mixins"),
    "FastEmbedRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "FastEmbedRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "sdk.sparse_embedding"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "categories.sparse_embedding"),
    "GeneralAgentClientOptionsType": (__spec__.parent, "categories.agent"),
    "GeneralDataClientOptionsType": (__spec__.parent, "categories.data"),
    "GeneralEmbeddingClientOptionsType": (__spec__.parent, "categories.embedding"),
    "GeneralRerankingClientOptionsType": (__spec__.parent, "categories.reranking"),
    "GoogleAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "GoogleClientOptions": (__spec__.parent, "clients.multi"),
    "GoogleEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "GoogleEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "GoogleEmbeddingRequestParams": (__spec__.parent, "sdk.embedding"),
    "GroqAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "GroqClientOptions": (__spec__.parent, "clients.agent"),
    "GrpcParams": (__spec__.parent, "clients.vector_store"),
    "HttpxClientParams": (__spec__.parent, "types"),
    "HuggingFaceAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "HuggingFaceClientOptions": (__spec__.parent, "clients.multi"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "HuggingFaceEmbeddingOptionsDict": (__spec__.parent, "sdk.embedding"),
    "HuggingFaceEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "LiteralProviderCategoryType": (__spec__.parent, "providers"),
    "LiteralProviderType": (__spec__.parent, "clients.agent"),
    "MappingProxyType": (__spec__.parent, "categories"),
    "MemoryConfig": (__spec__.parent, "categories.vector_store"),
    "MemoryVectorStoreProviderSettings": (__spec__.parent, "categories.vector_store"),
    "MistralAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "MistralClientOptions": (__spec__.parent, "clients.multi"),
    "MistralEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "sdk.embedding"),
    "MistralEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "OpenRouterAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "ProviderConfigProfile": (__spec__.parent, "profiles"),
    "ProviderNameMap": (__spec__.parent, "providers"),
    "ProviderProfile": (__spec__.parent, "profiles"),
    "ProviderSettings": (__spec__.parent, "providers"),
    "ProviderSettingsDict": (__spec__.parent, "providers"),
    "PydanticGatewayClientOptions": (__spec__.parent, "clients.agent"),
    "PydanticGatewayProviderSettings": (__spec__.parent, "categories.agent"),
    "QdrantClientOptions": (__spec__.parent, "clients.vector_store"),
    "QdrantCollectionConfig": (__spec__.parent, "categories.vector_store"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "categories.vector_store"),
    "RerankingConfigT": (__spec__.parent, "sdk.reranking"),
    "RerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "RerankingProviderSettingsType": (__spec__.parent, "profiles"),
    "ScalarType": (__spec__.parent, "sdk.embedding"),
    "SentenceTransformersClientOptions": (__spec__.parent, "clients.multi"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "SentenceTransformersEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "sdk.embedding"),
    "SentenceTransformersModelOptions": (__spec__.parent, "clients.multi"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "SentenceTransformersRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "SentenceTransformersRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "sdk.sparse_embedding"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "sdk.embedding"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "SparseEmbeddingConfigT": (__spec__.parent, "sdk.sparse_embedding"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "categories.sparse_embedding"),
    "SparseEmbeddingProviderSettingsType": (__spec__.parent, "profiles"),
    "TavilyClientOptions": (__spec__.parent, "clients.data"),
    "TavilyProviderSettings": (__spec__.parent, "categories.data"),
    "TavilySearchContextToolConfig": (__spec__.parent, "sdk.data"),
    "VectorStoreProviderSettings": (__spec__.parent, "categories.vector_store"),
    "VectorStoreProviderSettingsType": (__spec__.parent, "providers"),
    "VersionedProfile": (__spec__.parent, "profiles"),
    "VoyageClientOptions": (__spec__.parent, "clients.multi"),
    "VoyageEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "sdk.embedding"),
    "VoyageEmbeddingProviderSettings": (__spec__.parent, "categories.embedding"),
    "VoyageRerankingConfig": (__spec__.parent, "sdk.reranking"),
    "VoyageRerankingOptionsDict": (__spec__.parent, "sdk.reranking"),
    "VoyageRerankingProviderSettings": (__spec__.parent, "categories.reranking"),
    "create_backup_embeddings": (__spec__.parent, "backup_models"),
    "get_backup_embedding_config": (__spec__.parent, "backup_models"),
    "get_backup_embedding_provider": (__spec__.parent, "backup_models"),
    "get_backup_model_info": (__spec__.parent, "backup_models"),
    "merge_agent_model_settings": (__spec__.parent, "providers"),
    "OpenAIAgentClientOptions": (__spec__.parent, "clients.agent"),
    "OpenAIAgentProviderSettings": (__spec__.parent, "categories.agent"),
    "OpenAIClientOptions": (__spec__.parent, "clients.multi"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "sdk.embedding"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "sdk.embedding"),
    "parse_version": (__spec__.parent, "profiles"),
    "XAIClientOptions": (__spec__.parent, "clients.agent"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "HAS_ANTHROPIC",
    "HAS_FASTEMBED",
    "HAS_ST",
    "AgentModelConfig",
    "AgentModelConfigT",
    "AgentModelNameString",
    "AgentModelSettings",
    "AgentProviderSettingsType",
    "AnthropicAgentClientOptionsType",
    "AnthropicAgentProviderSettings",
    "AnthropicAgentProviderSettingsType",
    "AnthropicAzureAgentProviderSettings",
    "AnthropicAzureClientOptions",
    "AnthropicBedrockAgentProviderSettings",
    "AnthropicBedrockClientOptions",
    "AnthropicClientOptions",
    "AnthropicGoogleVertexAgentProviderSettings",
    "AnthropicGoogleVertexClientOptions",
    "AsymmetricEmbeddingProviderSettings",
    "AsymmetricEmbeddingProviderSettingsDict",
    "AzureClientOptionsType",
    "AzureEmbeddingProviderSettings",
    "AzureOptions",
    "AzureProviderMixin",
    "BaseAgentProviderSettings",
    "BaseAnthropicClientOptions",
    "BaseDataProviderSettings",
    "BaseEmbeddingConfig",
    "BaseEmbeddingProviderSettings",
    "BaseProviderCategorySettings",
    "BaseProviderCategorySettingsDict",
    "BaseRerankingConfig",
    "BaseRerankingProviderSettings",
    "BaseSparseEmbeddingConfig",
    "BaseSparseEmbeddingProviderSettings",
    "BaseToolConfig",
    "BaseVectorStoreProviderSettings",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockModelConfig",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingModelConfig",
    "BedrockRerankingOptionsDict",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "Bm25Config",
    "CerebrasAgentProviderSettings",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CodeWeaverProviderSettingsDict",
    "CohereAgentModelConfig",
    "CohereAgentProviderSettings",
    "CohereClientOptions",
    "CohereEmbeddingConfig",
    "CohereEmbeddingOptionsDict",
    "CohereEmbeddingProviderSettings",
    "CohereRequestOptionsDict",
    "CohereRerankingConfig",
    "CohereRerankingOptionsDict",
    "CohereRerankingProviderSettings",
    "CollectionConfig",
    "ConfigurationError",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "CoreEmbeddingProviderSettingsType",
    "DataProviderSettingsType",
    "DataToolConfigT",
    "DatatypeMismatchError",
    "DefaultAgentProviderSettings",
    "DefaultEmbeddingProviderSettings",
    "DefaultRerankingProviderSettings",
    "DefaultSparseEmbeddingProviderSettings",
    "DefaultVectorStoreProviderSettings",
    "DeterminedDefaults",
    "DimensionMismatchError",
    "DocumentRepr",
    "DuckDuckGoClientOptions",
    "DuckDuckGoProviderSettings",
    "DuckDuckGoSearchToolConfig",
    "EmbeddingCapabilityGroupDep",
    "EmbeddingConfigT",
    "EmbeddingMixin",
    "EmbeddingProviderSettings",
    "EmbeddingProviderSettingsType",
    "ExaAnswerToolOptions",
    "ExaClientOptions",
    "ExaContentsOptions",
    "ExaFindSimilarToolOptions",
    "ExaGetContentsToolOptions",
    "ExaProviderSettings",
    "ExaSearchToolOptions",
    "ExaToolConfig",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingOptionsDict",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "GeneralAgentClientOptionsType",
    "GeneralDataClientOptionsType",
    "GeneralEmbeddingClientOptionsType",
    "GeneralRerankingClientOptionsType",
    "GoogleAgentProviderSettings",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GoogleEmbeddingProviderSettings",
    "GoogleEmbeddingRequestParams",
    "GroqAgentProviderSettings",
    "GroqClientOptions",
    "GrpcParams",
    "HttpxClientParams",
    "HuggingFaceAgentProviderSettings",
    "HuggingFaceClientOptions",
    "HuggingFaceEmbeddingConfig",
    "HuggingFaceEmbeddingOptionsDict",
    "HuggingFaceEmbeddingProviderSettings",
    "LiteralProviderCategoryType",
    "LiteralProviderType",
    "MappingProxyType",
    "MemoryConfig",
    "MemoryVectorStoreProviderSettings",
    "MistralAgentProviderSettings",
    "MistralClientOptions",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "MistralEmbeddingProviderSettings",
    "NonAnthropicAgentProviderSettingsType",
    "OpenAIAgentClientOptions",
    "OpenAIAgentProviderSettings",
    "OpenAIClientOptions",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "OpenRouterAgentProviderSettings",
    "ProviderCategorySettingsType",
    "ProviderConfigProfile",
    "ProviderNameMap",
    "ProviderProfile",
    "ProviderSettings",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "PydanticGatewayClientOptions",
    "PydanticGatewayProviderSettings",
    "QdrantClientOptions",
    "QdrantCollectionConfig",
    "QdrantVectorStoreProviderSettings",
    "RerankingConfigT",
    "RerankingProviderSettings",
    "RerankingProviderSettingsType",
    "ScalarType",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEmbeddingProviderSettings",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersModelOptions",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersRerankingOptionsDict",
    "SentenceTransformersRerankingProviderSettings",
    "SentenceTransformersSparseEmbeddingConfig",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SimpleAgentClientOptionsType",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingProviderSettings",
    "SparseEmbeddingProviderSettingsType",
    "TavilyClientOptions",
    "TavilyProviderSettings",
    "TavilySearchContextToolConfig",
    "VectorStoreProviderSettings",
    "VectorStoreProviderSettingsType",
    "VersionedProfile",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageEmbeddingProviderSettings",
    "VoyageRerankingConfig",
    "VoyageRerankingOptionsDict",
    "VoyageRerankingProviderSettings",
    "XAIClientOptions",
    "create_backup_embeddings",
    "get_backup_embedding_config",
    "get_backup_embedding_provider",
    "get_backup_model_info",
    "merge_agent_model_settings",
    "parse_version",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
