# sourcery skip: no-complex-if-expressions, no-relative-imports
#!/usr/bin/env -S uv run -s
# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# ///script
# python-version = ">=3.12"
# dependencies = ["cyclopts"]
# ///
"""Generates CLI documentation from cyclopts help and command structure."""

from __future__ import annotations

import sys

from datetime import UTC, datetime
from pathlib import Path
from textwrap import dedent

from codeweaver.cli.__main__ import app as codeweaver_app


SAVE_PATH = Path(__file__).parent.parent.parent / "docs" / "CLI.md"


def generate_cli_docs() -> str:
    """Generate CLI documentation for CodeWeaver."""
    from cyclopts.docs.markdown import generate_markdown_docs

    return generate_markdown_docs(codeweaver_app)


def header() -> str:
    """Generate the header for the CLI documentation."""
    return dedent(f"""
    ---
    # SPDX-FileCopyrightText: 2025 Knitli Inc.
    # SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
    #
    # SPDX-License-Identifier: MIT OR Apache-2.0
    title: CodeWeaver CLI Documentation
    description: Documentation for the CodeWeaver command-line interface (CLI).
    date: {datetime.now(UTC).date().isoformat()}
    slug: cli-commands
    tags: [cli, commands, tui]
    ---
    <!-- This file is auto-generated by `scripts/build/generate-cli-docs.py`. Do not edit directly. -->

    """)


def footer() -> str:
    """Generate the footer for the CLI documentation."""
    return dedent("""
    <!-- End of auto-generated content -->
    """)


def save_cli_docs(filepath: Path = SAVE_PATH) -> None:
    """Save the generated CLI documentation to a file."""
    content = f"{header()}\n{generate_cli_docs()}\n{footer()}"
    filepath.write_text(content, encoding="utf-8")


def main() -> None:
    """Main function to generate and save CLI documentation."""
    filepath = Path(sys.argv[1]) if len(sys.argv) > 1 else SAVE_PATH
    save_cli_docs(filepath)


if __name__ == "__main__":
    main()
