# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Global type definitions for CodeWeaver.

We usually try to keep types close to where they are used, but some types
are used so widely that it makes sense to define them globally here.
"""

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core.utils.lazy_import import create_lazy_getattr


if TYPE_CHECKING:
    # Import everything for IDE and type checker support
    # These imports are never executed at runtime, only during type checking
    from codeweaver.core.chunks import (
        ChunkSequence,
        CodeChunk,
        CodeChunkDict,
        SerializedCodeChunk,
        SerializedStrOnlyCodeChunk,
        StructuredDataInput,
    )
    from codeweaver.core.discovery import DiscoveredFile
    from codeweaver.core.language import (
        ConfigLanguage,
        ConfigNamePair,
        LanguageConfigFile,
        SemanticSearchLanguage,
        find_config_paths,
        has_semantic_extension,
        is_semantic_config_ext,
        language_from_config_file,
        languages_present_from_configs,
    )
    from codeweaver.core.metadata import ChunkKind, ChunkSource, ExtKind, ExtLangPair, Metadata
    from codeweaver.core.spans import Span, SpanGroup, SpanTuple
    from codeweaver.core.stores import (
        BlakeStore,
        StoreDict,
        UUIDStore,
        make_blake_store,
        make_uuid_store,
        to_uuid,
    )
    from codeweaver.core.types import (
        BASEDMODEL_CONFIG,
        DATACLASS_CONFIG,
        FROZEN_BASEDMODEL_CONFIG,
        MISSING,
        UNSET,
        AnonymityConversion,
        BaseDataclassEnum,
        BasedModel,
        BaseEnum,
        BaseEnumData,
        BlakeHashKey,
        BlakeKey,
        CategoryName,
        CategoryNameT,
        DataclassSerializationMixin,
        DelimiterDict,
        DelimiterKind,
        DelimiterPattern,
        DeserializationKwargs,
        DevToolName,
        DevToolNameT,
        DictView,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        EmbeddingModelName,
        EmbeddingModelNameT,
        EnvVarInfo,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        LanguageFamily,
        LanguageName,
        LanguageNameT,
        LineStrategy,
        LiteralStringT,
        LlmToolName,
        LlmToolNameT,
        Missing,
        ModelName,
        ModelNameT,
        Provider,
        ProviderEnvVars,
        ProviderKind,
        QueryResult,
        RawEmbeddingVectors,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        RootedRoot,
        SearchResult,
        SearchStrategy,
        Sentinel,
        SentinelName,
        SentinelNameT,
        SerializationKwargs,
        SparseEmbedding,
        StoredEmbeddingVectors,
        StrategizedQuery,
        ThingName,
        ThingNameT,
        Unset,
        UUID7Hex,
        UUID7HexT,
        clean_sentinel_from_schema,
        generate_field_title,
        generate_title,
        get_provider_kinds,
    )
    from codeweaver.core.utils import (
        DictInputTypesT,
        DictOutputTypesT,
        LazyImport,
        asyncio_or_uvloop,
        backup_file_path,
        clean_args,
        dict_set_to_tuple,
        elapsed_time_to_human_readable,
        ensure_iterable,
        file_is_binary,
        format_descriptor,
        format_docstring,
        format_file_link,
        format_signature,
        format_snippet_name,
        generate_collection_name,
        get_blake_hash,
        get_blake_hash_generic,
        get_class_attrs,
        get_class_constructor,
        get_class_methods,
        get_class_properties,
        get_class_variables,
        get_codeweaver_config_paths,
        get_function_annotations,
        get_function_parameters,
        get_function_signature,
        get_git_branch,
        get_git_revision,
        get_optimal_workers,
        get_possible_env_vars,
        get_project_path,
        get_settings_map_for,
        get_source_code,
        get_terminal_width,
        get_tooling_dirs,
        get_user_config_dir,
        getdoc,
        getmodule,
        getmodulename,
        getsourcefile,
        has_git,
        has_package,
        humanize,
        in_codeweaver_clone,
        in_ide,
        is_ci,
        is_class,
        is_codeweaver_config_path,
        is_debug,
        is_git_dir,
        is_pydantic_basemodel,
        is_test_environment,
        is_tty,
        is_typeadapter,
        is_wsl,
        is_wsl_vscode,
        isclass,
        isfunction,
        ismethod,
        lazy_import,
        low_priority,
        normalize_ext,
        resolve_project_root,
        rpartial,
        sanitize_unicode,
        set_relative_path,
        supported_language_count,
        supported_languages,
        to_lowly_lowercase,
        to_tokens,
        truncate_text,
        uuid7,
        uuid7_as_timestamp,
        validate_regex_pattern,
        very_low_priority,
        we_are_in_jetbrains,
        we_are_in_vscode,
    )
    from codeweaver.semantic.types import SemanticMetadata


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AnonymityConversion": (__spec__.parent, "types"),
    "BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "BaseDataclassEnum": (__spec__.parent, "types"),
    "BaseEnum": (__spec__.parent, "types"),
    "BaseEnumData": (__spec__.parent, "types"),
    "BasedModel": (__spec__.parent, "types"),
    "BatchKeyIndex": (__spec__.parent, "chunks"),
    "BatchKeys": (__spec__.parent, "chunks"),
    "BlakeHashKey": (__spec__.parent, "stores"),
    "BlakeKey": (__spec__.parent, "stores"),
    "BlakeStore": (__spec__.parent, "stores"),
    "CategoryName": (__spec__.parent, "types"),
    "CategoryNameT": (__spec__.parent, "types"),
    "ChunkKind": (__spec__.parent, "metadata"),
    "ChunkSequence": (__spec__.parent, "chunks"),
    "ChunkSource": (__spec__.parent, "metadata"),
    "CodeChunk": (__spec__.parent, "chunks"),
    "CodeChunkDict": (__spec__.parent, "chunks"),
    "ConfigLanguage": (__spec__.parent, "language"),
    "ConfigNamePair": (__spec__.parent, "language"),
    "DATACLASS_CONFIG": (__spec__.parent, "types"),
    "DataclassSerializationMixin": (__spec__.parent, "types"),
    "DelimiterDict": (__spec__.parent, "types"),
    "DelimiterKind": (__spec__.parent, "types"),
    "DelimiterPattern": (__spec__.parent, "types"),
    "DeserializationKwargs": (__spec__.parent, "types"),
    "DevToolName": (__spec__.parent, "types"),
    "DevToolNameT": (__spec__.parent, "types"),
    "DictInputTypesT": (__spec__.parent, "utils"),
    "DictOutputTypesT": (__spec__.parent, "utils"),
    "DictView": (__spec__.parent, "types"),
    "DirectoryName": (__spec__.parent, "types"),
    "DirectoryNameT": (__spec__.parent, "types"),
    "DirectoryPath": (__spec__.parent, "types"),
    "DirectoryPathT": (__spec__.parent, "types"),
    "DiscoveredFile": (__spec__.parent, "discovery"),
    "EmbeddingModelName": (__spec__.parent, "types"),
    "EmbeddingModelNameT": (__spec__.parent, "types"),
    "EnvVarInfo": (__spec__.parent, "types"),
    "ExtKind": (__spec__.parent, "metadata"),
    "ExtLangPair": (__spec__.parent, "metadata"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "FileExt": (__spec__.parent, "types"),
    "FileExtensionT": (__spec__.parent, "types"),
    "FileGlob": (__spec__.parent, "types"),
    "FileGlobT": (__spec__.parent, "types"),
    "FileName": (__spec__.parent, "types"),
    "FileNameT": (__spec__.parent, "types"),
    "FilePath": (__spec__.parent, "types"),
    "FilePathT": (__spec__.parent, "types"),
    "FilteredKey": (__spec__.parent, "types"),
    "FilteredKeyT": (__spec__.parent, "types"),
    "LanguageConfigFile": (__spec__.parent, "language"),
    "LanguageFamily": (__spec__.parent, "types"),
    "LanguageName": (__spec__.parent, "types"),
    "LanguageNameT": (__spec__.parent, "types"),
    "LazyImport": (__spec__.parent, "utils"),
    "LineStrategy": (__spec__.parent, "types"),
    "LiteralStringT": (__spec__.parent, "types"),
    "LlmToolName": (__spec__.parent, "types"),
    "LlmToolNameT": (__spec__.parent, "types"),
    "MISSING": (__spec__.parent, "types"),
    "Metadata": (__spec__.parent, "metadata"),
    "Missing": (__spec__.parent, "types"),
    "ModelName": (__spec__.parent, "types"),
    "ModelNameT": (__spec__.parent, "types"),
    "Provider": (__spec__.parent, "types"),
    "ProviderEnvVars": (__spec__.parent, "types"),
    "ProviderKind": (__spec__.parent, "types"),
    "QueryResult": (__spec__.parent, "types"),
    "RawEmbeddingVectors": (__spec__.parent, "types"),
    "RerankingModelName": (__spec__.parent, "types"),
    "RerankingModelNameT": (__spec__.parent, "types"),
    "Role": (__spec__.parent, "types"),
    "RoleT": (__spec__.parent, "types"),
    "RootedRoot": (__spec__.parent, "types"),
    "SearchResult": (__spec__.parent, "types"),
    "SearchStrategy": (__spec__.parent, "types"),
    "SemanticMetadata": ("codeweaver.semantic", "types"),
    "SemanticSearchLanguage": (__spec__.parent, "language"),
    "Sentinel": (__spec__.parent, "types"),
    "SentinelName": (__spec__.parent, "types"),
    "SentinelNameT": (__spec__.parent, "types"),
    "SerializationKwargs": (__spec__.parent, "types"),
    "SerializedCodeChunk": (__spec__.parent, "chunks"),
    "SerializedStrOnlyCodeChunk": (__spec__.parent, "chunks"),
    "Span": (__spec__.parent, "spans"),
    "SpanGroup": (__spec__.parent, "spans"),
    "SpanTuple": (__spec__.parent, "spans"),
    "SparseEmbedding": (__spec__.parent, "types"),
    "StoreDict": (__spec__.parent, "stores"),
    "StoredEmbeddingVectors": (__spec__.parent, "types"),
    "StrategizedQuery": (__spec__.parent, "types"),
    "StructuredDataInput": (__spec__.parent, "chunks"),
    "ThingName": (__spec__.parent, "types"),
    "ThingNameT": (__spec__.parent, "types"),
    "UNSET": (__spec__.parent, "types"),
    "UUID7Hex": (__spec__.parent, "types"),
    "UUID7HexT": (__spec__.parent, "types"),
    "UUIDStore": (__spec__.parent, "stores"),
    "Unset": (__spec__.parent, "types"),
    "asyncio_or_uvloop": (__spec__.parent, "utils"),
    "backup_file_path": (__spec__.parent, "utils"),
    "clean_args": (__spec__.parent, "utils"),
    "clean_sentinel_from_schema": (__spec__.parent, "types"),
    "dict_set_to_tuple": (__spec__.parent, "utils"),
    "elapsed_time_to_human_readable": (__spec__.parent, "utils"),
    "ensure_iterable": (__spec__.parent, "utils"),
    "file_is_binary": (__spec__.parent, "utils"),
    "find_config_paths": (__spec__.parent, "language"),
    "format_descriptor": (__spec__.parent, "utils"),
    "format_docstring": (__spec__.parent, "utils"),
    "format_file_link": (__spec__.parent, "utils"),
    "format_signature": (__spec__.parent, "utils"),
    "format_snippet_name": (__spec__.parent, "utils"),
    "generate_collection_name": (__spec__.parent, "utils"),
    "generate_field_title": (__spec__.parent, "types"),
    "generate_title": (__spec__.parent, "types"),
    "get_blake_hash": (__spec__.parent, "utils"),
    "get_blake_hash_generic": (__spec__.parent, "utils"),
    "get_class_attrs": (__spec__.parent, "utils"),
    "get_class_constructor": (__spec__.parent, "utils"),
    "get_class_methods": (__spec__.parent, "utils"),
    "get_class_properties": (__spec__.parent, "utils"),
    "get_class_variables": (__spec__.parent, "utils"),
    "get_codeweaver_config_paths": (__spec__.parent, "utils"),
    "get_function_annotations": (__spec__.parent, "utils"),
    "get_function_parameters": (__spec__.parent, "utils"),
    "get_function_signature": (__spec__.parent, "utils"),
    "get_git_branch": (__spec__.parent, "utils"),
    "get_git_revision": (__spec__.parent, "utils"),
    "get_optimal_workers": (__spec__.parent, "utils"),
    "get_possible_env_vars": (__spec__.parent, "utils"),
    "get_project_path": (__spec__.parent, "utils"),
    "get_provider_kinds": (__spec__.parent, "types"),
    "get_settings_map_for": (__spec__.parent, "utils"),
    "get_source_code": (__spec__.parent, "utils"),
    "get_terminal_width": (__spec__.parent, "utils"),
    "get_tooling_dirs": (__spec__.parent, "utils"),
    "get_user_config_dir": (__spec__.parent, "utils"),
    "getdoc": (__spec__.parent, "utils"),
    "getmodule": (__spec__.parent, "utils"),
    "getmodulename": (__spec__.parent, "utils"),
    "getsourcefile": (__spec__.parent, "utils"),
    "has_git": (__spec__.parent, "utils"),
    "has_package": (__spec__.parent, "utils"),
    "has_semantic_extension": (__spec__.parent, "language"),
    "humanize": (__spec__.parent, "utils"),
    "in_codeweaver_clone": (__spec__.parent, "utils"),
    "in_ide": (__spec__.parent, "utils"),
    "is_ci": (__spec__.parent, "utils"),
    "is_class": (__spec__.parent, "utils"),
    "is_codeweaver_config_path": (__spec__.parent, "utils"),
    "is_debug": (__spec__.parent, "utils"),
    "is_git_dir": (__spec__.parent, "utils"),
    "is_pydantic_basemodel": (__spec__.parent, "utils"),
    "is_semantic_config_ext": (__spec__.parent, "language"),
    "is_test_environment": (__spec__.parent, "utils"),
    "is_tty": (__spec__.parent, "utils"),
    "is_typeadapter": (__spec__.parent, "utils"),
    "is_wsl": (__spec__.parent, "utils"),
    "is_wsl_vscode": (__spec__.parent, "utils"),
    "isclass": (__spec__.parent, "utils"),
    "isfunction": (__spec__.parent, "utils"),
    "ismethod": (__spec__.parent, "utils"),
    "keyword_args": (__spec__.parent, "utils"),
    "positional_args": (__spec__.parent, "utils"),
    "takes_kwargs": (__spec__.parent, "utils"),
    "language_from_config_file": (__spec__.parent, "language"),
    "languages_present_from_configs": (__spec__.parent, "language"),
    "lazy_import": (__spec__.parent, "utils"),
    "low_priority": (__spec__.parent, "utils"),
    "make_blake_store": (__spec__.parent, "stores"),
    "make_uuid_store": (__spec__.parent, "stores"),
    "normalize_ext": (__spec__.parent, "utils"),
    "resolve_project_root": (__spec__.parent, "utils"),
    "rpartial": (__spec__.parent, "utils"),
    "sanitize_unicode": (__spec__.parent, "utils"),
    "set_relative_path": (__spec__.parent, "utils"),
    "supported_language_count": (__spec__.parent, "general"),
    "supported_languages": (__spec__.parent, "general"),
    "to_lowly_lowercase": (__spec__.parent, "utils"),
    "to_tokens": (__spec__.parent, "utils"),
    "to_uuid": (__spec__.parent, "stores"),
    "truncate_text": (__spec__.parent, "utils"),
    "uuid7": (__spec__.parent, "utils"),
    "uuid7_as_timestamp": (__spec__.parent, "utils"),
    "validate_regex_pattern": (__spec__.parent, "utils"),
    "very_low_priority": (__spec__.parent, "utils"),
    "we_are_in_jetbrains": (__spec__.parent, "utils"),
    "we_are_in_vscode": (__spec__.parent, "utils"),
})
"""Dynamically import submodules and classes for the core package.

Maps class/function/type names to their respective module paths for lazy loading.
"""


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BASEDMODEL_CONFIG",
    "DATACLASS_CONFIG",
    "FROZEN_BASEDMODEL_CONFIG",
    "MISSING",
    "UNSET",
    "AnonymityConversion",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BasedModel",
    "BatchKeyIndex",
    "BatchKeys",
    "BlakeHashKey",
    "BlakeKey",
    "BlakeStore",
    "CategoryName",
    "CategoryNameT",
    "ChunkKind",
    "ChunkSequence",
    "ChunkSource",
    "CodeChunk",
    "CodeChunkDict",
    "ConfigLanguage",
    "ConfigNamePair",
    "DataclassSerializationMixin",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterPattern",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictInputTypesT",
    "DictOutputTypesT",
    "DictView",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DiscoveredFile",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "EnvVarInfo",
    "ExtKind",
    "ExtLangPair",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FilteredKey",
    "FilteredKeyT",
    "LanguageConfigFile",
    "LanguageFamily",
    "LanguageName",
    "LanguageNameT",
    "LazyImport",
    "LineStrategy",
    "LiteralStringT",
    "LlmToolName",
    "LlmToolNameT",
    "Metadata",
    "Missing",
    "ModelName",
    "ModelNameT",
    "Provider",
    "ProviderEnvVars",
    "ProviderKind",
    "QueryResult",
    "RawEmbeddingVectors",
    "RerankingModelName",
    "RerankingModelNameT",
    "Role",
    "RoleT",
    "RootedRoot",
    "SearchResult",
    "SearchStrategy",
    "SemanticMetadata",
    "SemanticSearchLanguage",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "SerializationKwargs",
    "SerializedCodeChunk",
    "SerializedStrOnlyCodeChunk",
    "Span",
    "SpanGroup",
    "SpanTuple",
    "SparseEmbedding",
    "StoreDict",
    "StoredEmbeddingVectors",
    "StrategizedQuery",
    "StructuredDataInput",
    "ThingName",
    "ThingNameT",
    "UUID7Hex",
    "UUID7HexT",
    "UUIDStore",
    "Unset",
    "asyncio_or_uvloop",
    "backup_file_path",
    "clean_args",
    "clean_sentinel_from_schema",
    "create_lazy_getattr",
    "dict_set_to_tuple",
    "elapsed_time_to_human_readable",
    "ensure_iterable",
    "file_is_binary",
    "find_config_paths",
    "format_descriptor",
    "format_docstring",
    "format_file_link",
    "format_signature",
    "format_snippet_name",
    "generate_collection_name",
    "generate_field_title",
    "generate_title",
    "get_blake_hash",
    "get_blake_hash_generic",
    "get_class_attrs",
    "get_class_constructor",
    "get_class_methods",
    "get_class_properties",
    "get_class_variables",
    "get_codeweaver_config_paths",
    "get_function_annotations",
    "get_function_parameters",
    "get_function_signature",
    "get_git_branch",
    "get_git_revision",
    "get_optimal_workers",
    "get_possible_env_vars",
    "get_project_path",
    "get_provider_kinds",
    "get_settings_map_for",
    "get_source_code",
    "get_terminal_width",
    "get_tooling_dirs",
    "get_user_config_dir",
    "getdoc",
    "getmodule",
    "getmodulename",
    "getsourcefile",
    "has_git",
    "has_package",
    "has_semantic_extension",
    "humanize",
    "in_codeweaver_clone",
    "in_ide",
    "is_ci",
    "is_class",
    "is_codeweaver_config_path",
    "is_debug",
    "is_git_dir",
    "is_pydantic_basemodel",
    "is_semantic_config_ext",
    "is_test_environment",
    "is_tty",
    "is_typeadapter",
    "is_wsl",
    "is_wsl_vscode",
    "isclass",
    "isfunction",
    "ismethod",
    "keyword_args",
    "language_from_config_file",
    "languages_present_from_configs",
    "lazy_import",
    "low_priority",
    "make_blake_store",
    "make_uuid_store",
    "normalize_ext",
    "positional_args",
    "resolve_project_root",
    "rpartial",
    "sanitize_unicode",
    "set_relative_path",
    "supported_language_count",
    "supported_languages",
    "takes_kwargs",
    "to_lowly_lowercase",
    "to_tokens",
    "to_uuid",
    "truncate_text",
    "uuid7",
    "uuid7_as_timestamp",
    "validate_regex_pattern",
    "very_low_priority",
    "we_are_in_jetbrains",
    "we_are_in_vscode",
)


def __dir__() -> list[str]:
    """List available attributes for the core package."""
    return list(__all__)
