# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Global type definitions for CodeWeaver.

We usually try to keep types close to where they are used, but some types
are used so widely that it makes sense to define them globally here.
"""

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.common.utils.lazy_getter import create_lazy_getattr


if TYPE_CHECKING:
    # Import everything for IDE and type checker support
    # These imports are never executed at runtime, only during type checking
    from codeweaver.core.chunks import (
        ChunkSequence,
        CodeChunk,
        CodeChunkDict,
        SerializedCodeChunk,
        SerializedStrOnlyCodeChunk,
        StructuredDataInput,
    )
    from codeweaver.core.discovery import DiscoveredFile
    from codeweaver.core.language import (
        ConfigLanguage,
        ConfigNamePair,
        LanguageConfigFile,
        SemanticSearchLanguage,
        find_config_paths,
        has_semantic_extension,
        is_semantic_config_ext,
        language_from_config_file,
        languages_present_from_configs,
    )
    from codeweaver.core.metadata import (
        ChunkKind,
        ChunkSource,
        ExtKind,
        ExtLangPair,
        Metadata,
        SemanticMetadata,
    )
    from codeweaver.core.spans import Span, SpanGroup, SpanTuple
    from codeweaver.core.stores import (
        BlakeHashKey,
        BlakeKey,
        BlakeStore,
        StoreDict,
        UUIDStore,
        make_blake_store,
        make_uuid_store,
        to_uuid,
    )
    from codeweaver.core.types import (
        BASEDMODEL_CONFIG,
        DATACLASS_CONFIG,
        FROZEN_BASEDMODEL_CONFIG,
        UNSET,
        AnonymityConversion,
        BaseDataclassEnum,
        BasedModel,
        BaseEnum,
        BaseEnumData,
        CategoryName,
        CategoryNameT,
        DataclassSerializationMixin,
        DelimiterDict,
        DelimiterKind,
        DelimiterPattern,
        DeserializationKwargs,
        DevToolName,
        DevToolNameT,
        DictView,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        EmbeddingModelName,
        EmbeddingModelNameT,
        EnvVarInfo,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        LanguageFamily,
        LanguageName,
        LanguageNameT,
        LineStrategy,
        LiteralStringT,
        LlmToolName,
        LlmToolNameT,
        ModelName,
        ModelNameT,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        RootedRoot,
        SearchResult,
        SearchStrategy,
        Sentinel,
        SentinelName,
        SentinelNameT,
        SerializationKwargs,
        StrategizedQuery,
        ThingName,
        ThingNameT,
        Unset,
        UUID7Hex,
        UUID7HexT,
        generate_field_title,
        generate_title,
    )
    from codeweaver.core.utils import (
        elapsed_time_to_human_readable,
        get_git_branch,
        get_git_revision,
        get_project_path,
        get_tooling_dirs,
        get_user_config_dir,
        in_codeweaver_clone,
        is_git_dir,
        normalize_ext,
        sanitize_unicode,
        set_relative_path,
        truncate_text,
        uuid7,
    )


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AnonymityConversion": (__spec__.parent, "types"),
    "BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "BaseDataclassEnum": (__spec__.parent, "types"),
    "BaseEnum": (__spec__.parent, "types"),
    "BaseEnumData": (__spec__.parent, "types"),
    "BasedModel": (__spec__.parent, "types"),
    "BlakeHashKey": (__spec__.parent, "stores"),
    "BlakeKey": (__spec__.parent, "stores"),
    "BlakeStore": (__spec__.parent, "stores"),
    "CategoryName": (__spec__.parent, "types"),
    "CategoryNameT": (__spec__.parent, "types"),
    "ChunkKind": (__spec__.parent, "metadata"),
    "ChunkSequence": (__spec__.parent, "chunks"),
    "ChunkSource": (__spec__.parent, "metadata"),
    "CodeChunk": (__spec__.parent, "chunks"),
    "CodeChunkDict": (__spec__.parent, "chunks"),
    "ConfigLanguage": (__spec__.parent, "language"),
    "ConfigNamePair": (__spec__.parent, "language"),
    "DATACLASS_CONFIG": (__spec__.parent, "types"),
    "DataclassSerializationMixin": (__spec__.parent, "types"),
    "DelimiterDict": (__spec__.parent, "types"),
    "DelimiterKind": (__spec__.parent, "types"),
    "DelimiterPattern": (__spec__.parent, "types"),
    "DeserializationKwargs": (__spec__.parent, "types"),
    "DevToolName": (__spec__.parent, "types"),
    "DevToolNameT": (__spec__.parent, "types"),
    "DictView": (__spec__.parent, "types"),
    "DirectoryName": (__spec__.parent, "types"),
    "DirectoryNameT": (__spec__.parent, "types"),
    "DirectoryPath": (__spec__.parent, "types"),
    "DirectoryPathT": (__spec__.parent, "types"),
    "DiscoveredFile": (__spec__.parent, "discovery"),
    "EmbeddingModelName": (__spec__.parent, "types"),
    "EmbeddingModelNameT": (__spec__.parent, "types"),
    "EnvVarInfo": (__spec__.parent, "types"),
    "ExtKind": (__spec__.parent, "metadata"),
    "ExtLangPair": (__spec__.parent, "metadata"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "types"),
    "FileExt": (__spec__.parent, "types"),
    "FileExtensionT": (__spec__.parent, "types"),
    "FileGlob": (__spec__.parent, "types"),
    "FileGlobT": (__spec__.parent, "types"),
    "FileName": (__spec__.parent, "types"),
    "FileNameT": (__spec__.parent, "types"),
    "FilePath": (__spec__.parent, "types"),
    "FilePathT": (__spec__.parent, "types"),
    "FilteredKey": (__spec__.parent, "types"),
    "FilteredKeyT": (__spec__.parent, "types"),
    "LanguageConfigFile": (__spec__.parent, "language"),
    "LanguageFamily": (__spec__.parent, "types"),
    "LanguageName": (__spec__.parent, "types"),
    "LanguageNameT": (__spec__.parent, "types"),
    "LineStrategy": (__spec__.parent, "types"),
    "LiteralStringT": (__spec__.parent, "types"),
    "LlmToolName": (__spec__.parent, "types"),
    "LlmToolNameT": (__spec__.parent, "types"),
    "Metadata": (__spec__.parent, "metadata"),
    "ModelName": (__spec__.parent, "types"),
    "ModelNameT": (__spec__.parent, "types"),
    "RerankingModelName": (__spec__.parent, "types"),
    "RerankingModelNameT": (__spec__.parent, "types"),
    "Role": (__spec__.parent, "types"),
    "RoleT": (__spec__.parent, "types"),
    "RootedRoot": (__spec__.parent, "types"),
    "SearchResult": (__spec__.parent, "types"),
    "SearchStrategy": (__spec__.parent, "types"),
    "SemanticMetadata": (__spec__.parent, "metadata"),
    "SemanticSearchLanguage": (__spec__.parent, "language"),
    "Sentinel": (__spec__.parent, "types"),
    "SentinelName": (__spec__.parent, "types"),
    "SentinelNameT": (__spec__.parent, "types"),
    "SerializationKwargs": (__spec__.parent, "types"),
    "SerializedCodeChunk": (__spec__.parent, "chunks"),
    "SerializedStrOnlyCodeChunk": (__spec__.parent, "chunks"),
    "Span": (__spec__.parent, "spans"),
    "SpanGroup": (__spec__.parent, "spans"),
    "SpanTuple": (__spec__.parent, "spans"),
    "StoreDict": (__spec__.parent, "stores"),
    "StrategizedQuery": (__spec__.parent, "types"),
    "StructuredDataInput": (__spec__.parent, "chunks"),
    "ThingName": (__spec__.parent, "types"),
    "ThingNameT": (__spec__.parent, "types"),
    "UNSET": (__spec__.parent, "types"),
    "UUID7Hex": (__spec__.parent, "types"),
    "UUID7HexT": (__spec__.parent, "types"),
    "UUIDStore": (__spec__.parent, "stores"),
    "Unset": (__spec__.parent, "types"),
    "elapsed_time_to_human_readable": (__spec__.parent, "utils"),
    "find_config_paths": (__spec__.parent, "language"),
    "generate_field_title": (__spec__.parent, "types"),
    "generate_title": (__spec__.parent, "types"),
    "get_git_branch": (__spec__.parent, "utils"),
    "get_git_revision": (__spec__.parent, "utils"),
    "get_project_path": (__spec__.parent, "utils"),
    "get_tooling_dirs": (__spec__.parent, "utils"),
    "get_user_config_dir": (__spec__.parent, "utils"),
    "has_semantic_extension": (__spec__.parent, "language"),
    "in_codeweaver_clone": (__spec__.parent, "utils"),
    "is_git_dir": (__spec__.parent, "utils"),
    "is_semantic_config_ext": (__spec__.parent, "language"),
    "language_from_config_file": (__spec__.parent, "language"),
    "languages_present_from_configs": (__spec__.parent, "language"),
    "make_blake_store": (__spec__.parent, "stores"),
    "make_uuid_store": (__spec__.parent, "stores"),
    "normalize_ext": (__spec__.parent, "utils"),
    "sanitize_unicode": (__spec__.parent, "utils"),
    "set_relative_path": (__spec__.parent, "utils"),
    "to_uuid": (__spec__.parent, "stores"),
    "truncate_text": (__spec__.parent, "utils"),
    "uuid7": (__spec__.parent, "utils"),
})
"""Dynamically import submodules and classes for the core package.

Maps class/function/type names to their respective module paths for lazy loading.
"""


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BASEDMODEL_CONFIG",
    "DATACLASS_CONFIG",
    "FROZEN_BASEDMODEL_CONFIG",
    "UNSET",
    "AnonymityConversion",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BasedModel",
    "BlakeHashKey",
    "BlakeKey",
    "BlakeStore",
    "CategoryName",
    "CategoryNameT",
    "ChunkKind",
    "ChunkSequence",
    "ChunkSource",
    "CodeChunk",
    "CodeChunkDict",
    "ConfigLanguage",
    "ConfigNamePair",
    "DataclassSerializationMixin",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterPattern",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictView",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DiscoveredFile",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "EnvVarInfo",
    "ExtKind",
    "ExtLangPair",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FilteredKey",
    "FilteredKeyT",
    "LanguageConfigFile",
    "LanguageFamily",
    "LanguageName",
    "LanguageNameT",
    "LineStrategy",
    "LiteralStringT",
    "LlmToolName",
    "LlmToolNameT",
    "Metadata",
    "ModelName",
    "ModelNameT",
    "RerankingModelName",
    "RerankingModelNameT",
    "Role",
    "RoleT",
    "RootedRoot",
    "SearchResult",
    "SearchStrategy",
    "SemanticMetadata",
    "SemanticSearchLanguage",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "SerializationKwargs",
    "SerializedCodeChunk",
    "SerializedStrOnlyCodeChunk",
    "Span",
    "SpanGroup",
    "SpanTuple",
    "StoreDict",
    "StrategizedQuery",
    "StructuredDataInput",
    "ThingName",
    "ThingNameT",
    "UUID7Hex",
    "UUID7HexT",
    "UUIDStore",
    "Unset",
    "elapsed_time_to_human_readable",
    "find_config_paths",
    "generate_field_title",
    "generate_title",
    "get_git_branch",
    "get_git_revision",
    "get_project_path",
    "get_tooling_dirs",
    "get_user_config_dir",
    "has_semantic_extension",
    "in_codeweaver_clone",
    "is_git_dir",
    "is_semantic_config_ext",
    "language_from_config_file",
    "languages_present_from_configs",
    "make_blake_store",
    "make_uuid_store",
    "normalize_ext",
    "sanitize_unicode",
    "set_relative_path",
    "to_uuid",
    "truncate_text",
    "uuid7",
)


def __dir__() -> list[str]:
    """List available attributes for the core package."""
    return list(__all__)
