# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Package-level lazy imports for codeweaver.core."""

from __future__ import annotations

from types import MappingProxyType

# === MANAGED EXPORTS ===
# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.core._logging import (
        IS_CI,
        IS_TTY,
        LOG_PATH,
        SESSION_LOG_FILE,
        create_session_file_handler,
        get_rich_console,
        get_rich_handler,
        get_session_log_path,
        log_to_client_or_fallback,
        setup_logger,
    )
    from codeweaver.core.chunks import (
        BatchKeys,
        ChunkSequence,
        CodeChunkDict,
        SerializedCodeChunk,
        SerializedStrOnlyCodeChunk,
        StructuredDataInput,
    )
    from codeweaver.core.config._logging import (
        DefaultLoggingSettings,
        FiltersDict,
        FormattersDict,
        HandlersDict,
        LoggersDict,
        LoggingConfigDict,
        LoggingSettingsDict,
        NewType,
        SerializableLoggingFilter,
    )
    from codeweaver.core.config.core_settings import CodeWeaverCoreSettings
    from codeweaver.core.config.envs import ProviderKey, SetProviderEnvVarsDict, SettingsEnvVars
    from codeweaver.core.config.loader import get_settings
    from codeweaver.core.config.telemetry import (
        DefaultTelemetrySettings,
        TelemetrySettings,
        TelemetrySettingsDict,
    )
    from codeweaver.core.config.types import BaseCodeWeaverSettingsDict
    from codeweaver.core.constants import (
        BACKUP_DENSE_VECTOR_NAME,
        BACKUP_EMBEDDING_MODEL_FALLBACK,
        BACKUP_EMBEDDING_MODEL_PRIMARY,
        BACKUP_RERANKING_MODEL,
        BASE_RETRYABLE_EXCEPTIONS,
        CLOUD_EMBEDDING_COST_PER_1K_TOKENS,
        CLOUD_RERANKING_COST_PER_1K_TOKENS,
        CODEWEAVER_DESCRIPTION,
        CODEWEAVER_ICON,
        CONTEXT_AGENT_COST_PER_1K_TOKENS,
        CONTEXT_AGENT_EXPLANATORY_TASK_CONFIG,
        CONTEXT_AGENT_INTENT_AND_TASK_VALIDATION_CONFIG,
        CONTEXT_AGENT_RESULT_REVIEW_CONFIG,
        CONTEXT_AGENT_TAGS,
        DATATYPE_FIELDS,
        DEFAULT_AGENT_TEMPERATURE,
        DEFAULT_AGENT_TIMEOUT,
        DEFAULT_AGENT_TOP_P,
        DEFAULT_BLAKE_STORE_MAX_SIZE,
        DEFAULT_CHECKPOINT_SUBPATH,
        DEFAULT_COLLECTION_NAME_PREFIX,
        DEFAULT_DAEMON_STARTUP_CHECK_INTERVAL,
        DEFAULT_DAEMON_STARTUP_WAIT,
        DEFAULT_DENSE_WEIGHT,
        DEFAULT_EMBEDDING_BATCH_SIZE,
        DEFAULT_EMBEDDING_REGISTRY_MAX_SIZE,
        DEFAULT_EMBEDDING_TIMEOUT,
        DEFAULT_HNSW_EF_CONSTRUCTION,
        DEFAULT_HNSW_FULL_SCAN_THRESHOLD,
        DEFAULT_HNSW_M,
        DEFAULT_HNSW_PAYLOAD_M,
        DEFAULT_HOST,
        DEFAULT_HTTPX_KEEPALIVE_EXPIRY,
        DEFAULT_HTTPX_MAX_CONNECTIONS,
        DEFAULT_HTTPX_MAX_KEEPALIVE_CONNECTIONS,
        DEFAULT_LOCAL_EMBEDDING_BATCH_SIZE,
        DEFAULT_LOG_LEVEL,
        DEFAULT_MANAGEMENT_PORT,
        DEFAULT_MANIFEST_SUBPATH,
        DEFAULT_MAX_CONCURRENT_BATCHES,
        DEFAULT_MAX_QUEUE_SIZE,
        DEFAULT_MAX_RESULTS,
        DEFAULT_MAX_TOKENS,
        DEFAULT_MCP_MAX_RETRY_ATTEMPTS,
        DEFAULT_MCP_PORT,
        DEFAULT_MCP_RATE_LIMIT_BURST_CAPACITY,
        DEFAULT_MCP_RATE_LIMIT_MAX_REQUESTS_PER_SECOND,
        DEFAULT_MCP_RETRY_BACKOFF_MULTIPLIER,
        DEFAULT_MCP_RETRY_BASE_DELAY,
        DEFAULT_MCP_RETRY_MAX_DELAY,
        DEFAULT_MCP_TIMEOUT,
        DEFAULT_OPEN_BREAKER_DURATION,
        DEFAULT_PERSIST_INTERVAL,
        DEFAULT_POOL_ACQUIRE_TIMEOUT,
        DEFAULT_POOL_CONNECTION_TIMEOUT,
        DEFAULT_POOL_READ_TIMEOUT,
        DEFAULT_POOL_WRITE_TIMEOUT,
        DEFAULT_RECONCILIATION_SERVICE_BATCH_SIZE,
        DEFAULT_RERANKING_MAX_RESULTS,
        DEFAULT_RERANKING_TIMEOUT,
        DEFAULT_RICH_HANDLER_OPTIONS,
        DEFAULT_SEMANTIC_IDENTIFICATION_CONFIDENCE_THRESHOLD,
        DEFAULT_SERVER_SHUTDOWN_TIMEOUT,
        DEFAULT_SNAPSHOT_RETENTION_COUNT,
        DEFAULT_SPARSE_WEIGHT,
        DEFAULT_USER_DIR_NAME,
        DEFAULT_UUID_STORE_MAX_SIZE,
        DEFAULT_VECTOR_STORE_BATCH_SIZE,
        DEFAULT_VECTOR_STORE_MAX_RESULTS,
        DEFAULT_VECTOR_STORE_PERSIST_SUBPATH,
        DEFAULT_WATCHER_DEBOUNCE_MILLISECONDS,
        DEFAULT_WATCHER_GRACE_PERIOD,
        DEFAULT_WATCHER_STEP_MILLISECONDS,
        DIMENSION_FIELDS,
        ELLIPSIS,
        ENV_CI_INDICATORS,
        ENV_EXPLICIT_TRUE_VALUES,
        FILE_BATCH_SIZE,
        FIND_CODE_DESCRIPTION,
        FIND_CODE_INSTRUCTION,
        FIND_CODE_TITLE,
        FIVE_MINUTES,
        HEALTH_ENDPOINT,
        INDEXER_WINDDOWN_TIMEOUT,
        INTROSPECTION_ATTRIBUTES,
        LOCAL_EMBEDDING_COST_PER_1K_TOKENS,
        LOCALHOST,
        LOGGERS_TO_SUPPRESS,
        MAX_INLINE_CONTENT_SIZE,
        MAX_RETRY_ATTEMPTS,
        MAX_SEMANTIC_CHUNKER_RECURSION_DEPTH,
        MCP_ENDPOINT,
        METRICS_ENDPOINT,
        ONE,
        ONE_DAY,
        ONE_GIGABYTE,
        ONE_HOUR,
        ONE_HUNDRED,
        ONE_HUNDRED_MEGABYTES,
        ONE_KILOBYTE,
        ONE_LINE,
        ONE_MEGABYTE,
        ONE_MINUTE,
        ONE_POINT_ZERO,
        ONE_SECOND,
        ONNX_CUDA_PROVIDER,
        PARALLEL_CHUNKING_THRESHOLD,
        POSIX_NEWLINE,
        PREFERRED_MODELS_FOR_CONTEXT_AGENT_TASKS,
        PREFERRED_SEARCH_PROVIDER_ORDER,
        PRIMARY_SPARSE_VECTOR_NAME,
        PRIMARY_VECTOR_NAME,
        PYDANTIC_AI_MODEL_CAPABILITIES_PROVIDERS,
        PYTHON_SHEBANG,
        QDRANT_MEMORY_LOCATION,
        RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL,
        RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL_BARE,
        RECOMMENDED_CLOUD_EMBEDDING_MODEL,
        RECOMMENDED_CLOUD_RERANKING_MODEL,
        RECOMMENDED_LOCAL_CONTEXT_AGENT_MODEL,
        RECOMMENDED_LOCAL_EMBEDDING_MODEL,
        RECOMMENDED_LOCAL_RERANKING_MODEL,
        RECOMMENDED_SPARSE_EMBEDDING_MODEL,
        SEMANTIC_CHUNKER_PERFORMANCE_THRESHOLD_MS,
        SETTINGS_ENDPOINT,
        SHEBANG,
        SHUTDOWN_ENDPOINT,
        SOTA_CONTEXT_AGENT_MODEL,
        SOTA_EMBEDDING_MODEL,
        SOTA_RERANKING_MODEL,
        SPACE,
        STATE_ENDPOINT,
        STATUS_ENDPOINT,
        TAB,
        TEN_MINUTES,
        ULTRALIGHT_CONTEXT_AGENT_MODEL,
        ULTRALIGHT_EMBEDDING_MODEL,
        ULTRALIGHT_RERANKING_MODEL,
        ULTRALIGHT_SPARSE_EMBEDDING_MODEL,
        USER_AGENT_COST_PER_1K_TOKENS,
        USER_AGENT_TAGS,
        VERSION_ENDPOINT,
        WATCHER_WINDDOWN_TIMEOUT,
        WHITESPACES,
        WINDOWS_NEWLINE,
        ZERO,
        ZERO_POINT_ZERO,
    )
    from codeweaver.core.dependencies.component_settings import (
        LoggerDep,
        LoggingSettingsDep,
        ResolvedGitBranchDep,
        ResolvedProjectNameDep,
        ResolvedProjectPathHashDep,
        ServiceCardsDep,
        TelemetrySettingsDep,
    )
    from codeweaver.core.dependencies.core_settings import SettingsDep, SettingsMapDep
    from codeweaver.core.dependencies.services import (
        ProgressReporterDep,
        StatisticsDep,
        TelemetryServiceDep,
    )
    from codeweaver.core.di.container import (
        Container,
        ResolutionResult,
        TypeAliasType,
        get_container,
    )
    from codeweaver.core.di.depends import (
        INJECTED,
        Depends,
        DependsPlaceholder,
        depends,
        is_depends_marker,
    )
    from codeweaver.core.di.utils import ProviderMetadata, dependency_provider
    from codeweaver.core.discovery import ResolvedProjectPathDep
    from codeweaver.core.exceptions import (
        CircularDependencyError,
        ClassVar,
        CodeWeaverDeveloperError,
        CodeWeaverError,
        CollectionNotFoundError,
        ConfigurationLockError,
        DatatypeMismatchError,
        DependencyInjectionError,
        DependencyNotAvailableError,
        DependencyResolutionError,
        DimensionMismatchError,
        IndexingError,
        InitializationError,
        InvalidEmbeddingModelError,
        LocationInfo,
        MissingValueError,
        ModelSwitchError,
        NamedTuple,
        NodeParsingFailureError,
        PersistenceError,
        ProviderError,
        ProviderSwitchError,
        QueryError,
        RerankingProviderError,
        ScopeViolationError,
        UnresolvableDependencyError,
        ValidationError,
    )
    from codeweaver.core.file_extensions import (
        CODE_FILES_EXTENSIONS,
        CONFIG_FILE_LANGUAGES,
        DATA_FILES_EXTENSIONS,
        DEFAULT_EXCLUDED_DIRS,
        DEFAULT_EXCLUDED_EXTENSIONS,
        DOC_FILES_EXTENSIONS,
        FALLBACK_TEST,
        LANGUAGE_SPECIFIC_PATHS,
        METADATA_PATH,
        REPO_POLICY_FILES,
        TEST_DIR_NAMES,
        TEST_FILE_PATTERNS,
        FallBackTestDef,
        LlmTool,
        all_js_exts,
    )
    from codeweaver.core.language import (
        ConfigLanguage,
        KeyPath,
        LanguageConfigFile,
        RepoConventions,
        SemanticSearchLanguage,
        find_config_paths,
        get_ext_lang_pairs_generator,
        has_semantic_extension,
        is_semantic_config_ext,
        language_from_config_file,
        language_from_path,
        languages_present_from_configs,
    )
    from codeweaver.core.metadata import (
        BASH_SHEBANG_PATTERN,
        EXTENSION_TESTS,
        PERL_SHEBANG_PATTERN,
        PYTHON_SHEBANG_PATTERN,
        ChunkKind,
        ChunkSource,
        ExtCategory,
        ExtLangPair,
        ExtTestDef,
        determine_ext_category,
        get_ext_lang_pair_for_file,
        get_ext_lang_pairs,
        get_language_from_extension,
        get_semantic_or_config_lang,
    )
    from codeweaver.core.repo import (
        AsyncPath,
        DirectoryPurpose,
        PathOrFalse,
        RepoChecklist,
        RepoChecklistDict,
        RepoDirectory,
    )
    from codeweaver.core.secondary_languages import SecondarySupportedLanguage
    from codeweaver.core.spans import Span, SpanGroup, SpanTuple
    from codeweaver.core.statistics import (
        UUID7_STR,
        CodeWeaverSettingsType,
        FailoverStats,
        FileStatistics,
        Identifier,
        SessionStatistics,
        TimingStatistics,
        TokenCategory,
        TokenCost,
        TokenCounter,
        add_failed_request,
        add_successful_request,
        get_session_statistics,
        normalize_language,
        record_timed_http_request,
        timed_http,
    )
    from codeweaver.core.stores import (
        BlakeStore,
        StoreDict,
        UUIDStore,
        make_blake_store,
        make_uuid_store,
        to_uuid,
    )
    from codeweaver.core.telemetry.client import TelemetryService, TracebackType
    from codeweaver.core.telemetry.events import (
        SearchEvent,
        SessionEvent,
        TelemetryEvent,
        capture_search_event,
    )
    from codeweaver.core.telemetry.utils import IntifyingPatterns
    from codeweaver.core.types import (
        LiteralProvider,
        LiteralProviderCategory,
        LiteralProviderCategoryType,
        LiteralProviderType,
        LiteralSDKClient,
        LiteralSDKClientType,
        ProviderCategoryLiteralString,
        ProviderLiteralString,
        SDKClientLiteralString,
    )
    from codeweaver.core.types.aliases import (
        Annotated,
        CategoryNameT,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        EmbeddingModelName,
        EmbeddingModelNameT,
        Field,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        GetPydanticSchema,
        LanguageName,
        LanguageNameT,
        LiteralString,
        ModelName,
        ModelNameT,
        PathLike,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        SentinelName,
        SentinelNameT,
        ThingName,
        ThingNameT,
        ThingOrCategoryNameT,
        UUID7Hex,
        UUID7HexT,
    )
    from codeweaver.core.types.dataclasses import (
        DATACLASS_CONFIG,
        AnonymityConversion,
        BaseEnumData,
        ConfigDict,
        DataclassSerializationMixin,
        DeserializationKwargs,
        IncEx,
        Iterator,
        NotRequired,
        PrivateAttr,
        Self,
        SerializationKwargs,
        TypedDict,
        Unpack,
        cached_property,
        dataclass,
        generate_field_title,
        generate_title,
    )
    from codeweaver.core.types.delimiter import (
        LANGUAGE_TO_FAMILY,
        BaseEnum,
        DelimiterDict,
        DelimiterKind,
        DelimiterPattern,
        LanguageFamily,
        LineStrategy,
        Required,
    )
    from codeweaver.core.types.dictview import DictView, ItemsView, KeysView, Mapping, ValuesView
    from codeweaver.core.types.embeddings import (
        BasedModel,
        ChunkEmbeddings,
        CodeChunk,
        CodeWeaverSparseEmbedding,
        DataType,
        EmbeddingBatchInfo,
        EmbeddingKind,
        QueryResult,
        RawEmbeddingVectors,
        StoredEmbeddingVectors,
        override,
    )
    from codeweaver.core.types.enum import (
        BaseDataclassEnum,
        Enum,
        FilteredCallable,
        FilteredReturn,
        Generator,
        auto,
        computed_field,
        unique,
    )
    from codeweaver.core.types.env import EnvFormat, EnvVarInfo, ProviderEnvVars, VariableInfo
    from codeweaver.core.types.models import (
        BASEDMODEL_CONFIG,
        FILTERED_KEYS,
        FROZEN_BASEDMODEL_CONFIG,
        RootedRoot,
        RootModel,
        abc,
        clean_sentinel_from_schema,
    )
    from codeweaver.core.types.provider import (
        ProviderCategory,
        SDKClient,
        get_categories,
        get_default_provider_import_for_category,
    )
    from codeweaver.core.types.search import (
        AfterValidator,
        DiscoveredFile,
        Metadata,
        SearchResult,
        SearchStrategy,
        StrategizedQuery,
    )
    from codeweaver.core.types.sentinel import (
        UNSET,
        DontGenerateJsonSchema,
        FrameType,
        GenerateJsonSchema,
        GetCoreSchemaHandler,
        GetJsonSchemaHandler,
        JsonSchemaValue,
        PydanticOmit,
        Sentinel,
        Unset,
        core_schema,
    )
    from codeweaver.core.types.service_cards import (
        Coroutine,
        ServiceCard,
        ServiceMetadata,
        defaultdict,
        get_local_only_provider_members,
        get_local_only_providers,
        get_openai_provider_members,
        get_openai_providers,
        get_provider_capabilities_map,
        get_provider_category_sdk_clients_for_provider,
        get_provider_clients,
        get_provider_literals,
        get_providers_for_category,
        get_sdk_client,
        get_sdk_client_map,
        get_service_card,
        get_service_cards,
        get_sometimes_local_provider_members,
        get_sometimes_local_providers,
        service_card_factory,
    )
    from codeweaver.core.types.settings_model import (
        DEFAULT_BASE_SETTINGS_CONFIG,
        BaseCodeWeaverSettings,
        BaseSettings,
        SettingsConfigDict,
    )
    from codeweaver.core.types.statistics import (
        CallHookTimingDict,
        CategoryKey,
        HttpRequestsDict,
        McpComponentRequests,
        McpComponentTimingDict,
        McpOperationRequests,
        McpTimingDict,
        OperationsKey,
        RequestKind,
        ResourceUri,
        SummaryKey,
        TimingStatisticsDict,
        ToolOrPromptName,
    )
    from codeweaver.core.types.utils import (
        ComputedFieldInfo,
        DynamicClassAttribute,
        FieldInfo,
        add_enum_alias,
        add_enum_member,
    )
    from codeweaver.core.ui_protocol import (
        NoOpProgressReporter,
        ProgressReporter,
        RichConsoleProgressReporter,
    )
    from codeweaver.core.utils import TYPE_CHECKING, MappingProxyType
    from codeweaver.core.utils.checks import (
        LOCALHOST_INDICATORS,
        Any,
        AnyUrl,
        BaseModel,
        Path,
        TypeAdapter,
        TypeIs,
        cache,
        file_is_binary,
        has_package,
        httpx,
        inspect,
        is_ci,
        is_class,
        is_debug,
        is_local_host,
        is_pydantic_basemodel,
        is_test_environment,
        is_typeadapter,
        is_wsl,
        is_wsl_vscode,
        logger,
        logging,
        metadata,
        os,
        platform,
        python_version,
        sys,
        urllib,
        util,
    )
    from codeweaver.core.utils.environment import (
        ENV_EXPLICIT_FALSE_VALUES,
        ENV_JETBRAINS_INDICATOR,
        ENV_VSCODE_INDICATORS,
        LOCALHOST_URL,
        Literal,
        NonNegativeInt,
        PositiveInt,
        Provider,
        console,
        contextlib,
        detect_root_package,
        find_qdrant_instance,
        format_file_link,
        get_codeweaver_config_paths,
        get_codeweaver_prefix,
        get_possible_env_vars,
        get_terminal_width,
        importlib,
        in_ide,
        is_codeweaver_config_path,
        is_tty,
        qdrant_instance_live_at_port,
        settings_type_for_root_package,
        we_are_in_jetbrains,
        we_are_in_vscode,
    )
    from codeweaver.core.utils.filesystem import (
        COMMON_LLM_TOOLING_PATHS,
        COMMON_TOOLING_PATHS,
        MISSING,
        DevToolName,
        DevToolNameT,
        LlmToolName,
        LlmToolNameT,
        Missing,
        cast,
        get_git_branch,
        get_git_revision,
        get_project_path,
        get_tooling_dirs,
        get_user_cache_dir,
        get_user_config_dir,
        get_user_data_dir,
        get_user_state_dir,
        has_git,
        in_codeweaver_clone,
        is_git_dir,
        normalize_ext,
        platformdirs,
        set_relative_path,
        shutil,
        subprocess,
        try_git_rev_parse,
    )
    from codeweaver.core.utils.general import (
        Callable,
        CategoryName,
        DictInputTypesT,
        DictOutputTypesT,
        Hashable,
        Iterable,
        LiteralStringT,
        deep_merge_dicts,
        dict_set_to_tuple,
        ensure_iterable,
        generate_collection_name,
        rpartial,
        supported_language_count,
        supported_languages,
    )
    from codeweaver.core.utils.generation import (
        ONE_MILLISECOND_IN_MICROSECONDS,
        UUID7,
        BlakeHashKey,
        BlakeKey,
        datetime,
        get_blake_hash,
        get_blake_hash_generic,
        overload,
        uuid7,
        uuid7_as_timestamp,
    )
    from codeweaver.core.utils.introspect import (
        Attribute,
        Parameter,
        Sequence,
        Signature,
        clean_args,
        get_caller,
        get_caller_module,
        get_caller_modulename,
        get_class_attrs,
        get_class_constructor,
        get_class_methods,
        get_class_properties,
        get_class_variables,
        get_file_path,
        get_function_annotations,
        get_function_parameters,
        get_function_signature,
        get_generic_params_for_type,
        get_source_code,
        get_source_start_end,
        getdoc,
        getmodule,
        getmodulename,
        getsourcefile,
        is_constructor_arg,
        isclass,
        isfunction,
        ismethod,
        keyword_args,
        positional_args,
        return_type,
        takes_args,
        takes_kwargs,
    )
    from codeweaver.core.utils.procs import (
        ModuleType,
        asyncio,
        asyncio_or_uvloop,
        contextmanager,
        effective_cpu_count,
        get_cpu_count,
        get_optimal_workers,
        low_priority,
        very_low_priority,
    )
    from codeweaver.core.utils.text import (
        BOUNDARY,
        CONTROL_CHARS,
        INJECT_PATTERN,
        INVISIBLE_CHARS,
        INVISIBLE_PATTERN,
        LOWLY_WORDS,
        MAX_REGEX_PATTERN_LENGTH,
        NORMALIZE_FORM,
        POSSIBLE_PROMPT_INJECTS,
        REMOVE_ID,
        ConfigurationError,
        NonNegativeFloat,
        elapsed_time_to_human_readable,
        format_descriptor,
        format_docstring,
        format_signature,
        format_snippet_name,
        humanize,
        re,
        sanitize_unicode,
        textcase,
        textwrap,
        to_lowly_lowercase,
        to_tokens,
        truncate_text,
        unicodedata,
        validate_regex_pattern,
        variable_to_env_var,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BACKUP_DENSE_VECTOR_NAME": (__spec__.parent, "constants"),
    "BACKUP_EMBEDDING_MODEL_FALLBACK": (__spec__.parent, "constants"),
    "BACKUP_EMBEDDING_MODEL_PRIMARY": (__spec__.parent, "constants"),
    "BACKUP_RERANKING_MODEL": (__spec__.parent, "constants"),
    "BASE_RETRYABLE_EXCEPTIONS": (__spec__.parent, "constants"),
    "BASEDMODEL_CONFIG": (__spec__.parent, "types.models"),
    "BASH_SHEBANG_PATTERN": (__spec__.parent, "metadata"),
    "BOUNDARY": (__spec__.parent, "utils.text"),
    "CODE_FILES_EXTENSIONS": (__spec__.parent, "file_extensions"),
    "CODEWEAVER_DESCRIPTION": (__spec__.parent, "constants"),
    "CODEWEAVER_ICON": (__spec__.parent, "constants"),
    "COMMON_LLM_TOOLING_PATHS": (__spec__.parent, "utils.filesystem"),
    "COMMON_TOOLING_PATHS": (__spec__.parent, "utils.filesystem"),
    "CONFIG_FILE_LANGUAGES": (__spec__.parent, "file_extensions"),
    "CONTEXT_AGENT_EXPLANATORY_TASK_CONFIG": (__spec__.parent, "constants"),
    "CONTEXT_AGENT_INTENT_AND_TASK_VALIDATION_CONFIG": (__spec__.parent, "constants"),
    "CONTEXT_AGENT_RESULT_REVIEW_CONFIG": (__spec__.parent, "constants"),
    "CONTEXT_AGENT_TAGS": (__spec__.parent, "constants"),
    "CONTROL_CHARS": (__spec__.parent, "utils.text"),
    "DATA_FILES_EXTENSIONS": (__spec__.parent, "file_extensions"),
    "DATACLASS_CONFIG": (__spec__.parent, "types.dataclasses"),
    "DATATYPE_FIELDS": (__spec__.parent, "constants"),
    "DEFAULT_AGENT_TEMPERATURE": (__spec__.parent, "constants"),
    "DEFAULT_AGENT_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_AGENT_TOP_P": (__spec__.parent, "constants"),
    "DEFAULT_BASE_SETTINGS_CONFIG": (__spec__.parent, "types.settings_model"),
    "DEFAULT_BLAKE_STORE_MAX_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_CHECKPOINT_SUBPATH": (__spec__.parent, "constants"),
    "DEFAULT_COLLECTION_NAME_PREFIX": (__spec__.parent, "constants"),
    "DEFAULT_DAEMON_STARTUP_CHECK_INTERVAL": (__spec__.parent, "constants"),
    "DEFAULT_DAEMON_STARTUP_WAIT": (__spec__.parent, "constants"),
    "DEFAULT_DENSE_WEIGHT": (__spec__.parent, "constants"),
    "DEFAULT_EMBEDDING_BATCH_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_EMBEDDING_REGISTRY_MAX_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_EMBEDDING_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_EXCLUDED_DIRS": (__spec__.parent, "file_extensions"),
    "DEFAULT_EXCLUDED_EXTENSIONS": (__spec__.parent, "file_extensions"),
    "DEFAULT_HNSW_EF_CONSTRUCTION": (__spec__.parent, "constants"),
    "DEFAULT_HNSW_FULL_SCAN_THRESHOLD": (__spec__.parent, "constants"),
    "DEFAULT_HNSW_M": (__spec__.parent, "constants"),
    "DEFAULT_HNSW_PAYLOAD_M": (__spec__.parent, "constants"),
    "DEFAULT_HOST": (__spec__.parent, "constants"),
    "DEFAULT_HTTPX_KEEPALIVE_EXPIRY": (__spec__.parent, "constants"),
    "DEFAULT_HTTPX_MAX_CONNECTIONS": (__spec__.parent, "constants"),
    "DEFAULT_HTTPX_MAX_KEEPALIVE_CONNECTIONS": (__spec__.parent, "constants"),
    "DEFAULT_LOCAL_EMBEDDING_BATCH_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_LOG_LEVEL": (__spec__.parent, "constants"),
    "DEFAULT_MANAGEMENT_PORT": (__spec__.parent, "constants"),
    "DEFAULT_MANIFEST_SUBPATH": (__spec__.parent, "constants"),
    "DEFAULT_MAX_CONCURRENT_BATCHES": (__spec__.parent, "constants"),
    "DEFAULT_MAX_QUEUE_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_MAX_RESULTS": (__spec__.parent, "constants"),
    "DEFAULT_MAX_TOKENS": (__spec__.parent, "constants"),
    "DEFAULT_MCP_MAX_RETRY_ATTEMPTS": (__spec__.parent, "constants"),
    "DEFAULT_MCP_PORT": (__spec__.parent, "constants"),
    "DEFAULT_MCP_RATE_LIMIT_BURST_CAPACITY": (__spec__.parent, "constants"),
    "DEFAULT_MCP_RATE_LIMIT_MAX_REQUESTS_PER_SECOND": (__spec__.parent, "constants"),
    "DEFAULT_MCP_RETRY_BACKOFF_MULTIPLIER": (__spec__.parent, "constants"),
    "DEFAULT_MCP_RETRY_BASE_DELAY": (__spec__.parent, "constants"),
    "DEFAULT_MCP_RETRY_MAX_DELAY": (__spec__.parent, "constants"),
    "DEFAULT_MCP_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_OPEN_BREAKER_DURATION": (__spec__.parent, "constants"),
    "DEFAULT_PERSIST_INTERVAL": (__spec__.parent, "constants"),
    "DEFAULT_POOL_ACQUIRE_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_POOL_CONNECTION_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_POOL_READ_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_POOL_WRITE_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_RECONCILIATION_SERVICE_BATCH_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_RERANKING_MAX_RESULTS": (__spec__.parent, "constants"),
    "DEFAULT_RERANKING_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_RICH_HANDLER_OPTIONS": (__spec__.parent, "constants"),
    "DEFAULT_SEMANTIC_IDENTIFICATION_CONFIDENCE_THRESHOLD": (__spec__.parent, "constants"),
    "DEFAULT_SERVER_SHUTDOWN_TIMEOUT": (__spec__.parent, "constants"),
    "DEFAULT_SNAPSHOT_RETENTION_COUNT": (__spec__.parent, "constants"),
    "DEFAULT_SPARSE_WEIGHT": (__spec__.parent, "constants"),
    "DEFAULT_USER_DIR_NAME": (__spec__.parent, "constants"),
    "DEFAULT_UUID_STORE_MAX_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_VECTOR_STORE_BATCH_SIZE": (__spec__.parent, "constants"),
    "DEFAULT_VECTOR_STORE_MAX_RESULTS": (__spec__.parent, "constants"),
    "DEFAULT_VECTOR_STORE_PERSIST_SUBPATH": (__spec__.parent, "constants"),
    "DEFAULT_WATCHER_DEBOUNCE_MILLISECONDS": (__spec__.parent, "constants"),
    "DEFAULT_WATCHER_GRACE_PERIOD": (__spec__.parent, "constants"),
    "DEFAULT_WATCHER_STEP_MILLISECONDS": (__spec__.parent, "constants"),
    "DIMENSION_FIELDS": (__spec__.parent, "constants"),
    "DOC_FILES_EXTENSIONS": (__spec__.parent, "file_extensions"),
    "ELLIPSIS": (__spec__.parent, "constants"),
    "ENV_CI_INDICATORS": (__spec__.parent, "constants"),
    "ENV_EXPLICIT_FALSE_VALUES": (__spec__.parent, "utils.environment"),
    "ENV_EXPLICIT_TRUE_VALUES": (__spec__.parent, "constants"),
    "ENV_JETBRAINS_INDICATOR": (__spec__.parent, "utils.environment"),
    "ENV_VSCODE_INDICATORS": (__spec__.parent, "utils.environment"),
    "EXTENSION_TESTS": (__spec__.parent, "metadata"),
    "FALLBACK_TEST": (__spec__.parent, "file_extensions"),
    "FILE_BATCH_SIZE": (__spec__.parent, "constants"),
    "FILTERED_KEYS": (__spec__.parent, "types.models"),
    "FIND_CODE_DESCRIPTION": (__spec__.parent, "constants"),
    "FIND_CODE_INSTRUCTION": (__spec__.parent, "constants"),
    "FIND_CODE_TITLE": (__spec__.parent, "constants"),
    "FIVE_MINUTES": (__spec__.parent, "constants"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "types.models"),
    "HEALTH_ENDPOINT": (__spec__.parent, "constants"),
    "INDEXER_WINDDOWN_TIMEOUT": (__spec__.parent, "constants"),
    "INJECT_PATTERN": (__spec__.parent, "utils.text"),
    "INJECTED": (__spec__.parent, "di.depends"),
    "INTROSPECTION_ATTRIBUTES": (__spec__.parent, "constants"),
    "INVISIBLE_CHARS": (__spec__.parent, "utils.text"),
    "INVISIBLE_PATTERN": (__spec__.parent, "utils.text"),
    "IS_CI": (__spec__.parent, "_logging"),
    "IS_TTY": (__spec__.parent, "_logging"),
    "LANGUAGE_SPECIFIC_PATHS": (__spec__.parent, "file_extensions"),
    "LANGUAGE_TO_FAMILY": (__spec__.parent, "types.delimiter"),
    "LOCALHOST": (__spec__.parent, "constants"),
    "LOCALHOST_INDICATORS": (__spec__.parent, "utils.checks"),
    "LOCALHOST_URL": (__spec__.parent, "utils.environment"),
    "LOG_PATH": (__spec__.parent, "_logging"),
    "LOGGERS_TO_SUPPRESS": (__spec__.parent, "constants"),
    "LOWLY_WORDS": (__spec__.parent, "utils.text"),
    "MAX_INLINE_CONTENT_SIZE": (__spec__.parent, "constants"),
    "MAX_REGEX_PATTERN_LENGTH": (__spec__.parent, "utils.text"),
    "MAX_RETRY_ATTEMPTS": (__spec__.parent, "constants"),
    "MAX_SEMANTIC_CHUNKER_RECURSION_DEPTH": (__spec__.parent, "constants"),
    "MCP_ENDPOINT": (__spec__.parent, "constants"),
    "METADATA_PATH": (__spec__.parent, "file_extensions"),
    "METRICS_ENDPOINT": (__spec__.parent, "constants"),
    "MISSING": (__spec__.parent, "utils.filesystem"),
    "NORMALIZE_FORM": (__spec__.parent, "utils.text"),
    "ONE": (__spec__.parent, "constants"),
    "ONE_DAY": (__spec__.parent, "constants"),
    "ONE_GIGABYTE": (__spec__.parent, "constants"),
    "ONE_HOUR": (__spec__.parent, "constants"),
    "ONE_HUNDRED": (__spec__.parent, "constants"),
    "ONE_HUNDRED_MEGABYTES": (__spec__.parent, "constants"),
    "ONE_KILOBYTE": (__spec__.parent, "constants"),
    "ONE_LINE": (__spec__.parent, "constants"),
    "ONE_MEGABYTE": (__spec__.parent, "constants"),
    "ONE_MILLISECOND_IN_MICROSECONDS": (__spec__.parent, "utils.generation"),
    "ONE_MINUTE": (__spec__.parent, "constants"),
    "ONE_POINT_ZERO": (__spec__.parent, "constants"),
    "ONE_SECOND": (__spec__.parent, "constants"),
    "ONNX_CUDA_PROVIDER": (__spec__.parent, "constants"),
    "PARALLEL_CHUNKING_THRESHOLD": (__spec__.parent, "constants"),
    "PERL_SHEBANG_PATTERN": (__spec__.parent, "metadata"),
    "POSIX_NEWLINE": (__spec__.parent, "constants"),
    "POSSIBLE_PROMPT_INJECTS": (__spec__.parent, "utils.text"),
    "PREFERRED_MODELS_FOR_CONTEXT_AGENT_TASKS": (__spec__.parent, "constants"),
    "PREFERRED_SEARCH_PROVIDER_ORDER": (__spec__.parent, "constants"),
    "PRIMARY_SPARSE_VECTOR_NAME": (__spec__.parent, "constants"),
    "PRIMARY_VECTOR_NAME": (__spec__.parent, "constants"),
    "PYDANTIC_AI_MODEL_CAPABILITIES_PROVIDERS": (__spec__.parent, "constants"),
    "PYTHON_SHEBANG": (__spec__.parent, "constants"),
    "PYTHON_SHEBANG_PATTERN": (__spec__.parent, "metadata"),
    "QDRANT_MEMORY_LOCATION": (__spec__.parent, "constants"),
    "RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL_BARE": (__spec__.parent, "constants"),
    "RECOMMENDED_CLOUD_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_CLOUD_RERANKING_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_LOCAL_CONTEXT_AGENT_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_LOCAL_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_LOCAL_RERANKING_MODEL": (__spec__.parent, "constants"),
    "RECOMMENDED_SPARSE_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "REMOVE_ID": (__spec__.parent, "utils.text"),
    "REPO_POLICY_FILES": (__spec__.parent, "file_extensions"),
    "SEMANTIC_CHUNKER_PERFORMANCE_THRESHOLD_MS": (__spec__.parent, "constants"),
    "SESSION_LOG_FILE": (__spec__.parent, "_logging"),
    "SETTINGS_ENDPOINT": (__spec__.parent, "constants"),
    "SHEBANG": (__spec__.parent, "constants"),
    "SHUTDOWN_ENDPOINT": (__spec__.parent, "constants"),
    "SOTA_CONTEXT_AGENT_MODEL": (__spec__.parent, "constants"),
    "SOTA_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "SOTA_RERANKING_MODEL": (__spec__.parent, "constants"),
    "SPACE": (__spec__.parent, "constants"),
    "STATE_ENDPOINT": (__spec__.parent, "constants"),
    "STATUS_ENDPOINT": (__spec__.parent, "constants"),
    "TAB": (__spec__.parent, "constants"),
    "TEN_MINUTES": (__spec__.parent, "constants"),
    "TEST_DIR_NAMES": (__spec__.parent, "file_extensions"),
    "TEST_FILE_PATTERNS": (__spec__.parent, "file_extensions"),
    "TYPE_CHECKING": (__spec__.parent, "utils"),
    "ULTRALIGHT_CONTEXT_AGENT_MODEL": (__spec__.parent, "constants"),
    "ULTRALIGHT_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "ULTRALIGHT_RERANKING_MODEL": (__spec__.parent, "constants"),
    "ULTRALIGHT_SPARSE_EMBEDDING_MODEL": (__spec__.parent, "constants"),
    "UNSET": (__spec__.parent, "types.sentinel"),
    "USER_AGENT_TAGS": (__spec__.parent, "constants"),
    "VERSION_ENDPOINT": (__spec__.parent, "constants"),
    "WATCHER_WINDDOWN_TIMEOUT": (__spec__.parent, "constants"),
    "WHITESPACES": (__spec__.parent, "constants"),
    "WINDOWS_NEWLINE": (__spec__.parent, "constants"),
    "ZERO": (__spec__.parent, "constants"),
    "ZERO_POINT_ZERO": (__spec__.parent, "constants"),
    "AfterValidator": (__spec__.parent, "types.search"),
    "Annotated": (__spec__.parent, "types.aliases"),
    "AnonymityConversion": (__spec__.parent, "types.dataclasses"),
    "Any": (__spec__.parent, "utils.checks"),
    "AnyUrl": (__spec__.parent, "utils.checks"),
    "AsyncPath": (__spec__.parent, "repo"),
    "Attribute": (__spec__.parent, "utils.introspect"),
    "BaseCodeWeaverSettings": (__spec__.parent, "types.settings_model"),
    "BaseCodeWeaverSettingsDict": (__spec__.parent, "config.types"),
    "BaseDataclassEnum": (__spec__.parent, "types.enum"),
    "BasedModel": (__spec__.parent, "types.embeddings"),
    "BaseEnum": (__spec__.parent, "types.delimiter"),
    "BaseEnumData": (__spec__.parent, "types.dataclasses"),
    "BaseModel": (__spec__.parent, "utils.checks"),
    "BaseSettings": (__spec__.parent, "types.settings_model"),
    "BatchKeys": (__spec__.parent, "chunks"),
    "BlakeHashKey": (__spec__.parent, "utils.generation"),
    "BlakeKey": (__spec__.parent, "utils.generation"),
    "BlakeStore": (__spec__.parent, "stores"),
    "Callable": (__spec__.parent, "utils.general"),
    "CallHookTimingDict": (__spec__.parent, "types.statistics"),
    "CategoryName": (__spec__.parent, "utils.general"),
    "ChunkEmbeddings": (__spec__.parent, "types.embeddings"),
    "ChunkKind": (__spec__.parent, "metadata"),
    "ChunkSource": (__spec__.parent, "metadata"),
    "CircularDependencyError": (__spec__.parent, "exceptions"),
    "ClassVar": (__spec__.parent, "exceptions"),
    "CodeChunk": (__spec__.parent, "types.embeddings"),
    "CodeChunkDict": (__spec__.parent, "chunks"),
    "CodeWeaverCoreSettings": (__spec__.parent, "config.core_settings"),
    "CodeWeaverDeveloperError": (__spec__.parent, "exceptions"),
    "CodeWeaverError": (__spec__.parent, "exceptions"),
    "CodeWeaverSettingsType": (__spec__.parent, "statistics"),
    "CodeWeaverSparseEmbedding": (__spec__.parent, "types.embeddings"),
    "CollectionNotFoundError": (__spec__.parent, "exceptions"),
    "ComputedFieldInfo": (__spec__.parent, "types.utils"),
    "ConfigDict": (__spec__.parent, "types.dataclasses"),
    "ConfigLanguage": (__spec__.parent, "language"),
    "ConfigurationError": (__spec__.parent, "utils.text"),
    "ConfigurationLockError": (__spec__.parent, "exceptions"),
    "Container": (__spec__.parent, "di.container"),
    "Coroutine": (__spec__.parent, "types.service_cards"),
    "DataclassSerializationMixin": (__spec__.parent, "types.dataclasses"),
    "DataType": (__spec__.parent, "types.embeddings"),
    "DatatypeMismatchError": (__spec__.parent, "exceptions"),
    "DefaultLoggingSettings": (__spec__.parent, "config._logging"),
    "DefaultTelemetrySettings": (__spec__.parent, "config.telemetry"),
    "DelimiterDict": (__spec__.parent, "types.delimiter"),
    "DelimiterKind": (__spec__.parent, "types.delimiter"),
    "DelimiterPattern": (__spec__.parent, "types.delimiter"),
    "DependencyInjectionError": (__spec__.parent, "exceptions"),
    "DependencyNotAvailableError": (__spec__.parent, "exceptions"),
    "DependencyResolutionError": (__spec__.parent, "exceptions"),
    "Depends": (__spec__.parent, "di.depends"),
    "DependsPlaceholder": (__spec__.parent, "di.depends"),
    "DeserializationKwargs": (__spec__.parent, "types.dataclasses"),
    "DevToolName": (__spec__.parent, "utils.filesystem"),
    "DevToolNameT": (__spec__.parent, "utils.filesystem"),
    "DictView": (__spec__.parent, "types.dictview"),
    "DimensionMismatchError": (__spec__.parent, "exceptions"),
    "DirectoryName": (__spec__.parent, "types.aliases"),
    "DirectoryPurpose": (__spec__.parent, "repo"),
    "DiscoveredFile": (__spec__.parent, "types.search"),
    "DontGenerateJsonSchema": (__spec__.parent, "types.sentinel"),
    "DynamicClassAttribute": (__spec__.parent, "types.utils"),
    "EmbeddingBatchInfo": (__spec__.parent, "types.embeddings"),
    "EmbeddingKind": (__spec__.parent, "types.embeddings"),
    "EmbeddingModelName": (__spec__.parent, "types.aliases"),
    "Enum": (__spec__.parent, "types.enum"),
    "EnvFormat": (__spec__.parent, "types.env"),
    "EnvVarInfo": (__spec__.parent, "types.env"),
    "ExtCategory": (__spec__.parent, "metadata"),
    "ExtLangPair": (__spec__.parent, "metadata"),
    "ExtTestDef": (__spec__.parent, "metadata"),
    "FailoverStats": (__spec__.parent, "statistics"),
    "FallBackTestDef": (__spec__.parent, "file_extensions"),
    "Field": (__spec__.parent, "types.aliases"),
    "FieldInfo": (__spec__.parent, "types.utils"),
    "FileExt": (__spec__.parent, "types.aliases"),
    "FileGlob": (__spec__.parent, "types.aliases"),
    "FileName": (__spec__.parent, "types.aliases"),
    "FileStatistics": (__spec__.parent, "statistics"),
    "FilteredKey": (__spec__.parent, "types.aliases"),
    "FormattersDict": (__spec__.parent, "config._logging"),
    "FrameType": (__spec__.parent, "types.sentinel"),
    "GenerateJsonSchema": (__spec__.parent, "types.sentinel"),
    "Generator": (__spec__.parent, "types.enum"),
    "GetCoreSchemaHandler": (__spec__.parent, "types.sentinel"),
    "GetJsonSchemaHandler": (__spec__.parent, "types.sentinel"),
    "GetPydanticSchema": (__spec__.parent, "types.aliases"),
    "HandlersDict": (__spec__.parent, "config._logging"),
    "Hashable": (__spec__.parent, "utils.general"),
    "HttpRequestsDict": (__spec__.parent, "types.statistics"),
    "Identifier": (__spec__.parent, "statistics"),
    "IncEx": (__spec__.parent, "types.dataclasses"),
    "IndexingError": (__spec__.parent, "exceptions"),
    "InitializationError": (__spec__.parent, "exceptions"),
    "IntifyingPatterns": (__spec__.parent, "telemetry.utils"),
    "InvalidEmbeddingModelError": (__spec__.parent, "exceptions"),
    "ItemsView": (__spec__.parent, "types.dictview"),
    "Iterable": (__spec__.parent, "utils.general"),
    "Iterator": (__spec__.parent, "types.dataclasses"),
    "JsonSchemaValue": (__spec__.parent, "types.sentinel"),
    "KeysView": (__spec__.parent, "types.dictview"),
    "LanguageConfigFile": (__spec__.parent, "language"),
    "LanguageFamily": (__spec__.parent, "types.delimiter"),
    "LanguageName": (__spec__.parent, "types.aliases"),
    "LineStrategy": (__spec__.parent, "types.delimiter"),
    "Literal": (__spec__.parent, "utils.environment"),
    "LiteralProvider": (__spec__.parent, "types"),
    "LiteralProviderCategory": (__spec__.parent, "types"),
    "LiteralString": (__spec__.parent, "types.aliases"),
    "LiteralStringT": (__spec__.parent, "utils.general"),
    "LlmToolName": (__spec__.parent, "utils.filesystem"),
    "LlmToolNameT": (__spec__.parent, "utils.filesystem"),
    "LocationInfo": (__spec__.parent, "exceptions"),
    "LoggersDict": (__spec__.parent, "config._logging"),
    "LoggingConfigDict": (__spec__.parent, "config._logging"),
    "LoggingSettingsDict": (__spec__.parent, "config._logging"),
    "Mapping": (__spec__.parent, "types.dictview"),
    "MappingProxyType": (__spec__.parent, "utils"),
    "McpComponentTimingDict": (__spec__.parent, "types.statistics"),
    "McpTimingDict": (__spec__.parent, "types.statistics"),
    "Metadata": (__spec__.parent, "types.search"),
    "Missing": (__spec__.parent, "utils.filesystem"),
    "MissingValueError": (__spec__.parent, "exceptions"),
    "ModelName": (__spec__.parent, "types.aliases"),
    "ModelSwitchError": (__spec__.parent, "exceptions"),
    "ModuleType": (__spec__.parent, "utils.procs"),
    "NamedTuple": (__spec__.parent, "exceptions"),
    "NewType": (__spec__.parent, "config._logging"),
    "NodeParsingFailureError": (__spec__.parent, "exceptions"),
    "NonNegativeFloat": (__spec__.parent, "utils.text"),
    "NonNegativeInt": (__spec__.parent, "utils.environment"),
    "NoOpProgressReporter": (__spec__.parent, "ui_protocol"),
    "NotRequired": (__spec__.parent, "types.dataclasses"),
    "Parameter": (__spec__.parent, "utils.introspect"),
    "Path": (__spec__.parent, "utils.checks"),
    "PathLike": (__spec__.parent, "types.aliases"),
    "PersistenceError": (__spec__.parent, "exceptions"),
    "PositiveInt": (__spec__.parent, "utils.environment"),
    "PrivateAttr": (__spec__.parent, "types.dataclasses"),
    "ProgressReporter": (__spec__.parent, "ui_protocol"),
    "Provider": (__spec__.parent, "utils.environment"),
    "ProviderCategory": (__spec__.parent, "types.provider"),
    "ProviderCategoryLiteralString": (__spec__.parent, "types"),
    "ProviderEnvVars": (__spec__.parent, "types.env"),
    "ProviderError": (__spec__.parent, "exceptions"),
    "ProviderLiteralString": (__spec__.parent, "types"),
    "ProviderMetadata": (__spec__.parent, "di.utils"),
    "ProviderSwitchError": (__spec__.parent, "exceptions"),
    "PydanticOmit": (__spec__.parent, "types.sentinel"),
    "QueryError": (__spec__.parent, "exceptions"),
    "QueryResult": (__spec__.parent, "types.embeddings"),
    "RepoChecklist": (__spec__.parent, "repo"),
    "RepoChecklistDict": (__spec__.parent, "repo"),
    "RepoConventions": (__spec__.parent, "language"),
    "RepoDirectory": (__spec__.parent, "repo"),
    "Required": (__spec__.parent, "types.delimiter"),
    "RerankingModelName": (__spec__.parent, "types.aliases"),
    "RerankingProviderError": (__spec__.parent, "exceptions"),
    "ResolutionResult": (__spec__.parent, "di.container"),
    "ResolvedProjectPathDep": (__spec__.parent, "discovery"),
    "RichConsoleProgressReporter": (__spec__.parent, "ui_protocol"),
    "Role": (__spec__.parent, "types.aliases"),
    "RootedRoot": (__spec__.parent, "types.models"),
    "RootModel": (__spec__.parent, "types.models"),
    "ScopeViolationError": (__spec__.parent, "exceptions"),
    "SearchEvent": (__spec__.parent, "telemetry.events"),
    "SearchResult": (__spec__.parent, "types.search"),
    "SearchStrategy": (__spec__.parent, "types.search"),
    "Self": (__spec__.parent, "types.dataclasses"),
    "SemanticSearchLanguage": (__spec__.parent, "language"),
    "Sentinel": (__spec__.parent, "types.sentinel"),
    "SentinelName": (__spec__.parent, "types.aliases"),
    "SentinelNameT": (__spec__.parent, "types.aliases"),
    "Sequence": (__spec__.parent, "utils.introspect"),
    "SerializableLoggingFilter": (__spec__.parent, "config._logging"),
    "SerializationKwargs": (__spec__.parent, "types.dataclasses"),
    "ServiceCard": (__spec__.parent, "types.service_cards"),
    "ServiceMetadata": (__spec__.parent, "types.service_cards"),
    "SessionEvent": (__spec__.parent, "telemetry.events"),
    "SessionStatistics": (__spec__.parent, "statistics"),
    "SetProviderEnvVarsDict": (__spec__.parent, "config.envs"),
    "SettingsConfigDict": (__spec__.parent, "types.settings_model"),
    "SettingsDep": (__spec__.parent, "dependencies.core_settings"),
    "SettingsEnvVars": (__spec__.parent, "config.envs"),
    "Signature": (__spec__.parent, "utils.introspect"),
    "Span": (__spec__.parent, "spans"),
    "SpanGroup": (__spec__.parent, "spans"),
    "SpanTuple": (__spec__.parent, "spans"),
    "StoreDict": (__spec__.parent, "stores"),
    "StrategizedQuery": (__spec__.parent, "types.search"),
    "TelemetryEvent": (__spec__.parent, "telemetry.events"),
    "TelemetryService": (__spec__.parent, "telemetry.client"),
    "TelemetrySettings": (__spec__.parent, "config.telemetry"),
    "TelemetrySettingsDict": (__spec__.parent, "config.telemetry"),
    "ThingName": (__spec__.parent, "types.aliases"),
    "TimingStatistics": (__spec__.parent, "statistics"),
    "TimingStatisticsDict": (__spec__.parent, "types.statistics"),
    "TokenCategory": (__spec__.parent, "statistics"),
    "TokenCost": (__spec__.parent, "statistics"),
    "TokenCounter": (__spec__.parent, "statistics"),
    "TracebackType": (__spec__.parent, "telemetry.client"),
    "TypeAdapter": (__spec__.parent, "utils.checks"),
    "TypeAliasType": (__spec__.parent, "di.container"),
    "TypedDict": (__spec__.parent, "types.dataclasses"),
    "TypeIs": (__spec__.parent, "utils.checks"),
    "Unpack": (__spec__.parent, "types.dataclasses"),
    "UnresolvableDependencyError": (__spec__.parent, "exceptions"),
    "Unset": (__spec__.parent, "types.sentinel"),
    "ValidationError": (__spec__.parent, "exceptions"),
    "ValuesView": (__spec__.parent, "types.dictview"),
    "VariableInfo": (__spec__.parent, "types.env"),
    "abc": (__spec__.parent, "types.models"),
    "add_enum_alias": (__spec__.parent, "types.utils"),
    "add_enum_member": (__spec__.parent, "types.utils"),
    "add_failed_request": (__spec__.parent, "statistics"),
    "add_successful_request": (__spec__.parent, "statistics"),
    "all_js_exts": (__spec__.parent, "file_extensions"),
    "asyncio": (__spec__.parent, "utils.procs"),
    "asyncio_or_uvloop": (__spec__.parent, "utils.procs"),
    "auto": (__spec__.parent, "types.enum"),
    "cache": (__spec__.parent, "utils.checks"),
    "cached_property": (__spec__.parent, "types.dataclasses"),
    "capture_search_event": (__spec__.parent, "telemetry.events"),
    "cast": (__spec__.parent, "utils.filesystem"),
    "clean_args": (__spec__.parent, "utils.introspect"),
    "clean_sentinel_from_schema": (__spec__.parent, "types.models"),
    "CLOUD_EMBEDDING_COST_PER_1K_TOKENS": (__spec__.parent, "constants"),
    "CLOUD_RERANKING_COST_PER_1K_TOKENS": (__spec__.parent, "constants"),
    "computed_field": (__spec__.parent, "types.enum"),
    "console": (__spec__.parent, "utils.environment"),
    "CONTEXT_AGENT_COST_PER_1K_TOKENS": (__spec__.parent, "constants"),
    "contextlib": (__spec__.parent, "utils.environment"),
    "contextmanager": (__spec__.parent, "utils.procs"),
    "core_schema": (__spec__.parent, "types.sentinel"),
    "create_session_file_handler": (__spec__.parent, "_logging"),
    "dataclass": (__spec__.parent, "types.dataclasses"),
    "datetime": (__spec__.parent, "utils.generation"),
    "deep_merge_dicts": (__spec__.parent, "utils.general"),
    "defaultdict": (__spec__.parent, "types.service_cards"),
    "dependency_provider": (__spec__.parent, "di.utils"),
    "depends": (__spec__.parent, "di.depends"),
    "detect_root_package": (__spec__.parent, "utils.environment"),
    "determine_ext_category": (__spec__.parent, "metadata"),
    "dict_set_to_tuple": (__spec__.parent, "utils.general"),
    "effective_cpu_count": (__spec__.parent, "utils.procs"),
    "elapsed_time_to_human_readable": (__spec__.parent, "utils.text"),
    "ensure_iterable": (__spec__.parent, "utils.general"),
    "file_is_binary": (__spec__.parent, "utils.checks"),
    "find_config_paths": (__spec__.parent, "language"),
    "find_qdrant_instance": (__spec__.parent, "utils.environment"),
    "format_descriptor": (__spec__.parent, "utils.text"),
    "format_docstring": (__spec__.parent, "utils.text"),
    "format_file_link": (__spec__.parent, "utils.environment"),
    "format_signature": (__spec__.parent, "utils.text"),
    "format_snippet_name": (__spec__.parent, "utils.text"),
    "generate_collection_name": (__spec__.parent, "utils.general"),
    "generate_field_title": (__spec__.parent, "types.dataclasses"),
    "generate_title": (__spec__.parent, "types.dataclasses"),
    "get_blake_hash": (__spec__.parent, "utils.generation"),
    "get_blake_hash_generic": (__spec__.parent, "utils.generation"),
    "get_caller": (__spec__.parent, "utils.introspect"),
    "get_caller_module": (__spec__.parent, "utils.introspect"),
    "get_caller_modulename": (__spec__.parent, "utils.introspect"),
    "get_categories": (__spec__.parent, "types.provider"),
    "get_class_attrs": (__spec__.parent, "utils.introspect"),
    "get_class_constructor": (__spec__.parent, "utils.introspect"),
    "get_class_methods": (__spec__.parent, "utils.introspect"),
    "get_class_properties": (__spec__.parent, "utils.introspect"),
    "get_class_variables": (__spec__.parent, "utils.introspect"),
    "get_codeweaver_config_paths": (__spec__.parent, "utils.environment"),
    "get_codeweaver_prefix": (__spec__.parent, "utils.environment"),
    "get_container": (__spec__.parent, "di.container"),
    "get_cpu_count": (__spec__.parent, "utils.procs"),
    "get_default_provider_import_for_category": (__spec__.parent, "types.provider"),
    "get_ext_lang_pair_for_file": (__spec__.parent, "metadata"),
    "get_ext_lang_pairs": (__spec__.parent, "metadata"),
    "get_ext_lang_pairs_generator": (__spec__.parent, "language"),
    "get_file_path": (__spec__.parent, "utils.introspect"),
    "get_function_annotations": (__spec__.parent, "utils.introspect"),
    "get_function_parameters": (__spec__.parent, "utils.introspect"),
    "get_function_signature": (__spec__.parent, "utils.introspect"),
    "get_generic_params_for_type": (__spec__.parent, "utils.introspect"),
    "get_git_branch": (__spec__.parent, "utils.filesystem"),
    "get_git_revision": (__spec__.parent, "utils.filesystem"),
    "get_language_from_extension": (__spec__.parent, "metadata"),
    "get_local_only_provider_members": (__spec__.parent, "types.service_cards"),
    "get_local_only_providers": (__spec__.parent, "types.service_cards"),
    "get_openai_provider_members": (__spec__.parent, "types.service_cards"),
    "get_openai_providers": (__spec__.parent, "types.service_cards"),
    "get_optimal_workers": (__spec__.parent, "utils.procs"),
    "get_possible_env_vars": (__spec__.parent, "utils.environment"),
    "get_project_path": (__spec__.parent, "utils.filesystem"),
    "get_provider_capabilities_map": (__spec__.parent, "types.service_cards"),
    "get_provider_category_sdk_clients_for_provider": (__spec__.parent, "types.service_cards"),
    "get_provider_clients": (__spec__.parent, "types.service_cards"),
    "get_provider_literals": (__spec__.parent, "types.service_cards"),
    "get_providers_for_category": (__spec__.parent, "types.service_cards"),
    "get_rich_console": (__spec__.parent, "_logging"),
    "get_rich_handler": (__spec__.parent, "_logging"),
    "get_sdk_client": (__spec__.parent, "types.service_cards"),
    "get_sdk_client_map": (__spec__.parent, "types.service_cards"),
    "get_semantic_or_config_lang": (__spec__.parent, "metadata"),
    "get_service_card": (__spec__.parent, "types.service_cards"),
    "get_service_cards": (__spec__.parent, "types.service_cards"),
    "get_session_log_path": (__spec__.parent, "_logging"),
    "get_session_statistics": (__spec__.parent, "statistics"),
    "get_settings": (__spec__.parent, "config.loader"),
    "get_sometimes_local_provider_members": (__spec__.parent, "types.service_cards"),
    "get_sometimes_local_providers": (__spec__.parent, "types.service_cards"),
    "get_source_code": (__spec__.parent, "utils.introspect"),
    "get_source_start_end": (__spec__.parent, "utils.introspect"),
    "get_terminal_width": (__spec__.parent, "utils.environment"),
    "get_tooling_dirs": (__spec__.parent, "utils.filesystem"),
    "get_user_cache_dir": (__spec__.parent, "utils.filesystem"),
    "get_user_config_dir": (__spec__.parent, "utils.filesystem"),
    "get_user_data_dir": (__spec__.parent, "utils.filesystem"),
    "get_user_state_dir": (__spec__.parent, "utils.filesystem"),
    "getdoc": (__spec__.parent, "utils.introspect"),
    "getmodule": (__spec__.parent, "utils.introspect"),
    "getmodulename": (__spec__.parent, "utils.introspect"),
    "getsourcefile": (__spec__.parent, "utils.introspect"),
    "has_git": (__spec__.parent, "utils.filesystem"),
    "has_package": (__spec__.parent, "utils.checks"),
    "has_semantic_extension": (__spec__.parent, "language"),
    "httpx": (__spec__.parent, "utils.checks"),
    "humanize": (__spec__.parent, "utils.text"),
    "importlib": (__spec__.parent, "utils.environment"),
    "in_codeweaver_clone": (__spec__.parent, "utils.filesystem"),
    "in_ide": (__spec__.parent, "utils.environment"),
    "inspect": (__spec__.parent, "utils.checks"),
    "is_ci": (__spec__.parent, "utils.checks"),
    "is_class": (__spec__.parent, "utils.checks"),
    "is_codeweaver_config_path": (__spec__.parent, "utils.environment"),
    "is_constructor_arg": (__spec__.parent, "utils.introspect"),
    "is_debug": (__spec__.parent, "utils.checks"),
    "is_depends_marker": (__spec__.parent, "di.depends"),
    "is_git_dir": (__spec__.parent, "utils.filesystem"),
    "is_local_host": (__spec__.parent, "utils.checks"),
    "is_pydantic_basemodel": (__spec__.parent, "utils.checks"),
    "is_semantic_config_ext": (__spec__.parent, "language"),
    "is_test_environment": (__spec__.parent, "utils.checks"),
    "is_tty": (__spec__.parent, "utils.environment"),
    "is_typeadapter": (__spec__.parent, "utils.checks"),
    "is_wsl": (__spec__.parent, "utils.checks"),
    "is_wsl_vscode": (__spec__.parent, "utils.checks"),
    "isclass": (__spec__.parent, "utils.introspect"),
    "isfunction": (__spec__.parent, "utils.introspect"),
    "ismethod": (__spec__.parent, "utils.introspect"),
    "keyword_args": (__spec__.parent, "utils.introspect"),
    "language_from_config_file": (__spec__.parent, "language"),
    "language_from_path": (__spec__.parent, "language"),
    "languages_present_from_configs": (__spec__.parent, "language"),
    "LiteralSDKClient": (__spec__.parent, "types"),
    "LOCAL_EMBEDDING_COST_PER_1K_TOKENS": (__spec__.parent, "constants"),
    "log_to_client_or_fallback": (__spec__.parent, "_logging"),
    "logger": (__spec__.parent, "utils.checks"),
    "logging": (__spec__.parent, "utils.checks"),
    "low_priority": (__spec__.parent, "utils.procs"),
    "make_blake_store": (__spec__.parent, "stores"),
    "make_uuid_store": (__spec__.parent, "stores"),
    "metadata": (__spec__.parent, "utils.checks"),
    "normalize_ext": (__spec__.parent, "utils.filesystem"),
    "normalize_language": (__spec__.parent, "statistics"),
    "os": (__spec__.parent, "utils.checks"),
    "overload": (__spec__.parent, "utils.generation"),
    "override": (__spec__.parent, "types.embeddings"),
    "platform": (__spec__.parent, "utils.checks"),
    "platformdirs": (__spec__.parent, "utils.filesystem"),
    "positional_args": (__spec__.parent, "utils.introspect"),
    "python_version": (__spec__.parent, "utils.checks"),
    "qdrant_instance_live_at_port": (__spec__.parent, "utils.environment"),
    "re": (__spec__.parent, "utils.text"),
    "record_timed_http_request": (__spec__.parent, "statistics"),
    "return_type": (__spec__.parent, "utils.introspect"),
    "rpartial": (__spec__.parent, "utils.general"),
    "sanitize_unicode": (__spec__.parent, "utils.text"),
    "SDKClient": (__spec__.parent, "types.provider"),
    "SDKClientLiteralString": (__spec__.parent, "types"),
    "service_card_factory": (__spec__.parent, "types.service_cards"),
    "set_relative_path": (__spec__.parent, "utils.filesystem"),
    "settings_type_for_root_package": (__spec__.parent, "utils.environment"),
    "setup_logger": (__spec__.parent, "_logging"),
    "shutil": (__spec__.parent, "utils.filesystem"),
    "subprocess": (__spec__.parent, "utils.filesystem"),
    "supported_language_count": (__spec__.parent, "utils.general"),
    "supported_languages": (__spec__.parent, "utils.general"),
    "sys": (__spec__.parent, "utils.checks"),
    "takes_args": (__spec__.parent, "utils.introspect"),
    "takes_kwargs": (__spec__.parent, "utils.introspect"),
    "textcase": (__spec__.parent, "utils.text"),
    "textwrap": (__spec__.parent, "utils.text"),
    "timed_http": (__spec__.parent, "statistics"),
    "to_lowly_lowercase": (__spec__.parent, "utils.text"),
    "to_tokens": (__spec__.parent, "utils.text"),
    "to_uuid": (__spec__.parent, "stores"),
    "truncate_text": (__spec__.parent, "utils.text"),
    "try_git_rev_parse": (__spec__.parent, "utils.filesystem"),
    "unicodedata": (__spec__.parent, "utils.text"),
    "unique": (__spec__.parent, "types.enum"),
    "urllib": (__spec__.parent, "utils.checks"),
    "USER_AGENT_COST_PER_1K_TOKENS": (__spec__.parent, "constants"),
    "util": (__spec__.parent, "utils.checks"),
    "UUID7": (__spec__.parent, "utils.generation"),
    "uuid7": (__spec__.parent, "utils.generation"),
    "uuid7_as_timestamp": (__spec__.parent, "utils.generation"),
    "UUID7Hex": (__spec__.parent, "types.aliases"),
    "UUID7HexT": (__spec__.parent, "types.aliases"),
    "UUIDStore": (__spec__.parent, "stores"),
    "validate_regex_pattern": (__spec__.parent, "utils.text"),
    "variable_to_env_var": (__spec__.parent, "utils.text"),
    "very_low_priority": (__spec__.parent, "utils.procs"),
    "we_are_in_jetbrains": (__spec__.parent, "utils.environment"),
    "we_are_in_vscode": (__spec__.parent, "utils.environment"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BACKUP_DENSE_VECTOR_NAME",
    "BACKUP_EMBEDDING_MODEL_FALLBACK",
    "BACKUP_EMBEDDING_MODEL_PRIMARY",
    "BACKUP_RERANKING_MODEL",
    "BASEDMODEL_CONFIG",
    "BASE_RETRYABLE_EXCEPTIONS",
    "BASH_SHEBANG_PATTERN",
    "BOUNDARY",
    "CLOUD_EMBEDDING_COST_PER_1K_TOKENS",
    "CLOUD_RERANKING_COST_PER_1K_TOKENS",
    "CODEWEAVER_DESCRIPTION",
    "CODEWEAVER_ICON",
    "CODE_FILES_EXTENSIONS",
    "COMMON_LLM_TOOLING_PATHS",
    "COMMON_TOOLING_PATHS",
    "CONFIG_FILE_LANGUAGES",
    "CONTEXT_AGENT_COST_PER_1K_TOKENS",
    "CONTEXT_AGENT_EXPLANATORY_TASK_CONFIG",
    "CONTEXT_AGENT_INTENT_AND_TASK_VALIDATION_CONFIG",
    "CONTEXT_AGENT_RESULT_REVIEW_CONFIG",
    "CONTEXT_AGENT_TAGS",
    "CONTROL_CHARS",
    "DATACLASS_CONFIG",
    "DATATYPE_FIELDS",
    "DATA_FILES_EXTENSIONS",
    "DEFAULT_AGENT_TEMPERATURE",
    "DEFAULT_AGENT_TIMEOUT",
    "DEFAULT_AGENT_TOP_P",
    "DEFAULT_BASE_SETTINGS_CONFIG",
    "DEFAULT_BLAKE_STORE_MAX_SIZE",
    "DEFAULT_CHECKPOINT_SUBPATH",
    "DEFAULT_COLLECTION_NAME_PREFIX",
    "DEFAULT_DAEMON_STARTUP_CHECK_INTERVAL",
    "DEFAULT_DAEMON_STARTUP_WAIT",
    "DEFAULT_DENSE_WEIGHT",
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "DEFAULT_EMBEDDING_REGISTRY_MAX_SIZE",
    "DEFAULT_EMBEDDING_TIMEOUT",
    "DEFAULT_EXCLUDED_DIRS",
    "DEFAULT_EXCLUDED_EXTENSIONS",
    "DEFAULT_HNSW_EF_CONSTRUCTION",
    "DEFAULT_HNSW_FULL_SCAN_THRESHOLD",
    "DEFAULT_HNSW_M",
    "DEFAULT_HNSW_PAYLOAD_M",
    "DEFAULT_HOST",
    "DEFAULT_HTTPX_KEEPALIVE_EXPIRY",
    "DEFAULT_HTTPX_MAX_CONNECTIONS",
    "DEFAULT_HTTPX_MAX_KEEPALIVE_CONNECTIONS",
    "DEFAULT_LOCAL_EMBEDDING_BATCH_SIZE",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_MANAGEMENT_PORT",
    "DEFAULT_MANIFEST_SUBPATH",
    "DEFAULT_MAX_CONCURRENT_BATCHES",
    "DEFAULT_MAX_QUEUE_SIZE",
    "DEFAULT_MAX_RESULTS",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_MCP_MAX_RETRY_ATTEMPTS",
    "DEFAULT_MCP_PORT",
    "DEFAULT_MCP_RATE_LIMIT_BURST_CAPACITY",
    "DEFAULT_MCP_RATE_LIMIT_MAX_REQUESTS_PER_SECOND",
    "DEFAULT_MCP_RETRY_BACKOFF_MULTIPLIER",
    "DEFAULT_MCP_RETRY_BASE_DELAY",
    "DEFAULT_MCP_RETRY_MAX_DELAY",
    "DEFAULT_MCP_TIMEOUT",
    "DEFAULT_OPEN_BREAKER_DURATION",
    "DEFAULT_PERSIST_INTERVAL",
    "DEFAULT_POOL_ACQUIRE_TIMEOUT",
    "DEFAULT_POOL_CONNECTION_TIMEOUT",
    "DEFAULT_POOL_READ_TIMEOUT",
    "DEFAULT_POOL_WRITE_TIMEOUT",
    "DEFAULT_RECONCILIATION_SERVICE_BATCH_SIZE",
    "DEFAULT_RERANKING_MAX_RESULTS",
    "DEFAULT_RERANKING_TIMEOUT",
    "DEFAULT_RICH_HANDLER_OPTIONS",
    "DEFAULT_SEMANTIC_IDENTIFICATION_CONFIDENCE_THRESHOLD",
    "DEFAULT_SERVER_SHUTDOWN_TIMEOUT",
    "DEFAULT_SNAPSHOT_RETENTION_COUNT",
    "DEFAULT_SPARSE_WEIGHT",
    "DEFAULT_USER_DIR_NAME",
    "DEFAULT_UUID_STORE_MAX_SIZE",
    "DEFAULT_VECTOR_STORE_BATCH_SIZE",
    "DEFAULT_VECTOR_STORE_MAX_RESULTS",
    "DEFAULT_VECTOR_STORE_PERSIST_SUBPATH",
    "DEFAULT_WATCHER_DEBOUNCE_MILLISECONDS",
    "DEFAULT_WATCHER_GRACE_PERIOD",
    "DEFAULT_WATCHER_STEP_MILLISECONDS",
    "DIMENSION_FIELDS",
    "DOC_FILES_EXTENSIONS",
    "ELLIPSIS",
    "ENV_CI_INDICATORS",
    "ENV_EXPLICIT_FALSE_VALUES",
    "ENV_EXPLICIT_TRUE_VALUES",
    "ENV_JETBRAINS_INDICATOR",
    "ENV_VSCODE_INDICATORS",
    "EXTENSION_TESTS",
    "FALLBACK_TEST",
    "FILE_BATCH_SIZE",
    "FILTERED_KEYS",
    "FIND_CODE_DESCRIPTION",
    "FIND_CODE_INSTRUCTION",
    "FIND_CODE_TITLE",
    "FIVE_MINUTES",
    "FROZEN_BASEDMODEL_CONFIG",
    "HEALTH_ENDPOINT",
    "INDEXER_WINDDOWN_TIMEOUT",
    "INJECTED",
    "INJECT_PATTERN",
    "INTROSPECTION_ATTRIBUTES",
    "INVISIBLE_CHARS",
    "INVISIBLE_PATTERN",
    "IS_CI",
    "IS_TTY",
    "LANGUAGE_SPECIFIC_PATHS",
    "LANGUAGE_TO_FAMILY",
    "LOCALHOST",
    "LOCALHOST_INDICATORS",
    "LOCALHOST_URL",
    "LOCAL_EMBEDDING_COST_PER_1K_TOKENS",
    "LOGGERS_TO_SUPPRESS",
    "LOG_PATH",
    "LOWLY_WORDS",
    "MAX_INLINE_CONTENT_SIZE",
    "MAX_REGEX_PATTERN_LENGTH",
    "MAX_RETRY_ATTEMPTS",
    "MAX_SEMANTIC_CHUNKER_RECURSION_DEPTH",
    "MCP_ENDPOINT",
    "METADATA_PATH",
    "METRICS_ENDPOINT",
    "MISSING",
    "NORMALIZE_FORM",
    "ONE",
    "ONE_DAY",
    "ONE_GIGABYTE",
    "ONE_HOUR",
    "ONE_HUNDRED",
    "ONE_HUNDRED_MEGABYTES",
    "ONE_KILOBYTE",
    "ONE_LINE",
    "ONE_MEGABYTE",
    "ONE_MILLISECOND_IN_MICROSECONDS",
    "ONE_MINUTE",
    "ONE_POINT_ZERO",
    "ONE_SECOND",
    "ONNX_CUDA_PROVIDER",
    "PARALLEL_CHUNKING_THRESHOLD",
    "PERL_SHEBANG_PATTERN",
    "POSIX_NEWLINE",
    "POSSIBLE_PROMPT_INJECTS",
    "PREFERRED_MODELS_FOR_CONTEXT_AGENT_TASKS",
    "PREFERRED_SEARCH_PROVIDER_ORDER",
    "PRIMARY_SPARSE_VECTOR_NAME",
    "PRIMARY_VECTOR_NAME",
    "PYDANTIC_AI_MODEL_CAPABILITIES_PROVIDERS",
    "PYTHON_SHEBANG",
    "PYTHON_SHEBANG_PATTERN",
    "QDRANT_MEMORY_LOCATION",
    "RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL",
    "RECOMMENDED_CLOUD_CONTEXT_AGENT_MODEL_BARE",
    "RECOMMENDED_CLOUD_EMBEDDING_MODEL",
    "RECOMMENDED_CLOUD_RERANKING_MODEL",
    "RECOMMENDED_LOCAL_CONTEXT_AGENT_MODEL",
    "RECOMMENDED_LOCAL_EMBEDDING_MODEL",
    "RECOMMENDED_LOCAL_RERANKING_MODEL",
    "RECOMMENDED_SPARSE_EMBEDDING_MODEL",
    "REMOVE_ID",
    "REPO_POLICY_FILES",
    "SEMANTIC_CHUNKER_PERFORMANCE_THRESHOLD_MS",
    "SESSION_LOG_FILE",
    "SETTINGS_ENDPOINT",
    "SHEBANG",
    "SHUTDOWN_ENDPOINT",
    "SOTA_CONTEXT_AGENT_MODEL",
    "SOTA_EMBEDDING_MODEL",
    "SOTA_RERANKING_MODEL",
    "SPACE",
    "STATE_ENDPOINT",
    "STATUS_ENDPOINT",
    "TAB",
    "TEN_MINUTES",
    "TEST_DIR_NAMES",
    "TEST_FILE_PATTERNS",
    "TYPE_CHECKING",
    "ULTRALIGHT_CONTEXT_AGENT_MODEL",
    "ULTRALIGHT_EMBEDDING_MODEL",
    "ULTRALIGHT_RERANKING_MODEL",
    "ULTRALIGHT_SPARSE_EMBEDDING_MODEL",
    "UNSET",
    "USER_AGENT_COST_PER_1K_TOKENS",
    "USER_AGENT_TAGS",
    "UUID7",
    "UUID7_STR",
    "VERSION_ENDPOINT",
    "WATCHER_WINDDOWN_TIMEOUT",
    "WHITESPACES",
    "WINDOWS_NEWLINE",
    "ZERO",
    "ZERO_POINT_ZERO",
    "AfterValidator",
    "Annotated",
    "AnonymityConversion",
    "Any",
    "AnyUrl",
    "AsyncPath",
    "Attribute",
    "BaseCodeWeaverSettings",
    "BaseCodeWeaverSettingsDict",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BaseModel",
    "BaseSettings",
    "BasedModel",
    "BatchKeys",
    "BlakeHashKey",
    "BlakeKey",
    "BlakeStore",
    "CallHookTimingDict",
    "Callable",
    "CategoryKey",
    "CategoryName",
    "CategoryNameT",
    "ChunkEmbeddings",
    "ChunkKind",
    "ChunkSequence",
    "ChunkSource",
    "CircularDependencyError",
    "ClassVar",
    "CodeChunk",
    "CodeChunkDict",
    "CodeWeaverCoreSettings",
    "CodeWeaverDeveloperError",
    "CodeWeaverError",
    "CodeWeaverSettingsType",
    "CodeWeaverSparseEmbedding",
    "CollectionNotFoundError",
    "ComputedFieldInfo",
    "ConfigDict",
    "ConfigLanguage",
    "ConfigurationError",
    "ConfigurationLockError",
    "Container",
    "Coroutine",
    "DataType",
    "DataclassSerializationMixin",
    "DatatypeMismatchError",
    "DefaultLoggingSettings",
    "DefaultTelemetrySettings",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterPattern",
    "DependencyInjectionError",
    "DependencyNotAvailableError",
    "DependencyResolutionError",
    "Depends",
    "DependsPlaceholder",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictInputTypesT",
    "DictOutputTypesT",
    "DictView",
    "DimensionMismatchError",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DirectoryPurpose",
    "DiscoveredFile",
    "DontGenerateJsonSchema",
    "DynamicClassAttribute",
    "EmbeddingBatchInfo",
    "EmbeddingKind",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "Enum",
    "EnvFormat",
    "EnvVarInfo",
    "ExtCategory",
    "ExtLangPair",
    "ExtTestDef",
    "FailoverStats",
    "FallBackTestDef",
    "Field",
    "FieldInfo",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FileStatistics",
    "FilteredCallable",
    "FilteredKey",
    "FilteredKeyT",
    "FilteredReturn",
    "FiltersDict",
    "FormattersDict",
    "FrameType",
    "GenerateJsonSchema",
    "Generator",
    "GetCoreSchemaHandler",
    "GetJsonSchemaHandler",
    "GetPydanticSchema",
    "HandlersDict",
    "Hashable",
    "HttpRequestsDict",
    "Identifier",
    "IncEx",
    "IndexingError",
    "InitializationError",
    "IntifyingPatterns",
    "InvalidEmbeddingModelError",
    "ItemsView",
    "Iterable",
    "Iterator",
    "JsonSchemaValue",
    "KeyPath",
    "KeysView",
    "LanguageConfigFile",
    "LanguageFamily",
    "LanguageName",
    "LanguageNameT",
    "LineStrategy",
    "Literal",
    "LiteralProvider",
    "LiteralProviderCategory",
    "LiteralProviderCategoryType",
    "LiteralProviderType",
    "LiteralSDKClient",
    "LiteralSDKClientType",
    "LiteralString",
    "LiteralStringT",
    "LlmTool",
    "LlmToolName",
    "LlmToolNameT",
    "LocationInfo",
    "LoggerDep",
    "LoggersDict",
    "LoggingConfigDict",
    "LoggingSettingsDep",
    "LoggingSettingsDict",
    "Mapping",
    "MappingProxyType",
    "McpComponentRequests",
    "McpComponentTimingDict",
    "McpOperationRequests",
    "McpTimingDict",
    "Metadata",
    "Missing",
    "MissingValueError",
    "ModelName",
    "ModelNameT",
    "ModelSwitchError",
    "ModuleType",
    "NamedTuple",
    "NewType",
    "NoOpProgressReporter",
    "NodeParsingFailureError",
    "NonNegativeFloat",
    "NonNegativeInt",
    "NotRequired",
    "OperationsKey",
    "Parameter",
    "Path",
    "PathLike",
    "PathOrFalse",
    "PersistenceError",
    "PositiveInt",
    "PrivateAttr",
    "ProgressReporter",
    "ProgressReporterDep",
    "Provider",
    "ProviderCategory",
    "ProviderCategoryLiteralString",
    "ProviderEnvVars",
    "ProviderError",
    "ProviderKey",
    "ProviderLiteralString",
    "ProviderMetadata",
    "ProviderSwitchError",
    "PydanticOmit",
    "QueryError",
    "QueryResult",
    "RawEmbeddingVectors",
    "RepoChecklist",
    "RepoChecklistDict",
    "RepoConventions",
    "RepoDirectory",
    "RequestKind",
    "Required",
    "RerankingModelName",
    "RerankingModelNameT",
    "RerankingProviderError",
    "ResolutionResult",
    "ResolvedGitBranchDep",
    "ResolvedProjectNameDep",
    "ResolvedProjectPathDep",
    "ResolvedProjectPathHashDep",
    "ResourceUri",
    "RichConsoleProgressReporter",
    "Role",
    "RoleT",
    "RootModel",
    "RootedRoot",
    "SDKClient",
    "SDKClientLiteralString",
    "ScopeViolationError",
    "SearchEvent",
    "SearchResult",
    "SearchStrategy",
    "SecondarySupportedLanguage",
    "Self",
    "SemanticSearchLanguage",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "Sequence",
    "SerializableLoggingFilter",
    "SerializationKwargs",
    "SerializedCodeChunk",
    "SerializedStrOnlyCodeChunk",
    "ServiceCard",
    "ServiceCardsDep",
    "ServiceMetadata",
    "SessionEvent",
    "SessionStatistics",
    "SetProviderEnvVarsDict",
    "SettingsConfigDict",
    "SettingsDep",
    "SettingsEnvVars",
    "SettingsMapDep",
    "Signature",
    "Span",
    "SpanGroup",
    "SpanTuple",
    "StatisticsDep",
    "StoreDict",
    "StoredEmbeddingVectors",
    "StrategizedQuery",
    "StructuredDataInput",
    "SummaryKey",
    "TelemetryEvent",
    "TelemetryService",
    "TelemetryServiceDep",
    "TelemetrySettings",
    "TelemetrySettingsDep",
    "TelemetrySettingsDict",
    "ThingName",
    "ThingNameT",
    "ThingOrCategoryNameT",
    "TimingStatistics",
    "TimingStatisticsDict",
    "TokenCategory",
    "TokenCost",
    "TokenCounter",
    "ToolOrPromptName",
    "TracebackType",
    "TypeAdapter",
    "TypeAliasType",
    "TypeIs",
    "TypedDict",
    "UUID7Hex",
    "UUID7HexT",
    "UUIDStore",
    "Unpack",
    "UnresolvableDependencyError",
    "Unset",
    "ValidationError",
    "ValuesView",
    "VariableInfo",
    "abc",
    "add_enum_alias",
    "add_enum_member",
    "add_failed_request",
    "add_successful_request",
    "all_js_exts",
    "asyncio",
    "asyncio_or_uvloop",
    "auto",
    "cache",
    "cached_property",
    "capture_search_event",
    "cast",
    "clean_args",
    "clean_sentinel_from_schema",
    "computed_field",
    "console",
    "contextlib",
    "contextmanager",
    "core_schema",
    "create_session_file_handler",
    "dataclass",
    "datetime",
    "deep_merge_dicts",
    "defaultdict",
    "dependency_provider",
    "depends",
    "detect_root_package",
    "determine_ext_category",
    "dict_set_to_tuple",
    "effective_cpu_count",
    "elapsed_time_to_human_readable",
    "ensure_iterable",
    "file_is_binary",
    "find_config_paths",
    "find_qdrant_instance",
    "format_descriptor",
    "format_docstring",
    "format_file_link",
    "format_signature",
    "format_snippet_name",
    "generate_collection_name",
    "generate_field_title",
    "generate_title",
    "get_blake_hash",
    "get_blake_hash_generic",
    "get_caller",
    "get_caller_module",
    "get_caller_modulename",
    "get_categories",
    "get_class_attrs",
    "get_class_constructor",
    "get_class_methods",
    "get_class_properties",
    "get_class_variables",
    "get_codeweaver_config_paths",
    "get_codeweaver_prefix",
    "get_container",
    "get_cpu_count",
    "get_default_provider_import_for_category",
    "get_ext_lang_pair_for_file",
    "get_ext_lang_pairs",
    "get_ext_lang_pairs_generator",
    "get_file_path",
    "get_function_annotations",
    "get_function_parameters",
    "get_function_signature",
    "get_generic_params_for_type",
    "get_git_branch",
    "get_git_revision",
    "get_language_from_extension",
    "get_local_only_provider_members",
    "get_local_only_providers",
    "get_openai_provider_members",
    "get_openai_providers",
    "get_optimal_workers",
    "get_possible_env_vars",
    "get_project_path",
    "get_provider_capabilities_map",
    "get_provider_category_sdk_clients_for_provider",
    "get_provider_clients",
    "get_provider_literals",
    "get_providers_for_category",
    "get_rich_console",
    "get_rich_handler",
    "get_sdk_client",
    "get_sdk_client_map",
    "get_semantic_or_config_lang",
    "get_service_card",
    "get_service_cards",
    "get_session_log_path",
    "get_session_statistics",
    "get_settings",
    "get_sometimes_local_provider_members",
    "get_sometimes_local_providers",
    "get_source_code",
    "get_source_start_end",
    "get_terminal_width",
    "get_tooling_dirs",
    "get_user_cache_dir",
    "get_user_config_dir",
    "get_user_data_dir",
    "get_user_state_dir",
    "getdoc",
    "getmodule",
    "getmodulename",
    "getsourcefile",
    "has_git",
    "has_package",
    "has_semantic_extension",
    "httpx",
    "humanize",
    "importlib",
    "in_codeweaver_clone",
    "in_ide",
    "inspect",
    "is_ci",
    "is_class",
    "is_codeweaver_config_path",
    "is_constructor_arg",
    "is_debug",
    "is_depends_marker",
    "is_git_dir",
    "is_local_host",
    "is_pydantic_basemodel",
    "is_semantic_config_ext",
    "is_test_environment",
    "is_tty",
    "is_typeadapter",
    "is_wsl",
    "is_wsl_vscode",
    "isclass",
    "isfunction",
    "ismethod",
    "keyword_args",
    "language_from_config_file",
    "language_from_path",
    "languages_present_from_configs",
    "log_to_client_or_fallback",
    "logger",
    "logging",
    "low_priority",
    "make_blake_store",
    "make_uuid_store",
    "metadata",
    "normalize_ext",
    "normalize_language",
    "os",
    "overload",
    "override",
    "platform",
    "platformdirs",
    "positional_args",
    "python_version",
    "qdrant_instance_live_at_port",
    "re",
    "record_timed_http_request",
    "return_type",
    "rpartial",
    "sanitize_unicode",
    "service_card_factory",
    "set_relative_path",
    "settings_type_for_root_package",
    "setup_logger",
    "shutil",
    "subprocess",
    "supported_language_count",
    "supported_languages",
    "sys",
    "takes_args",
    "takes_kwargs",
    "textcase",
    "textwrap",
    "timed_http",
    "to_lowly_lowercase",
    "to_tokens",
    "to_uuid",
    "truncate_text",
    "try_git_rev_parse",
    "unicodedata",
    "unique",
    "urllib",
    "util",
    "uuid7",
    "uuid7_as_timestamp",
    "validate_regex_pattern",
    "variable_to_env_var",
    "very_low_priority",
    "we_are_in_jetbrains",
    "we_are_in_vscode",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
