# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""
Constants used throughout the CodeWeaver project, primarily for default configurations.
"""

from __future__ import annotations

from pathlib import Path
from types import MappingProxyType
from typing import Literal, TypedDict

from codeweaver.core.metadata import ExtLangPair
from codeweaver.core.types import (
    DevToolName,
    DevToolNameT,
    DirectoryName,
    DirectoryNameT,
    FileExt,
    FileGlob,
    FileGlobT,
    LanguageName,
    LiteralStringT,
    LlmToolName,
    LlmToolNameT,
)


METADATA_PATH = "metadata"


DEFAULT_EXCLUDED_DIRS: frozenset[DirectoryName] = frozenset({
    DirectoryName(".DS_Store"),
    DirectoryName(".cache"),
    DirectoryName(".eslintcache"),
    DirectoryName(".git"),
    DirectoryName(".hg"),
    DirectoryName(".history"),
    DirectoryName(".idea"),
    DirectoryName(".jj"),
    DirectoryName(".next"),
    DirectoryName(".nuxt"),
    DirectoryName(".ruff_cache"),
    DirectoryName(".svn"),
    DirectoryName(".temp"),
    DirectoryName(".tmp"),
    DirectoryName(".tsbuildinfo"),
    DirectoryName(".venv"),
    DirectoryName(".vs"),
    DirectoryName("Debug"),
    DirectoryName("Release"),
    DirectoryName("Releases"),
    DirectoryName("Thumbs.db"),
    DirectoryName("__pycache__"),
    DirectoryName("__pytest_cache__"),
    DirectoryName("aarch64"),
    DirectoryName("arm"),
    DirectoryName("arm64"),
    DirectoryName("bower_components"),
    DirectoryName("debug"),
    DirectoryName("dist"),
    DirectoryName("htmlcov"),
    DirectoryName("lib64"),
    DirectoryName("log"),
    DirectoryName("logs"),
    DirectoryName("node_modules"),
    DirectoryName("obj"),
    DirectoryName("out"),
    DirectoryName("release"),
    DirectoryName("releases"),
    DirectoryName("remote-debug-profile"),
    DirectoryName("site"),
    DirectoryName("target"),
    DirectoryName("temp"),
    DirectoryName("tmp"),
    DirectoryName("vendor"),
    DirectoryName("venv"),
    DirectoryName("win32"),
    DirectoryName("win64"),
    DirectoryName("x64"),
    DirectoryName("x86"),
})

DEFAULT_EXCLUDED_EXTENSIONS: frozenset[FileExt] = frozenset({
    FileExt(".7z"),
    FileExt(".avi"),
    FileExt(".avif"),
    FileExt(".bmp"),
    FileExt(".builds"),
    FileExt(".cache"),
    FileExt(".class"),
    FileExt("codeweaver.local.json"),
    FileExt("codeweaver.local.toml"),
    FileExt("codeweaver.local.yaml"),
    FileExt(".code-workspace"),
    FileExt(".coverage"),
    FileExt(".coverage.xml"),
    FileExt(".dll"),
    FileExt(".dmg"),
    FileExt(".env"),
    FileExt(".exe"),
    FileExt(".gif"),
    FileExt(".gz"),
    FileExt(".iobj"),
    FileExt(".jar"),
    FileExt(".jpeg"),
    FileExt(".jpg"),
    FileExt(".lcov"),
    FileExt(".local"),
    FileExt(".lock"),
    FileExt(".log"),
    FileExt(".meta"),
    FileExt(".mov"),
    FileExt(".mp3"),
    FileExt(".mp4"),
    FileExt(".mpeg"),
    FileExt(".mpg"),
    FileExt(".ms"),
    FileExt(".msi"),
    FileExt(".o"),
    FileExt(".obj"),
    FileExt(".pch"),
    FileExt(".pdb"),
    FileExt(".pgc"),
    FileExt(".pgd"),
    FileExt(".png"),
    FileExt(".pyc"),
    FileExt(".pyo"),
    FileExt(".rar"),
    FileExt(".rsp"),
    FileExt(".scc"),
    FileExt(".sig"),
    FileExt(".snk"),
    FileExt(".so"),
    FileExt(".svclog"),
    FileExt(".svg"),
    FileExt(".swo"),
    FileExt(".swp"),
    FileExt(".tar"),
    FileExt(".temp"),
    FileExt(".tlb"),
    FileExt(".tlog"),
    FileExt(".tmp"),
    FileExt(".tmp_proj"),
    FileExt(".vspec"),
    FileExt(".vssscc"),
    FileExt(".wav"),
    FileExt(".webm"),
    FileExt(".webp"),
    FileExt(".zip"),
})

DATA_FILES_EXTENSIONS: tuple[ExtLangPair, ...] = (
    ExtLangPair(ext=FileExt(".csv"), language=LanguageName("csv")),
    ExtLangPair(ext=FileExt(".dat"), language=LanguageName("data")),
    ExtLangPair(ext=FileExt(".db"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".dbf"), language=LanguageName("dbf")),
    ExtLangPair(
        ext=FileExt(".nw"), language=LanguageName("nw")
    ),  # Node-Webkit (.zip container with .nw extension) files
    ExtLangPair(ext=FileExt(".sqlite"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".sqlite3"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".svg"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".tsv"), language=LanguageName("tsv")),
    ExtLangPair(ext=FileExt(".xlsx"), language=LanguageName("excel")),
)

DOC_FILES_EXTENSIONS: tuple[ExtLangPair, ...] = (
    ExtLangPair(ext=FileExt(".1"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".2"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".3"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".4"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".5"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".6"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".7"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".8"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".9"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".Rmd"), language=LanguageName("rmarkdown")),
    ExtLangPair(ext=FileExt(".adoc"), language=LanguageName("asciidoc")),
    ExtLangPair(ext=FileExt(".asc"), language=LanguageName("asciidoc")),
    ExtLangPair(ext=FileExt(".asciidoc"), language=LanguageName("asciidoc")),
    ExtLangPair(ext=FileExt(".bib"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".confluence"), language=LanguageName("confluence")),
    ExtLangPair(ext=FileExt(".creole"), language=LanguageName("creole")),
    ExtLangPair(ext=FileExt(".dita"), language=LanguageName("dita")),
    ExtLangPair(ext=FileExt(".docbook"), language=LanguageName("docbook")),
    ExtLangPair(ext=FileExt(".help"), language=LanguageName("help")),
    ExtLangPair(ext=FileExt(".hlp"), language=LanguageName("help")),
    ExtLangPair(ext=FileExt(".info"), language=LanguageName("info")),
    ExtLangPair(ext=FileExt(".ipynb"), language=LanguageName("jupyter")),
    ExtLangPair(ext=FileExt(".lagda"), language=LanguageName("lagda")),
    ExtLangPair(ext=FileExt(".latex"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".lhs"), language=LanguageName("lhs")),
    ExtLangPair(ext=FileExt(".man"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".manpage"), language=LanguageName("man")),
    ExtLangPair(ext=FileExt(".markdown"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".md"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".mdown"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".mdx"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".mediawiki"), language=LanguageName("mediawiki")),
    ExtLangPair(ext=FileExt(".mkd"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".mkdn"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".org"), language=LanguageName("org")),
    ExtLangPair(ext=FileExt(".pod"), language=LanguageName("pod")),
    ExtLangPair(ext=FileExt(".pyx"), language=LanguageName("cython")),
    ExtLangPair(ext=FileExt(".rdoc"), language=LanguageName("markdown")),
    ExtLangPair(ext=FileExt(".rest"), language=LanguageName("restructuredtext")),
    ExtLangPair(ext=FileExt(".rmd"), language=LanguageName("rmd")),
    ExtLangPair(ext=FileExt(".rnw"), language=LanguageName("rnw")),
    ExtLangPair(ext=FileExt(".rst"), language=LanguageName("restructuredtext")),
    ExtLangPair(ext=FileExt(".rtf"), language=LanguageName("rtf")),
    ExtLangPair(ext=FileExt(".tex"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".texi"), language=LanguageName("texinfo")),
    ExtLangPair(ext=FileExt(".texinfo"), language=LanguageName("texinfo")),
    ExtLangPair(ext=FileExt(".text"), language=LanguageName("text")),
    ExtLangPair(ext=FileExt(".textile"), language=LanguageName("textile")),
    ExtLangPair(ext=FileExt(".txt"), language=LanguageName("text")),
    ExtLangPair(ext=FileExt(".wiki"), language=LanguageName("wiki")),
    ExtLangPair(ext=FileExt(".xml"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".yard"), language=LanguageName("yard")),
)
"""A tuple of `ExtLangPair` for documentation files."""

# spellchecker:off
CODE_FILES_EXTENSIONS: tuple[ExtLangPair, ...] = (
    ExtLangPair(ext=FileExt(".F"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".R"), language=LanguageName("r")),
    ExtLangPair(ext=FileExt(".Rprofile"), language=LanguageName("r")),
    ExtLangPair(ext=FileExt(".app.src"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".as"), language=LanguageName("assemblyscript")),
    ExtLangPair(ext=FileExt(".asd"), language=LanguageName("lisp")),
    ExtLangPair(ext=FileExt(".asm"), language=LanguageName("assembly")),
    ExtLangPair(ext=FileExt(".aux"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".astro"), language=LanguageName("astro")),
    ExtLangPair(ext=FileExt(".bat"), language=LanguageName("batch")),
    ExtLangPair(ext=FileExt(".bb"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".beef"), language=LanguageName("beef")),
    ExtLangPair(ext=FileExt(".binpb"), language=LanguageName("protobuf")),
    ExtLangPair(ext=FileExt(".boot"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".carbon"), language=LanguageName("carbon")),
    ExtLangPair(ext=FileExt(".cbl"), language=LanguageName("cobol")),
    ExtLangPair(ext=FileExt(".chapel"), language=LanguageName("chapel")),
    ExtLangPair(ext=FileExt(".clj"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".cljc"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".cljs"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".cljx"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".cls"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".cmake"), language=LanguageName("cmake")),
    ExtLangPair(ext=FileExt(".cob"), language=LanguageName("cobol")),
    ExtLangPair(ext=FileExt(".cobol"), language=LanguageName("cobol")),
    ExtLangPair(ext=FileExt(".coffee"), language=LanguageName("coffeescript")),
    ExtLangPair(ext=FileExt(".cr"), language=LanguageName("crystal")),
    ExtLangPair(ext=FileExt(".cu"), language=LanguageName("cuda")),
    ExtLangPair(ext=FileExt(".cue"), language=LanguageName("cue")),
    ExtLangPair(ext=FileExt(".cuh"), language=LanguageName("cuda")),
    ExtLangPair(ext=FileExt(".d"), language=LanguageName("dlang")),
    ExtLangPair(ext=FileExt(".dart"), language=LanguageName("dart")),
    ExtLangPair(ext=FileExt(".dfm"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".dhall"), language=LanguageName("dhall")),
    ExtLangPair(ext=FileExt(".dlang"), language=LanguageName("dlang")),
    ExtLangPair(ext=FileExt(".dpr"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".dts"), language=LanguageName("devicetree")),
    ExtLangPair(ext=FileExt(".dtsi"), language=LanguageName("devicetree")),
    ExtLangPair(ext=FileExt(".dtso"), language=LanguageName("devicetree")),
    ExtLangPair(ext=FileExt(".duck"), language=LanguageName("duck")),
    ExtLangPair(ext=FileExt(".dyck"), language=LanguageName("dyck")),
    ExtLangPair(ext=FileExt(".e"), language=LanguageName("eiffel")),
    ExtLangPair(ext=FileExt(".ecl"), language=LanguageName("ecl")),
    ExtLangPair(ext=FileExt(".eclsp"), language=LanguageName("ecl")),
    ExtLangPair(ext=FileExt(".eclxml"), language=LanguageName("ecl")),
    ExtLangPair(ext=FileExt(".edn"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".el"), language=LanguageName("emacs")),
    ExtLangPair(ext=FileExt(".elm"), language=LanguageName("elm")),
    ExtLangPair(ext=FileExt(".elv"), language=LanguageName("elvish")),
    ExtLangPair(ext=FileExt(".emacs"), language=LanguageName("emacs")),
    ExtLangPair(ext=FileExt(".erl"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".es"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".escript"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".eta"), language=LanguageName("eta")),
    ExtLangPair(ext=FileExt(".f"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f03"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f08"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f18"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f23"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f90"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".f95"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".factor"), language=LanguageName("factor")),
    ExtLangPair(ext=FileExt(".for"), language=LanguageName("fortran")),
    ExtLangPair(ext=FileExt(".fr"), language=LanguageName("frege")),
    ExtLangPair(ext=FileExt(".fs"), language=LanguageName("fsharp")),
    ExtLangPair(ext=FileExt(".fsi"), language=LanguageName("fsharp")),
    ExtLangPair(ext=FileExt(".fsx"), language=LanguageName("fsharp")),
    ExtLangPair(ext=FileExt(".gleam"), language=LanguageName("gleam")),
    ExtLangPair(ext=FileExt(".gql"), language=LanguageName("graphql")),
    ExtLangPair(ext=FileExt(".graphql"), language=LanguageName("graphql")),
    ExtLangPair(ext=FileExt(".graphqls"), language=LanguageName("graphql")),
    ExtLangPair(ext=FileExt(".groovy"), language=LanguageName("groovy")),
    ExtLangPair(ext=FileExt(".gs"), language=LanguageName("gosu")),
    ExtLangPair(ext=FileExt(".hack"), language=LanguageName("hack")),
    ExtLangPair(ext=FileExt(".hck"), language=LanguageName("hack")),
    ExtLangPair(ext=FileExt(".hcl"), language=LanguageName("hcl")),
    ExtLangPair(ext=FileExt(".hhi"), language=LanguageName("hack")),
    ExtLangPair(ext=FileExt(".hjson"), language=LanguageName("hjson")),
    ExtLangPair(ext=FileExt(".hlsl"), language=LanguageName("hlsl")),
    ExtLangPair(ext=FileExt(".hrl"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".hrl"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".idr"), language=LanguageName("idris")),
    ExtLangPair(ext=FileExt(".imba"), language=LanguageName("imba")),
    ExtLangPair(ext=FileExt(".io"), language=LanguageName("io")),
    ExtLangPair(ext=FileExt(".its"), language=LanguageName("devicetree")),
    ExtLangPair(ext=FileExt(".janet"), language=LanguageName("janet")),
    ExtLangPair(ext=FileExt(".jdn"), language=LanguageName("janet")),
    ExtLangPair(ext=FileExt(".jelly"), language=LanguageName("jelly")),  # jenkins
    ExtLangPair(ext=FileExt(".jinja"), language=LanguageName("jinja")),
    ExtLangPair(ext=FileExt(".jinja2"), language=LanguageName("jinja")),
    ExtLangPair(ext=FileExt(".jl"), language=LanguageName("julia")),
    ExtLangPair(ext=FileExt(".joke"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".joker"), language=LanguageName("clojure")),
    ExtLangPair(ext=FileExt(".jule"), language=LanguageName("jule")),
    ExtLangPair(ext=FileExt(".less"), language=LanguageName("less")),
    ExtLangPair(ext=FileExt(".lidr"), language=LanguageName("idris")),
    ExtLangPair(ext=FileExt(".lisp"), language=LanguageName("lisp")),
    ExtLangPair(ext=FileExt(".lpr"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".ls"), language=LanguageName("livescript")),
    ExtLangPair(ext=FileExt(".lsc"), language=LanguageName("lisp")),
    ExtLangPair(ext=FileExt(".lsp"), language=LanguageName("lisp")),
    ExtLangPair(ext=FileExt(".lucee"), language=LanguageName("lucee")),
    ExtLangPair(ext=FileExt(".m"), language=LanguageName("matlab")),
    ExtLangPair(ext=FileExt(".mak"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt(".makefile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt(".mk"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt(".ml"), language=LanguageName("ocaml")),
    ExtLangPair(ext=FileExt(".mli"), language=LanguageName("ocaml")),
    ExtLangPair(ext=FileExt(".mm"), language=LanguageName("objective-c")),
    ExtLangPair(ext=FileExt(".mojo"), language=LanguageName("mojo")),
    ExtLangPair(ext=FileExt(".move"), language=LanguageName("move")),
    ExtLangPair(ext=FileExt(".nh"), language=LanguageName("newick")),
    ExtLangPair(ext=FileExt(".nhx"), language=LanguageName("newick")),
    ExtLangPair(ext=FileExt(".nim"), language=LanguageName("nimble")),
    ExtLangPair(ext=FileExt(".nim.cfg"), language=LanguageName("nimble")),
    ExtLangPair(ext=FileExt(".nim.cfg"), language=LanguageName("nimble")),
    ExtLangPair(ext=FileExt(".nimble"), language=LanguageName("nimble")),
    ExtLangPair(ext=FileExt(".nimble.cfg"), language=LanguageName("nimble")),
    ExtLangPair(ext=FileExt(".nimble.json"), language=LanguageName("json")),
    ExtLangPair(ext=FileExt(".nimble.toml"), language=LanguageName("toml")),
    ExtLangPair(ext=FileExt(".nomad"), language=LanguageName("hcl")),
    ExtLangPair(ext=FileExt(".nu"), language=LanguageName("nushell")),
    ExtLangPair(ext=FileExt(".nushell"), language=LanguageName("nushell")),
    ExtLangPair(ext=FileExt(".nwk"), language=LanguageName("newick")),
    ExtLangPair(ext=FileExt(".odin"), language=LanguageName("odin")),
    ExtLangPair(ext=FileExt(".pas"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".pascal"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".pgsql"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".pharo"), language=LanguageName("pharo")),
    ExtLangPair(ext=FileExt(".pkl"), language=LanguageName("pkl")),
    ExtLangPair(ext=FileExt(".pl"), language=LanguageName("perl")),
    ExtLangPair(ext=FileExt(".pm"), language=LanguageName("perl")),
    ExtLangPair(ext=FileExt(".pony"), language=LanguageName("pony")),
    ExtLangPair(ext=FileExt(".pp"), language=LanguageName("pascal")),
    ExtLangPair(ext=FileExt(".proto"), language=LanguageName("protobuf")),
    ExtLangPair(ext=FileExt(".ps1"), language=LanguageName("powershell")),
    ExtLangPair(ext=FileExt(".psm1"), language=LanguageName("powershell")),
    ExtLangPair(ext=FileExt(".pssc"), language=LanguageName("powershell")),
    ExtLangPair(ext=FileExt(".purs"), language=LanguageName("purescript")),
    ExtLangPair(ext=FileExt(".pxd"), language=LanguageName("cython")),
    ExtLangPair(ext=FileExt(".pyx"), language=LanguageName("cython")),
    ExtLangPair(ext=FileExt(".qb64"), language=LanguageName("qb64")),
    ExtLangPair(ext=FileExt(".qml"), language=LanguageName("qml")),
    ExtLangPair(ext=FileExt(".r"), language=LanguageName("r")),
    ExtLangPair(ext=FileExt(".raku"), language=LanguageName("raku")),
    ExtLangPair(ext=FileExt(".rakudoc"), language=LanguageName("raku")),
    ExtLangPair(ext=FileExt(".rakudoc"), language=LanguageName("rakudo")),
    ExtLangPair(ext=FileExt(".rd"), language=LanguageName("r")),
    ExtLangPair(ext=FileExt(".re"), language=LanguageName("reason")),
    ExtLangPair(ext=FileExt(".red"), language=LanguageName("red")),
    ExtLangPair(ext=FileExt(".reds"), language=LanguageName("red")),
    ExtLangPair(ext=FileExt(".rei"), language=LanguageName("reason")),
    ExtLangPair(ext=FileExt(".res"), language=LanguageName("rescript")),
    ExtLangPair(ext=FileExt(".rescript"), language=LanguageName("rescript")),
    ExtLangPair(ext=FileExt(".ring"), language=LanguageName("ring")),
    ExtLangPair(ext=FileExt(".rkt"), language=LanguageName("racket")),
    ExtLangPair(ext=FileExt(".rktd"), language=LanguageName("racket")),
    ExtLangPair(ext=FileExt(".rktl"), language=LanguageName("racket")),
    ExtLangPair(ext=FileExt(".rsx"), language=LanguageName("r")),
    ExtLangPair(ext=FileExt(".s"), language=LanguageName("assembly")),
    ExtLangPair(ext=FileExt(".sas"), language=LanguageName("sas")),
    ExtLangPair(ext=FileExt(".sass"), language=LanguageName("sass")),
    ExtLangPair(ext=FileExt(".sc"), language=LanguageName("scheme")),
    ExtLangPair(ext=FileExt(".sch"), language=LanguageName("scheme")),
    ExtLangPair(ext=FileExt(".scheme"), language=LanguageName("scheme")),
    ExtLangPair(ext=FileExt(".scm"), language=LanguageName("scheme")),
    ExtLangPair(ext=FileExt(".scss"), language=LanguageName("scss")),
    ExtLangPair(ext=FileExt(".sld"), language=LanguageName("scheme")),
    ExtLangPair(ext=FileExt(".smali"), language=LanguageName("smali")),
    ExtLangPair(ext=FileExt(".sml"), language=LanguageName("sml")),  # Standard ML
    ExtLangPair(ext=FileExt(".sql"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".sqlite"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".sqlite3"), language=LanguageName("sql")),
    ExtLangPair(ext=FileExt(".sty"), language=LanguageName("latex")),
    ExtLangPair(
        ext=FileExt(".sv"), language=LanguageName("verilog")
    ),  # systemverilog -- more likely these days than `v` for verilog
    ExtLangPair(ext=FileExt(".svelte"), language=LanguageName("svelte")),
    ExtLangPair(ext=FileExt(".svh"), language=LanguageName("verilog")),
    ExtLangPair(ext=FileExt(".tex"), language=LanguageName("latex")),
    ExtLangPair(ext=FileExt(".textproto"), language=LanguageName("protobuf")),
    ExtLangPair(ext=FileExt(".tf"), language=LanguageName("hcl")),
    ExtLangPair(ext=FileExt(".tfvars"), language=LanguageName("hcl")),
    ExtLangPair(ext=FileExt(".txtpb"), language=LanguageName("protobuf")),
    ExtLangPair(
        ext=FileExt(".v"), language=LanguageName("coq")
    ),  # coq vernacular files -- could also be verilog. We have a parser for coq so we'll default to that.
    ExtLangPair(ext=FileExt(".vala"), language=LanguageName("vala")),
    ExtLangPair(ext=FileExt(".vale"), language=LanguageName("vale")),
    ExtLangPair(ext=FileExt(".vapi"), language=LanguageName("vala")),
    ExtLangPair(ext=FileExt(".vbs"), language=LanguageName("vbscript")),
    ExtLangPair(ext=FileExt(".vhd"), language=LanguageName("vhdl")),
    ExtLangPair(ext=FileExt(".vhdl"), language=LanguageName("vhdl")),
    ExtLangPair(ext=FileExt(".vlang"), language=LanguageName("vlang")),
    ExtLangPair(ext=FileExt(".vls"), language=LanguageName("vlang")),
    ExtLangPair(ext=FileExt(".vsh"), language=LanguageName("vlang")),
    ExtLangPair(ext=FileExt(".vue"), language=LanguageName("vue")),
    ExtLangPair(ext=FileExt(".workflow"), language=LanguageName("hcl")),
    ExtLangPair(ext=FileExt(".xaml"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xhtml"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xib"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xlf"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xlf"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xmi"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xml"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xml.dist"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xml.in"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xml.inc"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xrl"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".xsd"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".xsh"), language=LanguageName("xonsh")),
    ExtLangPair(ext=FileExt(".xsl"), language=LanguageName("xml")),
    ExtLangPair(ext=FileExt(".yrl"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt(".zig"), language=LanguageName("zig")),
    ExtLangPair(ext=FileExt(".zsh"), language=LanguageName("zsh")),
    ExtLangPair(ext=FileExt("BSDmakefile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("CMakefile"), language=LanguageName("cmake")),
    ExtLangPair(ext=FileExt("Cask"), language=LanguageName("emacs")),
    ExtLangPair(ext=FileExt("Dockerfile"), language=LanguageName("docker")),
    ExtLangPair(ext=FileExt("Emakefile"), language=LanguageName("erlang")),
    ExtLangPair(ext=FileExt("GNUmakefile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Justfile"), language=LanguageName("just")),
    ExtLangPair(ext=FileExt("Kbuild"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile.am"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile.boot"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile.in"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile.inc"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Makefile.wat"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("Rakefile"), language=LanguageName("rake")),
    ExtLangPair(ext=FileExt("_emacs"), language=LanguageName("emacs")),
    ExtLangPair(ext=FileExt("makefile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("makefile.sco"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("mkfile"), language=LanguageName("make")),
    ExtLangPair(ext=FileExt("rebar.config"), language=LanguageName("erlang")),
    # We're only going to cover the main ones for VB6, but langchain has a splitter for it so we'll support it.
    ExtLangPair(ext=FileExt(".bas"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".cls"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".ctl"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".frm"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".pag"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".res"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".vb"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".vba"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".vbg"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".vbi"), language=LanguageName("visualbasic6")),
    ExtLangPair(ext=FileExt(".vbp"), language=LanguageName("visualbasic6")),
)
# spellchecker:on
"""A tuple of `ExtLangPair`."""

TEST_DIR_NAMES: tuple[DirectoryNameT, ...] = (
    DirectoryName("__tests__"),
    DirectoryName("__specs__"),
    DirectoryName("test"),
    DirectoryName("tests"),
    DirectoryName("spec"),
    DirectoryName("specs"),
    DirectoryName("test-*"),
    DirectoryName("spec-*"),
    DirectoryName("Tests"),  # swift
)

TEST_FILE_PATTERNS: tuple[FileGlobT, ...] = (
    FileGlob("*.test.*"),
    FileGlob("*.spec.*"),
    FileGlob("*_test.*"),
    FileGlob("*_spec.*"),
)


COMMON_TOOLING_PATHS: tuple[tuple[DevToolNameT, tuple[Path, ...]], ...] = (
    (DevToolName("ast-grep"), (Path("sgconfig.yml"),)),
    (DevToolName("cargo"), (Path("Cargo.toml"), Path("Cargo.lock"), Path(".cargo"))),
    (
        DevToolName("docker"),
        (
            Path("Dockerfile"),
            Path("docker-compose.yml"),
            Path("docker-compose.yaml"),
            Path("docker"),
        ),
    ),
    (
        DevToolName("devcontainer"),
        (
            Path(".devcontainer"),
            Path(".devcontainer/devcontainer.json"),
            Path(".devcontainer/devcontainer.local.json"),
        ),
    ),
    (DevToolName("bazel"), (Path("WORKSPACE"), Path("BUILD.bazel"), Path("BUILD"))),
    (
        DevToolName("cmake"),
        (
            Path("CMakeLists.txt"),
            Path("CMakeCache.txt"),
            Path("cmake-build-debug"),
            Path("CMakeFiles"),
        ),
    ),
    (
        DevToolName("bun"),
        (Path("bun.lockb"), Path("bunfig.toml"), Path("bunfig.json"), Path("bun.lock")),
    ),
    (DevToolName("changesets"), (Path(".changeset"),)),
    (DevToolName("composer"), (Path("composer.json"), Path("composer.lock"))),
    (DevToolName("esbuild"), (Path("esbuild.config.js"), Path("esbuild.config.ts"))),
    (
        DevToolName("gradle"),
        (
            Path("build.gradle"),
            Path("build.gradle.kts"),
            Path("gradlew"),
            Path("gradlew.bat"),
            Path("gradle"),
            Path("settings.gradle"),
            Path("settings.gradle.kts"),
        ),
    ),
    (DevToolName("deno"), (Path("deno.json"), Path("deno.jsonc"), Path("deno.lock"))),
    (DevToolName("hardhat"), (Path("hardhat.config.js"), Path("hardhat.config.ts"))),
    (DevToolName("hk"), (Path("hk.pkl"),)),
    (DevToolName("husky"), (Path(".husky"), Path(".husky/pre-commit"), Path(".husky/pre-push"))),
    (DevToolName("intellij"), (Path(".idea"), Path(".idea/misc.xml"), Path(".idea/modules.xml"))),
    (DevToolName("just"), (Path("Justfile"), Path("justfile"))),
    (DevToolName("lerna"), (Path("lerna.json"),)),
    (
        DevToolName("maven"),
        (Path("pom.xml"), Path("settings.xml"), Path(".mvn"), Path("mvnw"), Path("mvnw.cmd")),
    ),
    (DevToolName("mise"), (Path("mise.toml"),)),
    (DevToolName("moon"), (Path("moon.yml"), Path("moon.yaml"), Path(".moon"))),
    (DevToolName("nextjs"), (Path("next.config.js"), Path("next.config.ts"))),
    (DevToolName("npm"), (Path("package-lock.json"), Path(".npmrc"))),
    (DevToolName("nuxt"), (Path("nuxt.config.js"), Path("nuxt.config.ts"))),
    (DevToolName("nx"), (Path("nx.json"), Path("workspace.json"), Path("angular.json"))),
    (DevToolName("pnpm"), (Path("pnpm-lock.yaml"), Path("pnpm-workspace.yaml"))),
    (DevToolName("poetry"), (Path("poetry.lock"),)),
    (DevToolName("pre-commit"), (Path(".pre-commit-config.yaml"), Path(".pre-commit-config.yml"))),
    (
        DevToolName("proto"),
        (Path("proto.toml"), Path("proto.pkl"), Path("prototools.toml"), Path("prototools.pkl")),
    ),
    (DevToolName("rollbar"), (Path("rollbar.config.js"), Path("rollbar.config.ts"))),
    (DevToolName("rollup"), (Path("rollup.config.js"), Path("rollup.config.ts"))),
    (DevToolName("ruff"), (Path("ruff.toml"), Path(".ruff.toml"))),
    (DevToolName("rush"), (Path("rush.json"),)),
    (
        DevToolName("sbt"),
        (Path("build.sbt"), Path("project/build.properties"), Path("project/plugins.sbt")),
    ),
    (DevToolName("skaffold"), (Path("skaffold.yaml"), Path("skaffold.yml"))),
    (
        DevToolName("stylelint"),
        (
            Path(".stylelintrc"),
            Path(".stylelintrc.json"),
            Path(".stylelintrc.yaml"),
            Path(".stylelintrc.yml"),
        ),
    ),
    (DevToolName("tailwind"), (Path("tailwind.config.js"), Path("tailwind.config.ts"))),
    (DevToolName("typos"), (Path("_typos.toml"), Path(".typos.toml"), Path("typos.toml"))),
    (DevToolName("turborepo"), (Path("turbo.json"),)),
    (DevToolName("uv"), (Path("uv.toml"), Path("uv.lock"))),
    (DevToolName("vite"), (Path("vite.config.js"), Path("vite.config.ts"))),
    (DevToolName("vitest"), (Path("vitest.config.js"), Path("vitest.config.ts"))),
    (
        DevToolName("vscode"),
        (Path(".vscode"), Path(".vscode/settings.json"), Path(".vscode/launch.json")),
    ),
    (DevToolName("webpack"), (Path("webpack.config.js"), Path("webpack.config.ts"))),
    (DevToolName("xtask"), (Path("xtask"), Path("xtask/src/main.rs"))),
    (DevToolName("yarn"), (Path("yarn.lock"), Path(".yarn"), Path(".yarnrc"), Path(".yarnrc.yml"))),
)
"""Common paths for build and development tooling used in projects. This needs expansion, pull requests are welcome!"""

type LlmTool = Literal[
    "agents",
    "claude",
    "codeweaver",
    "codex",
    "continue",
    "copilot",
    "cursor",
    "mcp",
    "roo",
    "serena",
    "specify",
]

COMMON_LLM_TOOLING_PATHS: tuple[tuple[LlmToolNameT, tuple[Path, ...]], ...] = (
    (LlmToolName("agents"), (Path("AGENTS.md"),)),
    (LlmToolName("codex"), (Path(".codex"),)),
    (
        LlmToolName("claude"),
        (Path("CLAUDE.md"), Path(".claude"), Path("claudedocs"), Path(".claude/commands")),
    ),
    (
        LlmToolName("codeweaver"),
        (
            Path("codeweaver.local.toml"),
            Path("codeweaver.local.yaml"),
            Path("codeweaver.local.json"),
            Path(".codeweaver"),
        ),
    ),
    (LlmToolName("continue"), (Path(".continue"),)),
    (LlmToolName("copilot"), (Path(".github/chatmodes"), Path(".github/prompts"))),
    (LlmToolName("cursor"), (Path(".cursor"), Path(".cursor/config.yml"))),
    (
        LlmToolName("mcp"),
        (Path(".mcp.json"), Path("mcp.json"), Path(".roo/mcp.json"), Path(".vscode/mcp.json")),
    ),
    (LlmToolName("roo"), (Path(".roo"), Path(".roomodes"), Path(".roo/commands"))),
    (LlmToolName("serena"), (Path(".serena"), Path(".serena/project.yml"))),
    (
        LlmToolName("specify"),
        (
            Path(".specify"),
            Path(".specify/memory"),
            Path(".specify/scripts/bash"),
            Path(".specify/templates"),
        ),
    ),
)
"""Common paths for LLM tooling used in projects. This needs expansion -- right now it's literally just what I've used."""

_js_fam_paths = (
    Path("package.json"),
    Path("package-lock.json"),
    Path("yarn.lock"),
    Path("pnpm-lock.yaml"),
    Path("node_modules"),
    Path("bun.lockb"),
    Path("bun.lock"),
)

LANGUAGE_SPECIFIC_PATHS: MappingProxyType[LanguageName, tuple[Path, ...]] = MappingProxyType({
    LanguageName("csharp"): (Path("*.csproj"), Path("*.sln")),
    LanguageName("elixir"): (Path("mix.exs"), Path("mix.lock")),
    LanguageName("erlang"): (Path("rebar.config"), Path("rebar.lock")),
    LanguageName("go"): (
        Path("go.mod"),
        Path("go.sum"),
        Path("go.work"),
        Path("cmd"),
        Path("internal"),
    ),
    LanguageName("haskell"): (Path("stack.yaml"), Path("cabal.project"), Path("package.yaml")),
    LanguageName("java"): (
        Path("build.gradle"),
        Path("build.gradle.kts"),
        Path("pom.xml"),
        Path("pom.xml"),
        Path("src/main/java"),
        Path("src/main/tests"),
    ),
    LanguageName("javascript"): _js_fam_paths,
    LanguageName("jsx"): _js_fam_paths,
    LanguageName("kotlin"): (Path("src/main/kotlin"), Path("src/test/kotlin")),
    LanguageName("lua"): (Path("*.rockspec"),),
    LanguageName("php"): (Path("composer.json"), Path("composer.lock")),
    LanguageName("python"): (
        Path("Pipfile"),
        Path("Pipfile.lock"),
        Path("pyproject.toml"),
        Path("requirements-dev.txt"),
        Path("requirements.txt"),
        Path("setup.cfg"),
        Path("setup.py"),
    ),
    LanguageName("ruby"): (
        Path("*.gemspec"),
        Path("Gemfile"),
        Path("Gemfile.lock"),
        Path("Rakefile"),
        Path("config.ru"),
        Path("spec"),
    ),
    LanguageName("rust"): (Path("Cargo.toml"), Path("Cargo.lock")),
    LanguageName("scala"): (
        Path("build.sbt"),
        Path("project/build.properties"),
        Path("project/plugins.sbt"),
        Path("src/main/scala"),
        Path("src/test/scala"),
    ),
    LanguageName("solidity"): (
        Path("contracts"),
        Path("foundry.toml"),
        Path("hardhat.config.js"),
        Path("hardhat.config.ts"),
        Path("truffle-config.js"),
        Path("truffle-config.ts"),
    ),
    LanguageName("swift"): (Path("Package.swift"), Path(".xcodeproj"), Path(".xcworkspace")),
    LanguageName("typescript"): _js_fam_paths,
    LanguageName("tsx"): _js_fam_paths,
})
"""A mapping of language names to their specific common project paths."""


class FallBackTestDef(TypedDict):
    """Definition for a fallback test based on file content."""

    values: tuple[LiteralStringT, ...]
    """The values to check for in the file content."""
    on: Literal["in", "not in"]
    """The condition to check: 'in' or 'not in'. Not in will check that none of the values are present. 'in' will check that at least one value is present."""
    fallback_to: LanguageName
    """The language to fallback to if the test passes."""


FALLBACK_TEST: MappingProxyType[FileExt, FallBackTestDef] = MappingProxyType({
    FileExt(".v"): {
        "values": ("Proof", "Qed", "Proof", "Defined", "Admitted"),
        "on": "not in",
        "fallback_to": LanguageName("verilog"),
    },
    FileExt(".m"): {
        "values": ("switch", "end", "parfor", "function"),
        "on": "not in",
        "fallback_to": LanguageName("objective-c"),
    },
})
"""A mapping of file extensions to their fallback test definitions."""


CONFIG_FILE_LANGUAGES = frozenset({
    LanguageName("bash"),
    LanguageName("cfg"),
    LanguageName("cmake"),
    LanguageName("docker"),
    LanguageName("hcl"),
    LanguageName("ini"),
    LanguageName("json"),
    LanguageName("json5"),
    LanguageName("jsonc"),
    LanguageName("just"),
    LanguageName("make"),
    LanguageName("pkl"),
    LanguageName("properties"),
    LanguageName("toml"),
    LanguageName("xml"),
    LanguageName("yaml"),
})


def _get_languages_helper() -> tuple[
    frozenset[LanguageName],
    frozenset[LanguageName],
    frozenset[LanguageName],
    frozenset[LanguageName],
]:
    """Helper function to get all languages as frozensets."""
    code_langs: set[LanguageName] = {ext.language for ext in CODE_FILES_EXTENSIONS}
    data_langs: set[LanguageName] = {ext.language for ext in DATA_FILES_EXTENSIONS}
    doc_langs: set[LanguageName] = {ext.language for ext in DOC_FILES_EXTENSIONS}
    all_langs: set[LanguageName] = code_langs | data_langs | doc_langs
    return frozenset(code_langs), frozenset(data_langs), frozenset(doc_langs), frozenset(all_langs)


CODE_LANGUAGES, DATA_LANGUAGES, DOCS_LANGUAGES, ALL_LANGUAGES = _get_languages_helper()
"""Frozen sets of languages for code, data, documentation, and all combined."""


__all__ = (
    "ALL_LANGUAGES",
    "CODE_FILES_EXTENSIONS",
    "CODE_LANGUAGES",
    "COMMON_LLM_TOOLING_PATHS",
    "COMMON_TOOLING_PATHS",
    "CONFIG_FILE_LANGUAGES",
    "DATA_FILES_EXTENSIONS",
    "DATA_LANGUAGES",
    "DEFAULT_EXCLUDED_DIRS",
    "DEFAULT_EXCLUDED_EXTENSIONS",
    "DOCS_LANGUAGES",
    "DOC_FILES_EXTENSIONS",
    "FALLBACK_TEST",
    "TEST_DIR_NAMES",
    "TEST_FILE_PATTERNS",
    "ExtLangPair",
    "FallBackTestDef",
)
