# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Setup Python Environment
description: Minimal Python environment setup
inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.12"
  fetch-depth:
    description: Git fetch depth for checkout
    required: false
    default: "0"
  skip-checkout:
    description: Skip checkout step (if already checked out by calling workflow)
    required: false
    default: "false"
  github-token:
    description: GitHub token for mise installation (to avoid rate limits)
    required: false
    default: ""
outputs:
  PYTHON_PATH:
    description: Path to the Python executable
    value: ${{ steps.python-setup.outputs.PYTHON_PATH }}
  UV_PATH:
    description: Path to uv executable
    value: ${{ steps.python-setup.outputs.UV_PATH }}
runs:
  using: composite
  steps:
    - name: Checkout code
      if: inputs.skip-checkout != 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Free up disk space
      shell: bash
      run: ./scripts/dev-env/ci-free-disk-space.sh
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@9b03c627221f32cb88b299427119da30671cf9cc # v5
      with:
        python-version: ${{ inputs.python-version }}
        # Support free-threaded Python (e.g., 3.13t, 3.14t)
        allow-prereleases: true
    - name: Install pip packages
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install uv
        echo "PYTHON_PATH=$(which python)" >> "$GITHUB_OUTPUT"
        echo "UV_PATH=$(which uv)" >> "$GITHUB_OUTPUT"
      id: python-setup
