# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""CodeWeaver server package initialization."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.server.agent_api import FindCodeResponseSummary, IntentType, find_code
    from codeweaver.server.config import (
        AVAILABLE_MIDDLEWARE,
        CodeWeaverMCPConfig,
        CodeWeaverMCPConfigDict,
        CodeWeaverSettings,
        CodeWeaverSettingsDict,
        DefaultEndpointSettings,
        DefaultFastMcpHttpRunArgs,
        DefaultFastMcpServerSettings,
        DefaultUvicornSettings,
        DefaultUvicornSettingsForMcp,
        ErrorHandlingMiddlewareSettings,
        FastMcpHttpRunArgs,
        FastMcpHttpServerSettings,
        FastMcpServerSettingsDict,
        FastMcpStdioServerSettings,
        LoggingMiddlewareSettings,
        MCPConfig,
        MCPConfigDict,
        MiddlewareOptions,
        RateLimitingMiddlewareSettings,
        RetryMiddlewareSettings,
        StdioCodeWeaverConfig,
        StdioCodeWeaverConfigDict,
        UvicornServerSettings,
        UvicornServerSettingsDict,
    )
    from codeweaver.server.dependencies import CodeWeaverStateDep
    from codeweaver.server.health import (
        EmbeddingProviderServiceInfo,
        HealthResponse,
        HealthService,
        IndexingInfo,
        IndexingProgressInfo,
        RerankingServiceInfo,
        ServicesInfo,
        SparseEmbeddingServiceInfo,
        StatisticsInfo,
        VectorStoreServiceInfo,
    )
    from codeweaver.server.lifespan import background_services_lifespan, http_lifespan
    from codeweaver.server.management import ManagementServer
    from codeweaver.server.mcp import (
        TOOL_DEFINITIONS,
        CwMcpHttpState,
        ErrorHandlingMiddleware,
        LoggingMiddleware,
        McpMiddleware,
        RateLimitingMiddleware,
        ResponseCachingMiddleware,
        RetryMiddleware,
        StatisticsMiddleware,
        StructuredLoggingMiddleware,
        ToolAnnotationsDict,
        ToolRegistrationDict,
        create_http_server,
        create_stdio_server,
        find_code_tool,
        find_code_tool_definition,
        get_bulk_tool,
        register_tool,
    )
    from codeweaver.server.server import CodeWeaverState, lifespan


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AVAILABLE_MIDDLEWARE": (__spec__.parent, "middleware"),
    "CodeWeaverMCPConfig": (__spec__.parent, "mcp"),
    "CodeWeaverMCPConfigDict": (__spec__.parent, "config"),
    "CodeWeaverSettings": (__spec__.parent, "settings"),
    "CodeWeaverSettingsDict": (__spec__.parent, "config"),
    "CodeWeaverState": (__spec__.parent, "server"),
    "CwMcpHttpState": (__spec__.parent, "mcp"),
    "EmbeddingProviderServiceInfo": (__spec__.parent, "health"),
    "ErrorHandlingMiddleware": (__spec__.parent, "mcp"),
    "ErrorHandlingMiddlewareSettings": (__spec__.parent, "middleware"),
    "FastMcpHttpRunArgs": (__spec__.parent, "config"),
    "FastMcpHttpServerSettings": (__spec__.parent, "settings"),
    "FastMcpServerSettingsDict": (__spec__.parent, "config"),
    "FastMcpStdioServerSettings": (__spec__.parent, "settings"),
    "FastEmbedGPUProviderSettings": (__spec__.parent, "providers"),
    "FindCodeResponseSummary": (__spec__.parent, "agent_api"),
    "DefaultEndpointSettings": (__spec__.parent, "config"),
    "DefaultFastMcpHttpRunArgs": (__spec__.parent, "config"),
    "DefaultFastMcpServerSettings": (__spec__.parent, "config"),
    "DefaultUvicornSettings": (__spec__.parent, "config"),
    "DefaultUvicornSettingsForMcp": (__spec__.parent, "config"),
    "HealthResponse": (__spec__.parent, "health"),
    "HealthService": (__spec__.parent, "health"),
    "IndexingInfo": (__spec__.parent, "health"),
    "IndexingProgressInfo": (__spec__.parent, "health"),
    "IntentType": (__spec__.parent, "agent_api"),
    "LoggingMiddleware": (__spec__.parent, "mcp"),
    "LoggingMiddlewareSettings": (__spec__.parent, "middleware"),
    "LoggingSettingsDict": (__spec__.parent, "_logging"),
    "MCPConfig": (__spec__.parent, "mcp"),
    "MCPConfigDict": (__spec__.parent, "config"),
    "ManagementServer": (__spec__.parent, "management"),
    "McpMiddleware": (__spec__.parent, "mcp"),
    "MiddlewareOptions": (__spec__.parent, "middleware"),
    "RateLimitingMiddleware": (__spec__.parent, "mcp"),
    "RateLimitingMiddlewareSettings": (__spec__.parent, "middleware"),
    "RerankingServiceInfo": (__spec__.parent, "health"),
    "ResponseCachingMiddleware": (__spec__.parent, "mcp"),
    "RetryMiddleware": (__spec__.parent, "mcp"),
    "RetryMiddlewareSettings": (__spec__.parent, "middleware"),
    "SerializableLoggingFilter": (__spec__.parent, "_logging"),
    "ServicesInfo": (__spec__.parent, "health"),
    "SparseEmbeddingServiceInfo": (__spec__.parent, "health"),
    "StatisticsInfo": (__spec__.parent, "health"),
    "StatisticsMiddleware": (__spec__.parent, "mcp"),
    "StdioCodeWeaverConfig": (__spec__.parent, "mcp"),
    "StdioCodeWeaverConfigDict": (__spec__.parent, "config"),
    "StructuredLoggingMiddleware": (__spec__.parent, "mcp"),
    "TOOL_DEFINITIONS": (__spec__.parent, "mcp"),
    "ToolAnnotationsDict": (__spec__.parent, "mcp"),
    "ToolRegistrationDict": (__spec__.parent, "mcp"),
    "UvicornServerSettings": (__spec__.parent, "config"),
    "UvicornServerSettingsDict": (__spec__.parent, "config"),
    "VectorStoreServiceInfo": (__spec__.parent, "health"),
    "background_services_lifespan": (__spec__.parent, "lifespan"),
    "create_http_server": (__spec__.parent, "server"),
    "create_stdio_server": (__spec__.parent, "server"),
    "find_code": (__spec__.parent, "agent_api"),
    "find_code_tool": (__spec__.parent, "user_agent"),
    "find_code_tool_definition": (__spec__.parent, "tools"),
    "get_bulk_tool": (__spec__.parent, "tools"),
    "http_lifespan": (__spec__.parent, "lifespan"),
    "lifespan": (__spec__.parent, "server"),
    "register_tool": (__spec__.parent, "tools"),
    "update_settings": (__spec__.parent, "settings"),
})

__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "AVAILABLE_MIDDLEWARE",
    "TOOL_DEFINITIONS",
    "CodeWeaverMCPConfig",
    "CodeWeaverMCPConfigDict",
    "CodeWeaverSettings",
    "CodeWeaverSettingsDict",
    "CodeWeaverState",
    "CwMcpHttpState",
    "DefaultEndpointSettings",
    "DefaultFastMcpHttpRunArgs",
    "DefaultFastMcpServerSettings",
    "DefaultUvicornSettings",
    "DefaultUvicornSettingsForMcp",
    "EmbeddingProviderServiceInfo",
    "ErrorHandlingMiddleware",
    "ErrorHandlingMiddlewareSettings",
    "FastEmbedGPUProviderSettings",
    "FastMcpHttpRunArgs",
    "FastMcpHttpServerSettings",
    "FastMcpServerSettingsDict",
    "FastMcpStdioServerSettings",
    "FindCodeResponseSummary",
    "HealthResponse",
    "HealthService",
    "IndexingInfo",
    "IndexingProgressInfo",
    "IntentType",
    "LoggingMiddleware",
    "LoggingMiddlewareSettings",
    "MCPConfig",
    "MCPConfigDict",
    "ManagementServer",
    "McpMiddleware",
    "MiddlewareOptions",
    "RateLimitingMiddleware",
    "RateLimitingMiddlewareSettings",
    "RerankingServiceInfo",
    "ResponseCachingMiddleware",
    "RetryMiddleware",
    "RetryMiddlewareSettings",
    "ServicesInfo",
    "SparseEmbeddingServiceInfo",
    "StatisticsInfo",
    "StatisticsMiddleware",
    "StdioCodeWeaverConfig",
    "StdioCodeWeaverConfigDict",
    "StructuredLoggingMiddleware",
    "ToolAnnotationsDict",
    "ToolRegistrationDict",
    "UvicornServerSettings",
    "UvicornServerSettingsDict",
    "VectorStoreServiceInfo",
    "background_services_lifespan",
    "create_http_server",
    "create_stdio_server",
    "find_code",
    "find_code_tool",
    "find_code_tool_definition",
    "get_bulk_tool",
    "http_lifespan",
    "lifespan",
    "register_tool",
    "update_settings",
)


def __dir__() -> list[str]:
    return list(__all__)
