# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""CodeWeaver server package initialization."""

from __future__ import annotations

from types import MappingProxyType

# === MANAGED EXPORTS ===
# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.server._assets import CODEWEAVER_SVG_ICON
    from codeweaver.server._logging import getLogger, setup_logger
    from codeweaver.server.agent_api import MappingProxyType, get_user_agent
    from codeweaver.server.agent_api.find_code import (
        IntentType,
        MatchedSection,
        SearchPackageDep,
        TelemetrySettingsDep,
        find_code,
    )
    from codeweaver.server.agent_api.find_code.conversion import CodeMatchType
    from codeweaver.server.agent_api.find_code.intent import (
        IntentResult,
        QueryComplexity,
        QueryIntent,
    )
    from codeweaver.server.agent_api.find_code.pipeline import QueryError
    from codeweaver.server.agent_api.find_code.types import (
        CodeMatch,
        FindCodeResponseSummary,
        FindCodeSubmission,
        ValidationError,
    )
    from codeweaver.server.background_services import run_background_indexing, start_watcher
    from codeweaver.server.config.mcp import (
        CodeWeaverMCPConfig,
        FastMCPConfig,
        FastMCPRemoteMCPServer,
        FastMCPStdioMCPServer,
        MCPConfig,
        MCPServerConfig,
        MissingValueError,
        StdioCodeWeaverConfig,
        update_mcp_config_file,
    )
    from codeweaver.server.config.middleware import (
        DefaultMiddlewareSettings,
        ErrorHandlingMiddlewareSettings,
        LoggingMiddlewareSettings,
        McpMiddlewareContext,
        MiddlewareOptions,
        RateLimitingMiddlewareSettings,
        ResponseCachingMiddlewareSettings,
        RetryMiddlewareSettings,
    )
    from codeweaver.server.config.server_defaults import (
        DefaultEndpointSettings,
        DefaultFastMcpHttpRunArgs,
        DefaultFastMcpServerSettings,
        DefaultUvicornSettings,
        DefaultUvicornSettingsForMcp,
    )
    from codeweaver.server.config.settings import (
        BaseFastMcpServerSettings,
        CodeWeaverSettings,
        CodeWeaverSettingsDict,
        FastMcpHttpServerSettings,
        FastMcpStdioServerSettings,
    )
    from codeweaver.server.config.types import (
        CodeWeaverMCPConfigDict,
        EndpointSettingsDict,
        FastMcpHttpRunArgs,
        FastMcpServerSettingsDict,
        HTTPProtocolType,
        InterfaceType,
        LifespanType,
        MCPConfigDict,
        StdioCodeWeaverConfigDict,
        UvicornServerSettings,
        UvicornServerSettingsDict,
        WSProtocolType,
    )
    from codeweaver.server.dependencies import (
        CodeWeaverStateDep,
        FailoverServiceDep,
        HealthServiceDep,
        IndexingServiceDep,
        ManagementServerDep,
        ProviderSettingsDep,
        ResolvedProjectNameDep,
        ResolvedProjectPathDep,
        SettingsDep,
        StatisticsDep,
        TelemetryServiceDep,
    )
    from codeweaver.server.health.health_service import ConfigurationError, HealthService
    from codeweaver.server.health.models import (
        EmbeddingProviderServiceInfo,
        FailoverInfo,
        HealthResponse,
        IndexingInfo,
        IndexingProgressInfo,
        RerankingServiceInfo,
        ResourceInfo,
        ServicesInfo,
        SparseEmbeddingServiceInfo,
        StatisticsInfo,
        VectorStoreServiceInfo,
    )
    from codeweaver.server.lifespan import (
        CodeWeaverSettingsType,
        background_services_lifespan,
        http_lifespan,
    )
    from codeweaver.server.management import (
        ManagementServer,
        SettingsMapDep,
        favicon,
        health,
        settings,
        settings_info,
        shutdown_handler,
        state_info,
        stats_info,
        status_info,
        version_info,
    )
    from codeweaver.server.mcp.middleware.fastmcp import (
        DetailedTimingMiddleware,
        ErrorHandlingMiddleware,
        LoggingMiddleware,
        RateLimitingMiddleware,
        ResponseCachingMiddleware,
        RetryMiddleware,
        StructuredLoggingMiddleware,
    )
    from codeweaver.server.mcp.middleware.statistics import ProviderError
    from codeweaver.server.mcp.server import (
        McpMiddleware,
        StatisticsMiddleware,
        StdioClientLifespan,
        create_http_server,
        create_stdio_server,
    )
    from codeweaver.server.mcp.state import CwMcpHttpState, FastMCPServerSettings
    from codeweaver.server.mcp.tools import (
        ContextAgentToolkit,
        ToolCollectionDict,
        get_bulk_tool,
        register_tool,
    )
    from codeweaver.server.mcp.types import ToolAnnotationsDict, ToolRegistrationDict
    from codeweaver.server.mcp.user_agent import find_code_tool
    from codeweaver.server.server import (
        BRACKET_PATTERN,
        ASGIMiddleware,
        CodeWeaverState,
        InitializationError,
        lifespan,
        version,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BRACKET_PATTERN": (__spec__.parent, "server"),
    "CODEWEAVER_SVG_ICON": (__spec__.parent, "_assets"),
    "BaseFastMcpServerSettings": (__spec__.parent, "config.settings"),
    "CodeMatch": (__spec__.parent, "agent_api.find_code.types"),
    "CodeMatchType": (__spec__.parent, "agent_api.find_code.conversion"),
    "CodeWeaverSettings": (__spec__.parent, "config.settings"),
    "CodeWeaverSettingsDict": (__spec__.parent, "config.settings"),
    "CodeWeaverSettingsType": (__spec__.parent, "lifespan"),
    "CodeWeaverState": (__spec__.parent, "server"),
    "ConfigurationError": (__spec__.parent, "health.health_service"),
    "ContextAgentToolkit": (__spec__.parent, "mcp.tools"),
    "CwMcpHttpState": (__spec__.parent, "mcp.state"),
    "DefaultEndpointSettings": (__spec__.parent, "config.server_defaults"),
    "DefaultFastMcpHttpRunArgs": (__spec__.parent, "config.server_defaults"),
    "DefaultFastMcpServerSettings": (__spec__.parent, "config.server_defaults"),
    "DefaultMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "DefaultUvicornSettings": (__spec__.parent, "config.server_defaults"),
    "DefaultUvicornSettingsForMcp": (__spec__.parent, "config.server_defaults"),
    "DetailedTimingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "EmbeddingProviderServiceInfo": (__spec__.parent, "health.models"),
    "EndpointSettingsDict": (__spec__.parent, "config.types"),
    "ErrorHandlingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "ErrorHandlingMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "FailoverInfo": (__spec__.parent, "health.models"),
    "FailoverServiceDep": (__spec__.parent, "dependencies"),
    "FastMcpHttpRunArgs": (__spec__.parent, "config.types"),
    "FastMcpHttpServerSettings": (__spec__.parent, "config.settings"),
    "FastMcpServerSettingsDict": (__spec__.parent, "config.types"),
    "FastMcpStdioServerSettings": (__spec__.parent, "config.settings"),
    "FindCodeResponseSummary": (__spec__.parent, "agent_api.find_code.types"),
    "FindCodeSubmission": (__spec__.parent, "agent_api.find_code.types"),
    "HealthResponse": (__spec__.parent, "health.models"),
    "HealthService": (__spec__.parent, "health.health_service"),
    "IndexingInfo": (__spec__.parent, "health.models"),
    "IndexingProgressInfo": (__spec__.parent, "health.models"),
    "IndexingServiceDep": (__spec__.parent, "dependencies"),
    "InitializationError": (__spec__.parent, "server"),
    "IntentResult": (__spec__.parent, "agent_api.find_code.intent"),
    "IntentType": (__spec__.parent, "agent_api.find_code"),
    "InterfaceType": (__spec__.parent, "config.types"),
    "LifespanType": (__spec__.parent, "config.types"),
    "LoggingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "LoggingMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "ManagementServer": (__spec__.parent, "management"),
    "MappingProxyType": (__spec__.parent, "agent_api"),
    "MatchedSection": (__spec__.parent, "agent_api.find_code"),
    "McpMiddleware": (__spec__.parent, "mcp.server"),
    "McpMiddlewareContext": (__spec__.parent, "config.middleware"),
    "MiddlewareOptions": (__spec__.parent, "config.middleware"),
    "MissingValueError": (__spec__.parent, "config.mcp"),
    "ProviderError": (__spec__.parent, "mcp.middleware.statistics"),
    "ProviderSettingsDep": (__spec__.parent, "dependencies"),
    "QueryComplexity": (__spec__.parent, "agent_api.find_code.intent"),
    "QueryError": (__spec__.parent, "agent_api.find_code.pipeline"),
    "QueryIntent": (__spec__.parent, "agent_api.find_code.intent"),
    "RateLimitingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "RateLimitingMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "RerankingServiceInfo": (__spec__.parent, "health.models"),
    "ResolvedProjectNameDep": (__spec__.parent, "dependencies"),
    "ResolvedProjectPathDep": (__spec__.parent, "dependencies"),
    "ResourceInfo": (__spec__.parent, "health.models"),
    "ResponseCachingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "ResponseCachingMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "RetryMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "RetryMiddlewareSettings": (__spec__.parent, "config.middleware"),
    "SearchPackageDep": (__spec__.parent, "agent_api.find_code"),
    "ServicesInfo": (__spec__.parent, "health.models"),
    "SettingsDep": (__spec__.parent, "dependencies"),
    "SettingsMapDep": (__spec__.parent, "management"),
    "SparseEmbeddingServiceInfo": (__spec__.parent, "health.models"),
    "StatisticsDep": (__spec__.parent, "dependencies"),
    "StatisticsInfo": (__spec__.parent, "health.models"),
    "StatisticsMiddleware": (__spec__.parent, "mcp.server"),
    "StdioCodeWeaverConfig": (__spec__.parent, "config.mcp"),
    "StdioCodeWeaverConfigDict": (__spec__.parent, "config.types"),
    "StructuredLoggingMiddleware": (__spec__.parent, "mcp.middleware.fastmcp"),
    "TelemetryServiceDep": (__spec__.parent, "dependencies"),
    "TelemetrySettingsDep": (__spec__.parent, "agent_api.find_code"),
    "ToolAnnotationsDict": (__spec__.parent, "mcp.types"),
    "ToolCollectionDict": (__spec__.parent, "mcp.tools"),
    "ToolRegistrationDict": (__spec__.parent, "mcp.types"),
    "UvicornServerSettings": (__spec__.parent, "config.types"),
    "UvicornServerSettingsDict": (__spec__.parent, "config.types"),
    "ValidationError": (__spec__.parent, "agent_api.find_code.types"),
    "VectorStoreServiceInfo": (__spec__.parent, "health.models"),
    "ASGIMiddleware": (__spec__.parent, "server"),
    "background_services_lifespan": (__spec__.parent, "lifespan"),
    "CodeWeaverMCPConfig": (__spec__.parent, "config.mcp"),
    "CodeWeaverMCPConfigDict": (__spec__.parent, "config.types"),
    "create_http_server": (__spec__.parent, "mcp.server"),
    "create_stdio_server": (__spec__.parent, "mcp.server"),
    "FastMCPConfig": (__spec__.parent, "config.mcp"),
    "FastMCPRemoteMCPServer": (__spec__.parent, "config.mcp"),
    "FastMCPStdioMCPServer": (__spec__.parent, "config.mcp"),
    "favicon": (__spec__.parent, "management"),
    "find_code": (__spec__.parent, "agent_api.find_code"),
    "find_code_tool": (__spec__.parent, "mcp.user_agent"),
    "get_bulk_tool": (__spec__.parent, "mcp.tools"),
    "get_user_agent": (__spec__.parent, "agent_api"),
    "getLogger": (__spec__.parent, "_logging"),
    "health": (__spec__.parent, "management"),
    "http_lifespan": (__spec__.parent, "lifespan"),
    "HTTPProtocolType": (__spec__.parent, "config.types"),
    "lifespan": (__spec__.parent, "server"),
    "MCPConfig": (__spec__.parent, "config.mcp"),
    "MCPConfigDict": (__spec__.parent, "config.types"),
    "register_tool": (__spec__.parent, "mcp.tools"),
    "run_background_indexing": (__spec__.parent, "background_services"),
    "settings": (__spec__.parent, "management"),
    "settings_info": (__spec__.parent, "management"),
    "setup_logger": (__spec__.parent, "_logging"),
    "shutdown_handler": (__spec__.parent, "management"),
    "start_watcher": (__spec__.parent, "background_services"),
    "state_info": (__spec__.parent, "management"),
    "stats_info": (__spec__.parent, "management"),
    "status_info": (__spec__.parent, "management"),
    "update_mcp_config_file": (__spec__.parent, "config.mcp"),
    "version": (__spec__.parent, "server"),
    "version_info": (__spec__.parent, "management"),
    "WSProtocolType": (__spec__.parent, "config.types"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BRACKET_PATTERN",
    "CODEWEAVER_SVG_ICON",
    "ASGIMiddleware",
    "BaseFastMcpServerSettings",
    "CodeMatch",
    "CodeMatchType",
    "CodeWeaverMCPConfig",
    "CodeWeaverMCPConfigDict",
    "CodeWeaverSettings",
    "CodeWeaverSettingsDict",
    "CodeWeaverSettingsType",
    "CodeWeaverState",
    "CodeWeaverStateDep",
    "ConfigurationError",
    "ContextAgentToolkit",
    "CwMcpHttpState",
    "DefaultEndpointSettings",
    "DefaultFastMcpHttpRunArgs",
    "DefaultFastMcpServerSettings",
    "DefaultMiddlewareSettings",
    "DefaultUvicornSettings",
    "DefaultUvicornSettingsForMcp",
    "DetailedTimingMiddleware",
    "EmbeddingProviderServiceInfo",
    "EndpointSettingsDict",
    "ErrorHandlingMiddleware",
    "ErrorHandlingMiddlewareSettings",
    "FailoverInfo",
    "FailoverServiceDep",
    "FastMCPConfig",
    "FastMCPRemoteMCPServer",
    "FastMCPServerSettings",
    "FastMCPStdioMCPServer",
    "FastMcpHttpRunArgs",
    "FastMcpHttpServerSettings",
    "FastMcpServerSettingsDict",
    "FastMcpStdioServerSettings",
    "FindCodeResponseSummary",
    "FindCodeSubmission",
    "HTTPProtocolType",
    "HealthResponse",
    "HealthService",
    "HealthServiceDep",
    "IndexingInfo",
    "IndexingProgressInfo",
    "IndexingServiceDep",
    "InitializationError",
    "IntentResult",
    "IntentType",
    "InterfaceType",
    "LifespanType",
    "LoggingMiddleware",
    "LoggingMiddlewareSettings",
    "MCPConfig",
    "MCPConfigDict",
    "MCPServerConfig",
    "ManagementServer",
    "ManagementServerDep",
    "MappingProxyType",
    "MatchedSection",
    "McpMiddleware",
    "McpMiddlewareContext",
    "MiddlewareOptions",
    "MissingValueError",
    "ProviderError",
    "ProviderSettingsDep",
    "QueryComplexity",
    "QueryError",
    "QueryIntent",
    "RateLimitingMiddleware",
    "RateLimitingMiddlewareSettings",
    "RerankingServiceInfo",
    "ResolvedProjectNameDep",
    "ResolvedProjectPathDep",
    "ResourceInfo",
    "ResponseCachingMiddleware",
    "ResponseCachingMiddlewareSettings",
    "RetryMiddleware",
    "RetryMiddlewareSettings",
    "SearchPackageDep",
    "ServicesInfo",
    "SettingsDep",
    "SettingsMapDep",
    "SparseEmbeddingServiceInfo",
    "StatisticsDep",
    "StatisticsInfo",
    "StatisticsMiddleware",
    "StdioClientLifespan",
    "StdioCodeWeaverConfig",
    "StdioCodeWeaverConfigDict",
    "StructuredLoggingMiddleware",
    "TelemetryServiceDep",
    "TelemetrySettingsDep",
    "ToolAnnotationsDict",
    "ToolCollectionDict",
    "ToolRegistrationDict",
    "UvicornServerSettings",
    "UvicornServerSettingsDict",
    "ValidationError",
    "VectorStoreServiceInfo",
    "WSProtocolType",
    "background_services_lifespan",
    "create_http_server",
    "create_stdio_server",
    "favicon",
    "find_code",
    "find_code_tool",
    "getLogger",
    "get_bulk_tool",
    "get_user_agent",
    "health",
    "http_lifespan",
    "lifespan",
    "register_tool",
    "run_background_indexing",
    "settings",
    "settings_info",
    "setup_logger",
    "shutdown_handler",
    "start_watcher",
    "state_info",
    "stats_info",
    "status_info",
    "update_mcp_config_file",
    "version",
    "version_info",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
