# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Delimiter system for semantic code chunking.

This module provides a comprehensive delimiter-based chunking system with:

- Pattern-based delimiter definitions (DSL)
- Language family classification and reuse
- Cross-platform line ending support
- Unknown language inference
- Automatic delimiter generation
- Async/non-blocking language detection

The delimiter system is organized into three tiers:

1. **Patterns** (`patterns.py`): Language-agnostic delimiter patterns. Additionally, `custom.py` provides language-specific overrides and additions, like for Bash's `keyword`...`done` semantics like `do...done`.
2. **Families** (`families.py`): Reusable language family delimiter groups
3. **Languages** (generated): Language-specific delimiter sets composed from patterns

Together, these components enable robust and flexible code chunking across many programming languages, with over 170 languages explicitly supported, and the ability to infer delimiters for unknown languages (note: CodeWeaver does not index unknown file extensions, so users must expressly set new languages for indexing in the configuration, either with `codeweaver.settings.CodeWeaverSettings.custom_delimiters` or `codeweaver.settings.CodeWeaverSettings.custom_languages`).

Key exports:
    - DelimiterPattern: Pattern definition for delimiter generation
    - LanguageFamily: Language family classification
    - expand_pattern: Convert patterns to concrete delimiters
    - detect_language_family: Infer family without blocking event loop (async)
"""

from __future__ import annotations

from types import MappingProxyType

# === MANAGED EXPORTS ===
# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.engine.chunker.delimiters.custom import (
        ASSEMBLY_SEMICOLON_COMMENT,
        BASH_CASE_PATTERN,
        BASH_DO_PATTERN,
        BASH_FOR_PATTERN,
        BASH_IF_PATTERN,
        BASH_UNTIL_PATTERN,
        BASH_WHILE_PATTERN,
        COBOL_ASTERISK_COMMENT_PATTERN,
        COBOL_DIVISION_PATTERN,
        COBOL_EVALUATE_PATTERN,
        COBOL_IF_PATTERN,
        COBOL_INLINE_COMMENT_PATTERN,
        COBOL_PERFORM_PATTERN,
        COBOL_SEARCH_PATTERN,
        COBOL_SECTION_PATTERN,
        COQ_MATCH_END_PATTERN,
        COQ_SECTION_END_PATTERN,
        CSV_PATTERN,
        CUSTOM_PATTERNS,
        ELIXIR_DEFMODULE_PATTERN,
        ELIXIR_DEFP_PATTERN,
        ELIXIR_DO_END_PATTERN,
        GO_DEFER_PATTERN,
        GO_GO_PATTERN,
        GO_TYPE_PATTERN,
        HTML_TAGS_PATTERNS,
        LUA_DO_END_PATTERN,
        LUA_FOR_END_PATTERN,
        LUA_FUNCTION_END_PATTERN,
        LUA_IF_END_PATTERN,
        LUA_REPEAT_UNTIL_PATTERN,
        LUA_WHILE_END_PATTERN,
        PKL_DOC_COMMENT_PATTERN,
        PKL_IMPORT_PATTERN,
        POD_SECTION_PATTERN,
        POD_SUB_PATTERN,
        PROTOBUF_DECLARATION_PATTERN,
        PROTOBUF_DEFINITION_PATTERN,
        PROTOBUF_HIERARCHY_PATTERN,
        PYTHON_DECORATOR_AT_PATTERN,
        RST_COMMENT_PATTERN,
        RST_SECTION_PATTERN,
        RTF_EMPTY_PATTERN,
        RTF_LINE_PATTERN,
        RTF_PARAGRAPH_PATTERN,
        RTF_WHITESPACE_PATTERN,
        RUBY_DO_END_PATTERN,
        RUST_ATTRIBUTE_PATTERN,
        RUST_IMPL_PATTERN,
        RUST_MACRO_PATTERN,
        RUST_TYPE_PATTERN,
        TEXINFO_BLOCK_PATTERN,
        TSV_PATTERN,
        generate_rst_character_ranges,
        get_custom_patterns,
    )
    from codeweaver.engine.chunker.delimiters.families import (
        PatternKey,
        defined_languages,
        detect_family_characteristics,
        detect_language_family,
        get_family_patterns,
    )
    from codeweaver.engine.chunker.delimiters.patterns import (
        ALL_PATTERNS,
        ARRAY_PATTERN,
        BEGIN_END_BLOCK_PATTERN,
        BRACE_BLOCK_PATTERN,
        C_BLOCK_COMMENT_PATTERN,
        CLASS_PATTERN,
        CONDITIONAL_PATTERN,
        CONDITIONAL_TEX_PATTERN,
        CONTEXT_MANAGER_PATTERN,
        DASH_COMMENT_PATTERN,
        DECORATOR_PATTERN,
        DOCSTRING_ELIXIR_PATTERN,
        DOCSTRING_HASH_PATTERN,
        DOCSTRING_MATLAB_PATTERN,
        DOCSTRING_QUOTE_PATTERN,
        DOCSTRING_RUBY_PATTERN,
        DOCSTRING_SEMICOLON_PATTERN,
        DOCSTRING_SLASH_PATTERN,
        EMPTY_PATTERN,
        ENUM_PATTERN,
        EXCLAMATION_COMMENT_PATTERN,
        EXTENSION_PATTERN,
        FUNCTION_PATTERN,
        HASH_COMMENT_PATTERN,
        HASKELL_BLOCK_COMMENT_PATTERN,
        HTML_COMMENT_PATTERN,
        IMPL_PATTERN,
        INTERFACE_PATTERN,
        JULIA_BLOCK_COMMENT_PATTERN,
        LATEX_ALIGN_PATTERNS,
        LATEX_ARRAY_PATTERNS,
        LATEX_BLOCK_PATTERNS,
        LATEX_ENV_PATTERN,
        LATEX_LITERALS_PATTERNS,
        LATEX_SECTION_PATTERN,
        LATEX_STRING_PATTERN,
        LET_END_BLOCK_PATTERN,
        LINEBREAK,
        LISP_BLOCK_COMMENT_PATTERN,
        LOOP_PATTERN,
        ML_BLOCK_COMMENT_PATTERN,
        MODULE_BOUNDARY_PATTERN,
        MODULE_PATTERN,
        NEWLINE_PATTERN,
        NIM_BLOCK_COMMENT_PATTERN,
        PARAGRAPH_BREAK,
        PARAGRAPH_PATTERN,
        PERCENT_COMMENT_PATTERN,
        PRAGMA_PATTERN,
        PROOF_BLOCK_PATTERN,
        PROPERTY_PATTERN,
        RUST_RAW_STRING_COMMENT_PATTERN,
        SEMICOLON_COMMENT_PATTERN,
        SLASH_COMMENT_PATTERN,
        STAR_COMMENT_PATTERN,
        STRING_ANGLE_PATTERN,
        STRING_BACKTICK_QUOTE_PATTERN,
        STRING_BYTES_PATTERN,
        STRING_FORMATTED_PATTERN,
        STRING_HASH_PATTERN,
        STRING_QUOTE_PATTERN,
        STRING_RAW_BYTES_PATTERN,
        STRING_RAW_FORMATTED_PATTERN,
        STRING_RAW_PATTERN,
        STRING_STAR_PATTERN,
        STRUCT_PATTERN,
        TEMPLATE_ANGLE_PATTERN,
        TEMPLATE_BACKTICK_PATTERN,
        TEMPLATE_BRACE_PATTERN,
        TEMPLATE_BRACKET_PATTERN,
        TEMPLATE_PERCENT_PATTERN,
        TEMPLATE_PIPE_PATTERN,
        TEMPLATE_TILDE_PATTERN,
        TRY_CATCH_PATTERN,
        TUPLE_PATTERN,
        TYPE_ALIAS_PATTERN,
        WHITESPACE_PATTERN,
        expand_pattern,
        generate_latex_patterns,
        kind_from_delimiter_tuple,
        matches_pattern,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ALL_PATTERNS": (__spec__.parent, "patterns"),
    "ARRAY_PATTERN": (__spec__.parent, "patterns"),
    "ASSEMBLY_SEMICOLON_COMMENT": (__spec__.parent, "custom"),
    "BASH_CASE_PATTERN": (__spec__.parent, "custom"),
    "BASH_DO_PATTERN": (__spec__.parent, "custom"),
    "BASH_FOR_PATTERN": (__spec__.parent, "custom"),
    "BASH_IF_PATTERN": (__spec__.parent, "custom"),
    "BASH_UNTIL_PATTERN": (__spec__.parent, "custom"),
    "BASH_WHILE_PATTERN": (__spec__.parent, "custom"),
    "BEGIN_END_BLOCK_PATTERN": (__spec__.parent, "patterns"),
    "BRACE_BLOCK_PATTERN": (__spec__.parent, "patterns"),
    "C_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "CLASS_PATTERN": (__spec__.parent, "patterns"),
    "COBOL_ASTERISK_COMMENT_PATTERN": (__spec__.parent, "custom"),
    "COBOL_DIVISION_PATTERN": (__spec__.parent, "custom"),
    "COBOL_EVALUATE_PATTERN": (__spec__.parent, "custom"),
    "COBOL_IF_PATTERN": (__spec__.parent, "custom"),
    "COBOL_INLINE_COMMENT_PATTERN": (__spec__.parent, "custom"),
    "COBOL_PERFORM_PATTERN": (__spec__.parent, "custom"),
    "COBOL_SEARCH_PATTERN": (__spec__.parent, "custom"),
    "COBOL_SECTION_PATTERN": (__spec__.parent, "custom"),
    "CONDITIONAL_PATTERN": (__spec__.parent, "patterns"),
    "CONDITIONAL_TEX_PATTERN": (__spec__.parent, "patterns"),
    "CONTEXT_MANAGER_PATTERN": (__spec__.parent, "patterns"),
    "COQ_MATCH_END_PATTERN": (__spec__.parent, "custom"),
    "COQ_SECTION_END_PATTERN": (__spec__.parent, "custom"),
    "CSV_PATTERN": (__spec__.parent, "custom"),
    "CUSTOM_PATTERNS": (__spec__.parent, "custom"),
    "DASH_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "DECORATOR_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_ELIXIR_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_HASH_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_MATLAB_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_QUOTE_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_RUBY_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_SEMICOLON_PATTERN": (__spec__.parent, "patterns"),
    "DOCSTRING_SLASH_PATTERN": (__spec__.parent, "patterns"),
    "ELIXIR_DEFMODULE_PATTERN": (__spec__.parent, "custom"),
    "ELIXIR_DEFP_PATTERN": (__spec__.parent, "custom"),
    "ELIXIR_DO_END_PATTERN": (__spec__.parent, "custom"),
    "EMPTY_PATTERN": (__spec__.parent, "patterns"),
    "ENUM_PATTERN": (__spec__.parent, "patterns"),
    "EXCLAMATION_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "EXTENSION_PATTERN": (__spec__.parent, "patterns"),
    "FUNCTION_PATTERN": (__spec__.parent, "patterns"),
    "GO_DEFER_PATTERN": (__spec__.parent, "custom"),
    "GO_GO_PATTERN": (__spec__.parent, "custom"),
    "GO_TYPE_PATTERN": (__spec__.parent, "custom"),
    "HASH_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "HASKELL_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "HTML_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "HTML_TAGS_PATTERNS": (__spec__.parent, "custom"),
    "IMPL_PATTERN": (__spec__.parent, "patterns"),
    "INTERFACE_PATTERN": (__spec__.parent, "patterns"),
    "JULIA_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "LATEX_ALIGN_PATTERNS": (__spec__.parent, "patterns"),
    "LATEX_ARRAY_PATTERNS": (__spec__.parent, "patterns"),
    "LATEX_BLOCK_PATTERNS": (__spec__.parent, "patterns"),
    "LATEX_ENV_PATTERN": (__spec__.parent, "patterns"),
    "LATEX_LITERALS_PATTERNS": (__spec__.parent, "patterns"),
    "LATEX_SECTION_PATTERN": (__spec__.parent, "patterns"),
    "LATEX_STRING_PATTERN": (__spec__.parent, "patterns"),
    "LET_END_BLOCK_PATTERN": (__spec__.parent, "patterns"),
    "LINEBREAK": (__spec__.parent, "patterns"),
    "LISP_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "LOOP_PATTERN": (__spec__.parent, "patterns"),
    "LUA_DO_END_PATTERN": (__spec__.parent, "custom"),
    "LUA_FOR_END_PATTERN": (__spec__.parent, "custom"),
    "LUA_FUNCTION_END_PATTERN": (__spec__.parent, "custom"),
    "LUA_IF_END_PATTERN": (__spec__.parent, "custom"),
    "LUA_REPEAT_UNTIL_PATTERN": (__spec__.parent, "custom"),
    "LUA_WHILE_END_PATTERN": (__spec__.parent, "custom"),
    "ML_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "MODULE_BOUNDARY_PATTERN": (__spec__.parent, "patterns"),
    "MODULE_PATTERN": (__spec__.parent, "patterns"),
    "NEWLINE_PATTERN": (__spec__.parent, "patterns"),
    "NIM_BLOCK_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "PARAGRAPH_BREAK": (__spec__.parent, "patterns"),
    "PARAGRAPH_PATTERN": (__spec__.parent, "patterns"),
    "PERCENT_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "PKL_DOC_COMMENT_PATTERN": (__spec__.parent, "custom"),
    "PKL_IMPORT_PATTERN": (__spec__.parent, "custom"),
    "POD_SECTION_PATTERN": (__spec__.parent, "custom"),
    "POD_SUB_PATTERN": (__spec__.parent, "custom"),
    "PRAGMA_PATTERN": (__spec__.parent, "patterns"),
    "PROOF_BLOCK_PATTERN": (__spec__.parent, "patterns"),
    "PROPERTY_PATTERN": (__spec__.parent, "patterns"),
    "PROTOBUF_DECLARATION_PATTERN": (__spec__.parent, "custom"),
    "PROTOBUF_DEFINITION_PATTERN": (__spec__.parent, "custom"),
    "PROTOBUF_HIERARCHY_PATTERN": (__spec__.parent, "custom"),
    "PYTHON_DECORATOR_AT_PATTERN": (__spec__.parent, "custom"),
    "RST_COMMENT_PATTERN": (__spec__.parent, "custom"),
    "RST_SECTION_PATTERN": (__spec__.parent, "custom"),
    "RTF_EMPTY_PATTERN": (__spec__.parent, "custom"),
    "RTF_LINE_PATTERN": (__spec__.parent, "custom"),
    "RTF_PARAGRAPH_PATTERN": (__spec__.parent, "custom"),
    "RTF_WHITESPACE_PATTERN": (__spec__.parent, "custom"),
    "RUBY_DO_END_PATTERN": (__spec__.parent, "custom"),
    "RUST_ATTRIBUTE_PATTERN": (__spec__.parent, "custom"),
    "RUST_IMPL_PATTERN": (__spec__.parent, "custom"),
    "RUST_MACRO_PATTERN": (__spec__.parent, "custom"),
    "RUST_RAW_STRING_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "RUST_TYPE_PATTERN": (__spec__.parent, "custom"),
    "SEMICOLON_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "SLASH_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "STAR_COMMENT_PATTERN": (__spec__.parent, "patterns"),
    "STRING_ANGLE_PATTERN": (__spec__.parent, "patterns"),
    "STRING_BACKTICK_QUOTE_PATTERN": (__spec__.parent, "patterns"),
    "STRING_BYTES_PATTERN": (__spec__.parent, "patterns"),
    "STRING_FORMATTED_PATTERN": (__spec__.parent, "patterns"),
    "STRING_HASH_PATTERN": (__spec__.parent, "patterns"),
    "STRING_QUOTE_PATTERN": (__spec__.parent, "patterns"),
    "STRING_RAW_BYTES_PATTERN": (__spec__.parent, "patterns"),
    "STRING_RAW_FORMATTED_PATTERN": (__spec__.parent, "patterns"),
    "STRING_RAW_PATTERN": (__spec__.parent, "patterns"),
    "STRING_STAR_PATTERN": (__spec__.parent, "patterns"),
    "STRUCT_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_ANGLE_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_BACKTICK_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_BRACE_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_BRACKET_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_PERCENT_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_PIPE_PATTERN": (__spec__.parent, "patterns"),
    "TEMPLATE_TILDE_PATTERN": (__spec__.parent, "patterns"),
    "TEXINFO_BLOCK_PATTERN": (__spec__.parent, "custom"),
    "TRY_CATCH_PATTERN": (__spec__.parent, "patterns"),
    "TSV_PATTERN": (__spec__.parent, "custom"),
    "TUPLE_PATTERN": (__spec__.parent, "patterns"),
    "TYPE_ALIAS_PATTERN": (__spec__.parent, "patterns"),
    "WHITESPACE_PATTERN": (__spec__.parent, "patterns"),
    "PatternKey": (__spec__.parent, "families"),
    "defined_languages": (__spec__.parent, "families"),
    "detect_family_characteristics": (__spec__.parent, "families"),
    "detect_language_family": (__spec__.parent, "families"),
    "expand_pattern": (__spec__.parent, "patterns"),
    "generate_latex_patterns": (__spec__.parent, "patterns"),
    "generate_rst_character_ranges": (__spec__.parent, "custom"),
    "get_custom_patterns": (__spec__.parent, "custom"),
    "get_family_patterns": (__spec__.parent, "families"),
    "kind_from_delimiter_tuple": (__spec__.parent, "patterns"),
    "matches_pattern": (__spec__.parent, "patterns"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "ALL_PATTERNS",
    "ARRAY_PATTERN",
    "ASSEMBLY_SEMICOLON_COMMENT",
    "BASH_CASE_PATTERN",
    "BASH_DO_PATTERN",
    "BASH_FOR_PATTERN",
    "BASH_IF_PATTERN",
    "BASH_UNTIL_PATTERN",
    "BASH_WHILE_PATTERN",
    "BEGIN_END_BLOCK_PATTERN",
    "BRACE_BLOCK_PATTERN",
    "CLASS_PATTERN",
    "COBOL_ASTERISK_COMMENT_PATTERN",
    "COBOL_DIVISION_PATTERN",
    "COBOL_EVALUATE_PATTERN",
    "COBOL_IF_PATTERN",
    "COBOL_INLINE_COMMENT_PATTERN",
    "COBOL_PERFORM_PATTERN",
    "COBOL_SEARCH_PATTERN",
    "COBOL_SECTION_PATTERN",
    "CONDITIONAL_PATTERN",
    "CONDITIONAL_TEX_PATTERN",
    "CONTEXT_MANAGER_PATTERN",
    "COQ_MATCH_END_PATTERN",
    "COQ_SECTION_END_PATTERN",
    "CSV_PATTERN",
    "CUSTOM_PATTERNS",
    "C_BLOCK_COMMENT_PATTERN",
    "DASH_COMMENT_PATTERN",
    "DECORATOR_PATTERN",
    "DOCSTRING_ELIXIR_PATTERN",
    "DOCSTRING_HASH_PATTERN",
    "DOCSTRING_MATLAB_PATTERN",
    "DOCSTRING_QUOTE_PATTERN",
    "DOCSTRING_RUBY_PATTERN",
    "DOCSTRING_SEMICOLON_PATTERN",
    "DOCSTRING_SLASH_PATTERN",
    "ELIXIR_DEFMODULE_PATTERN",
    "ELIXIR_DEFP_PATTERN",
    "ELIXIR_DO_END_PATTERN",
    "EMPTY_PATTERN",
    "ENUM_PATTERN",
    "EXCLAMATION_COMMENT_PATTERN",
    "EXTENSION_PATTERN",
    "FUNCTION_PATTERN",
    "GO_DEFER_PATTERN",
    "GO_GO_PATTERN",
    "GO_TYPE_PATTERN",
    "HASH_COMMENT_PATTERN",
    "HASKELL_BLOCK_COMMENT_PATTERN",
    "HTML_COMMENT_PATTERN",
    "HTML_TAGS_PATTERNS",
    "IMPL_PATTERN",
    "INTERFACE_PATTERN",
    "JULIA_BLOCK_COMMENT_PATTERN",
    "LATEX_ALIGN_PATTERNS",
    "LATEX_ARRAY_PATTERNS",
    "LATEX_BLOCK_PATTERNS",
    "LATEX_ENV_PATTERN",
    "LATEX_LITERALS_PATTERNS",
    "LATEX_SECTION_PATTERN",
    "LATEX_STRING_PATTERN",
    "LET_END_BLOCK_PATTERN",
    "LINEBREAK",
    "LISP_BLOCK_COMMENT_PATTERN",
    "LOOP_PATTERN",
    "LUA_DO_END_PATTERN",
    "LUA_FOR_END_PATTERN",
    "LUA_FUNCTION_END_PATTERN",
    "LUA_IF_END_PATTERN",
    "LUA_REPEAT_UNTIL_PATTERN",
    "LUA_WHILE_END_PATTERN",
    "ML_BLOCK_COMMENT_PATTERN",
    "MODULE_BOUNDARY_PATTERN",
    "MODULE_PATTERN",
    "NEWLINE_PATTERN",
    "NIM_BLOCK_COMMENT_PATTERN",
    "PARAGRAPH_BREAK",
    "PARAGRAPH_PATTERN",
    "PERCENT_COMMENT_PATTERN",
    "PKL_DOC_COMMENT_PATTERN",
    "PKL_IMPORT_PATTERN",
    "POD_SECTION_PATTERN",
    "POD_SUB_PATTERN",
    "PRAGMA_PATTERN",
    "PROOF_BLOCK_PATTERN",
    "PROPERTY_PATTERN",
    "PROTOBUF_DECLARATION_PATTERN",
    "PROTOBUF_DEFINITION_PATTERN",
    "PROTOBUF_HIERARCHY_PATTERN",
    "PYTHON_DECORATOR_AT_PATTERN",
    "RST_COMMENT_PATTERN",
    "RST_SECTION_PATTERN",
    "RTF_EMPTY_PATTERN",
    "RTF_LINE_PATTERN",
    "RTF_PARAGRAPH_PATTERN",
    "RTF_WHITESPACE_PATTERN",
    "RUBY_DO_END_PATTERN",
    "RUST_ATTRIBUTE_PATTERN",
    "RUST_IMPL_PATTERN",
    "RUST_MACRO_PATTERN",
    "RUST_RAW_STRING_COMMENT_PATTERN",
    "RUST_TYPE_PATTERN",
    "SEMICOLON_COMMENT_PATTERN",
    "SLASH_COMMENT_PATTERN",
    "STAR_COMMENT_PATTERN",
    "STRING_ANGLE_PATTERN",
    "STRING_BACKTICK_QUOTE_PATTERN",
    "STRING_BYTES_PATTERN",
    "STRING_FORMATTED_PATTERN",
    "STRING_HASH_PATTERN",
    "STRING_QUOTE_PATTERN",
    "STRING_RAW_BYTES_PATTERN",
    "STRING_RAW_FORMATTED_PATTERN",
    "STRING_RAW_PATTERN",
    "STRING_STAR_PATTERN",
    "STRUCT_PATTERN",
    "TEMPLATE_ANGLE_PATTERN",
    "TEMPLATE_BACKTICK_PATTERN",
    "TEMPLATE_BRACE_PATTERN",
    "TEMPLATE_BRACKET_PATTERN",
    "TEMPLATE_PERCENT_PATTERN",
    "TEMPLATE_PIPE_PATTERN",
    "TEMPLATE_TILDE_PATTERN",
    "TEXINFO_BLOCK_PATTERN",
    "TRY_CATCH_PATTERN",
    "TSV_PATTERN",
    "TUPLE_PATTERN",
    "TYPE_ALIAS_PATTERN",
    "WHITESPACE_PATTERN",
    "PatternKey",
    "defined_languages",
    "detect_family_characteristics",
    "detect_language_family",
    "expand_pattern",
    "generate_latex_patterns",
    "generate_rst_character_ranges",
    "get_custom_patterns",
    "get_family_patterns",
    "kind_from_delimiter_tuple",
    "matches_pattern",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
