# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Package-level lazy imports for codeweaver.core.utils."""

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core.utils.lazy_importer import LazyImport, create_lazy_getattr, lazy_import


if TYPE_CHECKING:
    from codeweaver.core.utils.checks import (
        LOCALHOST_INDICATORS,
        TypeIs,
        file_is_binary,
        has_package,
        is_ci,
        is_class,
        is_debug,
        is_local_host,
        is_pydantic_basemodel,
        is_test_environment,
        is_typeadapter,
        is_wsl,
        is_wsl_vscode,
    )
    from codeweaver.core.utils.environment import (
        detect_root_package,
        find_qdrant_instance,
        format_file_link,
        get_codeweaver_config_paths,
        get_codeweaver_prefix,
        get_possible_env_vars,
        get_terminal_width,
        in_ide,
        is_codeweaver_config_path,
        is_tty,
        qdrant_instance_live_at_port,
        settings_type_for_root_package,
        we_are_in_jetbrains,
        we_are_in_vscode,
    )
    from codeweaver.core.utils.filesystem import (
        COMMON_LLM_TOOLING_PATHS,
        COMMON_TOOLING_PATHS,
        get_git_branch,
        get_git_revision,
        get_project_path,
        get_tooling_dirs,
        get_user_cache_dir,
        get_user_config_dir,
        get_user_data_dir,
        get_user_state_dir,
        has_git,
        in_codeweaver_clone,
        is_git_dir,
        normalize_ext,
        set_relative_path,
        try_git_rev_parse,
    )
    from codeweaver.core.utils.general import (
        deep_merge_dicts,
        dict_set_to_tuple,
        ensure_iterable,
        generate_collection_name,
        rpartial,
        supported_language_count,
        supported_languages,
    )
    from codeweaver.core.utils.generation import (
        get_blake_hash,
        get_blake_hash_generic,
        uuid7,
        uuid7_as_timestamp,
    )
    from codeweaver.core.utils.introspect import (
        clean_args,
        get_caller,
        get_caller_module,
        get_caller_modulename,
        get_class_attrs,
        get_class_constructor,
        get_class_methods,
        get_class_properties,
        get_class_variables,
        get_file_path,
        get_function_annotations,
        get_function_parameters,
        get_function_signature,
        get_generic_params_for_type,
        get_source_code,
        get_source_start_end,
        getdoc,
        getmodule,
        getmodulename,
        getsourcefile,
        is_constructor_arg,
        isclass,
        isfunction,
        ismethod,
        keyword_args,
        positional_args,
        return_type,
        takes_args,
        takes_kwargs,
    )
    from codeweaver.core.utils.procs import (
        asyncio_or_uvloop,
        effective_cpu_count,
        get_cpu_count,
        get_optimal_workers,
        low_priority,
        python_version,
        very_low_priority,
    )
    from codeweaver.core.utils.text import (
        BOUNDARY,
        CONTROL_CHARS,
        INJECT_PATTERN,
        INVISIBLE_CHARS,
        INVISIBLE_PATTERN,
        LOWLY_WORDS,
        MAX_REGEX_PATTERN_LENGTH,
        NORMALIZE_FORM,
        POSSIBLE_PROMPT_INJECTS,
        REMOVE_ID,
        elapsed_time_to_human_readable,
        format_descriptor,
        format_docstring,
        format_signature,
        format_snippet_name,
        humanize,
        sanitize_unicode,
        to_lowly_lowercase,
        to_tokens,
        truncate_text,
        validate_regex_pattern,
        variable_to_env_var,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BOUNDARY": (__spec__.parent, "text"),
    "COMMON_LLM_TOOLING_PATHS": (__spec__.parent, "filesystem"),
    "COMMON_TOOLING_PATHS": (__spec__.parent, "filesystem"),
    "CONTROL_CHARS": (__spec__.parent, "text"),
    "INJECT_PATTERN": (__spec__.parent, "text"),
    "INVISIBLE_CHARS": (__spec__.parent, "text"),
    "INVISIBLE_PATTERN": (__spec__.parent, "text"),
    "LOCALHOST_INDICATORS": (__spec__.parent, "checks"),
    "LOWLY_WORDS": (__spec__.parent, "text"),
    "MAX_REGEX_PATTERN_LENGTH": (__spec__.parent, "text"),
    "NORMALIZE_FORM": (__spec__.parent, "text"),
    "POSSIBLE_PROMPT_INJECTS": (__spec__.parent, "text"),
    "REMOVE_ID": (__spec__.parent, "text"),
    "TypeIs": (__spec__.parent, "checks"),
    "asyncio_or_uvloop": (__spec__.parent, "procs"),
    "clean_args": (__spec__.parent, "introspect"),
    "detect_root_package": (__spec__.parent, "environment"),
    "dict_set_to_tuple": (__spec__.parent, "general"),
    "deep_merge_dicts": (__spec__.parent, "general"),
    "effective_cpu_count": (__spec__.parent, "procs"),
    "elapsed_time_to_human_readable": (__spec__.parent, "text"),
    "ensure_iterable": (__spec__.parent, "general"),
    "file_is_binary": (__spec__.parent, "checks"),
    "find_qdrant_instance": (__spec__.parent, "environment"),
    "format_descriptor": (__spec__.parent, "text"),
    "format_docstring": (__spec__.parent, "text"),
    "format_file_link": (__spec__.parent, "environment"),
    "format_signature": (__spec__.parent, "text"),
    "format_snippet_name": (__spec__.parent, "text"),
    "generate_collection_name": (__spec__.parent, "general"),
    "get_blake_hash": (__spec__.parent, "generation"),
    "get_blake_hash_generic": (__spec__.parent, "generation"),
    "get_caller": (__spec__.parent, "introspect"),
    "get_caller_module": (__spec__.parent, "introspect"),
    "get_caller_modulename": (__spec__.parent, "introspect"),
    "get_class_attrs": (__spec__.parent, "introspect"),
    "get_class_constructor": (__spec__.parent, "introspect"),
    "get_class_methods": (__spec__.parent, "introspect"),
    "get_class_properties": (__spec__.parent, "introspect"),
    "get_class_variables": (__spec__.parent, "introspect"),
    "get_codeweaver_config_paths": (__spec__.parent, "environment"),
    "get_codeweaver_prefix": (__spec__.parent, "environment"),
    "get_cpu_count": (__spec__.parent, "procs"),
    "get_file_path": (__spec__.parent, "introspect"),
    "get_function_annotations": (__spec__.parent, "introspect"),
    "get_function_parameters": (__spec__.parent, "introspect"),
    "get_function_signature": (__spec__.parent, "introspect"),
    "get_generic_params_for_type": (__spec__.parent, "introspect"),
    "get_git_branch": (__spec__.parent, "filesystem"),
    "get_git_revision": (__spec__.parent, "filesystem"),
    "get_optimal_workers": (__spec__.parent, "procs"),
    "get_possible_env_vars": (__spec__.parent, "environment"),
    "get_project_path": (__spec__.parent, "filesystem"),
    "get_source_code": (__spec__.parent, "introspect"),
    "get_source_start_end": (__spec__.parent, "introspect"),
    "get_terminal_width": (__spec__.parent, "environment"),
    "get_tooling_dirs": (__spec__.parent, "filesystem"),
    "get_user_cache_dir": (__spec__.parent, "filesystem"),
    "get_user_config_dir": (__spec__.parent, "filesystem"),
    "get_user_data_dir": (__spec__.parent, "filesystem"),
    "get_user_state_dir": (__spec__.parent, "filesystem"),
    "getdoc": (__spec__.parent, "introspect"),
    "getmodule": (__spec__.parent, "introspect"),
    "getmodulename": (__spec__.parent, "introspect"),
    "getsourcefile": (__spec__.parent, "introspect"),
    "has_git": (__spec__.parent, "filesystem"),
    "has_package": (__spec__.parent, "checks"),
    "humanize": (__spec__.parent, "text"),
    "in_codeweaver_clone": (__spec__.parent, "filesystem"),
    "in_ide": (__spec__.parent, "environment"),
    "is_ci": (__spec__.parent, "checks"),
    "is_class": (__spec__.parent, "checks"),
    "is_codeweaver_config_path": (__spec__.parent, "environment"),
    "is_constructor_arg": (__spec__.parent, "introspect"),
    "is_debug": (__spec__.parent, "checks"),
    "is_git_dir": (__spec__.parent, "filesystem"),
    "is_local_host": (__spec__.parent, "checks"),
    "is_pydantic_basemodel": (__spec__.parent, "checks"),
    "is_test_environment": (__spec__.parent, "checks"),
    "is_tty": (__spec__.parent, "environment"),
    "is_typeadapter": (__spec__.parent, "checks"),
    "is_wsl": (__spec__.parent, "checks"),
    "is_wsl_vscode": (__spec__.parent, "checks"),
    "isclass": (__spec__.parent, "introspect"),
    "isfunction": (__spec__.parent, "introspect"),
    "ismethod": (__spec__.parent, "introspect"),
    "keyword_args": (__spec__.parent, "introspect"),
    "low_priority": (__spec__.parent, "procs"),
    "normalize_ext": (__spec__.parent, "filesystem"),
    "positional_args": (__spec__.parent, "introspect"),
    "python_version": (__spec__.parent, "procs"),
    "qdrant_instance_live_at_port": (__spec__.parent, "environment"),
    "return_type": (__spec__.parent, "introspect"),
    "rpartial": (__spec__.parent, "general"),
    "sanitize_unicode": (__spec__.parent, "text"),
    "set_relative_path": (__spec__.parent, "filesystem"),
    "settings_type_for_root_package": (__spec__.parent, "environment"),
    "supported_language_count": (__spec__.parent, "general"),
    "supported_languages": (__spec__.parent, "general"),
    "takes_args": (__spec__.parent, "introspect"),
    "takes_kwargs": (__spec__.parent, "introspect"),
    "to_lowly_lowercase": (__spec__.parent, "text"),
    "to_tokens": (__spec__.parent, "text"),
    "truncate_text": (__spec__.parent, "text"),
    "try_git_rev_parse": (__spec__.parent, "filesystem"),
    "uuid7": (__spec__.parent, "generation"),
    "uuid7_as_timestamp": (__spec__.parent, "generation"),
    "validate_regex_pattern": (__spec__.parent, "text"),
    "variable_to_env_var": (__spec__.parent, "text"),
    "very_low_priority": (__spec__.parent, "procs"),
    "we_are_in_jetbrains": (__spec__.parent, "environment"),
    "we_are_in_vscode": (__spec__.parent, "environment"),
})

__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BOUNDARY",
    "COMMON_LLM_TOOLING_PATHS",
    "COMMON_TOOLING_PATHS",
    "CONTROL_CHARS",
    "INJECT_PATTERN",
    "INVISIBLE_CHARS",
    "INVISIBLE_PATTERN",
    "LOCALHOST_INDICATORS",
    "LOWLY_WORDS",
    "MAX_REGEX_PATTERN_LENGTH",
    "NORMALIZE_FORM",
    "POSSIBLE_PROMPT_INJECTS",
    "REMOVE_ID",
    "LazyImport",
    "TypeIs",
    "asyncio_or_uvloop",
    "clean_args",
    "create_lazy_getattr",
    "deep_merge_dicts",
    "detect_root_package",
    "dict_set_to_tuple",
    "effective_cpu_count",
    "elapsed_time_to_human_readable",
    "ensure_iterable",
    "file_is_binary",
    "find_qdrant_instance",
    "format_descriptor",
    "format_docstring",
    "format_file_link",
    "format_signature",
    "format_snippet_name",
    "generate_collection_name",
    "get_blake_hash",
    "get_blake_hash_generic",
    "get_caller",
    "get_caller_module",
    "get_caller_modulename",
    "get_class_attrs",
    "get_class_constructor",
    "get_class_methods",
    "get_class_properties",
    "get_class_variables",
    "get_codeweaver_config_paths",
    "get_codeweaver_prefix",
    "get_cpu_count",
    "get_file_path",
    "get_function_annotations",
    "get_function_parameters",
    "get_function_signature",
    "get_generic_params_for_type",
    "get_git_branch",
    "get_git_revision",
    "get_optimal_workers",
    "get_possible_env_vars",
    "get_project_path",
    "get_source_code",
    "get_source_start_end",
    "get_terminal_width",
    "get_tooling_dirs",
    "get_user_cache_dir",
    "get_user_config_dir",
    "get_user_data_dir",
    "get_user_state_dir",
    "getdoc",
    "getmodule",
    "getmodulename",
    "getsourcefile",
    "has_git",
    "has_package",
    "humanize",
    "in_codeweaver_clone",
    "in_ide",
    "is_ci",
    "is_class",
    "is_codeweaver_config_path",
    "is_constructor_arg",
    "is_debug",
    "is_git_dir",
    "is_local_host",
    "is_pydantic_basemodel",
    "is_test_environment",
    "is_tty",
    "is_typeadapter",
    "is_wsl",
    "is_wsl_vscode",
    "isclass",
    "isfunction",
    "ismethod",
    "keyword_args",
    "lazy_import",
    "low_priority",
    "normalize_ext",
    "positional_args",
    "python_version",
    "qdrant_instance_live_at_port",
    "return_type",
    "rpartial",
    "sanitize_unicode",
    "set_relative_path",
    "settings_type_for_root_package",
    "supported_language_count",
    "supported_languages",
    "takes_args",
    "takes_kwargs",
    "to_lowly_lowercase",
    "to_tokens",
    "truncate_text",
    "try_git_rev_parse",
    "uuid7",
    "uuid7_as_timestamp",
    "validate_regex_pattern",
    "variable_to_env_var",
    "very_low_priority",
    "we_are_in_jetbrains",
    "we_are_in_vscode",
)


def __dir__() -> list[str]:
    return list(__all__)
