"""Core utility functions for (most) CodeWeaver packages."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core.utils.lazy_import import LazyImport, create_lazy_getattr, lazy_import


if TYPE_CHECKING:
    from codeweaver.core.utils.checks import (
        file_is_binary,
        has_package,
        is_ci,
        is_class,
        is_debug,
        is_pydantic_basemodel,
        is_test_environment,
        is_typeadapter,
        is_wsl,
        is_wsl_vscode,
    )
    from codeweaver.core.utils.environment import (
        get_possible_env_vars,
        in_ide,
        is_tty,
        we_are_in_jetbrains,
        we_are_in_vscode,
    )
    from codeweaver.core.utils.filesystem import (
        COMMON_LLM_TOOLING_PATHS,
        COMMON_TOOLING_PATHS,
        backup_file_path,
        get_git_branch,
        get_git_revision,
        get_project_path,
        get_tooling_dirs,
        get_user_config_dir,
        has_git,
        in_codeweaver_clone,
        is_git_dir,
        normalize_ext,
        set_relative_path,
        try_git_rev_parse,
    )
    from codeweaver.core.utils.general import (
        DictInputTypesT,
        DictOutputTypesT,
        dict_set_to_tuple,
        ensure_iterable,
        generate_collection_name,
        rpartial,
    )
    from codeweaver.core.utils.generation import (
        get_blake_hash,
        get_blake_hash_generic,
        uuid7,
        uuid7_as_timestamp,
    )
    from codeweaver.core.utils.introspect import (
        clean_args,
        get_class_attrs,
        get_class_constructor,
        get_class_methods,
        get_class_properties,
        get_class_variables,
        get_function_annotations,
        get_function_parameters,
        get_function_signature,
        get_source_code,
        getdoc,
        getmodule,
        getmodulename,
        getsourcefile,
        isclass,
        isfunction,
        ismethod,
    )
    from codeweaver.core.utils.procs import (
        asyncio_or_uvloop,
        get_optimal_workers,
        low_priority,
        very_low_priority,
    )
    from codeweaver.core.utils.text import (
        elapsed_time_to_human_readable,
        format_descriptor,
        format_docstring,
        format_signature,
        format_snippet_name,
        humanize,
        sanitize_unicode,
        to_lowly_lowercase,
        to_tokens,
        truncate_text,
        validate_regex_pattern,
    )


_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "COMMON_LLM_TOOLING_PATHS": (__spec__.parent, "filesystem"),
    "COMMON_TOOLING_PATHS": (__spec__.parent, "filesystem"),
    "DictInputTypesT": (__spec__.parent, "general"),
    "DictOutputTypesT": (__spec__.parent, "general"),
    "asyncio_or_uvloop": (__spec__.parent, "procs"),
    "backup_file_path": (__spec__.parent, "filesystem"),
    "clean_args": (__spec__.parent, "introspect"),
    "dict_set_to_tuple": (__spec__.parent, "general"),
    "elapsed_time_to_human_readable": (__spec__.parent, "text"),
    "ensure_iterable": (__spec__.parent, "general"),
    "file_is_binary": (__spec__.parent, "checks"),
    "format_descriptor": (__spec__.parent, "text"),
    "format_docstring": (__spec__.parent, "text"),
    "format_signature": (__spec__.parent, "text"),
    "format_snippet_name": (__spec__.parent, "text"),
    "generate_collection_name": (__spec__.parent, "general"),
    "get_blake_hash": (__spec__.parent, "generation"),
    "get_blake_hash_generic": (__spec__.parent, "generation"),
    "get_class_attrs": (__spec__.parent, "introspect"),
    "get_class_constructor": (__spec__.parent, "introspect"),
    "get_class_methods": (__spec__.parent, "introspect"),
    "get_class_properties": (__spec__.parent, "introspect"),
    "get_class_variables": (__spec__.parent, "introspect"),
    "get_function_annotations": (__spec__.parent, "introspect"),
    "get_function_parameters": (__spec__.parent, "introspect"),
    "get_function_signature": (__spec__.parent, "introspect"),
    "get_git_branch": (__spec__.parent, "filesystem"),
    "get_git_revision": (__spec__.parent, "filesystem"),
    "get_optimal_workers": (__spec__.parent, "procs"),
    "get_possible_env_vars": (__spec__.parent, "environment"),
    "get_project_path": (__spec__.parent, "filesystem"),
    "get_source_code": (__spec__.parent, "introspect"),
    "get_tooling_dirs": (__spec__.parent, "filesystem"),
    "get_user_config_dir": (__spec__.parent, "filesystem"),
    "getdoc": (__spec__.parent, "introspect"),
    "getmodule": (__spec__.parent, "introspect"),
    "getmodulename": (__spec__.parent, "introspect"),
    "getsourcefile": (__spec__.parent, "introspect"),
    "has_git": (__spec__.parent, "filesystem"),
    "has_package": (__spec__.parent, "checks"),
    "humanize": (__spec__.parent, "text"),
    "in_codeweaver_clone": (__spec__.parent, "filesystem"),
    "in_ide": (__spec__.parent, "environment"),
    "is_ci": (__spec__.parent, "checks"),
    "is_class": (__spec__.parent, "checks"),
    "is_debug": (__spec__.parent, "checks"),
    "is_git_dir": (__spec__.parent, "filesystem"),
    "is_pydantic_basemodel": (__spec__.parent, "checks"),
    "is_test_environment": (__spec__.parent, "checks"),
    "is_tty": (__spec__.parent, "environment"),
    "is_typeadapter": (__spec__.parent, "checks"),
    "is_wsl": (__spec__.parent, "checks"),
    "is_wsl_vscode": (__spec__.parent, "checks"),
    "isclass": (__spec__.parent, "introspect"),
    "isfunction": (__spec__.parent, "introspect"),
    "ismethod": (__spec__.parent, "introspect"),
    "low_priority": (__spec__.parent, "procs"),
    "normalize_ext": (__spec__.parent, "filesystem"),
    "rpartial": (__spec__.parent, "general"),
    "sanitize_unicode": (__spec__.parent, "text"),
    "set_relative_path": (__spec__.parent, "filesystem"),
    "to_lowly_lowercase": (__spec__.parent, "text"),
    "to_tokens": (__spec__.parent, "text"),
    "truncate_text": (__spec__.parent, "text"),
    "try_git_rev_parse": (__spec__.parent, "filesystem"),
    "uuid7": (__spec__.parent, "generation"),
    "uuid7_as_timestamp": (__spec__.parent, "generation"),
    "validate_regex_pattern": (__spec__.parent, "text"),
    "very_low_priority": (__spec__.parent, "procs"),
    "we_are_in_jetbrains": (__spec__.parent, "environment"),
    "we_are_in_vscode": (__spec__.parent, "environment"),
})

__getattr = create_lazy_getattr(
    dynamic_imports=_dynamic_imports, module_globals=globals(), module_name=__name__
)


__all__ = (
    "COMMON_LLM_TOOLING_PATHS",
    "COMMON_TOOLING_PATHS",
    "DictInputTypesT",
    "DictOutputTypesT",
    "LazyImport",
    "asyncio_or_uvloop",
    "backup_file_path",
    "clean_args",
    "create_lazy_getattr",
    "dict_set_to_tuple",
    "elapsed_time_to_human_readable",
    "ensure_iterable",
    "file_is_binary",
    "format_descriptor",
    "format_docstring",
    "format_signature",
    "format_snippet_name",
    "generate_collection_name",
    "get_blake_hash",
    "get_blake_hash_generic",
    "get_class_attrs",
    "get_class_constructor",
    "get_class_methods",
    "get_class_properties",
    "get_class_variables",
    "get_function_annotations",
    "get_function_parameters",
    "get_function_signature",
    "get_git_branch",
    "get_git_revision",
    "get_optimal_workers",
    "get_possible_env_vars",
    "get_project_path",
    "get_source_code",
    "get_tooling_dirs",
    "get_user_config_dir",
    "getdoc",
    "getmodule",
    "getmodulename",
    "getsourcefile",
    "has_git",
    "has_package",
    "humanize",
    "in_codeweaver_clone",
    "in_ide",
    "is_ci",
    "is_class",
    "is_debug",
    "is_git_dir",
    "is_pydantic_basemodel",
    "is_test_environment",
    "is_tty",
    "is_typeadapter",
    "is_wsl",
    "is_wsl_vscode",
    "isclass",
    "isfunction",
    "ismethod",
    "lazy_import",
    "low_priority",
    "normalize_ext",
    "rpartial",
    "sanitize_unicode",
    "set_relative_path",
    "to_lowly_lowercase",
    "to_tokens",
    "truncate_text",
    "try_git_rev_parse",
    "uuid7",
    "uuid7_as_timestamp",
    "validate_regex_pattern",
    "very_low_priority",
    "we_are_in_jetbrains",
    "we_are_in_vscode",
)


def __dir__() -> list[str]:
    """List available attributes for the module."""
    return list(__all__)
