# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""The providers package provides definitions and capabilities for various service providers used in CodeWeaver at the root level, and contains subpackages for embedding, reranking, and vector store providers."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core.utils.lazy_importer import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.providers.agent import (
        AbstractToolset,
        AgentModel,
        AgentModelSettings,
        AgentProfile,
        AgentProfileSpec,
        AgentProvider,
        CombinedToolset,
        DownloadedItem,
        ExternalToolset,
        FilteredToolset,
        FunctionToolset,
        PrefixedToolset,
        PreparedToolset,
        RenamedToolset,
        ToolsetTool,
        WrapperToolset,
        cached_async_http_client,
        download_item,
        get_agent_model_provider,
        infer_agent_provider_class,
        infer_model,
        load_default_agent_providers,
        override_allow_model_requests,
    )
    from codeweaver.providers.config import (
        DATATYPE_FIELDS,
        DIMENSION_FIELDS,
        AgentProviderSettings,
        AllDefaultProviderSettings,
        AzureEmbeddingProviderSettings,
        BaseEmbeddingConfig,
        BaseProviderSettings,
        BaseProviderSettingsDict,
        BaseRerankingConfig,
        BedrockClientOptions,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingProviderSettings,
        BedrockEmbeddingRequestParams,
        BedrockRerankingConfig,
        BedrockRerankingProviderSettings,
        BedrockTitanV2ConfigDict,
        ClientOptions,
        CohereClientOptions,
        CohereRerankingConfig,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        DataProviderSettings,
        EmbeddingConfigT,
        EmbeddingProviderSettings,
        FastEmbedClientOptions,
        FastEmbedEmbeddingConfig,
        FastEmbedEmbeddingProviderSettings,
        FastEmbedRerankingConfig,
        FastEmbedRerankingProviderSettings,
        FastEmbedSparseEmbeddingConfig,
        FastEmbedSparseEmbeddingProviderSettings,
        GoogleClientOptions,
        GoogleEmbeddingConfig,
        GrpcParams,
        HFInferenceClientOptions,
        HttpxClientParams,
        HuggingFaceEmbeddingConfig,
        MemoryConfig,
        MemoryVectorStoreProviderSettings,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        OpenAIClientOptions,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        ProviderSettings,
        ProviderSettingsDict,
        QdrantClientOptions,
        QdrantVectorStoreProviderSettings,
        RerankingConfigT,
        RerankingProviderSettings,
        SentenceTransformersClientOptions,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SentenceTransformersRerankingConfig,
        SentenceTransformersSparseEmbeddingConfig,
        SerializedEmbeddingOptionsDict,
        SerializedRerankingOptionsDict,
        SparseEmbeddingConfigT,
        SparseEmbeddingProviderSettings,
        VectorStoreProviderSettings,
        VoyageClientOptions,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
        VoyageRerankingConfig,
    )
    from codeweaver.providers.data import (
        DataProviderType,
        get_data_provider,
        load_default_data_providers,
    )
    from codeweaver.providers.dependencies import (
        AgentProviderSettingsDep,
        AllDataProviderConfigsDep,
        AllEmbeddingConfigsDep,
        AllProviderSettingsDep,
        AllRerankingConfigsDep,
        AllSparseEmbeddingConfigsDep,
        AllVectorStoreConfigsDep,
        ConfiguredCapabilitiesDep,
        EmbeddingCapabilityGroupDep,
        EmbeddingCapabilityResolverDep,
        EmbeddingClientDep,
        EmbeddingProviderDep,
        EmbeddingProviderSettingsDep,
        EmbeddingRegistryDep,
        ProviderSettingsDep,
        RerankingCapabilityResolverDep,
        RerankingClientDep,
        RerankingProviderDep,
        RerankingProviderSettingsDep,
        SearchPackageDep,
        SparseCapabilityResolverDep,
        SparseEmbeddingClientDep,
        SparseEmbeddingProviderDep,
        SparseEmbeddingProviderSettingsDep,
        TokenizerDep,
        VectorStoreClientDep,
        VectorStoreProviderDep,
        VectorStoreProviderSettingsDep,
    )
    from codeweaver.providers.embedding import (
        BedrockEmbeddingProvider,
        CohereEmbeddingProvider,
        EmbeddingCapabilityResolver,
        EmbeddingModelCapabilities,
        EmbeddingProvider,
        EmbeddingRegistry,
        FastEmbedEmbeddingProvider,
        FastEmbedSparseProvider,
        GoogleEmbeddingProvider,
        HuggingFaceEmbeddingProvider,
        MistralEmbeddingProvider,
        OpenAIEmbeddingBase,
        SentenceTransformersEmbeddingProvider,
        SentenceTransformersSparseProvider,
        SparseEmbeddingCapabilityResolver,
        SparseEmbeddingModelCapabilities,
        SparseEmbeddingProvider,
        VoyageEmbeddingProvider,
        get_embedding_registry,
    )
    from codeweaver.providers.exceptions import CircuitBreakerOpenError
    from codeweaver.providers.http_pool import HttpClientPool, PoolLimits, PoolTimeouts
    from codeweaver.providers.optimize import (
        AvailableOptimizations,
        OptimizationDecisions,
        decide_fastembed_runtime,
        get_optimizations,
    )
    from codeweaver.providers.reranking import (
        BedrockRerankingProvider,
        CohereRerankingProvider,
        FastEmbedRerankingProvider,
        RerankingCapabilityResolver,
        RerankingModelCapabilities,
        RerankingProvider,
        RerankingResult,
        SentenceTransformersRerankingProvider,
        VoyageRerankingProvider,
    )
    from codeweaver.providers.types import (
        BaseCapabilityResolver,
        BaseEmbeddingCapabilityResolver,
        BaseRerankingCapabilityResolver,
        BaseSparseEmbeddingCapabilityResolver,
        CircuitBreakerState,
        EmbeddingCapabilityGroup,
        EmbeddingCapabilityType,
        RerankingCapabilityType,
        VectorConfig,
        VectorRole,
        VectorSet,
    )
    from codeweaver.providers.vector_stores import (
        CollectionMetadata,
        HybridVectorPayload,
        MemoryVectorStoreProvider,
        QdrantVectorStoreProvider,
        VectorStoreProvider,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AbstractToolset": (__spec__.parent, "agent"),
    "AgentModel": (__spec__.parent, "agent"),
    "AgentModelSettings": (__spec__.parent, "agent"),
    "AgentProfile": (__spec__.parent, "agent"),
    "AgentProfileSpec": (__spec__.parent, "agent"),
    "AgentProvider": (__spec__.parent, "agent"),
    "AgentProviderSettings": (__spec__.parent, "config"),
    "AgentProviderSettingsDep": (__spec__.parent, "dependencies"),
    "AgentProviderSettingsType": (__spec__.parent, "config"),
    "AllDataProviderConfigsDep": (__spec__.parent, "dependencies"),
    "AllDefaultProviderSettings": (__spec__.parent, "config.providers"),
    "AllEmbeddingConfigsDep": (__spec__.parent, "dependencies"),
    "AllProviderSettingsDep": (__spec__.parent, "dependencies"),
    "AllRerankingConfigsDep": (__spec__.parent, "dependencies"),
    "AllSparseEmbeddingConfigsDep": (__spec__.parent, "dependencies"),
    "AllVectorStoreConfigsDep": (__spec__.parent, "dependencies"),
    "AvailableOptimizations": (__spec__.parent, "optimize"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "config"),
    "BaseCapabilityResolver": (__spec__.parent, "types"),
    "BaseEmbeddingCapabilityResolver": (__spec__.parent, "types"),
    "BaseEmbeddingConfig": (__spec__.parent, "embedding"),
    "BaseProviderSettings": (__spec__.parent, "config"),
    "BaseProviderSettingsDict": (__spec__.parent, "config"),
    "BaseRerankingCapabilityResolver": (__spec__.parent, "types"),
    "BaseRerankingConfig": (__spec__.parent, "config"),
    "BaseSparseEmbeddingCapabilityResolver": (__spec__.parent, "types"),
    "BedrockClientOptions": (__spec__.parent, "config"),
    "BedrockCohereConfigDict": (__spec__.parent, "config"),
    "BedrockEmbeddingConfig": (__spec__.parent, "config"),
    "BedrockEmbeddingProvider": (__spec__.parent, "embedding"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "config"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "config"),
    "BedrockRerankingConfig": (__spec__.parent, "config"),
    "BedrockRerankingProvider": (__spec__.parent, "reranking"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "config"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "config"),
    "CircuitBreakerOpenError": (__spec__.parent, "exceptions"),
    "CircuitBreakerState": (__spec__.parent, "types"),
    "ClientOptions": (__spec__.parent, "config"),
    "ConfiguredCapability": (__spec__.parent, "types"),
    "CodeWeaverProviderSettings": (__spec__.parent, "config"),
    "CohereClientOptions": (__spec__.parent, "config"),
    "CohereEmbeddingProvider": (__spec__.parent, "embedding"),
    "CohereRerankingConfig": (__spec__.parent, "config"),
    "CohereRerankingProvider": (__spec__.parent, "reranking"),
    "CollectionConfig": (__spec__.parent, "config"),
    "CollectionMetadata": (__spec__.parent, "vector_stores"),
    "CombinedToolset": (__spec__.parent, "agent"),
    "ConfiguredCapabilitiesDep": (__spec__.parent, "dependencies"),
    "ConnectionConfiguration": (__spec__.parent, "config"),
    "ConnectionRateLimitConfig": (__spec__.parent, "config"),
    "DATATYPE_FIELDS": (__spec__.parent, "config"),
    "DIMENSION_FIELDS": (__spec__.parent, "config"),
    "DataProviderSettings": (__spec__.parent, "config"),
    "DataProviderSettingsType": (__spec__.parent, "config"),
    "DataProviderType": (__spec__.parent, "data"),
    "DownloadedItem": (__spec__.parent, "agent"),
    "EmbeddingCapabilityGroup": (__spec__.parent, "types"),
    "EmbeddingCapabilityGroupDep": (__spec__.parent, "dependencies"),
    "EmbeddingCapabilityResolverDep": (__spec__.parent, "dependencies"),
    "EmbeddingCapabilityType": (__spec__.parent, "types"),
    "EmbeddingClientDep": (__spec__.parent, "dependencies"),
    "EmbeddingConfigT": (__spec__.parent, "config"),
    "EmbeddingErrorInfo": (__spec__.parent, "embedding.providers.base"),
    "EmbeddingModelCapabilities": (__spec__.parent, "embedding"),
    "EmbeddingProvider": (__spec__.parent, "embedding"),
    "EmbeddingProviderDep": (__spec__.parent, "dependencies"),
    "EmbeddingProviderSettings": (__spec__.parent, "config"),
    "EmbeddingProviderSettingsDep": (__spec__.parent, "dependencies"),
    "EmbeddingProviderSettingsType": (__spec__.parent, "config"),
    "EmbeddingRegistry": (__spec__.parent, "embedding"),
    "EmbeddingRegistryDep": (__spec__.parent, "dependencies"),
    "ExternalToolset": (__spec__.parent, "config"),
    "FastEmbedClientOptions": (__spec__.parent, "config"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "config"),
    "FastEmbedEmbeddingProvider": (__spec__.parent, "embedding.providers.fastembed"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedRerankingConfig": (__spec__.parent, "config"),
    "FastEmbedRerankingProvider": (__spec__.parent, "reranking"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "config"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedSparseProvider": (__spec__.parent, "embedding"),
    "FilteredToolset": (__spec__.parent, "agent"),
    "FunctionToolset": (__spec__.parent, "agent"),
    "GeneralEmbeddingClientOptionsType": (__spec__.parent, "config"),
    "GeneralRerankingClientOptionsType": (__spec__.parent, "config"),
    "GoogleClientOptions": (__spec__.parent, "config"),
    "GoogleEmbeddingConfig": (__spec__.parent, "config"),
    "GoogleEmbeddingProvider": (__spec__.parent, "embedding"),
    "GrpcParams": (__spec__.parent, "config"),
    "HFInferenceClientOptions": (__spec__.parent, "config"),
    "HttpClientPool": (__spec__.parent, "http_pool"),
    "HttpxClientParams": (__spec__.parent, "config"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "config"),
    "HuggingFaceEmbeddingProvider": (__spec__.parent, "embedding"),
    "HybridVectorPayload": (__spec__.parent, "vector_stores"),
    "MemoryConfig": (__spec__.parent, "config"),
    "MemoryVectorStoreProvider": (__spec__.parent, "vector_stores"),
    "MemoryVectorStoreProviderSettings": (__spec__.parent, "config"),
    "MistralEmbeddingConfig": (__spec__.parent, "config"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "config"),
    "MistralEmbeddingProvider": (__spec__.parent, "embedding"),
    "ModelString": (__spec__.parent, "config"),
    "OpenAIClientOptions": (__spec__.parent, "config"),
    "OpenAIEmbeddingBase": (__spec__.parent, "embedding"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "config"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "config"),
    "OptimizationDecisions": (__spec__.parent, "optimize"),
    "PoolLimits": (__spec__.parent, "http_pool"),
    "PoolTimeouts": (__spec__.parent, "http_pool"),
    "PrefixedToolset": (__spec__.parent, "agent"),
    "PreparedToolset": (__spec__.parent, "agent"),
    "ProviderSettings": (__spec__.parent, "config"),
    "ProviderSettingsDep": (__spec__.parent, "dependencies"),
    "ProviderSettingsDict": (__spec__.parent, "config"),
    "ProviderSettingsView": (__spec__.parent, "config"),
    "QdrantClientOptions": (__spec__.parent, "config"),
    "QdrantVectorStoreProvider": (__spec__.parent, "vector_stores"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "config"),
    "RenamedToolset": (__spec__.parent, "agent"),
    "RerankingCapabilityResolver": (__spec__.parent, "reranking"),
    "RerankingCapabilityResolverDep": (__spec__.parent, "dependencies"),
    "RerankingCapabilityType": (__spec__.parent, "types"),
    "RerankingClientDep": (__spec__.parent, "dependencies"),
    "RerankingConfigT": (__spec__.parent, "config"),
    "RerankingModelCapabilities": (__spec__.parent, "reranking"),
    "RerankingProvider": (__spec__.parent, "reranking"),
    "RerankingProviderDep": (__spec__.parent, "dependencies"),
    "RerankingProviderSettings": (__spec__.parent, "config"),
    "RerankingProviderSettingsDep": (__spec__.parent, "dependencies"),
    "RerankingProviderSettingsType": (__spec__.parent, "config"),
    "RerankingResult": (__spec__.parent, "reranking"),
    "SearchPackageDep": (__spec__.parent, "dependencies"),
    "SentenceTransformersClientOptions": (__spec__.parent, "config"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "config"),
    "SentenceTransformersEmbeddingProvider": (__spec__.parent, "embedding"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "embedding"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "config"),
    "SentenceTransformersRerankingProvider": (__spec__.parent, "reranking"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "config"),
    "SentenceTransformersSparseProvider": (__spec__.parent, "embedding"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "config"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "reranking"),
    "SparseCapabilityResolverDep": (__spec__.parent, "dependencies"),
    "SparseEmbeddingCapabilityResolver": (__spec__.parent, "embedding"),
    "SparseEmbeddingClientDep": (__spec__.parent, "dependencies"),
    "SparseEmbeddingConfigT": (__spec__.parent, "config"),
    "SparseEmbeddingModelCapabilities": (__spec__.parent, "embedding"),
    "SparseEmbeddingProvider": (__spec__.parent, "embedding"),
    "SparseEmbeddingProviderDep": (__spec__.parent, "dependencies"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "config"),
    "SparseEmbeddingProviderSettingsDep": (__spec__.parent, "dependencies"),
    "TokenizerDep": (__spec__.parent, "dependencies"),
    "ToolsetTool": (__spec__.parent, "agent"),
    "VectorStoreClientDep": (__spec__.parent, "dependencies"),
    "VectorStoreProvider": (__spec__.parent, "vector_stores.base"),
    "VectorStoreProviderDep": (__spec__.parent, "dependencies"),
    "VectorStoreProviderSettings": (__spec__.parent, "config"),
    "VectorStoreProviderSettingsDep": (__spec__.parent, "dependencies"),
    "VectorStoreProviderSettingsType": (__spec__.parent, "config"),
    "VectorConfig": (__spec__.parent, "types"),
    "VectorRole": (__spec__.parent, "types"),
    "VectorSet": (__spec__.parent, "types"),
    "VoyageClientOptions": (__spec__.parent, "config"),
    "VoyageEmbeddingConfig": (__spec__.parent, "config"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "config"),
    "VoyageEmbeddingProvider": (__spec__.parent, "embedding"),
    "VoyageRerankingConfig": (__spec__.parent, "config"),
    "VoyageRerankingProvider": (__spec__.parent, "reranking"),
    "WrapperToolset": (__spec__.parent, "agent"),
    "cached_async_http_client": (__spec__.parent, "agent"),
    "decide_fastembed_runtime": (__spec__.parent, "optimize"),
    "download_item": (__spec__.parent, "agent"),
    "get_agent_model_provider": (__spec__.parent, "agent"),
    "get_data_provider": (__spec__.parent, "data"),
    "get_embedding_registry": (__spec__.parent, "embedding"),
    "get_optimizations": (__spec__.parent, "optimize"),
    "get_profile": (__spec__.parent, "config"),
    "infer_agent_provider_class": (__spec__.parent, "agent"),
    "infer_model": (__spec__.parent, "agent"),
    "load_default_agent_providers": (__spec__.parent, "agent"),
    "load_default_data_providers": (__spec__.parent, "data"),
    "override_allow_model_requests": (__spec__.parent, "agent"),
})


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "DATATYPE_FIELDS",
    "DIMENSION_FIELDS",
    "AbstractToolset",
    "AgentModel",
    "AgentModelSettings",
    "AgentProfile",
    "AgentProfileSpec",
    "AgentProvider",
    "AgentProviderSettings",
    "AgentProviderSettingsDep",
    "AgentProviderSettingsType",
    "AllDataProviderConfigsDep",
    "AllDefaultProviderSettings",
    "AllEmbeddingConfigsDep",
    "AllProviderSettingsDep",
    "AllRerankingConfigsDep",
    "AllSparseEmbeddingConfigsDep",
    "AllVectorStoreConfigsDep",
    "AvailableOptimizations",
    "AzureEmbeddingProviderSettings",
    "AzureProviderMixin",
    "BaseCapabilityResolver",
    "BaseEmbeddingCapabilityResolver",
    "BaseEmbeddingConfig",
    "BaseProviderSettings",
    "BaseProviderSettingsDict",
    "BaseRerankingCapabilityResolver",
    "BaseRerankingConfig",
    "BaseSparseEmbeddingCapabilityResolver",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProvider",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingProvider",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "CircuitBreakerOpenError",
    "CircuitBreakerState",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CohereClientOptions",
    "CohereEmbeddingProvider",
    "CohereProviderSettings",
    "CohereRerankingConfig",
    "CohereRerankingProvider",
    "CollectionConfig",
    "CollectionMetadata",
    "CombinedToolset",
    "ConfiguredCapabilitiesDep",
    "ConfiguredCapability",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "DataProviderSettings",
    "DataProviderSettingsType",
    "DataProviderType",
    "DownloadedItem",
    "EmbeddingBatchInfoEmbeddingConfig",
    "EmbeddingCapabilityGroup",
    "EmbeddingCapabilityGroupDep",
    "EmbeddingCapabilityResolver",
    "EmbeddingCapabilityResolverDep",
    "EmbeddingCapabilityType",
    "EmbeddingClientDep",
    "EmbeddingConfigT",
    "EmbeddingErrorInfo",
    "EmbeddingModelCapabilities",
    "EmbeddingProvider",
    "EmbeddingProviderDep",
    "EmbeddingProviderSettings",
    "EmbeddingProviderSettingsDep",
    "EmbeddingProviderSettingsType",
    "EmbeddingRegistry",
    "EmbeddingRegistryDep",
    "ExternalToolset",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProvider",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingProvider",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "FastEmbedSparseProvider",
    "FilteredToolset",
    "FunctionToolset",
    "GeneralEmbeddingClientOptionsType",
    "GeneralRerankingClientOptionsType",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GoogleEmbeddingProvider",
    "GrpcParams",
    "HFInferenceClientOptions",
    "HttpClientPool",
    "HttpxClientParams",
    "HuggingFaceEmbeddingConfig",
    "HuggingFaceEmbeddingProvider",
    "HybridVectorPayload",
    "MemoryConfig",
    "MemoryConfig",
    "MemoryVectorStoreProvider",
    "MemoryVectorStoreProviderSettings",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "MistralEmbeddingProvider",
    "ModelString",
    "OpenAIClientOptions",
    "OpenAIEmbeddingBase",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "OptimizationDecisions",
    "PoolLimits",
    "PoolTimeouts",
    "PrefixedToolset",
    "PreparedToolset",
    "Provider",  # Re-export from core.types (backwards compatibility)
    "ProviderSettings",
    "ProviderSettingsDep",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "QdrantClientOptions",
    "QdrantVectorStoreProvider",
    "QdrantVectorStoreProviderSettings",
    "RenamedToolset",
    "RerankingCapabilityResolver",
    "RerankingCapabilityResolverDep",
    "RerankingCapabilityType",
    "RerankingClientDep",
    "RerankingConfigT",
    "RerankingModelCapabilities",
    "RerankingProvider",
    "RerankingProviderDep",
    "RerankingProviderSettings",
    "RerankingProviderSettingsDep",
    "RerankingProviderSettingsType",
    "RerankingResult",
    "SearchPackageDep",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEmbeddingProvider",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersRerankingProvider",
    "SentenceTransformersSparseEmbeddingConfig",
    "SentenceTransformersSparseProvider",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SparseCapabilityResolverDep",
    "SparseEmbeddingCapabilityResolver",
    "SparseEmbeddingCapabilityResolver",
    "SparseEmbeddingClientDep",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingModelCapabilities",
    "SparseEmbeddingProvider",
    "SparseEmbeddingProviderDep",
    "SparseEmbeddingProviderSettings",
    "SparseEmbeddingProviderSettingsDep",
    "TokenizerDep",
    "ToolsetTool",
    "VectorConfig",
    "VectorRole",
    "VectorSet",
    "VectorStoreClientDep",
    "VectorStoreProvider",
    "VectorStoreProviderDep",
    "VectorStoreProviderSettings",
    "VectorStoreProviderSettings",
    "VectorStoreProviderSettingsDep",
    "VectorStoreProviderSettingsType",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageEmbeddingProvider",
    "VoyageRerankingConfig",
    "VoyageRerankingProvider",
    "WrapperToolset",
    "cached_async_http_client",
    "decide_fastembed_runtime",
    "download_item",
    "get_agent_model_provider",
    "get_data_provider",
    "get_embedding_registry",
    "get_optimizations",
    "get_profile",
    "infer_agent_provider_class",
    "infer_model",
    "load_default_agent_providers",
    "load_default_data_providers",
    "override_allow_model_requests",
)


def __dir__() -> list[str]:
    """Override dir() to include all dynamically imported names."""
    return list(__all__)
