# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""The providers package provides definitions and capabilities for various service providers used in CodeWeaver at the root level, and contains subpackages for embedding, reranking, and vector store providers."""

from __future__ import annotations

from importlib import import_module
from types import MappingProxyType
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from codeweaver.providers.agent import (
        AbstractToolset,
        AgentModel,
        AgentModelSettings,
        AgentProfile,
        AgentProfileSpec,
        AgentProvider,
        CombinedToolset,
        DownloadedItem,
        ExternalToolset,
        FilteredToolset,
        FunctionToolset,
        PrefixedToolset,
        PreparedToolset,
        RenamedToolset,
        ToolsetTool,
        WrapperToolset,
        cached_async_http_client,
        download_item,
        get_agent_model_provider,
        infer_agent_provider_class,
        infer_model,
        load_default_agent_providers,
        override_allow_model_requests,
    )
    from codeweaver.providers.config import (
        DATATYPE_FIELDS,
        DIMENSION_FIELDS,
        AgentProviderSettings,
        AgentProviderSettingsType,
        AllDefaultProviderSettings,
        AzureEmbeddingProviderSettings,
        BaseEmbeddingConfig,
        BaseProviderSettings,
        BaseProviderSettingsDict,
        BaseRerankingConfig,
        BedrockClientOptions,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingProviderSettings,
        BedrockEmbeddingRequestParams,
        BedrockRerankingConfig,
        BedrockRerankingProviderSettings,
        BedrockTitanV2ConfigDict,
        ClientOptions,
        CohereClientOptions,
        CohereRerankingConfig,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        DataProviderSettings,
        DataProviderSettingsType,
        EmbeddingConfigT,
        EmbeddingProviderSettings,
        EmbeddingProviderSettingsType,
        FastEmbedClientOptions,
        FastEmbedEmbeddingConfig,
        FastEmbedEmbeddingProviderSettings,
        FastEmbedRerankingConfig,
        FastEmbedRerankingProviderSettings,
        FastEmbedSparseEmbeddingConfig,
        FastEmbedSparseEmbeddingProviderSettings,
        GeneralEmbeddingClientOptionsType,
        GeneralRerankingClientOptionsType,
        GoogleClientOptions,
        GoogleEmbeddingConfig,
        GrpcParams,
        HFInferenceClientOptions,
        HttpxClientParams,
        HuggingFaceEmbeddingConfig,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        ModelString,
        OpenAIClientOptions,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        ProviderSettings,
        ProviderSettingsDict,
        ProviderSettingsView,
        QdrantClientOptions,
        QdrantVectorStoreProviderSettings,
        RerankingConfigT,
        RerankingProviderSettings,
        RerankingProviderSettingsType,
        SentenceTransformersClientOptions,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SentenceTransformersRerankingConfig,
        SentenceTransformersSparseEmbeddingConfig,
        SerializedEmbeddingOptionsDict,
        SerializedRerankingOptionsDict,
        SparseEmbeddingConfigT,
        SparseEmbeddingProviderSettings,
        VectorConfig,
        VectorStoreProviderSettings,
        VectorStoreProviderSettingsType,
        VoyageClientOptions,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
        VoyageRerankingConfig,
        get_profile,
    )
    from codeweaver.providers.data import get_data_provider, load_default_data_providers
    from codeweaver.providers.embedding import (
        BedrockEmbeddingProvider,
        CohereEmbeddingProvider,
        EmbeddingCapabilityResolver,
        EmbeddingCapabilityResolverDep,
        EmbeddingModelCapabilities,
        EmbeddingProvider,
        EmbeddingRegistry,
        FastEmbedEmbeddingProvider,
        FastEmbedSparseProvider,
        GoogleEmbeddingProvider,
        HuggingFaceEmbeddingProvider,
        MistralEmbeddingProvider,
        OpenAIEmbeddingBase,
        SentenceTransformersEmbeddingProvider,
        SentenceTransformersSparseProvider,
        SparseEmbeddingModelCapabilities,
        VoyageEmbeddingProvider,
        get_embedding_registry,
    )
    from codeweaver.providers.optimize import (
        AvailableOptimizations,
        OptimizationDecisions,
        decide_fastembed_runtime,
        get_optimizations,
    )
    from codeweaver.providers.reranking import (
        BedrockRerankingProvider,
        CohereRerankingProvider,
        FastEmbedRerankingProvider,
        QueryType,
        RerankingCapabilityResolver,
        RerankingCapabilityResolverDep,
        RerankingModelCapabilities,
        RerankingProvider,
        RerankingResult,
        SentenceTransformersRerankingProvider,
        VoyageRerankingProvider,
    )
    from codeweaver.providers.vector_stores import (
        CollectionMetadata,
        HybridVectorPayload,
        MemoryVectorStoreProvider,
        QdrantVectorStoreProvider,
        VectorStoreProvider,
        resolve_dimensions,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "AgentProviderSettings": (__spec__.parent, "kinds"),
    "AgentProviderSettingsType": (__spec__.parent, "providers"),
    "AllDefaultProviderSettings": (__spec__.parent, "providers"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BaseEmbeddingConfig": (__spec__.parent, "embedding"),
    "BaseProviderSettings": (__spec__.parent, "kinds"),
    "BaseProviderSettingsDict": (__spec__.parent, "kinds"),
    "BaseRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockClientOptions": (__spec__.parent, "clients"),
    "BedrockCohereConfigDict": (__spec__.parent, "embedding"),
    "BedrockEmbeddingConfig": (__spec__.parent, "embedding"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "BedrockRerankingConfig": (__spec__.parent, "reranking"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "kinds"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "embedding"),
    "ClientOptions": (__spec__.parent, "clients"),
    "CodeWeaverProviderSettings": (__spec__.parent, "root_settings"),
    "CohereClientOptions": (__spec__.parent, "clients"),
    "CohereRerankingConfig": (__spec__.parent, "reranking"),
    "CollectionConfig": (__spec__.parent, "kinds"),
    "ConnectionConfiguration": (__spec__.parent, "kinds"),
    "ConnectionRateLimitConfig": (__spec__.parent, "kinds"),
    "DATATYPE_FIELDS": (__spec__.parent, "embedding"),
    "DIMENSION_FIELDS": (__spec__.parent, "embedding"),
    "DataProviderSettings": (__spec__.parent, "kinds"),
    "DataProviderSettingsType": (__spec__.parent, "providers"),
    "EmbeddingConfigT": (__spec__.parent, "embedding"),
    "EmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "EmbeddingProviderSettingsType": (__spec__.parent, "providers"),
    "FastEmbedClientOptions": (__spec__.parent, "clients"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedRerankingConfig": (__spec__.parent, "reranking"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "kinds"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "GeneralEmbeddingClientOptionsType": (__spec__.parent, "clients"),
    "GeneralRerankingClientOptionsType": (__spec__.parent, "clients"),
    "GoogleClientOptions": (__spec__.parent, "clients"),
    "GoogleEmbeddingConfig": (__spec__.parent, "embedding"),
    "GrpcParams": (__spec__.parent, "clients"),
    "HFInferenceClientOptions": (__spec__.parent, "clients"),
    "HttpxClientParams": (__spec__.parent, "clients"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "embedding"),
    "MemoryConfig": (__spec__.parent, "kinds"),
    "MistralEmbeddingConfig": (__spec__.parent, "embedding"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "ModelString": (__spec__.parent, "kinds"),
    "OpenAIClientOptions": (__spec__.parent, "clients"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "embedding"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "embedding"),
    "ProviderSettings": (__spec__.parent, "providers"),
    "ProviderSettingsDict": (__spec__.parent, "providers"),
    "ProviderSettingsView": (__spec__.parent, "providers"),
    "QdrantClientOptions": (__spec__.parent, "clients"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "RerankingConfigT": (__spec__.parent, "reranking"),
    "RerankingProviderSettings": (__spec__.parent, "kinds"),
    "RerankingProviderSettingsType": (__spec__.parent, "providers"),
    "SentenceTransformersClientOptions": (__spec__.parent, "clients"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "embedding"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "embedding"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "reranking"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "embedding"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "reranking"),
    "SparseEmbeddingConfigT": (__spec__.parent, "embedding"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "kinds"),
    "VectorConfig": (__spec__.parent, "kinds"),
    "VectorStoreProviderSettings": (__spec__.parent, "kinds"),
    "VectorStoreProviderSettingsType": (__spec__.parent, "providers"),
    "VoyageClientOptions": (__spec__.parent, "clients"),
    "VoyageEmbeddingConfig": (__spec__.parent, "embedding"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "embedding"),
    "VoyageRerankingConfig": (__spec__.parent, "reranking"),
    "get_profile": (__spec__.parent, "profiles"),
    "AbstractToolset": (__spec__.parent, "agent"),
    "AgentModel": (__spec__.parent, "agent"),
    "AgentModelSettings": (__spec__.parent, "agent"),
    "AgentProfile": (__spec__.parent, "agent"),
    "AgentProfileSpec": (__spec__.parent, "agent"),
    "AgentProvider": (__spec__.parent, "agent"),
    "AvailableOptimizations": (__spec__.parent, "optimize"),
    "BedrockEmbeddingProvider": (__spec__.parent, "embedding"),
    "BedrockRerankingProvider": (__spec__.parent, "reranking"),
    "CohereEmbeddingProvider": (__spec__.parent, "embedding"),
    "CohereRerankingProvider": (__spec__.parent, "reranking"),
    "CollectionMetadata": (__spec__.parent, "vector_stores"),
    "CombinedToolset": (__spec__.parent, "agent"),
    "DownloadedItem": (__spec__.parent, "agent"),
    "EmbeddingCapabilityResolver": (__spec__.parent, "embedding"),
    "EmbeddingCapabilityResolverDep": (__spec__.parent, "embedding"),
    "EmbeddingModelCapabilities": (__spec__.parent, "embedding"),
    "EmbeddingProvider": (__spec__.parent, "embedding"),
    "EmbeddingRegistry": (__spec__.parent, "embedding"),
    "ExternalToolset": (__spec__.parent, "agent"),
    "FastEmbedEmbeddingProvider": (__spec__.parent, "embedding"),
    "FastEmbedRerankingProvider": (__spec__.parent, "reranking"),
    "FastEmbedSparseProvider": (__spec__.parent, "embedding"),
    "FilteredToolset": (__spec__.parent, "agent"),
    "FunctionToolset": (__spec__.parent, "agent"),
    "GoogleEmbeddingProvider": (__spec__.parent, "embedding"),
    "HuggingFaceEmbeddingProvider": (__spec__.parent, "embedding"),
    "HybridVectorPayload": (__spec__.parent, "vector_stores"),
    "MemoryVectorStoreProvider": (__spec__.parent, "vector_stores"),
    "MistralEmbeddingProvider": (__spec__.parent, "embedding"),
    "OpenAIEmbeddingBase": (__spec__.parent, "embedding"),
    "OptimizationDecisions": (__spec__.parent, "optimize"),
    "PrefixedToolset": (__spec__.parent, "agent"),
    "PreparedToolset": (__spec__.parent, "agent"),
    "QdrantVectorStoreProvider": (__spec__.parent, "vector_stores"),
    "QueryType": (__spec__.parent, "reranking"),
    "RenamedToolset": (__spec__.parent, "agent"),
    "RerankingCapabilityResolver": (__spec__.parent, "reranking"),
    "RerankingCapabilityResolverDep": (__spec__.parent, "reranking"),
    "RerankingModelCapabilities": (__spec__.parent, "reranking"),
    "RerankingProvider": (__spec__.parent, "reranking"),
    "RerankingResult": (__spec__.parent, "reranking"),
    "SentenceTransformersEmbeddingProvider": (__spec__.parent, "embedding"),
    "SentenceTransformersRerankingProvider": (__spec__.parent, "reranking"),
    "SentenceTransformersSparseProvider": (__spec__.parent, "embedding"),
    "SparseEmbeddingModelCapabilities": (__spec__.parent, "embedding"),
    "ToolsetTool": (__spec__.parent, "agent"),
    "VectorStoreProvider": (__spec__.parent, "vector_stores.base"),
    "VoyageEmbeddingProvider": (__spec__.parent, "embedding"),
    "VoyageRerankingProvider": (__spec__.parent, "reranking"),
    "WrapperToolset": (__spec__.parent, "agent"),
    "cached_async_http_client": (__spec__.parent, "agent"),
    "decide_fastembed_runtime": (__spec__.parent, "optimize"),
    "download_item": (__spec__.parent, "agent"),
    "get_agent_model_provider": (__spec__.parent, "agent"),
    "get_data_provider": (__spec__.parent, "data"),
    "get_embedding_registry": (__spec__.parent, "embedding"),
    "get_optimizations": (__spec__.parent, "optimize"),
    "infer_agent_provider_class": (__spec__.parent, "agent"),
    "infer_model": (__spec__.parent, "agent"),
    "load_default_agent_providers": (__spec__.parent, "agent"),
    "load_default_data_providers": (__spec__.parent, "data"),
    "override_allow_model_requests": (__spec__.parent, "agent"),
    "resolve_dimensions": (__spec__.parent, "vector_stores"),
})


def __getattr__(name: str) -> object:
    """Dynamically import submodules and classes for the providers package."""
    if name in _dynamic_imports:
        module_name, submodule_name = _dynamic_imports[name]
        module = import_module(f"{module_name}.{submodule_name}")
        result = getattr(module, name)
        globals()[name] = result  # Cache in globals for future access
        return result
    if globals().get(name) is not None:
        return globals()[name]
    raise AttributeError(f"module {__name__} has no attribute {name}")


__all__ = (
    "DATATYPE_FIELDS",
    "DIMENSION_FIELDS",
    "AbstractToolset",
    "AgentModel",
    "AgentModelSettings",
    "AgentProfile",
    "AgentProfileSpec",
    "AgentProvider",
    "AgentProviderSettings",
    "AgentProviderSettingsType",
    "AllDefaultProviderSettings",
    "AvailableOptimizations",
    "AzureEmbeddingProviderSettings",
    "AzureProviderMixin",
    "BaseEmbeddingConfig",
    "BaseProviderSettings",
    "BaseProviderSettingsDict",
    "BaseRerankingConfig",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProvider",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingProvider",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CohereClientOptions",
    "CohereEmbeddingProvider",
    "CohereProviderSettings",
    "CohereRerankingConfig",
    "CohereRerankingProvider",
    "CollectionConfig",
    "CollectionMetadata",
    "CombinedToolset",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "DataProviderSettings",
    "DataProviderSettingsType",
    "DownloadedItem",
    "EmbeddingCapabilityResolver",
    "EmbeddingCapabilityResolverDep",
    "EmbeddingConfigT",
    "EmbeddingModelCapabilities",
    "EmbeddingProvider",
    "EmbeddingProviderSettings",
    "EmbeddingProviderSettingsType",
    "EmbeddingRegistry",
    "ExternalToolset",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProvider",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingProvider",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "FastEmbedSparseProvider",
    "FilteredToolset",
    "FunctionToolset",
    "GeneralEmbeddingClientOptionsType",
    "GeneralRerankingClientOptionsType",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GoogleEmbeddingProvider",
    "GrpcParams",
    "HFInferenceClientOptions",
    "HttpxClientParams",
    "HuggingFaceEmbeddingConfig",
    "HuggingFaceEmbeddingProvider",
    "HybridVectorPayload",
    "MemoryConfig",
    "MemoryVectorStoreProvider",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "MistralEmbeddingProvider",
    "ModelString",
    "OpenAIClientOptions",
    "OpenAIEmbeddingBase",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "OptimizationDecisions",
    "PrefixedToolset",
    "PreparedToolset",
    "ProviderSettings",
    "ProviderSettingsDict",
    "ProviderSettingsView",
    "QdrantClientOptions",
    "QdrantVectorStoreProvider",
    "QdrantVectorStoreProviderSettings",
    "QueryType",
    "RenamedToolset",
    "RerankingCapabilityResolver",
    "RerankingCapabilityResolverDep",
    "RerankingConfigT",
    "RerankingModelCapabilities",
    "RerankingProvider",
    "RerankingProviderSettings",
    "RerankingProviderSettingsType",
    "RerankingResult",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEmbeddingProvider",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersRerankingProvider",
    "SentenceTransformersSparseEmbeddingConfig",
    "SentenceTransformersSparseProvider",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingModelCapabilities",
    "SparseEmbeddingProviderSettings",
    "ToolsetTool",
    "VectorConfig",
    "VectorStoreProvider",
    "VectorStoreProviderSettings",
    "VectorStoreProviderSettingsType",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageEmbeddingProvider",
    "VoyageRerankingConfig",
    "VoyageRerankingProvider",
    "WrapperToolset",
    "cached_async_http_client",
    "decide_fastembed_runtime",
    "download_item",
    "get_agent_model_provider",
    "get_data_provider",
    "get_embedding_registry",
    "get_optimizations",
    "get_profile",
    "infer_agent_provider_class",
    "infer_model",
    "load_default_agent_providers",
    "load_default_data_providers",
    "override_allow_model_requests",
    "resolve_dimensions",
)


def __dir__() -> list[str]:
    return list(__all__)
