# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

from fastembed.text.text_embedding import TextEmbedding

__all__ = ["TextEmbedding"]
