# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

import datetime

from typing import Any

UTC = ...

class TimedCache:
    NOT_FOUND = ...
    def __init__(self, expiration: datetime.timedelta) -> None: ...
    def set(self, key: Any, value: Any) -> None: ...
    def get(self, key: Any) -> Any: ...
    def clear(self) -> None: ...
