# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Setup Mise Environment
description: Complete Python development environment setup with mise and UV caching

inputs:
  python-version:
    description: Python version to install
    required: false
    default: '3.12'
  fetch-depth:
    description: Git fetch depth for checkout
    required: false
    default: '1'
  skip-checkout:
    description: Skip checkout step (if already checked out by calling workflow)
    required: false
    default: 'false'
  github-token:
    description: GitHub token for mise installation (to avoid rate limits)
    required: false
    default: ''
  profile:
    description: Task profile to use for mise setup one of 'minimal', 'reviewer', 'dev'
    required: true
    default: 'minimal'

outputs:
  MISE_PATH:
    description: Path to mise executable
    value: ${{ steps.mise-outputs.outputs.MISE_PATH }}
  MISE_ENV:
    description: Mise environment name
    value: ${{ steps.mise-outputs.outputs.MISE_ENV }}
  PROFILE:
    description: Profile used for setup
    value: ${{ steps.mise-outputs.outputs.PROFILE }}
  PYTHON_VERSION:
    description: Python version installed
    value: ${{ steps.mise-outputs.outputs.PYTHON_VERSION }}
  PYTHON_PATH:
    description: Path to Python executable
    value: ${{ steps.mise-outputs.outputs.PYTHON_PATH }}
  NEWPATH:
    description: Updated PATH including mise and python paths
    value: ${{ steps.mise-outputs.outputs.NEWPATH }}


runs:
  using: composite
  steps:
    - name: Checkout code
      if: inputs.skip-checkout != 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y curl git readline-common lzma bzip2
    - name: Free up disk space
      shell: bash
      run: ./scripts/dev-env/ci-free-disk-space.sh

    - name: Setup Mise for Minimal Profile
      if: inputs.profile == 'minimal'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        UV_PYTHON: ${{ inputs.python-version }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-minimal
    - name: Setup Mise for Reviewer Profile
      if: inputs.profile == 'reviewer'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        UV_PYTHON: ${{ inputs.python-version }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
    - name: Activate Reviewer Profile Environment
      if: inputs.profile == 'reviewer'
      shell: bash
      env:
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
      id: mise-setup-reviewer
      run: |
        uv sync
    - name: Setup Mise for Dev Profile
      if: inputs.profile == 'dev'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        UV_PYTHON: ${{ inputs.python-version }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-dev
    - name: Activate Dev Profile Environment
      if: inputs.profile == 'dev'
      shell: bash
      id: mise-setup-dev-activate
      env:
        MISE_ENV: dev
        MISE_EXPERIMENTAL: 1
        MISE_YES: 1
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        mise ://setup

    - name: Set outputs
      shell: bash
      id: mise-outputs
      run: |
        # Add mise to PATH since env export is disabled
        if [ "${{ inputs.profile }}" = "dev" ]; then
          echo "MISE_ENV=dev" >> "$GITHUB_OUTPUT"
          mise //:cloud-setup 2>&1 || true
        else
          echo "MISE_ENV=" >> "$GITHUB_OUTPUT"
        fi
        # setup PATH
        MISE_PATH="$(which mise)"
        echo "MISE_PATH=$MISE_PATH" >> "$GITHUB_OUTPUT"
        mise_bin_dir="$(dirname "$MISE_PATH")"
        python_path="$(which python)"
        python_bin_dir="$(dirname "$python_path")"
        NEWPATH="$mise_bin_dir:$python_bin_dir:$PATH"
        echo "NEWPATH=${NEWPATH}" >> "$GITHUB_OUTPUT"
        echo "PROFILE=${{ inputs.profile }}" >> "$GITHUB_OUTPUT"
        echo "PYTHON_VERSION=$(python --version | awk '{print $2}')" >> "$GITHUB_OUTPUT"
        echo "PYTHON_PATH=$python_path" >> "$GITHUB_OUTPUT"
