# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Setup Mise Environment
description: Complete Python development environment setup with mise and UV caching

inputs:
  python-version:
    description: Python version to install
    required: false
    default: '3.12'
  fetch-depth:
    description: Git fetch depth for checkout
    required: false
    default: '1'
  skip-checkout:
    description: Skip checkout step (if already checked out by calling workflow)
    required: false
    default: 'false'
  github-token:
    description: GitHub token for mise installation (to avoid rate limits)
    required: false
    default: ''
  profile:
    description: Task profile to use for mise setup one of 'minimal', 'reviewer', 'dev'
    required: true
    default: 'minimal'

outputs:
  # MISE_PATH, MISE_ENV, and PYTHON_PATH are typically in uppercase and may be case sensitive in some environments
  MISE_PATH:
    description: Path to mise executable
    value: ${{ steps.mise-outputs.outputs.MISE_PATH }}
  MISE_ENV:
    description: Mise environment name
    value: ${{ steps.mise-outputs.outputs.MISE_ENV }}
  profile:
    description: Profile used for setup
    value: ${{ steps.mise-outputs.outputs.profile }}
  python_version:
    description: Python version installed
    value: ${{ steps.mise-outputs.outputs.python_version }}
  PYTHON_PATH:
    description: Path to Python executable
    value: ${{ steps.mise-outputs.outputs.PYTHON_PATH }}
  MISE_PYTHON_VERSION:
    description: Python version used by mise
    value: ${{ steps.mise-outputs.outputs.MISE_PYTHON_VERSION }}
  MISE_PYTHON_PRECOMPILED_FLAVOR:
    description: Precompiled flavor used by mise (if any)
    value: ${{ steps.mise-outputs.outputs.MISE_PYTHON_PRECOMPILED_FLAVOR }}

runs:
  using: composite
  steps:
    - name: Checkout code
      if: inputs.skip-checkout != 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y curl git readline-common lzma bzip2 libbz2-dev
    - name: Free up disk space
      shell: bash
      run: ./scripts/dev-env/ci-free-disk-space.sh

    - name: Set up Environment for Free-Threaded Python
      shell: bash
      run: |
        # We need to do this for all python versions so that the environment variable is set
        # Because we can't use inputs.python-version after this step
        python_version="${{ inputs.python-version }}"
        if [[ "$python_version" == *"t" ]]; then
          echo "Setting up environment for free-threaded Python version '${python_version}'..."
          echo "MISE_PYTHON_PRECOMPILED_FLAVOR=freethreaded+pgo-full" >> $GITHUB_ENV
          echo "MISE_PYTHON_COMPILE=0" >> $GITHUB_ENV
          python_version_clean="${python_version:0:-1}"
          echo "MISE_PYTHON_VERSION=${python_version_clean}" >> $GITHUB_ENV
          echo "python_version=${python_version_clean}" >> $GITHUB_ENV
          uv_python_version="cpython-${python_version_clean}+freethreaded"
          echo "UV_PYTHON=${uv_python_version}" >> $GITHUB_ENV
        else
          echo "python_version=$python_version" >> $GITHUB_ENV
          echo "UV_PYTHON=$python_version" >> $GITHUB_ENV
        fi

    - name: Setup Mise for Minimal Profile
      if: inputs.profile == 'minimal'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        UV_PYTHON: ${{ env.UV_PYTHON }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-minimal
    - name: Setup Mise for Reviewer Profile
      if: inputs.profile == 'reviewer'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_PYTHON_COMPILE: 0
        MISE_PYTHON_PRECOMPILED_FLAVOR: ${{ env.MISE_PYTHON_PRECOMPILED_FLAVOR || '' }}
        MISE_PYTHON_VERSION: ${{ env.python_version }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
    - name: Activate Reviewer Profile Environment
      if: inputs.profile == 'reviewer'
      shell: bash
      env:
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
      id: mise-setup-reviewer
      run: |
        uv sync
    - name: Setup Mise for Dev Profile
      if: inputs.profile == 'dev'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_PYTHON_COMPILE: 0
        MISE_PYTHON_PRECOMPILED_FLAVOR: ${{ env.MISE_PYTHON_PRECOMPILED_FLAVOR || '' }}
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-dev
    - name: Activate Dev Profile Environment
      if: inputs.profile == 'dev'
      shell: bash
      id: mise-setup-dev-activate
      env:
        MISE_ENV: dev
        MISE_EXPERIMENTAL: 1
        MISE_YES: 1
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
        MISE_PYTHON_COMPILE: 0
        MISE_PYTHON_PRECOMPILED_FLAVOR: ${{ env.MISE_PYTHON_PRECOMPILED_FLAVOR || '' }}
        MISE_PYTHON_VERSION: ${{ env.python_version }}
      run: |

        mise //:cloud-setup 2>&1

    - name: Set outputs
      shell: bash
      id: mise-outputs
      env:
        MISE_PYTHON_VERSION: ${{ env.python_version }}
        MISE_PYTHON_PRECOMPILED_FLAVOR: ${{ env.MISE_PYTHON_PRECOMPILED_FLAVOR || '' }}
      run: |
        MISE_PATH="$(which mise)"
        echo "MISE_PATH=$MISE_PATH" >> "$GITHUB_OUTPUT"
        mise_bin_dir="$(dirname "$MISE_PATH")"
        python_path="$(which python)"
        python_bin_dir="$(dirname "$python_path")"
        echo "profile=${{ inputs.profile }}" >> "$GITHUB_OUTPUT"
        echo "python_version=$(python --version | awk '{print $2}')" >> "$GITHUB_OUTPUT"
        echo "PYTHON_PATH=$python_path" >> "$GITHUB_OUTPUT"
        echo "MISE_PYTHON_VERSION=${MISE_PYTHON_VERSION}" >> "$GITHUB_OUTPUT"
        echo "MISE_PYTHON_PRECOMPILED_FLAVOR=${MISE_PYTHON_PRECOMPILED_FLAVOR}" >> "$GITHUB_OUTPUT"