# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Setup Mise Environment
description: Complete Python development environment setup with mise and UV caching

inputs:
  python-version:
    description: Python version to install
    required: false
    default: '3.12'
  fetch-depth:
    description: Git fetch depth for checkout
    required: false
    default: '1'
  skip-checkout:
    description: Skip checkout step (if already checked out by calling workflow)
    required: false
    default: 'false'
  github-token:
    description: GitHub token for mise installation (to avoid rate limits)
    required: false
    default: ''
  profile:
    description: Task profile to use for mise setup one of 'minimal', 'reviewer', 'dev'
    required: true
    default: 'minimal'
  mise-debug:
    description: Enable debug output for mise commands
    required: false
    default: 'false'

outputs:
  # MISE_PATH, MISE_ENV, and PYTHON_PATH are typically in uppercase and may be case sensitive in some environments
  MISE_PATH:
    description: Path to mise executable
    value: ${{ steps.mise-outputs.outputs.MISE_PATH }}
  MISE_ENV:
    description: Mise environment name
    value: ${{ steps.mise-outputs.outputs.MISE_ENV }}
  PROFILE:
    description: Profile used for setup
    value: ${{ steps.mise-outputs.outputs.PROFILE }}
  PYTHON_PATH:
    description: Path to Python executable
    value: ${{ steps.mise-outputs.outputs.PYTHON_PATH }}
  MISE_PYTHON_VERSION:
    description: Python version used by mise
    value: ${{ steps.mise-outputs.outputs.MISE_PYTHON_VERSION }}

runs:
  using: composite
  steps:
    - name: Checkout code
      if: inputs.skip-checkout != 'true'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Free up disk space
      shell: bash
      run: ./scripts/dev-env/ci-free-disk-space.sh
    - name: Install system dependencies
      shell: bash
      run: |
        # ensure build-python dependencies are installed
        sudo apt-get update && sudo apt-get install -y curl git build-essential libssl-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev libncursesw5-dev xz-utils tk-dev libxml2-dev \
        libxmlsec1-dev libffi-dev liblzma-dev libzstd-dev

    - name: Set up Environment for Free-Threaded Python
      shell: bash
      env:
        MISE_PYTHON_VERSION: ${{ inputs.python-version }}
        UV_PYTHON: ${{ inputs.python-version }}
        PYTHON_VERSION: ${{ inputs.python-version }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
      run: |
        if [[ "${PYTHON_VERSION}" != *t ]]; then
          echo "Using standard Python version ${PYTHON_VERSION}..."
          echo "MISE_PYTHON_VERSION=${PYTHON_VERSION}" >> "$GITHUB_ENV"
          echo "UV_PYTHON=${PYTHON_VERSION}" >> "$GITHUB_ENV"
          exit 0
        fi
        echo "Setting up environment for free-threaded Python ${PYTHON_VERSION}..."
        python_version="${PYTHON_VERSION}"
        base_version="${python_version%t}"
        echo "Base version: ${base_version}"
        # I couldn't get Mise's handling of free-threaded Python versions to work correctly...
        # So, instead, we'll let mise install the base version, and use uv to get the free-threaded version
        # and then sync uv and mise and tell mise to use that version
        echo "MISE_PYTHON_VERSION=${base_version}" >> "$GITHUB_ENV"
        echo "UV_PYTHON=${base_version}+freethreaded" >> "$GITHUB_ENV"

    - name: Setup Mise for Minimal Profile
      if: inputs.profile == 'minimal'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
        MISE_PYTHON_COMPILE: 0
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-minimal
    - name: Setup Mise for Reviewer Profile
      if: inputs.profile == 'reviewer'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
        MISE_PYTHON_COMPILE: 0
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
    - name: Activate Reviewer Profile Environment
      if: inputs.profile == 'reviewer'
      shell: bash
      env:
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
      id: mise-setup-reviewer
      run: |
        uv sync
    - name: Setup Mise for Dev Profile
      if: inputs.profile == 'dev'
      uses: jdx/mise-action@eb508e65f0eb73d4fc9fc9505569833136217cc9
      env:
        MISE_YES: 1
        MISE_EXPERIMENTAL: 1
        MISE_ENV: dev
        MISE_VERBOSE: ${{ inputs.mise-debug }}
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_PYTHON_COMPILE: 0
      with:
        github_token: ${{ inputs.github-token }}
        experimental: true
        install: true
        cache: true
        cache_key_prefix: ${{ inputs.profile }}
        env: false
      id: mise-setup-dev
    - name: Insert Free-Threaded Python into Dev Profile
      if: inputs.profile == 'dev' && endsWith(inputs.python-version, 't')
      shell: bash
      id: mise-setup-dev-insert
      env:
        MISE_PYTHON_VERSION: ${{ env.MISE_PYTHON_VERSION }}
        UV_PYTHON: ${{ env.UV_PYTHON }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
      run: |
        echo "Inserting free-threaded Python version $UV_PYTHON into dev profile..."
        mise x uv@latest -- uv python install -U "cpython-${UV_PYTHON}" 2>&1
        mise sync python --uv
        new_mise_python_version="${MISE_PYTHON_VERSION}+freethreaded"
        echo "Telling mise to use $new_mise_python_version"
        mise use "python@${new_mise_python_version}" 2>&1
        echo "MISE_PYTHON_VERSION=${new_mise_python_version}" >> "$GITHUB_ENV"
    - name: Activate Dev Profile Environment
      if: inputs.profile == 'dev'
      shell: bash
      id: mise-setup-dev-activate
      env:
        MISE_ENV: dev
        MISE_EXPERIMENTAL: 1
        MISE_YES: 1
        MISE_GITHUB_TOKEN: ${{ inputs.github-token }}
        MISE_PYTHON_VERSION: ${{ env.MISE_PYTHON_VERSION }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
      run: |
        echo "starting cloud setup for $MISE_PYTHON_VERSION" 
        mise //:cloud-setup 2>&1

    - name: Set outputs
      shell: bash
      id: mise-outputs
      env:
        MISE_PYTHON_VERSION: ${{ env.MISE_PYTHON_VERSION }}
        MISE_VERBOSE: ${{ inputs.mise-debug }}
      run: |
        MISE_PATH="$(which mise)"
        echo "MISE_PATH=$MISE_PATH" >> "$GITHUB_OUTPUT"
        mise_bin_dir="$(dirname "$MISE_PATH")"
        python_path="$(which python)"
        python_bin_dir="$(dirname "$python_path")"
        echo "MISE_BIN_DIR=$mise_bin_dir" >> "$GITHUB_OUTPUT"
        echo "PYTHON_BIN_DIR=$python_bin_dir" >> "$GITHUB_OUTPUT"
        echo "PROFILE=${{ inputs.profile }}" >> "$GITHUB_OUTPUT"
        echo "PYTHON_PATH=$python_path" >> "$GITHUB_OUTPUT"
        echo "MISE_PYTHON_VERSION=$MISE_PYTHON_VERSION" >> "$GITHUB_OUTPUT"
