# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

from fastembed.rerank.cross_encoder.text_cross_encoder import TextCrossEncoder

__all__ = ["TextCrossEncoder"]
