"""Infrastructure package for CodeWeaver. Infrastructure includes cross-cutting concerns such as logging, statistics, utilities. The types module defines types used throughout the infrastructure package, but is not cross-cutting itself."""

from codeweaver.common.logging import log_to_client_or_fallback, setup_logger
from codeweaver.common.statistics import (
    FileStatistics,
    Identifier,
    SessionStatistics,
    TimingStatistics,
    TokenCategory,
    TokenCounter,
    add_failed_request,
    add_successful_request,
    get_session_statistics,
    record_timed_http_request,
    timed_http,
)
from codeweaver.common.types import (
    CallHookTimingDict,
    HttpRequestsDict,
    McpComponentRequests,
    McpComponentTimingDict,
    McpOperationRequests,
    McpTimingDict,
    ResourceUri,
    TimingStatisticsDict,
    ToolOrPromptName,
)
from codeweaver.common.utils import (
    MISSING,
    LazyImport,
    Missing,
    ensure_iterable,
    estimate_tokens,
    file_is_binary,
    get_git_branch,
    get_git_revision,
    get_possible_env_vars,
    get_project_root,
    has_package,
    in_codeweaver_clone,
    is_class,
    is_debug,
    is_git_dir,
    is_pydantic_basemodel,
    is_typeadapter,
    lazy_import,
    normalize_ext,
    rpartial,
    sanitize_unicode,
    set_relative_path,
    try_git_rev_parse,
    uuid7,
)


_MARKUP_TAG = "bold dark_orange"

CODEWEAVER_PREFIX = f"[{_MARKUP_TAG}]CodeWeaver[/{_MARKUP_TAG}]"

__all__ = (
    "CODEWEAVER_PREFIX",
    "MISSING",
    "CallHookTimingDict",
    "FileStatistics",
    "HttpRequestsDict",
    "Identifier",
    "LazyImport",
    "McpComponentRequests",
    "McpComponentTimingDict",
    "McpOperationRequests",
    "McpTimingDict",
    "Missing",
    "ResourceUri",
    "SessionStatistics",
    "TimingStatistics",
    "TimingStatisticsDict",
    "TokenCategory",
    "TokenCounter",
    "ToolOrPromptName",
    "add_failed_request",
    "add_successful_request",
    "ensure_iterable",
    "estimate_tokens",
    "file_is_binary",
    "get_git_branch",
    "get_git_revision",
    "get_possible_env_vars",
    "get_project_root",
    "get_session_statistics",
    "has_package",
    "in_codeweaver_clone",
    "is_class",
    "is_debug",
    "is_git_dir",
    "is_pydantic_basemodel",
    "is_typeadapter",
    "lazy_import",
    "log_to_client_or_fallback",
    "normalize_ext",
    "record_timed_http_request",
    "rpartial",
    "sanitize_unicode",
    "set_relative_path",
    "setup_logger",
    "timed_http",
    "try_git_rev_parse",
    "uuid7",
)
