; SPDX-FileCopyrightText: 2026 Knitli Inc.
;
; SPDX-License-Identifier: MIT OR Apache-2.0

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --cov=lazy_imports
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=50
    -v
    -ra

filterwarnings =
    error
    ignore::DeprecationWarning
    ignore::UserWarning
