# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Entrypoint for CodeWeaver's embedding model system.

We wanted to mirror `pydantic-ai`'s handling of LLM models, but we had to make a lot of adjustments to fit the embedding use case.
"""

from __future__ import annotations

from types import MappingProxyType

# === MANAGED EXPORTS ===
# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.
from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.providers.embedding.cache_manager import EmbeddingCacheManager
    from codeweaver.providers.embedding.capabilities.alibaba_nlp import (
        ALIBABA_NLP_GTE_MODERNBERT_BASE_CAPABILITIES,
        ALIBABA_NLP_GTE_MULTILINGUAL_BASE_CAPABILITIES,
        ALL_CAPABILITIES,
        CAP_MAP,
        AlibabaNlpEmbeddingCapabilities,
        AlibabaNlpProvider,
        get_alibaba_nlp_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.amazon import (
        AmazonEmbeddingCapabilities,
        get_amazon_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.baai import (
        BAAI_BGE_BASE_EN_V1_5_CAPABILITIES,
        BAAI_BGE_SMALL_EN_V1_5_CAPABILITIES,
        BGE_LARGE_EN_335M_CAPABILITIES,
        BaaiEmbeddingCapabilities,
        BaaiProvider,
        get_baai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.base import (
        HAS_FASTEMBED,
        HAS_ST,
        EmbeddingModelCapabilities,
        ModelFamily,
        SparseCapabilities,
        SparseEmbeddingModelCapabilities,
        get_sparse_caps,
    )
    from codeweaver.providers.embedding.capabilities.cohere import (
        MODEL_MAP,
        CohereEmbeddingCapabilities,
        get_cohere_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.google import (
        GoogleEmbeddingCapabilities,
        get_google_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.ibm_granite import (
        GRANITE_EMBEDDING_30M_CAPABILITIES,
        GRANITE_EMBEDDING_278M_CAPABILITIES,
        GRANITE_EMBEDDING_ENGLISH_R2_CAPABILITIES,
        GRANITE_EMBEDDING_SMALL_ENGLISH_R2_CAPABILITIES,
        IbmGraniteEmbeddingCapabilities,
        IbmGraniteProvider,
        get_ibm_granite_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.intfloat import (
        INTFLOAT_MULTILINGUAL_E5_LARGE_CAPABILITIES,
        INTFLOAT_MULTILINGUAL_E5_LARGE_INSTRUCT_CAPABILITIES,
        IntfloatEmbeddingCapabilities,
        IntfloatProvider,
        get_intfloat_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.jinaai import (
        JINAAI_JINA_EMBEDDINGS_V2_BASE_CODE_CAPABILITIES,
        JINAAI_JINA_EMBEDDINGS_V2_SMALL_EN_CAPABILITIES,
        JINAAI_JINA_EMBEDDINGS_V3_CAPABILITIES,
        JINAAI_JINA_EMBEDDINGS_V4_CAPABILITIES,
        JinaaiEmbeddingCapabilities,
        JinaaiProvider,
        get_jinaai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.minishlab import (
        MINISHLAB_M2V_BASE_GLOVE_CAPABILITIES,
        MINISHLAB_M2V_BASE_GLOVE_SUBWORD_CAPABILITIES,
        MINISHLAB_M2V_BASE_OUTPUT_CAPABILITIES,
        MINISHLAB_M2V_MULTILINGUAL_OUTPUT_CAPABILITIES,
        MINISHLAB_POTION_BASE_2M_CAPABILITIES,
        MINISHLAB_POTION_BASE_4M_CAPABILITIES,
        MINISHLAB_POTION_BASE_8M_CAPABILITIES,
        MinishlabEmbeddingCapabilities,
        MinishlabProvider,
        get_minishlab_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.mistral import (
        MistralEmbeddingCapabilities,
        get_mistral_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.mixedbread_ai import (
        MXBAI_EMBED_LARGE_CAPABILITIES,
        MixedbreadAiEmbeddingCapabilities,
        MixedbreadAiProvider,
        get_mixedbread_ai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.morph import (
        MORPH_LLM_EMBEDDING_V4_CAPABILITIES,
        get_morph_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.nomic_ai import (
        NOMIC_AI_MODERNBERT_EMBED_BASE_CAPABILITIES,
        NOMIC_AI_NOMIC_EMBED_TEXT_V2_MOE_CAPABILITIES,
        NomicAiEmbeddingCapabilities,
        NomicAiProvider,
        get_nomic_ai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.openai import (
        OpenaiEmbeddingCapabilities,
        get_openai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.qwen import (
        QWEN_QWEN3_EMBEDDING_0_6B_CAPABILITIES,
        QWEN_QWEN3_EMBEDDING_4B_CAPABILITIES,
        QWEN_QWEN3_EMBEDDING_8B_CAPABILITIES,
        QwenEmbeddingCapabilities,
        QwenProvider,
        get_qwen_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.resolver import (
        EmbeddingCapabilityResolver,
        SparseEmbeddingCapabilityResolver,
    )
    from codeweaver.providers.embedding.capabilities.sentence_transformers import (
        SENTENCE_TRANSFORMERS_ALL_MINILM_L6_V2_CAPABILITIES,
        SENTENCE_TRANSFORMERS_ALL_MINILM_L12_V2_CAPABILITIES,
        SENTENCE_TRANSFORMERS_ALL_MPNET_BASE_V2_CAPABILITIES,
        SENTENCE_TRANSFORMERS_GTR_T5_BASE_CAPABILITIES,
        SENTENCE_TRANSFORMERS_MULTI_QA_MINILM_L6_COS_V1_CAPABILITIES,
        SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MINILM_L12_V2_CAPABILITIES,
        SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MPNET_BASE_V2_CAPABILITIES,
        VOYAGE_4_NANO_CAPABILITIES,
        SentenceTransformersEmbeddingCapabilities,
        SentenceTransformersProvider,
        get_sentence_transformers_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.snowflake import (
        SNOWFLAKE_ARCTIC_EMBED2_568M_CAPABILITIES,
        SNOWFLAKE_ARCTIC_EMBED_L_V2_0_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_L_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_LONG_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_V2_0_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_S_CAPABILITIES,
        SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_XS_CAPABILITIES,
        SnowflakeEmbeddingCapabilities,
        SnowflakeProvider,
        get_snowflake_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.thenlper import (
        THENLPER_GTE_BASE_CAPABILITIES,
        THENLPER_GTE_LARGE_CAPABILITIES,
        ThenlperEmbeddingCapabilities,
        ThenlperProvider,
        get_thenlper_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.types import (
        EmbeddingCapabilitiesDict,
        PartialCapabilities,
    )
    from codeweaver.providers.embedding.capabilities.voyage import (
        VOYAGE_4_FAMILY,
        Voyage4ModelFamily,
        VoyageEmbeddingCapabilities,
        get_voyage_embedding_capabilities,
    )
    from codeweaver.providers.embedding.capabilities.whereisai import (
        WHEREISAI_UAE_CODE_LARGE_V1_CAPABILITIES,
        WHEREISAI_UAE_LARGE_V1_CAPABILITIES,
        WhereisaiEmbeddingCapabilities,
        WhereisaiProvider,
        get_whereisai_embedding_capabilities,
    )
    from codeweaver.providers.embedding.fastembed_extensions import (
        DENSE_MODELS,
        RERANKING_MODELS,
        add_models,
        get_cross_encoder,
        get_sparse_embedder,
        get_text_embedder,
    )
    from codeweaver.providers.embedding.providers.base import (
        DEFAULT_MAX_BATCH_TOKENS,
        EmbeddingCustomDeps,
        EmbeddingErrorInfo,
        EmbeddingImplementationDeps,
        EmbeddingProvider,
        SparseEmbeddingProvider,
        default_input_transformer,
        default_output_transformer,
    )
    from codeweaver.providers.embedding.providers.bedrock import (
        BaseBedrockModel,
        BedrockEmbeddingProvider,
        BedrockInvokeEmbeddingRequest,
        BedrockInvokeEmbeddingResponse,
        CohereEmbeddingRequestBody,
        CohereEmbeddingResponse,
        CohereRequestHandler,
        ImageDescription,
        InvokeRequestDict,
        TitanEmbeddingV2RequestBody,
        TitanEmbeddingV2Response,
        is_cohere_request,
        is_cohere_response,
        is_one_of_valid_types,
        is_titan_response,
        shared_serializer,
        shared_validator,
    )
    from codeweaver.providers.embedding.providers.cohere import CohereEmbeddingProvider
    from codeweaver.providers.embedding.providers.fastembed import (
        FastEmbedEmbeddingProvider,
        FastEmbedSparseProvider,
        fastembed_output_transformer,
        fastembed_sparse_output_transformer,
    )
    from codeweaver.providers.embedding.providers.google import (
        GoogleEmbeddingProvider,
        GoogleEmbeddingTasks,
    )
    from codeweaver.providers.embedding.providers.huggingface import (
        HuggingFaceEmbeddingProvider,
        huggingface_hub_input_transformer,
        huggingface_hub_output_transformer,
    )
    from codeweaver.providers.embedding.providers.litellm import (
        LITELLM_OPENAI_PROVIDERS,
        LiteLLMModelSpec,
    )
    from codeweaver.providers.embedding.providers.mistral import MistralEmbeddingProvider
    from codeweaver.providers.embedding.providers.openai_factory import OpenAIEmbeddingBase
    from codeweaver.providers.embedding.providers.sentence_transformers import (
        SentenceTransformersEmbeddingProvider,
        SentenceTransformersSparseProvider,
        process_for_instruction_model,
    )
    from codeweaver.providers.embedding.providers.voyage import (
        VoyageEmbeddingProvider,
        voyage_context_output_transformer,
        voyage_output_transformer,
    )
    from codeweaver.providers.embedding.registry import EmbeddingRegistry, get_embedding_registry

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ALIBABA_NLP_GTE_MODERNBERT_BASE_CAPABILITIES": (__spec__.parent, "capabilities.alibaba_nlp"),
    "ALIBABA_NLP_GTE_MULTILINGUAL_BASE_CAPABILITIES": (__spec__.parent, "capabilities.alibaba_nlp"),
    "ALL_CAPABILITIES": (__spec__.parent, "capabilities.alibaba_nlp"),
    "CAP_MAP": (__spec__.parent, "capabilities.alibaba_nlp"),
    "DEFAULT_MAX_BATCH_TOKENS": (__spec__.parent, "providers.base"),
    "DENSE_MODELS": (__spec__.parent, "fastembed_extensions"),
    "HAS_FASTEMBED": (__spec__.parent, "capabilities.base"),
    "HAS_ST": (__spec__.parent, "capabilities.base"),
    "LITELLM_OPENAI_PROVIDERS": (__spec__.parent, "providers.litellm"),
    "MODEL_MAP": (__spec__.parent, "capabilities.cohere"),
    "MXBAI_EMBED_LARGE_CAPABILITIES": (__spec__.parent, "capabilities.mixedbread_ai"),
    "NOMIC_AI_MODERNBERT_EMBED_BASE_CAPABILITIES": (__spec__.parent, "capabilities.nomic_ai"),
    "RERANKING_MODELS": (__spec__.parent, "fastembed_extensions"),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_L_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_LONG_CAPABILITIES": (
        __spec__.parent,
        "capabilities.snowflake",
    ),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_S_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_XS_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "THENLPER_GTE_BASE_CAPABILITIES": (__spec__.parent, "capabilities.thenlper"),
    "THENLPER_GTE_LARGE_CAPABILITIES": (__spec__.parent, "capabilities.thenlper"),
    "VOYAGE_4_FAMILY": (__spec__.parent, "capabilities.voyage"),
    "VOYAGE_4_NANO_CAPABILITIES": (__spec__.parent, "capabilities.sentence_transformers"),
    "AlibabaNlpEmbeddingCapabilities": (__spec__.parent, "capabilities.alibaba_nlp"),
    "AmazonEmbeddingCapabilities": (__spec__.parent, "capabilities.amazon"),
    "BaaiEmbeddingCapabilities": (__spec__.parent, "capabilities.baai"),
    "BaseBedrockModel": (__spec__.parent, "providers.bedrock"),
    "BedrockEmbeddingProvider": (__spec__.parent, "providers.bedrock"),
    "BedrockInvokeEmbeddingRequest": (__spec__.parent, "providers.bedrock"),
    "BedrockInvokeEmbeddingResponse": (__spec__.parent, "providers.bedrock"),
    "CohereEmbeddingCapabilities": (__spec__.parent, "capabilities.cohere"),
    "CohereEmbeddingProvider": (__spec__.parent, "providers.cohere"),
    "CohereEmbeddingRequestBody": (__spec__.parent, "providers.bedrock"),
    "CohereEmbeddingResponse": (__spec__.parent, "providers.bedrock"),
    "CohereRequestHandler": (__spec__.parent, "providers.bedrock"),
    "EmbeddingCacheManager": (__spec__.parent, "cache_manager"),
    "EmbeddingCapabilitiesDict": (__spec__.parent, "capabilities.types"),
    "EmbeddingCapabilityResolver": (__spec__.parent, "capabilities.resolver"),
    "EmbeddingErrorInfo": (__spec__.parent, "providers.base"),
    "EmbeddingModelCapabilities": (__spec__.parent, "capabilities.base"),
    "EmbeddingProvider": (__spec__.parent, "providers.base"),
    "EmbeddingRegistry": (__spec__.parent, "registry"),
    "FastEmbedEmbeddingProvider": (__spec__.parent, "providers.fastembed"),
    "FastEmbedSparseProvider": (__spec__.parent, "providers.fastembed"),
    "GoogleEmbeddingCapabilities": (__spec__.parent, "capabilities.google"),
    "GoogleEmbeddingProvider": (__spec__.parent, "providers.google"),
    "GoogleEmbeddingTasks": (__spec__.parent, "providers.google"),
    "HuggingFaceEmbeddingProvider": (__spec__.parent, "providers.huggingface"),
    "IbmGraniteEmbeddingCapabilities": (__spec__.parent, "capabilities.ibm_granite"),
    "ImageDescription": (__spec__.parent, "providers.bedrock"),
    "IntfloatEmbeddingCapabilities": (__spec__.parent, "capabilities.intfloat"),
    "InvokeRequestDict": (__spec__.parent, "providers.bedrock"),
    "JinaaiEmbeddingCapabilities": (__spec__.parent, "capabilities.jinaai"),
    "MinishlabEmbeddingCapabilities": (__spec__.parent, "capabilities.minishlab"),
    "MistralEmbeddingCapabilities": (__spec__.parent, "capabilities.mistral"),
    "MistralEmbeddingProvider": (__spec__.parent, "providers.mistral"),
    "MixedbreadAiEmbeddingCapabilities": (__spec__.parent, "capabilities.mixedbread_ai"),
    "ModelFamily": (__spec__.parent, "capabilities.base"),
    "NomicAiEmbeddingCapabilities": (__spec__.parent, "capabilities.nomic_ai"),
    "OpenaiEmbeddingCapabilities": (__spec__.parent, "capabilities.openai"),
    "QwenEmbeddingCapabilities": (__spec__.parent, "capabilities.qwen"),
    "SentenceTransformersEmbeddingCapabilities": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SentenceTransformersEmbeddingProvider": (__spec__.parent, "providers.sentence_transformers"),
    "SentenceTransformersSparseProvider": (__spec__.parent, "providers.sentence_transformers"),
    "SnowflakeEmbeddingCapabilities": (__spec__.parent, "capabilities.snowflake"),
    "SparseCapabilities": (__spec__.parent, "capabilities.base"),
    "SparseEmbeddingCapabilityResolver": (__spec__.parent, "capabilities.resolver"),
    "SparseEmbeddingModelCapabilities": (__spec__.parent, "capabilities.base"),
    "SparseEmbeddingProvider": (__spec__.parent, "providers.base"),
    "ThenlperEmbeddingCapabilities": (__spec__.parent, "capabilities.thenlper"),
    "TitanEmbeddingV2RequestBody": (__spec__.parent, "providers.bedrock"),
    "TitanEmbeddingV2Response": (__spec__.parent, "providers.bedrock"),
    "Voyage4ModelFamily": (__spec__.parent, "capabilities.voyage"),
    "VoyageEmbeddingCapabilities": (__spec__.parent, "capabilities.voyage"),
    "VoyageEmbeddingProvider": (__spec__.parent, "providers.voyage"),
    "WhereisaiEmbeddingCapabilities": (__spec__.parent, "capabilities.whereisai"),
    "add_models": (__spec__.parent, "fastembed_extensions"),
    "BAAI_BGE_BASE_EN_V1_5_CAPABILITIES": (__spec__.parent, "capabilities.baai"),
    "BAAI_BGE_SMALL_EN_V1_5_CAPABILITIES": (__spec__.parent, "capabilities.baai"),
    "BGE_LARGE_EN_335M_CAPABILITIES": (__spec__.parent, "capabilities.baai"),
    "default_input_transformer": (__spec__.parent, "providers.base"),
    "default_output_transformer": (__spec__.parent, "providers.base"),
    "fastembed_output_transformer": (__spec__.parent, "providers.fastembed"),
    "fastembed_sparse_output_transformer": (__spec__.parent, "providers.fastembed"),
    "get_alibaba_nlp_embedding_capabilities": (__spec__.parent, "capabilities.alibaba_nlp"),
    "get_amazon_embedding_capabilities": (__spec__.parent, "capabilities.amazon"),
    "get_baai_embedding_capabilities": (__spec__.parent, "capabilities.baai"),
    "get_cohere_embedding_capabilities": (__spec__.parent, "capabilities.cohere"),
    "get_cross_encoder": (__spec__.parent, "fastembed_extensions"),
    "get_embedding_registry": (__spec__.parent, "registry"),
    "get_google_embedding_capabilities": (__spec__.parent, "capabilities.google"),
    "get_ibm_granite_embedding_capabilities": (__spec__.parent, "capabilities.ibm_granite"),
    "get_intfloat_embedding_capabilities": (__spec__.parent, "capabilities.intfloat"),
    "get_jinaai_embedding_capabilities": (__spec__.parent, "capabilities.jinaai"),
    "get_minishlab_embedding_capabilities": (__spec__.parent, "capabilities.minishlab"),
    "get_mistral_embedding_capabilities": (__spec__.parent, "capabilities.mistral"),
    "get_mixedbread_ai_embedding_capabilities": (__spec__.parent, "capabilities.mixedbread_ai"),
    "get_morph_embedding_capabilities": (__spec__.parent, "capabilities.morph"),
    "get_nomic_ai_embedding_capabilities": (__spec__.parent, "capabilities.nomic_ai"),
    "get_openai_embedding_capabilities": (__spec__.parent, "capabilities.openai"),
    "get_qwen_embedding_capabilities": (__spec__.parent, "capabilities.qwen"),
    "get_sentence_transformers_embedding_capabilities": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "get_snowflake_embedding_capabilities": (__spec__.parent, "capabilities.snowflake"),
    "get_sparse_caps": (__spec__.parent, "capabilities.base"),
    "get_sparse_embedder": (__spec__.parent, "fastembed_extensions"),
    "get_text_embedder": (__spec__.parent, "fastembed_extensions"),
    "get_thenlper_embedding_capabilities": (__spec__.parent, "capabilities.thenlper"),
    "get_voyage_embedding_capabilities": (__spec__.parent, "capabilities.voyage"),
    "get_whereisai_embedding_capabilities": (__spec__.parent, "capabilities.whereisai"),
    "GRANITE_EMBEDDING_278M_CAPABILITIES": (__spec__.parent, "capabilities.ibm_granite"),
    "GRANITE_EMBEDDING_30M_CAPABILITIES": (__spec__.parent, "capabilities.ibm_granite"),
    "GRANITE_EMBEDDING_ENGLISH_R2_CAPABILITIES": (__spec__.parent, "capabilities.ibm_granite"),
    "GRANITE_EMBEDDING_SMALL_ENGLISH_R2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.ibm_granite",
    ),
    "huggingface_hub_input_transformer": (__spec__.parent, "providers.huggingface"),
    "huggingface_hub_output_transformer": (__spec__.parent, "providers.huggingface"),
    "INTFLOAT_MULTILINGUAL_E5_LARGE_CAPABILITIES": (__spec__.parent, "capabilities.intfloat"),
    "INTFLOAT_MULTILINGUAL_E5_LARGE_INSTRUCT_CAPABILITIES": (
        __spec__.parent,
        "capabilities.intfloat",
    ),
    "is_cohere_request": (__spec__.parent, "providers.bedrock"),
    "is_cohere_response": (__spec__.parent, "providers.bedrock"),
    "is_one_of_valid_types": (__spec__.parent, "providers.bedrock"),
    "is_titan_response": (__spec__.parent, "providers.bedrock"),
    "JINAAI_JINA_EMBEDDINGS_V2_BASE_CODE_CAPABILITIES": (__spec__.parent, "capabilities.jinaai"),
    "JINAAI_JINA_EMBEDDINGS_V2_SMALL_EN_CAPABILITIES": (__spec__.parent, "capabilities.jinaai"),
    "JINAAI_JINA_EMBEDDINGS_V3_CAPABILITIES": (__spec__.parent, "capabilities.jinaai"),
    "JINAAI_JINA_EMBEDDINGS_V4_CAPABILITIES": (__spec__.parent, "capabilities.jinaai"),
    "LiteLLMModelSpec": (__spec__.parent, "providers.litellm"),
    "MINISHLAB_M2V_BASE_GLOVE_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_M2V_BASE_GLOVE_SUBWORD_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_M2V_BASE_OUTPUT_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_M2V_MULTILINGUAL_OUTPUT_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_POTION_BASE_2M_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_POTION_BASE_4M_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MINISHLAB_POTION_BASE_8M_CAPABILITIES": (__spec__.parent, "capabilities.minishlab"),
    "MORPH_LLM_EMBEDDING_V4_CAPABILITIES": (__spec__.parent, "capabilities.morph"),
    "NOMIC_AI_NOMIC_EMBED_TEXT_V2_MOE_CAPABILITIES": (__spec__.parent, "capabilities.nomic_ai"),
    "OpenAIEmbeddingBase": (__spec__.parent, "providers.openai_factory"),
    "process_for_instruction_model": (__spec__.parent, "providers.sentence_transformers"),
    "QWEN_QWEN3_EMBEDDING_0_6B_CAPABILITIES": (__spec__.parent, "capabilities.qwen"),
    "QWEN_QWEN3_EMBEDDING_4B_CAPABILITIES": (__spec__.parent, "capabilities.qwen"),
    "QWEN_QWEN3_EMBEDDING_8B_CAPABILITIES": (__spec__.parent, "capabilities.qwen"),
    "SENTENCE_TRANSFORMERS_ALL_MINILM_L12_V2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_ALL_MINILM_L6_V2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_ALL_MPNET_BASE_V2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_GTR_T5_BASE_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_MULTI_QA_MINILM_L6_COS_V1_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MINILM_L12_V2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MPNET_BASE_V2_CAPABILITIES": (
        __spec__.parent,
        "capabilities.sentence_transformers",
    ),
    "shared_serializer": (__spec__.parent, "providers.bedrock"),
    "shared_validator": (__spec__.parent, "providers.bedrock"),
    "SNOWFLAKE_ARCTIC_EMBED2_568M_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "SNOWFLAKE_ARCTIC_EMBED_L_V2_0_CAPABILITIES": (__spec__.parent, "capabilities.snowflake"),
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_V2_0_CAPABILITIES": (
        __spec__.parent,
        "capabilities.snowflake",
    ),
    "voyage_context_output_transformer": (__spec__.parent, "providers.voyage"),
    "voyage_output_transformer": (__spec__.parent, "providers.voyage"),
    "WHEREISAI_UAE_CODE_LARGE_V1_CAPABILITIES": (__spec__.parent, "capabilities.whereisai"),
    "WHEREISAI_UAE_LARGE_V1_CAPABILITIES": (__spec__.parent, "capabilities.whereisai"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "ALIBABA_NLP_GTE_MODERNBERT_BASE_CAPABILITIES",
    "ALIBABA_NLP_GTE_MULTILINGUAL_BASE_CAPABILITIES",
    "ALL_CAPABILITIES",
    "BAAI_BGE_BASE_EN_V1_5_CAPABILITIES",
    "BAAI_BGE_SMALL_EN_V1_5_CAPABILITIES",
    "BGE_LARGE_EN_335M_CAPABILITIES",
    "CAP_MAP",
    "DEFAULT_MAX_BATCH_TOKENS",
    "DENSE_MODELS",
    "GRANITE_EMBEDDING_30M_CAPABILITIES",
    "GRANITE_EMBEDDING_278M_CAPABILITIES",
    "GRANITE_EMBEDDING_ENGLISH_R2_CAPABILITIES",
    "GRANITE_EMBEDDING_SMALL_ENGLISH_R2_CAPABILITIES",
    "HAS_FASTEMBED",
    "HAS_ST",
    "INTFLOAT_MULTILINGUAL_E5_LARGE_CAPABILITIES",
    "INTFLOAT_MULTILINGUAL_E5_LARGE_INSTRUCT_CAPABILITIES",
    "JINAAI_JINA_EMBEDDINGS_V2_BASE_CODE_CAPABILITIES",
    "JINAAI_JINA_EMBEDDINGS_V2_SMALL_EN_CAPABILITIES",
    "JINAAI_JINA_EMBEDDINGS_V3_CAPABILITIES",
    "JINAAI_JINA_EMBEDDINGS_V4_CAPABILITIES",
    "LITELLM_OPENAI_PROVIDERS",
    "MINISHLAB_M2V_BASE_GLOVE_CAPABILITIES",
    "MINISHLAB_M2V_BASE_GLOVE_SUBWORD_CAPABILITIES",
    "MINISHLAB_M2V_BASE_OUTPUT_CAPABILITIES",
    "MINISHLAB_M2V_MULTILINGUAL_OUTPUT_CAPABILITIES",
    "MINISHLAB_POTION_BASE_2M_CAPABILITIES",
    "MINISHLAB_POTION_BASE_4M_CAPABILITIES",
    "MINISHLAB_POTION_BASE_8M_CAPABILITIES",
    "MODEL_MAP",
    "MORPH_LLM_EMBEDDING_V4_CAPABILITIES",
    "MXBAI_EMBED_LARGE_CAPABILITIES",
    "NOMIC_AI_MODERNBERT_EMBED_BASE_CAPABILITIES",
    "NOMIC_AI_NOMIC_EMBED_TEXT_V2_MOE_CAPABILITIES",
    "QWEN_QWEN3_EMBEDDING_0_6B_CAPABILITIES",
    "QWEN_QWEN3_EMBEDDING_4B_CAPABILITIES",
    "QWEN_QWEN3_EMBEDDING_8B_CAPABILITIES",
    "RERANKING_MODELS",
    "SENTENCE_TRANSFORMERS_ALL_MINILM_L6_V2_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_ALL_MINILM_L12_V2_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_ALL_MPNET_BASE_V2_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_GTR_T5_BASE_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_MULTI_QA_MINILM_L6_COS_V1_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MINILM_L12_V2_CAPABILITIES",
    "SENTENCE_TRANSFORMERS_PARAPHRASE_MULTILINGUAL_MPNET_BASE_V2_CAPABILITIES",
    "SNOWFLAKE_ARCTIC_EMBED2_568M_CAPABILITIES",
    "SNOWFLAKE_ARCTIC_EMBED_L_V2_0_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_L_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_LONG_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_M_V2_0_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_S_CAPABILITIES",
    "SNOWFLAKE_SNOWFLAKE_ARCTIC_EMBED_XS_CAPABILITIES",
    "THENLPER_GTE_BASE_CAPABILITIES",
    "THENLPER_GTE_LARGE_CAPABILITIES",
    "VOYAGE_4_FAMILY",
    "VOYAGE_4_NANO_CAPABILITIES",
    "WHEREISAI_UAE_CODE_LARGE_V1_CAPABILITIES",
    "WHEREISAI_UAE_LARGE_V1_CAPABILITIES",
    "AlibabaNlpEmbeddingCapabilities",
    "AlibabaNlpProvider",
    "AmazonEmbeddingCapabilities",
    "BaaiEmbeddingCapabilities",
    "BaaiProvider",
    "BaseBedrockModel",
    "BedrockEmbeddingProvider",
    "BedrockInvokeEmbeddingRequest",
    "BedrockInvokeEmbeddingResponse",
    "CohereEmbeddingCapabilities",
    "CohereEmbeddingProvider",
    "CohereEmbeddingRequestBody",
    "CohereEmbeddingResponse",
    "CohereRequestHandler",
    "EmbeddingCacheManager",
    "EmbeddingCapabilitiesDict",
    "EmbeddingCapabilityResolver",
    "EmbeddingCustomDeps",
    "EmbeddingErrorInfo",
    "EmbeddingImplementationDeps",
    "EmbeddingModelCapabilities",
    "EmbeddingProvider",
    "EmbeddingRegistry",
    "FastEmbedEmbeddingProvider",
    "FastEmbedSparseProvider",
    "GoogleEmbeddingCapabilities",
    "GoogleEmbeddingProvider",
    "GoogleEmbeddingTasks",
    "HuggingFaceEmbeddingProvider",
    "IbmGraniteEmbeddingCapabilities",
    "IbmGraniteProvider",
    "ImageDescription",
    "IntfloatEmbeddingCapabilities",
    "IntfloatProvider",
    "InvokeRequestDict",
    "JinaaiEmbeddingCapabilities",
    "JinaaiProvider",
    "LiteLLMModelSpec",
    "MinishlabEmbeddingCapabilities",
    "MinishlabProvider",
    "MistralEmbeddingCapabilities",
    "MistralEmbeddingProvider",
    "MixedbreadAiEmbeddingCapabilities",
    "MixedbreadAiProvider",
    "ModelFamily",
    "NomicAiEmbeddingCapabilities",
    "NomicAiProvider",
    "OpenAIEmbeddingBase",
    "OpenaiEmbeddingCapabilities",
    "PartialCapabilities",
    "QwenEmbeddingCapabilities",
    "QwenProvider",
    "SentenceTransformersEmbeddingCapabilities",
    "SentenceTransformersEmbeddingProvider",
    "SentenceTransformersProvider",
    "SentenceTransformersSparseProvider",
    "SnowflakeEmbeddingCapabilities",
    "SnowflakeProvider",
    "SparseCapabilities",
    "SparseEmbeddingCapabilityResolver",
    "SparseEmbeddingModelCapabilities",
    "SparseEmbeddingProvider",
    "ThenlperEmbeddingCapabilities",
    "ThenlperProvider",
    "TitanEmbeddingV2RequestBody",
    "TitanEmbeddingV2Response",
    "Voyage4ModelFamily",
    "VoyageEmbeddingCapabilities",
    "VoyageEmbeddingProvider",
    "WhereisaiEmbeddingCapabilities",
    "WhereisaiProvider",
    "add_models",
    "default_input_transformer",
    "default_output_transformer",
    "fastembed_output_transformer",
    "fastembed_sparse_output_transformer",
    "get_alibaba_nlp_embedding_capabilities",
    "get_amazon_embedding_capabilities",
    "get_baai_embedding_capabilities",
    "get_cohere_embedding_capabilities",
    "get_cross_encoder",
    "get_embedding_registry",
    "get_google_embedding_capabilities",
    "get_ibm_granite_embedding_capabilities",
    "get_intfloat_embedding_capabilities",
    "get_jinaai_embedding_capabilities",
    "get_minishlab_embedding_capabilities",
    "get_mistral_embedding_capabilities",
    "get_mixedbread_ai_embedding_capabilities",
    "get_morph_embedding_capabilities",
    "get_nomic_ai_embedding_capabilities",
    "get_openai_embedding_capabilities",
    "get_qwen_embedding_capabilities",
    "get_sentence_transformers_embedding_capabilities",
    "get_snowflake_embedding_capabilities",
    "get_sparse_caps",
    "get_sparse_embedder",
    "get_text_embedder",
    "get_thenlper_embedding_capabilities",
    "get_voyage_embedding_capabilities",
    "get_whereisai_embedding_capabilities",
    "huggingface_hub_input_transformer",
    "huggingface_hub_output_transformer",
    "is_cohere_request",
    "is_cohere_response",
    "is_one_of_valid_types",
    "is_titan_response",
    "process_for_instruction_model",
    "shared_serializer",
    "shared_validator",
    "voyage_context_output_transformer",
    "voyage_output_transformer",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
