# SPDX-FileCopyrightText: (c) 2025 Knitli Inc.
# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
"""Entrypoint for CodeWeaver's embedding model system.

We wanted to mirror `pydantic-ai`'s handling of LLM models, but we had to make a lot of adjustments to fit the embedding use case.
"""

# sourcery skip: avoid-global-variables
from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.providers.config import (
        DATATYPE_FIELDS,
        DIMENSION_FIELDS,
        HAS_ANTHROPIC,
        INCOMPATIBLE_FIELDS,
        AllDefaultProviderSettings,
        AzureEmbeddingProviderSettings,
        AzureProviderMixin,
        BaseAgentProviderSettings,
        BaseEmbeddingConfig,
        BaseEmbeddingProviderSettings,
        BaseProviderCategorySettings,
        BaseProviderCategorySettingsDict,
        BaseRerankingConfig,
        BedrockClientOptions,
        BedrockCohereConfigDict,
        BedrockEmbeddingConfig,
        BedrockEmbeddingProviderSettings,
        BedrockEmbeddingRequestParams,
        BedrockProviderMixin,
        BedrockRerankingConfig,
        BedrockRerankingModelConfig,
        BedrockRerankingOptionsDict,
        BedrockRerankingProviderSettings,
        BedrockTitanV2ConfigDict,
        ClientOptions,
        CodeWeaverProviderSettings,
        CohereClientOptions,
        CohereRequestOptionsDict,
        CohereRerankingConfig,
        CohereRerankingOptionsDict,
        CollectionConfig,
        ConnectionConfiguration,
        ConnectionRateLimitConfig,
        DeterminedDefaults,
        EmbeddingConfigT,
        EmbeddingProviderSettings,
        FastEmbedClientOptions,
        FastEmbedEmbeddingConfig,
        FastEmbedEmbeddingProviderSettings,
        FastEmbedProviderMixin,
        FastEmbedRerankingConfig,
        FastEmbedRerankingOptionsDict,
        FastEmbedRerankingProviderSettings,
        FastEmbedSparseEmbeddingConfig,
        FastEmbedSparseEmbeddingProviderSettings,
        GoogleClientOptions,
        GoogleEmbeddingConfig,
        GoogleEmbeddingRequestParams,
        GrpcParams,
        HttpxClientParams,
        HuggingFaceClientOptions,
        HuggingFaceEmbeddingConfig,
        MemoryConfig,
        MistralClientOptions,
        MistralEmbeddingConfig,
        MistralEmbeddingOptionsDict,
        OpenAIClientOptions,
        OpenAIEmbeddingConfig,
        OpenAIEmbeddingRequestParams,
        ProviderConfigProfile,
        ProviderNameMap,
        ProviderProfile,
        ProviderSettings,
        ProviderSettingsDict,
        QdrantClientOptions,
        QdrantVectorStoreProviderSettings,
        RerankingConfigT,
        RerankingProviderSettings,
        SentenceTransformersClientOptions,
        SentenceTransformersEmbeddingConfig,
        SentenceTransformersEncodeDict,
        SentenceTransformersRerankingConfig,
        SentenceTransformersRerankingOptionsDict,
        SentenceTransformersSparseEmbeddingConfig,
        SerializedEmbeddingOptionsDict,
        SerializedRerankingOptionsDict,
        SparseEmbeddingConfigT,
        SparseEmbeddingProviderSettings,
        VectorStoreProviderSettings,
        VoyageClientOptions,
        VoyageEmbeddingConfig,
        VoyageEmbeddingOptionsDict,
        VoyageRerankingConfig,
        VoyageRerankingOptionsDict,
        merge_agent_model_settings,
    )
    from codeweaver.providers.embedding.capabilities.base import (
        EmbeddingModelCapabilities,
        SparseEmbeddingModelCapabilities,
    )
    from codeweaver.providers.embedding.capabilities.resolver import (
        EmbeddingCapabilityResolver,
        SparseEmbeddingCapabilityResolver,
    )
    from codeweaver.providers.embedding.fastembed_extensions import (
        get_sparse_embedder,
        get_text_embedder,
    )
    from codeweaver.providers.embedding.providers import (
        BedrockEmbeddingProvider,
        CohereEmbeddingProvider,
        FastEmbedEmbeddingProvider,
        FastEmbedSparseProvider,
        GoogleEmbeddingProvider,
        HuggingFaceEmbeddingProvider,
        MistralEmbeddingProvider,
        OpenAIEmbeddingBase,
        SentenceTransformersEmbeddingProvider,
        SentenceTransformersSparseProvider,
        VoyageEmbeddingProvider,
    )
    from codeweaver.providers.embedding.providers.base import (
        EmbeddingProvider,
        SparseEmbeddingProvider,
    )
    from codeweaver.providers.embedding.registry import EmbeddingRegistry, get_embedding_registry

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BedrockEmbeddingProvider": (__spec__.parent, "providers.bedrock"),
    "CohereEmbeddingProvider": (__spec__.parent, "providers.cohere"),
    "EmbeddingCapabilityResolver": (__spec__.parent, "capabilities.resolver"),
    "SparseEmbeddingCapabilityResolver": (__spec__.parent, "capabilities.resolver"),
    "EmbeddingModelCapabilities": (__spec__.parent, "capabilities.base"),
    "EmbeddingProvider": (__spec__.parent, "providers.base"),
    "EmbeddingRegistry": (__spec__.parent, "registry"),
    "FastEmbedEmbeddingProvider": (__spec__.parent, "providers.fastembed"),
    "FastEmbedSparseProvider": (__spec__.parent, "providers.fastembed"),
    "GoogleEmbeddingProvider": (__spec__.parent, "providers.google"),
    "HuggingFaceEmbeddingProvider": (__spec__.parent, "providers.huggingface"),
    "MistralEmbeddingProvider": (__spec__.parent, "providers.mistral"),
    "OpenAIEmbeddingBase": (__spec__.parent, "providers.openai_factory"),
    "SentenceTransformersEmbeddingProvider": (__spec__.parent, "providers.sentence_transformers"),
    "SentenceTransformersSparseProvider": (__spec__.parent, "providers.sentence_transformers"),
    "SparseEmbeddingModelCapabilities": (__spec__.parent, "capabilities.base"),
    "SparseEmbeddingProvider": (__spec__.parent, "providers.base"),
    "VoyageEmbeddingProvider": (__spec__.parent, "providers.voyage"),
    "get_embedding_registry": (__spec__.parent, "registry"),
    "get_sparse_embedder": (__spec__.parent, "fastembed_extensions"),
    "get_text_embedder": (__spec__.parent, "fastembed_extensions"),
    "DATATYPE_FIELDS": (__spec__.parent, "config"),
    "DIMENSION_FIELDS": (__spec__.parent, "config"),
    "HAS_ANTHROPIC": (__spec__.parent, "config"),
    "HAS_ST": (__spec__.parent, "config"),
    "INCOMPATIBLE_FIELDS": (__spec__.parent, "config"),
    "BaseAgentProviderSettings": (__spec__.parent, "config"),
    "AllDefaultProviderSettings": (__spec__.parent, "config"),
    "AzureEmbeddingProviderSettings": (__spec__.parent, "config"),
    "AzureProviderMixin": (__spec__.parent, "config"),
    "BaseEmbeddingConfig": (__spec__.parent, "config"),
    "BaseEmbeddingProviderSettings": (__spec__.parent, "config"),
    "BaseProviderCategorySettings": (__spec__.parent, "config"),
    "BaseProviderCategorySettingsDict": (__spec__.parent, "config"),
    "BaseRerankingConfig": (__spec__.parent, "config"),
    "BedrockClientOptions": (__spec__.parent, "config"),
    "BedrockCohereConfigDict": (__spec__.parent, "config"),
    "BedrockEmbeddingConfig": (__spec__.parent, "config"),
    "BedrockEmbeddingProviderSettings": (__spec__.parent, "config"),
    "BedrockEmbeddingRequestParams": (__spec__.parent, "config"),
    "BedrockProviderMixin": (__spec__.parent, "config"),
    "BedrockRerankingConfig": (__spec__.parent, "config"),
    "BedrockRerankingModelConfig": (__spec__.parent, "config"),
    "BedrockRerankingOptionsDict": (__spec__.parent, "config"),
    "BedrockRerankingProviderSettings": (__spec__.parent, "config"),
    "BedrockTitanV2ConfigDict": (__spec__.parent, "config"),
    "ClientOptions": (__spec__.parent, "config"),
    "CodeWeaverProviderSettings": (__spec__.parent, "config"),
    "CohereClientOptions": (__spec__.parent, "config"),
    "CohereRequestOptionsDict": (__spec__.parent, "config"),
    "CohereRerankingConfig": (__spec__.parent, "config"),
    "CohereRerankingOptionsDict": (__spec__.parent, "config"),
    "CollectionConfig": (__spec__.parent, "config"),
    "ConnectionConfiguration": (__spec__.parent, "config"),
    "ConnectionRateLimitConfig": (__spec__.parent, "config"),
    "DeterminedDefaults": (__spec__.parent, "config"),
    "EmbeddingConfigT": (__spec__.parent, "config"),
    "EmbeddingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedClientOptions": (__spec__.parent, "config"),
    "FastEmbedEmbeddingConfig": (__spec__.parent, "config"),
    "FastEmbedEmbeddingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedProviderMixin": (__spec__.parent, "config"),
    "FastEmbedRerankingConfig": (__spec__.parent, "config"),
    "FastEmbedRerankingOptionsDict": (__spec__.parent, "config"),
    "FastEmbedRerankingProviderSettings": (__spec__.parent, "config"),
    "FastEmbedSparseEmbeddingConfig": (__spec__.parent, "config"),
    "FastEmbedSparseEmbeddingProviderSettings": (__spec__.parent, "config"),
    "GoogleClientOptions": (__spec__.parent, "config"),
    "GoogleEmbeddingConfig": (__spec__.parent, "config"),
    "GoogleEmbeddingRequestParams": (__spec__.parent, "config"),
    "GrpcParams": (__spec__.parent, "config"),
    "HuggingFaceClientOptions": (__spec__.parent, "config"),
    "HttpxClientParams": (__spec__.parent, "config"),
    "HuggingFaceEmbeddingConfig": (__spec__.parent, "config"),
    "MemoryConfig": (__spec__.parent, "config"),
    "MistralClientOptions": (__spec__.parent, "config"),
    "MistralEmbeddingConfig": (__spec__.parent, "config"),
    "MistralEmbeddingOptionsDict": (__spec__.parent, "config"),
    "OpenAIClientOptions": (__spec__.parent, "config"),
    "OpenAIEmbeddingConfig": (__spec__.parent, "config"),
    "OpenAIEmbeddingRequestParams": (__spec__.parent, "config"),
    "ProviderConfigProfile": (__spec__.parent, "config"),
    "ProviderProfile": (__spec__.parent, "config"),
    "ProviderNameMap": (__spec__.parent, "config"),
    "ProviderSettings": (__spec__.parent, "config"),
    "ProviderSettingsDict": (__spec__.parent, "config"),
    "QdrantClientOptions": (__spec__.parent, "config"),
    "QdrantVectorStoreProviderSettings": (__spec__.parent, "config"),
    "RerankingConfigT": (__spec__.parent, "config"),
    "RerankingProviderSettings": (__spec__.parent, "config"),
    "SentenceTransformersClientOptions": (__spec__.parent, "config"),
    "SentenceTransformersEmbeddingConfig": (__spec__.parent, "config"),
    "SentenceTransformersEncodeDict": (__spec__.parent, "config"),
    "SentenceTransformersRerankingConfig": (__spec__.parent, "config"),
    "SentenceTransformersRerankingOptionsDict": (__spec__.parent, "config"),
    "SentenceTransformersSparseEmbeddingConfig": (__spec__.parent, "config"),
    "SerializedEmbeddingOptionsDict": (__spec__.parent, "config"),
    "SerializedRerankingOptionsDict": (__spec__.parent, "config"),
    "SparseEmbeddingConfigT": (__spec__.parent, "config"),
    "SparseEmbeddingProviderSettings": (__spec__.parent, "config"),
    "VectorStoreProviderSettings": (__spec__.parent, "config"),
    "VoyageClientOptions": (__spec__.parent, "config"),
    "VoyageEmbeddingConfig": (__spec__.parent, "config"),
    "VoyageEmbeddingOptionsDict": (__spec__.parent, "config"),
    "VoyageRerankingConfig": (__spec__.parent, "config"),
    "VoyageRerankingOptionsDict": (__spec__.parent, "config"),
    "discriminate_azure_embedding_client_options": (__spec__.parent, "config"),
    "merge_agent_model_settings": (__spec__.parent, "config"),
})


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "DATATYPE_FIELDS",
    "DIMENSION_FIELDS",
    "HAS_ANTHROPIC",
    "HAS_ST",
    "INCOMPATIBLE_FIELDS",
    "AllDefaultProviderSettings",
    "AzureEmbeddingProviderSettings",
    "AzureProviderMixin",
    "BaseAgentProviderSettings",
    "BaseEmbeddingConfig",
    "BaseEmbeddingProviderSettings",
    "BaseProviderCategorySettings",
    "BaseProviderCategorySettings",
    "BaseProviderCategorySettingsDict",
    "BaseProviderCategorySettingsDict",
    "BaseRerankingConfig",
    "BedrockClientOptions",
    "BedrockCohereConfigDict",
    "BedrockEmbeddingConfig",
    "BedrockEmbeddingProvider",
    "BedrockEmbeddingProviderSettings",
    "BedrockEmbeddingRequestParams",
    "BedrockProviderMixin",
    "BedrockRerankingConfig",
    "BedrockRerankingModelConfig",
    "BedrockRerankingOptionsDict",
    "BedrockRerankingProviderSettings",
    "BedrockTitanV2ConfigDict",
    "ClientOptions",
    "CodeWeaverProviderSettings",
    "CohereClientOptions",
    "CohereEmbeddingProvider",
    "CohereRequestOptionsDict",
    "CohereRerankingConfig",
    "CohereRerankingOptionsDict",
    "CollectionConfig",
    "ConnectionConfiguration",
    "ConnectionConfiguration",
    "ConnectionRateLimitConfig",
    "ConnectionRateLimitConfig",
    "DataProviderSettings",
    "DeterminedDefaults",
    "EmbeddingCapabilityResolver",
    "EmbeddingConfigT",
    "EmbeddingModelCapabilities",
    "EmbeddingProvider",
    "EmbeddingProviderSettings",
    "EmbeddingRegistry",
    "FastEmbedClientOptions",
    "FastEmbedEmbeddingConfig",
    "FastEmbedEmbeddingProvider",
    "FastEmbedEmbeddingProviderSettings",
    "FastEmbedProviderMixin",
    "FastEmbedRerankingConfig",
    "FastEmbedRerankingOptionsDict",
    "FastEmbedRerankingProviderSettings",
    "FastEmbedSparseEmbeddingConfig",
    "FastEmbedSparseEmbeddingProviderSettings",
    "FastEmbedSparseProvider",
    "GoogleClientOptions",
    "GoogleEmbeddingConfig",
    "GoogleEmbeddingProvider",
    "GoogleEmbeddingRequestParams",
    "GrpcParams",
    "HttpxClientParams",
    "HuggingFaceClientOptions",
    "HuggingFaceEmbeddingConfig",
    "HuggingFaceEmbeddingProvider",
    "InvalidEmbeddingModelError",
    "MemoryConfig",
    "MistralClientOptions",
    "MistralEmbeddingConfig",
    "MistralEmbeddingOptionsDict",
    "MistralEmbeddingProvider",
    "OpenAIClientOptions",
    "OpenAIEmbeddingBase",
    "OpenAIEmbeddingConfig",
    "OpenAIEmbeddingRequestParams",
    "ProviderConfigProfile",
    "ProviderConfigProfile",
    "ProviderNameMap",
    "ProviderProfile",
    "ProviderSettings",
    "ProviderSettingsDict",
    "QdrantClientOptions",
    "QdrantVectorStoreProviderSettings",
    "RerankingConfigT",
    "RerankingProviderSettings",
    "SentenceTransformersClientOptions",
    "SentenceTransformersEmbeddingConfig",
    "SentenceTransformersEmbeddingProvider",
    "SentenceTransformersEncodeDict",
    "SentenceTransformersRerankingConfig",
    "SentenceTransformersRerankingOptionsDict",
    "SentenceTransformersSparseEmbeddingConfig",
    "SentenceTransformersSparseProvider",
    "SerializedEmbeddingOptionsDict",
    "SerializedRerankingOptionsDict",
    "SparseEmbeddingCapabilityResolver",
    "SparseEmbeddingConfigT",
    "SparseEmbeddingModelCapabilities",
    "SparseEmbeddingProvider",
    "SparseEmbeddingProviderSettings",
    "VectorStoreProviderSettings",
    "VoyageClientOptions",
    "VoyageEmbeddingConfig",
    "VoyageEmbeddingOptionsDict",
    "VoyageEmbeddingProvider",
    "VoyageRerankingConfig",
    "VoyageRerankingOptionsDict",
    "discriminate_azure_embedding_client_options",
    "get_embedding_registry",
    "get_profile",
    "get_profile",
    "get_profile",
    "get_sparse_embedder",
    "get_text_embedder",
    "merge_agent_model_settings",
)


def __dir__() -> list[str]:
    """List available attributes for the embedding package."""
    return list(__all__)
