# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase

class AttentionQuant(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None:
        ...
    
    def should_quantize(self):
        ...
    
    def quantize(self): # -> None:
        """
        parameter node: Attention node.
        parameter new_nodes_list: List of new nodes created before processing this node.
        return: a list of nodes in topological order that represents quantized Attention node.
        """
        ...
    


