# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class QLinearWhere(QuantOperatorBase):
    def should_quantize(self): # -> Literal[True]:
        ...
    
    def quantize(self): # -> None:
        ...
    


class QDQWhere(QDQOperatorBase):
    def quantize(self): # -> None:
        ...
    


