# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""The engine package contains core functionality for indexing, chunking, and searching code and documentation data, but also for other data providers 🚋."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.engine.chunker import (
        ASTDepthExceededError,
        BinaryFileError,
        Boundary,
        ChunkerSelector,
        ChunkGovernor,
        ChunkingError,
        ChunkingTimeoutError,
        ChunkLimitExceededError,
        Delimiter,
        DelimiterChunker,
        DelimiterDict,
        DelimiterKind,
        DelimiterMatch,
        DelimiterPattern,
        GracefulChunker,
        LanguageFamily,
        LineStrategy,
        OversizedChunkError,
        ParseError,
        ResourceGovernor,
        SemanticChunker,
        SourceIdRegistry,
        chunk_files_parallel,
        chunk_files_parallel_dict,
        clear_store,
        detect_language_family,
        expand_pattern,
        get_store,
        source_id_for,
    )
    from codeweaver.engine.chunking_service import ChunkingService
    from codeweaver.engine.config import (
        ChunkerSettings,
        ChunkerSettingsDict,
        ConcurrencySettings,
        ConcurrencySettingsDict,
        CustomDelimiter,
        CustomLanguage,
        DefaultChunkerSettings,
        DefaultIndexerSettings,
        IndexerSettings,
        IndexerSettingsDict,
        PerformanceSettings,
        PerformanceSettingsDict,
        RignoreSettings,
    )
    from codeweaver.engine.indexer import (
        CheckpointManager,
        CheckpointSettingsFingerprint,
        FileManifestEntry,
        FileManifestManager,
        Indexer,
        IndexFileManifest,
        IndexingCheckpoint,
        IndexingPhase,
        IndexingProgressTracker,
        IndexingStats,
    )
    from codeweaver.engine.watcher import (
        CodeFilter,
        ConfigFilter,
        DefaultFilter,
        DocsFilter,
        ExtensionFilter,
        FileWatcher,
        IgnoreFilter,
    )

parent = __spec__.parent or "codeweaver.engine"

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ASTDepthExceededError": (f"{parent}.chunker", "exceptions"),
    "AnyVariants": (parent, "search"),
    "ArbitraryFilter": (parent, "search"),
    "BinaryFileError": (parent, "chunker"),
    "Boundary": (parent, "chunker"),
    "CheckpointManager": (parent, "indexer"),
    "CheckpointSettingsFingerprint": (parent, "indexer"),
    "ChunkGovernor": (parent, "chunker"),
    "ChunkLimitExceededError": (parent, "chunker"),
    "ChunkerSelector": (parent, "chunker"),
    "ChunkerSettings": (parent, "config"),
    "ChunkerSettingsDict": (parent, "config"),
    "ChunkingError": (parent, "chunker"),
    "ChunkingService": (parent, "chunking_service"),
    "ChunkingTimeoutError": (parent, "chunker"),
    "CodeFilter": (parent, "watcher"),
    "ConcurrencySettings": (parent, "indexer"),
    "ConcurrencySettingsDict": (parent, "indexer"),
    "Condition": (parent, "search"),
    "ConfigFilter": (parent, "watcher"),
    "CustomDelimiter": (parent, "chunker"),
    "CustomLanguage": (parent, "chunker"),
    "DatetimeRange": (parent, "search"),
    "DefaultChunkerSettings": (parent, "chunker"),
    "DefaultFilter": (parent, "watcher"),
    "DefaultIndexerSettings": (parent, "indexer"),
    "Delimiter": (parent, "chunker"),
    "DelimiterChunker": (parent, "chunker"),
    "DelimiterDict": (parent, "chunker"),
    "DelimiterKind": (parent, "chunker"),
    "DelimiterMatch": (parent, "chunker"),
    "DelimiterPattern": (parent, "chunker"),
    "DocsFilter": (parent, "watcher"),
    "Entry": (parent, "search"),
    "ExtendedPointId": (parent, "search"),
    "ExtensionFilter": (parent, "watcher"),
    "FieldCondition": (parent, "search"),
    "FileManifestEntry": (parent, "indexer"),
    "FileManifestManager": (parent, "indexer"),
    "FileWatcher": (parent, "watcher"),
    "Filter": (parent, "search"),
    "FilterableField": (parent, "search"),
    "GeoBoundingBox": (parent, "search"),
    "GeoLineString": (parent, "search"),
    "GeoPoint": (parent, "search"),
    "GeoPolygon": (parent, "search"),
    "GeoRadius": (parent, "search"),
    "GracefulChunker": (parent, "chunker"),
    "HasIdCondition": (parent, "search"),
    "HasVectorCondition": (parent, "search"),
    "IgnoreFilter": (parent, "watcher"),
    "IndexFileManifest": (parent, "indexer"),
    "Indexer": (parent, "indexer"),
    "IndexerSettings": (parent, "config"),
    "IndexerSettingsDict": (parent, "config"),
    "IndexingCheckpoint": (parent, "indexer"),
    "IndexingPhase": (parent, "indexer"),
    "IndexingProgressTracker": (parent, "indexer"),
    "IndexingStats": (parent, "indexer"),
    "IsEmptyCondition": (parent, "search"),
    "IsNullCondition": (parent, "search"),
    "LanguageFamily": (parent, "chunker"),
    "LineStrategy": (parent, "chunker"),
    "Match": (parent, "search"),
    "MatchAny": (parent, "search"),
    "MatchExcept": (parent, "search"),
    "MatchPhrase": (parent, "search"),
    "MatchText": (parent, "search"),
    "MatchValue": (parent, "search"),
    "MinShould": (parent, "search"),
    "Nested": (parent, "search"),
    "NestedCondition": (parent, "search"),
    "OversizedChunkError": (parent, "chunker"),
    "ParseError": (parent, "chunker"),
    "PayloadField": (parent, "search"),
    "PayloadMetadata": (parent, "search"),
    "PayloadSchemaType": (parent, "search"),
    "PerformanceSettings": (parent, "indexer"),
    "PerformanceSettingsDict": (parent, "indexer"),
    "Range": (parent, "search"),
    "ResourceGovernor": (parent, "chunker"),
    "RignoreSettings": (__spec__.parent, "config"),
    "SemanticChunker": (parent, "chunker"),
    "SourceIdRegistry": (parent, "chunker"),
    "ValueVariants": (parent, "search"),
    "ValuesCount": (parent, "search"),
    "chunk_files_parallel": (parent, "chunker"),
    "chunk_files_parallel_dict": (parent, "chunker"),
    "clear_store": (parent, "chunker"),
    "detect_language_family": (parent, "chunker"),
    "expand_pattern": (parent, "chunker"),
    "get_store": (parent, "chunker"),
    "make_partial_function": (parent, "search"),
    "source_id_for": (parent, "chunker"),
    "wrap_filters": (parent, "search"),
})


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "ASTDepthExceededError",
    "AnyVariants",
    "ArbitraryFilter",
    "BinaryFileError",
    "Boundary",
    "CheckpointManager",
    "CheckpointSettingsFingerprint",
    "ChunkGovernor",
    "ChunkLimitExceededError",
    "ChunkerSelector",
    "ChunkerSettings",
    "ChunkerSettingsDict",
    "ChunkingError",
    "ChunkingService",
    "ChunkingTimeoutError",
    "CodeFilter",
    "ConcurrencySettings",
    "ConcurrencySettingsDict",
    "Condition",
    "ConfigFilter",
    "CustomDelimiter",
    "CustomLanguage",
    "DatetimeRange",
    "DefaultChunkerSettings",
    "DefaultFilter",
    "DefaultIndexerSettings",
    "Delimiter",
    "DelimiterChunker",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterMatch",
    "DelimiterPattern",
    "DocsFilter",
    "Entry",
    "ExtendedPointId",
    "ExtensionFilter",
    "FieldCondition",
    "FileManifestEntry",
    "FileManifestManager",
    "FileWatcher",
    "Filter",
    "FilterableField",
    "GeoBoundingBox",
    "GeoLineString",
    "GeoPoint",
    "GeoPolygon",
    "GeoRadius",
    "GracefulChunker",
    "HasIdCondition",
    "HasVectorCondition",
    "IgnoreFilter",
    "IndexFileManifest",
    "Indexer",
    "IndexerSettings",
    "IndexerSettingsDict",
    "IndexingCheckpoint",
    "IndexingPhase",
    "IndexingProgressTracker",
    "IndexingStats",
    "IsEmptyCondition",
    "IsNullCondition",
    "LanguageFamily",
    "LineStrategy",
    "Match",
    "MatchAny",
    "MatchExcept",
    "MatchPhrase",
    "MatchText",
    "MatchValue",
    "MinShould",
    "Nested",
    "NestedCondition",
    "OversizedChunkError",
    "ParseError",
    "PayloadField",
    "PayloadMetadata",
    "PayloadSchemaType",
    "PerformanceSettings",
    "PerformanceSettingsDict",
    "Range",
    "ResourceGovernor",
    "RignoreSettings",
    "SemanticChunker",
    "SourceIdRegistry",
    "ValueVariants",
    "ValuesCount",
    "chunk_files_parallel",
    "chunk_files_parallel_dict",
    "clear_store",
    "detect_language_family",
    "expand_pattern",
    "get_store",
    "make_partial_function",
    "source_id_for",
    "wrap_filters",
)


def __dir__() -> list[str]:
    """List available attributes for the engine package."""
    return list(__all__)
