# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""The engine package contains core functionality for indexing, chunking, and searching code and documentation data, but also for other data providers 🚋."""

from __future__ import annotations

from types import MappingProxyType
from typing import TYPE_CHECKING

from codeweaver.core import create_lazy_getattr


if TYPE_CHECKING:
    from codeweaver.engine.chunker import (
        ASTDepthExceededError,
        BinaryFileError,
        Boundary,
        ChunkerSelector,
        ChunkGovernor,
        ChunkingError,
        ChunkingTimeoutError,
        ChunkLimitExceededError,
        Delimiter,
        DelimiterChunker,
        DelimiterDict,
        DelimiterKind,
        DelimiterMatch,
        DelimiterPattern,
        GracefulChunker,
        LanguageFamily,
        LineStrategy,
        OversizedChunkError,
        ParseError,
        ResourceGovernor,
        SemanticChunker,
        SourceIdRegistry,
        chunk_files_parallel,
        chunk_files_parallel_dict,
        detect_language_family,
        expand_pattern,
    )
    from codeweaver.engine.config import (
        ChunkerSettings,
        ChunkerSettingsDict,
        ConcurrencySettings,
        ConcurrencySettingsDict,
        CustomDelimiter,
        CustomLanguage,
        DefaultChunkerSettings,
        DefaultFailoverSettings,
        DefaultIndexerSettings,
        FailoverSettings,
        IndexerSettings,
        IndexerSettingsDict,
        PerformanceSettings,
        PerformanceSettingsDict,
        RignoreSettings,
    )
    from codeweaver.engine.dependencies import (
        BackupChunkingServiceDep,
        BackupIndexingServiceDep,
        CheckpointManagerDep,
        ChunkerSettingsDep,
        ChunkingServiceDep,
        ExtensionFilterDep,
        FailoverServiceDep,
        FailoverSettingsDep,
        IgnoreFilterDep,
        IndexerSettingsDep,
        IndexingStatsDep,
        ManifestManagerDep,
        ProgressTrackerDep,
        SourceIdRegistryDep,
    )
    from codeweaver.engine.managers import (
        CheckpointManager,
        CheckpointSettingsFingerprint,
        FileManifestEntry,
        FileManifestManager,
        IndexFileManifest,
        IndexingCheckpoint,
        IndexingPhase,
        IndexingProgressTracker,
        IndexingStats,
    )
    from codeweaver.engine.services import (
        ChunkingService,
        FailoverService,
        FileWatchingService,
        IndexingService,
    )
    from codeweaver.engine.watcher import (
        CodeFilter,
        ConfigFilter,
        DefaultFilter,
        DocsFilter,
        ExtensionFilter,
        IgnoreFilter,
        WatchfilesLogManager,
    )

parent = __spec__.parent or "codeweaver.engine"

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "ASTDepthExceededError": (f"{parent}.chunker", "exceptions"),
    "BackupChunkingServiceDep": (parent, "dependencies"),
    "BackupIndexingServiceDep": (parent, "dependencies"),
    "BinaryFileError": (parent, "chunker"),
    "Boundary": (parent, "chunker"),
    "CheckpointManager": (parent, "managers"),
    "CheckpointManagerDep": (parent, "dependencies"),
    "CheckpointSettingsFingerprint": (parent, "managers"),
    "ChunkGovernor": (parent, "chunker"),
    "ChunkLimitExceededError": (parent, "chunker"),
    "ChunkerSelector": (parent, "chunker"),
    "ChunkerSettings": (parent, "config"),
    "ChunkerSettingsDep": (parent, "dependencies"),
    "ChunkerSettingsDict": (parent, "config"),
    "ChunkingError": (parent, "chunker"),
    "ChunkingService": (parent, "services"),
    "ChunkingServiceDep": (parent, "dependencies"),
    "ChunkingTimeoutError": (parent, "chunker"),
    "CodeFilter": (parent, "watcher"),
    "ConcurrencySettings": (parent, "indexer"),
    "ConcurrencySettingsDict": (parent, "indexer"),
    "ConfigFilter": (parent, "watcher"),
    "CustomDelimiter": (parent, "chunker"),
    "CustomLanguage": (parent, "chunker"),
    "DatetimeRange": (parent, "search"),
    "DefaultChunkerSettings": (parent, "config"),
    "DefaultFailoverSettings": (parent, "config"),
    "DefaultFilter": (parent, "watcher"),
    "DefaultIndexerSettings": (parent, "indexer"),
    "Delimiter": (parent, "chunker"),
    "DelimiterChunker": (parent, "chunker"),
    "DelimiterDict": (parent, "chunker"),
    "DelimiterKind": (parent, "chunker"),
    "DelimiterMatch": (parent, "chunker"),
    "DelimiterPattern": (parent, "chunker"),
    "DocsFilter": (parent, "watcher"),
    "ExtensionFilter": (parent, "watcher"),
    "ExtensionFilterDep": (parent, "dependencies"),
    "FailoverService": (parent, "services"),
    "FailoverServiceDep": (parent, "dependencies"),
    "FailoverSettings": (parent, "config"),
    "FailoverSettingsDep": (parent, "dependencies"),
    "FileManifestEntry": (parent, "managers"),
    "FileManifestManager": (parent, "managers"),
    "FileWatchingService": (parent, "services"),
    "GracefulChunker": (parent, "chunker"),
    "IgnoreFilter": (parent, "watcher"),
    "IgnoreFilterDep": (parent, "dependencies"),
    "IndexFileManifest": (parent, "managers"),
    "IndexerSettings": (parent, "config"),
    "IndexerSettingsDep": (parent, "dependencies"),
    "IndexerSettingsDict": (parent, "config"),
    "IndexingCheckpoint": (parent, "managers"),
    "IndexingPhase": (parent, "managers"),
    "IndexingProgressTracker": (parent, "managers"),
    "IndexingService": (parent, "services"),
    "IndexingStats": (parent, "managers"),
    "IndexingStatsDep": (parent, "dependencies"),
    "LanguageFamily": (parent, "chunker"),
    "LineStrategy": (parent, "chunker"),
    "ManifestManagerDep": (parent, "dependencies"),
    "OversizedChunkError": (parent, "chunker"),
    "ParseError": (parent, "chunker"),
    "PerformanceSettings": (parent, "indexer"),
    "PerformanceSettingsDict": (parent, "indexer"),
    "ProgressTrackerDep": (parent, "dependencies"),
    "Range": (parent, "search"),
    "ResourceGovernor": (parent, "chunker"),
    "RignoreSettings": (parent, "config"),
    "SemanticChunker": (parent, "chunker"),
    "SourceIdRegistry": (parent, "chunker"),
    "SourceIdRegistryDep": (parent, "dependencies"),
    "ValuesCount": (parent, "search"),
    "WatchfilesLogManager": (parent, "watcher"),
    "chunk_files_parallel": (parent, "chunker"),
    "chunk_files_parallel_dict": (parent, "chunker"),
    "detect_language_family": (parent, "chunker"),
    "expand_pattern": (parent, "chunker"),
})


__getattr__ = create_lazy_getattr(_dynamic_imports, globals(), __name__)


__all__ = (
    "ASTDepthExceededError",
    "AnyVariants",
    "ArbitraryFilter",
    "BackupChunkingServiceDep",
    "BackupIndexingServiceDep",
    "BinaryFileError",
    "Boundary",
    "CheckpointManager",
    "CheckpointManagerDep",
    "CheckpointSettingsFingerprint",
    "ChunkGovernor",
    "ChunkLimitExceededError",
    "ChunkerSelector",
    "ChunkerSettings",
    "ChunkerSettingsDep",
    "ChunkerSettingsDict",
    "ChunkingError",
    "ChunkingService",
    "ChunkingServiceDep",
    "ChunkingTimeoutError",
    "CodeFilter",
    "ConcurrencySettings",
    "ConcurrencySettingsDict",
    "Condition",
    "ConfigFilter",
    "CustomDelimiter",
    "CustomLanguage",
    "DatetimeRange",
    "DefaultChunkerSettings",
    "DefaultFailoverSettings",
    "DefaultFilter",
    "DefaultIndexerSettings",
    "Delimiter",
    "DelimiterChunker",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterMatch",
    "DelimiterPattern",
    "DocsFilter",
    "Entry",
    "ExtendedPointId",
    "ExtensionFilter",
    "ExtensionFilterDep",
    "FailoverService",
    "FailoverServiceDep",
    "FailoverSettings",
    "FailoverSettingsDep",
    "FieldCondition",
    "FileManifestEntry",
    "FileManifestManager",
    "FileWatchingService",
    "Filter",
    "FilterableField",
    "GeoBoundingBox",
    "GeoLineString",
    "GeoPoint",
    "GeoPolygon",
    "GeoRadius",
    "GracefulChunker",
    "HasIdCondition",
    "HasVectorCondition",
    "IgnoreFilter",
    "IgnoreFilterDep",
    "IndexFileManifest",
    "IndexerSettings",
    "IndexerSettingsDep",
    "IndexerSettingsDict",
    "IndexingCheckpoint",
    "IndexingPhase",
    "IndexingProgressTracker",
    "IndexingService",
    "IndexingStats",
    "IndexingStatsDep",
    "IsEmptyCondition",
    "IsNullCondition",
    "LanguageFamily",
    "LineStrategy",
    "ManifestManagerDep",
    "Match",
    "MatchAny",
    "MatchExcept",
    "MatchPhrase",
    "MatchText",
    "MatchValue",
    "MinShould",
    "Nested",
    "NestedCondition",
    "OversizedChunkError",
    "ParseError",
    "PayloadField",
    "PayloadMetadata",
    "PayloadSchemaType",
    "PerformanceSettings",
    "PerformanceSettingsDict",
    "ProgressTrackerDep",
    "Range",
    "ResourceGovernor",
    "RignoreSettings",
    "SemanticChunker",
    "SourceIdRegistry",
    "SourceIdRegistryDep",
    "ValueVariants",
    "ValuesCount",
    "WatchfilesLogManager",
    "chunk_files_parallel",
    "chunk_files_parallel_dict",
    "detect_language_family",
    "expand_pattern",
    "make_partial_function",
    "wrap_filters",
)


def __dir__() -> list[str]:
    """List available attributes for the engine package."""
    return list(__all__)
