# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

import platform
from .onnxruntime_pybind11_state import *

"""
Ensure that dependencies are available and then load the extension module.
"""
if platform.system() == "Windows":
    ...
