# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""
This type stub file was generated by pyright.
"""

def find_cudart_versions(build_env=..., build_cuda_version=...): # -> list[int] | None:
    ...

