#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Code generator for __init__.py files from export manifests.

This module implements the Code Generator component that takes ExportManifest
objects and generates properly formatted __init__.py files with:
- Sentinel-based preservation of manual code
- Import statement generation (absolute/relative, TYPE_CHECKING)
- __all__ list generation
- Atomic writes with backup and rollback
- Syntax validation

Implementation follows:
- REQ-COMPAT-001: Generated output equivalent to existing system
- REQ-SAFE-001: Preserve manual edits above sentinel comments
- REQ-SAFE-002: Atomic writes with backup and rollback
"""

from __future__ import annotations

import ast
import contextlib
import hashlib
import shutil
import tempfile

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, NoReturn

from tools.lazy_imports.common.types import ExportManifest, ExportNode, MemberType


if TYPE_CHECKING:
    from collections.abc import Sequence


# Sentinel comment for managed section
SENTINEL = "# === MANAGED EXPORTS ==="
MANAGED_COMMENT = """# This section is automatically generated by the lazy import system.
# Manual edits below this line will be overwritten."""


@dataclass(frozen=True)
class GeneratedCode:
    """Generated code for a module's __init__.py file.

    Attributes:
        content: Complete file content including manual and managed sections
        manual_section: User's manual code preserved from above sentinel
        managed_section: Auto-generated code below sentinel
        export_count: Number of exports in __all__
        hash: SHA-256 hash of content for verification
    """

    content: str
    manual_section: str
    managed_section: str
    export_count: int
    hash: str

    @classmethod
    def create(cls, manual: str, managed: str, export_count: int) -> GeneratedCode:
        """Create GeneratedCode with computed hash.

        Args:
            manual: Manual section content
            managed: Managed section content
            export_count: Number of exports

        Returns:
            GeneratedCode instance
        """
        content = (
            f"{manual}\n\n{SENTINEL}\n{MANAGED_COMMENT}\n\n{managed}"
            if manual
            else f"{SENTINEL}\n{MANAGED_COMMENT}\n\n{managed}"
        )
        content_hash = hashlib.sha256(content.encode()).hexdigest()

        return cls(
            content=content,
            manual_section=manual,
            managed_section=managed,
            export_count=export_count,
            hash=content_hash,
        )


class CodeGenerator:
    """Generates __init__.py files from export manifests.

    The code generator takes export manifests produced by the propagation graph
    and generates properly formatted Python code with:
    - Preserved manual sections above sentinel
    - Organized imports (runtime vs TYPE_CHECKING)
    - Sorted __all__ declarations
    - Atomic file operations with backup

    Error handling:
    - FM-003: Syntax errors → rollback with clear message
    - FM-010: File system errors → preserve existing file, warn user
    - FM-011: Permission errors → clear message with resolution steps
    """

    def __init__(self, output_dir: Path):
        """Initialize code generator.

        Args:
            output_dir: Root directory for output (usually project root)
        """
        self.output_dir = output_dir

    def generate(self, manifest: ExportManifest) -> GeneratedCode:
        """Generate code for a single module.

        Takes an ExportManifest and generates complete __init__.py content
        including imports, __all__ list, and preserved manual section.

        Args:
            manifest: Export manifest to generate code from

        Returns:
            GeneratedCode with complete file content

        Example:
            >>> generator = CodeGenerator(Path("src"))
            >>> manifest = ExportManifest(...)
            >>> code = generator.generate(manifest)
            >>> print(code.content)
        """
        # Get target file path
        target = self._get_target_path(manifest.module_path)

        # Preserve manual section if file exists
        manual_section = ""
        if target.exists():
            manual_section = self._preserve_manual_section(target.read_text())

        # Generate managed section
        managed_section = self._generate_managed_section(manifest)

        return GeneratedCode.create(
            manual=manual_section, managed=managed_section, export_count=len(manifest.all_exports)
        )

    def write_file(self, module_path: str, code: GeneratedCode) -> None:
        """Write generated code to disk (atomic with backup).

        Implements atomic write pattern:
        1. Create backup of existing file
        2. Write to temporary file
        3. Validate syntax
        4. Atomic rename to target
        5. On error: restore backup and raise

        Args:
            module_path: Module path (e.g., "codeweaver.core.types")
            code: Generated code to write

        Raises:
            SyntaxError: If generated code has syntax errors
            OSError: If file operations fail
            PermissionError: If insufficient permissions

        Error Handling:
        - FM-003: Syntax validation before commit
        - FM-010: Preserve existing on file system errors
        - FM-011: Clear permission error messages
        """

        def _raise_syntax_error(errors: list[str]) -> NoReturn:
            raise SyntaxError(
                "❌ Error: Generated code has syntax errors\n\n"
                "Errors:\n" + "\n".join(f"  - {err}" for err in errors) + "\n\n"
                "This is a bug in the code generator.\n"
                "Please report this issue with the manifest that caused it."
            )

        target = self._get_target_path(module_path)

        # Ensure parent directory exists
        target.parent.mkdir(parents=True, exist_ok=True)

        # Backup existing file
        backup_path = None
        if target.exists():
            backup_path = target.with_suffix(".py.backup")
            try:
                shutil.copy2(target, backup_path)
            except OSError as e:
                raise OSError(
                    f"❌ Error: Cannot create backup of {target}\n"
                    f"   Reason: {e}\n\n"
                    f"Suggestions:\n"
                    f"- Check file permissions: chmod u+w {target}\n"
                    f"- Check disk space: df -h\n"
                    f"- Check file is not locked by another process"
                ) from e

        # Write to temporary file
        _temp_fd, temp_filepath = tempfile.mkstemp(
            suffix=".py", prefix="__init__", dir=target.parent, text=True
        )
        temp_path = Path(temp_filepath)

        try:
            # Write content
            with temp_path.open("w", encoding="utf-8") as f:
                f.write(code.content)

            if validation_errors := self.validate_generated(code):
                _raise_syntax_error(validation_errors)

            # Atomic rename
            temp_path.replace(target)

            # Remove backup on success
            if backup_path and backup_path.exists():
                backup_path.unlink()

        except (SyntaxError, OSError) as e:
            # Cleanup temp file
            if temp_path.exists():
                temp_path.unlink()

            # Restore backup
            if backup_path and backup_path.exists():
                with contextlib.suppress(OSError):
                    shutil.copy2(backup_path, target)
                    backup_path.unlink()
            # Re-raise with context
            if isinstance(e, PermissionError):
                raise PermissionError(
                    f"❌ Error: Permission denied writing to {target}\n\n"
                    f"Suggestions:\n"
                    f"- Check file permissions: ls -la {target}\n"
                    f"- Change permissions: chmod u+w {target}\n"
                    f"- Run as appropriate user: sudo -u <user> <command>"
                ) from e
            raise

    def validate_generated(self, code: GeneratedCode) -> list[str]:
        """Validate generated code (syntax, imports, etc.).

        Performs validation checks on generated code:
        - Python syntax validation via ast.parse()
        - Import statement structure
        - __all__ declaration format

        Args:
            code: Generated code to validate

        Returns:
            List of validation error messages (empty if valid)

        Example:
            >>> errors = generator.validate_generated(code)
            >>> if errors:
            ...     print("Validation failed:", errors)
        """
        errors = []

        # Validate Python syntax
        try:
            ast.parse(code.content)
        except SyntaxError as e:
            errors.append(f"Syntax error at line {e.lineno}: {e.msg}")

        # Validate __all__ is present
        if "__all__" not in code.content:
            errors.append("Missing __all__ declaration")

        # Validate imports (basic check - should have either imports or empty)
        lines = code.managed_section.split("\n")
        any(line.strip().startswith(("from ", "import ", "if TYPE_CHECKING:")) for line in lines)

        return errors

    def _preserve_manual_section(self, existing: str) -> str:
        """Extract manual code above sentinel.

        Preserves all user code that appears above the sentinel comment.
        If no sentinel exists, preserves entire file (backward compatibility).

        Args:
            existing: Existing file content

        Returns:
            Manual section content (without trailing newlines)

        Example:
            >>> manual = generator._preserve_manual_section(content)
            >>> print(manual)
            # My custom imports
            from typing import Protocol
        """
        if SENTINEL not in existing:
            # No sentinel - preserve entire file for safety
            # User will need to move their code above sentinel on first run
            return existing.rstrip()

        # Extract everything before sentinel
        return existing.split(SENTINEL)[0].rstrip()

    def _generate_managed_section(self, manifest: ExportManifest) -> str:
        """Generate the managed section below sentinel.

        Creates the auto-generated portion of the __init__.py file with:
        - from __future__ import annotations
        - TYPE_CHECKING imports
        - Runtime imports
        - __all__ declaration

        Args:
            manifest: Export manifest

        Returns:
            Managed section content

        Example:
            >>> section = generator._generate_managed_section(manifest)
            >>> print(section)
            from __future__ import annotations
            ...
        """
        parts = ["from __future__ import annotations", ""]

        # Group exports by whether they need TYPE_CHECKING
        runtime_exports, type_only_exports = self._categorize_exports(manifest.all_exports)

        # TYPE_CHECKING import if needed
        if type_only_exports:
            parts.extend(("from typing import TYPE_CHECKING", ""))
            # Runtime imports
        if runtime_exports and (
            runtime_imports := self._generate_imports(runtime_exports, type_checking=False)
        ):
            parts.extend((runtime_imports, ""))
            # TYPE_CHECKING block
        if type_only_exports:
            parts.append("if TYPE_CHECKING:")
            if type_imports := self._generate_imports(type_only_exports, type_checking=True):
                # Indent the imports
                indented = "\n".join(f"    {line}" for line in type_imports.split("\n"))
                parts.extend((indented, ""))
        # Generate __all__ list
        module_exports = self._generate_all_list(manifest.all_exports)
        parts.append(module_exports)

        return "\n".join(parts)

    def _categorize_exports(
        self, exports: Sequence[ExportNode]
    ) -> tuple[list[ExportNode], list[ExportNode]]:
        """Categorize exports into runtime vs TYPE_CHECKING.

        Type aliases and type variables should go in TYPE_CHECKING block.
        Everything else is runtime.

        Args:
            exports: List of exports to categorize

        Returns:
            Tuple of (runtime_exports, type_only_exports)
        """
        runtime = []
        type_only = []

        for export in exports:
            if export.member_type == MemberType.TYPE_ALIAS:
                type_only.append(export)
            else:
                runtime.append(export)

        return runtime, type_only

    def _generate_imports(self, exports: Sequence[ExportNode], *, type_checking: bool) -> str:
        """Generate import statements for exports.

        Groups exports by source module and generates appropriate import
        statements (absolute or relative based on module structure).

        Args:
            exports: Exports to generate imports for
            type_checking: Whether this is for TYPE_CHECKING block

        Returns:
            Import statements as string

        Example:
            >>> imports = generator._generate_imports(exports, False)
            >>> print(imports)
            from .submodule import SomeClass, some_function
            from .other import AnotherClass
        """
        if not exports:
            return ""

        # Group by source module (defined_in)
        by_module: dict[str, list[str]] = {}
        for export in exports:
            source = export.defined_in
            if source not in by_module:
                by_module[source] = []
            by_module[source].append(export.name)

        # Generate import statements
        import_lines = []
        for source_module in sorted(by_module.keys()):
            names = sorted(by_module[source_module])

            # Determine if we should use relative import
            # For now, use relative imports for submodules
            if "." in source_module:
                # Get the last component as relative import
                submodule = source_module.split(".")[-1]
                import_line = f"from .{submodule} import {', '.join(names)}"
            else:
                # Absolute import
                import_line = f"from {source_module} import {', '.join(names)}"

            import_lines.append(import_line)

        return "\n".join(import_lines)

    def _generate_all_list(self, exports: Sequence[ExportNode]) -> str:
        """Generate __all__ list.

        Creates a sorted __all__ list with one entry per line for readability.

        Args:
            exports: Exports to include in __all__

        Returns:
            __all__ declaration

        Example:
            >>> all_list = generator._generate_all_list(exports)
            >>> print(all_list)
            __all__ = [
                "AnotherClass",
                "SomeClass",
                "some_function",
            ]
        """
        if not exports:
            return "__all__ = []"

        names = sorted({e.name for e in exports})

        if len(names) == 1:
            # Single export - one line
            return f'__all__ = ["{names[0]}"]'

        # Multiple exports - one per line
        lines = ["__all__ = ["]
        lines.extend(f'    "{name}",' for name in names)
        lines.append("]")

        return "\n".join(lines)

    def _get_target_path(self, module_path: str) -> Path:
        """Get target file path for a module.

        Converts module path to file system path for __init__.py.

        Args:
            module_path: Module path (e.g., "codeweaver.core.types")

        Returns:
            Path to __init__.py file

        Example:
            >>> path = generator._get_target_path("codeweaver.core.types")
            >>> print(path)
            /path/to/codeweaver/core/types/__init__.py
        """
        parts = module_path.split(".")
        return self.output_dir / Path(*parts) / "__init__.py"


# Export validation helper


def _check_has_all_declaration(tree: ast.Module) -> bool:
    """Check if AST contains __all__ declaration.

    Args:
        tree: Parsed AST module

    Returns:
        True if __all__ is declared
    """
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    return True
    return False


def _validate_sentinel_structure(content: str) -> list[str]:
    """Validate sentinel comment structure in file content.

    Args:
        content: File content to validate

    Returns:
        List of validation errors (empty if valid)
    """
    errors = []
    if SENTINEL not in content:
        return errors

    # Validate structure
    parts = content.split(SENTINEL)
    if len(parts) != 2:
        errors.append(f"Multiple sentinel comments found ({len(parts) - 1})")

    # Validate managed section has imports and __all__
    managed = parts[1] if len(parts) == 2 else ""
    if "__all__" not in managed:
        errors.append("__all__ should be in managed section (below sentinel)")

    return errors


def validate_init_file(file_path: Path) -> list[str]:
    """Validate an existing __init__.py file.

    Checks that the file:
    - Has valid Python syntax
    - Has __all__ declaration
    - Has sentinel if it has managed exports
    - Imports match __all__

    Args:
        file_path: Path to __init__.py file

    Returns:
        List of validation errors (empty if valid)

    Example:
        >>> errors = validate_init_file(Path("codeweaver/__init__.py"))
        >>> if errors:
        ...     print("Validation failed:", errors)
    """
    if not file_path.exists():
        return [f"File does not exist: {file_path}"]

    try:
        content = file_path.read_text()
    except (OSError, UnicodeDecodeError) as e:
        return [f"Cannot read file: {e}"]

    # Validate syntax
    try:
        tree = ast.parse(content)
    except SyntaxError as e:
        return [f"Syntax error at line {e.lineno}: {e.msg}"]

    errors = []

    # Check for __all__
    if not _check_has_all_declaration(tree):
        errors.append("Missing __all__ declaration")

    # Check for sentinel structure
    errors.extend(_validate_sentinel_structure(content))

    return errors


__all__ = ["SENTINEL", "CodeGenerator", "GeneratedCode", "validate_init_file"]
