# SPDX-FileCopyrightText: 2026 Knitli Inc.
#
# SPDX-License-Identifier: MIT OR Apache-2.0

"""Type aliases and base models used throughout the CodeWeaver project."""

from __future__ import annotations

import types as _types


MappingProxyType = _types.MappingProxyType

from codeweaver.core.types.provider import (
    LiteralProvider,
    LiteralProviderCategory,
    LiteralSDKClient,
)
from codeweaver.core.types.service_cards import (
    ProviderCategoryLiteralString,
    ProviderLiteralString,
    SDKClientLiteralString,
)


type LiteralProviderCategoryType = ProviderCategoryLiteralString | LiteralProviderCategory

type LiteralProviderType = ProviderLiteralString | LiteralProvider

type LiteralSDKClientType = SDKClientLiteralString | LiteralSDKClient

# === MANAGED EXPORTS ===

# Exportify manages this section. It contains lazy-loading infrastructure
# for the package: imports and runtime declarations (__all__, __getattr__,
# __dir__). Manual edits will be overwritten by `exportify fix`.

from typing import TYPE_CHECKING

from lateimport import create_late_getattr


if TYPE_CHECKING:
    from codeweaver.core.types.aliases import (
        Annotated,
        BlakeHashKey,
        BlakeKey,
        CategoryName,
        CategoryNameT,
        DevToolName,
        DevToolNameT,
        DirectoryName,
        DirectoryNameT,
        DirectoryPath,
        DirectoryPathT,
        EmbeddingModelName,
        EmbeddingModelNameT,
        FileExt,
        FileExtensionT,
        FileGlob,
        FileGlobT,
        FileName,
        FileNameT,
        FilePath,
        FilePathT,
        FilteredKey,
        FilteredKeyT,
        GetPydanticSchema,
        LanguageName,
        LanguageNameT,
        LiteralString,
        LiteralStringT,
        LlmToolName,
        LlmToolNameT,
        ModelName,
        ModelNameT,
        NewType,
        Path,
        PathLike,
        RerankingModelName,
        RerankingModelNameT,
        Role,
        RoleT,
        SentinelName,
        SentinelNameT,
        ThingName,
        ThingNameT,
        ThingOrCategoryNameT,
        UUID7Hex,
        UUID7HexT,
    )
    from codeweaver.core.types.dataclasses import (
        DATACLASS_CONFIG,
        AnonymityConversion,
        Any,
        BaseEnumData,
        Callable,
        ConfigDict,
        DataclassSerializationMixin,
        DeserializationKwargs,
        IncEx,
        Iterator,
        Literal,
        NotRequired,
        PrivateAttr,
        Self,
        Sequence,
        SerializationKwargs,
        TypeAdapter,
        TypedDict,
        Unpack,
        cached_property,
        cast,
        dataclass,
        generate_field_title,
        generate_title,
    )
    from codeweaver.core.types.delimiter import (
        LANGUAGE_TO_FAMILY,
        BaseEnum,
        DelimiterDict,
        DelimiterKind,
        DelimiterPattern,
        LanguageFamily,
        LineStrategy,
        NamedTuple,
        PositiveInt,
        Required,
        textcase,
    )
    from codeweaver.core.types.dictview import (
        TYPE_CHECKING,
        DictView,
        ItemsView,
        KeysView,
        Mapping,
        MappingProxyType,
        ValuesView,
    )
    from codeweaver.core.types.embeddings import (
        UUID7,
        BasedModel,
        ChunkEmbeddings,
        CodeWeaverSparseEmbedding,
        DataType,
        EmbeddingBatchInfo,
        EmbeddingKind,
        NonNegativeInt,
        Provider,
        QueryResult,
        RawEmbeddingVectors,
        SparseEmbedding,
        StoredEmbeddingVectors,
        override,
    )
    from codeweaver.core.types.enum import (
        BaseDataclassEnum,
        Enum,
        FilteredCallable,
        FilteredReturn,
        Generator,
        auto,
        computed_field,
        contextlib,
        unique,
    )
    from codeweaver.core.types.env import EnvFormat, EnvVarInfo, ProviderEnvVars, VariableInfo
    from codeweaver.core.types.models import (
        BASEDMODEL_CONFIG,
        FILTERED_KEYS,
        FROZEN_BASEDMODEL_CONFIG,
        BaseModel,
        RootedRoot,
        RootModel,
        abc,
        clean_sentinel_from_schema,
    )
    from codeweaver.core.types.provider import (
        Iterable,
        LiteralProvider,
        LiteralProviderCategory,
        LiteralSDKClient,
        ProviderCategory,
        SDKClient,
        get_categories,
        get_default_provider_import_for_category,
        os,
    )
    from codeweaver.core.types.search import (
        AfterValidator,
        CodeChunk,
        DiscoveredFile,
        Metadata,
        NonNegativeFloat,
        SearchResult,
        SearchStrategy,
        StrategizedQuery,
        set_relative_path,
    )
    from codeweaver.core.types.sentinel import (
        MISSING,
        UNSET,
        DontGenerateJsonSchema,
        FrameType,
        GenerateJsonSchema,
        GetCoreSchemaHandler,
        GetJsonSchemaHandler,
        JsonSchemaValue,
        Missing,
        PydanticOmit,
        Sentinel,
        Unset,
        core_schema,
    )
    from codeweaver.core.types.service_cards import (
        Coroutine,
        ProviderCategoryLiteralString,
        ProviderLiteralString,
        SDKClientLiteralString,
        ServiceCard,
        ServiceMetadata,
        asyncio,
        cache,
        defaultdict,
        get_local_only_provider_members,
        get_local_only_providers,
        get_openai_provider_members,
        get_openai_providers,
        get_provider_capabilities_map,
        get_provider_category_sdk_clients_for_provider,
        get_provider_clients,
        get_provider_literals,
        get_providers_for_category,
        get_sdk_client,
        get_sdk_client_map,
        get_service_card,
        get_service_cards,
        get_sometimes_local_provider_members,
        get_sometimes_local_providers,
        has_package,
        overload,
        re,
        service_card_factory,
    )
    from codeweaver.core.types.settings_model import (
        DEFAULT_BASE_SETTINGS_CONFIG,
        BaseCodeWeaverSettings,
        BaseSettings,
        SettingsConfigDict,
    )
    from codeweaver.core.types.statistics import (
        AnyUrl,
        CallHookTimingDict,
        CategoryKey,
        HttpRequestsDict,
        McpComponentRequests,
        McpComponentTimingDict,
        McpOperationRequests,
        McpTimingDict,
        OperationsKey,
        RequestKind,
        ResourceUri,
        SummaryKey,
        TimingStatisticsDict,
        ToolOrPromptName,
    )
    from codeweaver.core.types.utils import (
        ComputedFieldInfo,
        DynamicClassAttribute,
        FieldInfo,
        add_enum_alias,
        add_enum_member,
        platform,
    )

_dynamic_imports: MappingProxyType[str, tuple[str, str]] = MappingProxyType({
    "BASEDMODEL_CONFIG": (__spec__.parent, "models"),
    "DATACLASS_CONFIG": (__spec__.parent, "dataclasses"),
    "DEFAULT_BASE_SETTINGS_CONFIG": (__spec__.parent, "settings_model"),
    "FILTERED_KEYS": (__spec__.parent, "models"),
    "FROZEN_BASEDMODEL_CONFIG": (__spec__.parent, "models"),
    "LANGUAGE_TO_FAMILY": (__spec__.parent, "delimiter"),
    "MISSING": (__spec__.parent, "sentinel"),
    "TYPE_CHECKING": (__spec__.parent, "dictview"),
    "UNSET": (__spec__.parent, "sentinel"),
    "AfterValidator": (__spec__.parent, "search"),
    "Annotated": (__spec__.parent, "aliases"),
    "AnonymityConversion": (__spec__.parent, "dataclasses"),
    "Any": (__spec__.parent, "dataclasses"),
    "AnyUrl": (__spec__.parent, "statistics"),
    "BaseCodeWeaverSettings": (__spec__.parent, "settings_model"),
    "BaseDataclassEnum": (__spec__.parent, "enum"),
    "BasedModel": (__spec__.parent, "embeddings"),
    "BaseEnum": (__spec__.parent, "delimiter"),
    "BaseEnumData": (__spec__.parent, "dataclasses"),
    "BaseModel": (__spec__.parent, "models"),
    "BaseSettings": (__spec__.parent, "settings_model"),
    "BlakeHashKey": (__spec__.parent, "aliases"),
    "BlakeKey": (__spec__.parent, "aliases"),
    "Callable": (__spec__.parent, "dataclasses"),
    "CallHookTimingDict": (__spec__.parent, "statistics"),
    "CategoryName": (__spec__.parent, "aliases"),
    "ChunkEmbeddings": (__spec__.parent, "embeddings"),
    "CodeChunk": (__spec__.parent, "search"),
    "CodeWeaverSparseEmbedding": (__spec__.parent, "embeddings"),
    "ComputedFieldInfo": (__spec__.parent, "utils"),
    "ConfigDict": (__spec__.parent, "dataclasses"),
    "Coroutine": (__spec__.parent, "service_cards"),
    "DataclassSerializationMixin": (__spec__.parent, "dataclasses"),
    "DataType": (__spec__.parent, "embeddings"),
    "DelimiterDict": (__spec__.parent, "delimiter"),
    "DelimiterKind": (__spec__.parent, "delimiter"),
    "DelimiterPattern": (__spec__.parent, "delimiter"),
    "DeserializationKwargs": (__spec__.parent, "dataclasses"),
    "DevToolName": (__spec__.parent, "aliases"),
    "DictView": (__spec__.parent, "dictview"),
    "DirectoryName": (__spec__.parent, "aliases"),
    "DiscoveredFile": (__spec__.parent, "search"),
    "DontGenerateJsonSchema": (__spec__.parent, "sentinel"),
    "DynamicClassAttribute": (__spec__.parent, "utils"),
    "EmbeddingBatchInfo": (__spec__.parent, "embeddings"),
    "EmbeddingKind": (__spec__.parent, "embeddings"),
    "EmbeddingModelName": (__spec__.parent, "aliases"),
    "Enum": (__spec__.parent, "enum"),
    "EnvFormat": (__spec__.parent, "env"),
    "EnvVarInfo": (__spec__.parent, "env"),
    "Field": (__spec__.parent, "aliases"),
    "FieldInfo": (__spec__.parent, "utils"),
    "FileExt": (__spec__.parent, "aliases"),
    "FileGlob": (__spec__.parent, "aliases"),
    "FileName": (__spec__.parent, "aliases"),
    "FilteredKey": (__spec__.parent, "aliases"),
    "FrameType": (__spec__.parent, "sentinel"),
    "GenerateJsonSchema": (__spec__.parent, "sentinel"),
    "Generator": (__spec__.parent, "enum"),
    "GetCoreSchemaHandler": (__spec__.parent, "sentinel"),
    "GetJsonSchemaHandler": (__spec__.parent, "sentinel"),
    "GetPydanticSchema": (__spec__.parent, "aliases"),
    "HttpRequestsDict": (__spec__.parent, "statistics"),
    "IncEx": (__spec__.parent, "dataclasses"),
    "ItemsView": (__spec__.parent, "dictview"),
    "Iterable": (__spec__.parent, "provider"),
    "Iterator": (__spec__.parent, "dataclasses"),
    "JsonSchemaValue": (__spec__.parent, "sentinel"),
    "KeysView": (__spec__.parent, "dictview"),
    "LanguageFamily": (__spec__.parent, "delimiter"),
    "LanguageName": (__spec__.parent, "aliases"),
    "LineStrategy": (__spec__.parent, "delimiter"),
    "Literal": (__spec__.parent, "dataclasses"),
    "LiteralString": (__spec__.parent, "aliases"),
    "LlmToolName": (__spec__.parent, "aliases"),
    "Mapping": (__spec__.parent, "dictview"),
    "MappingProxyType": (__spec__.parent, "dictview"),
    "McpComponentTimingDict": (__spec__.parent, "statistics"),
    "McpTimingDict": (__spec__.parent, "statistics"),
    "Metadata": (__spec__.parent, "search"),
    "Missing": (__spec__.parent, "sentinel"),
    "ModelName": (__spec__.parent, "aliases"),
    "NamedTuple": (__spec__.parent, "delimiter"),
    "NewType": (__spec__.parent, "aliases"),
    "NonNegativeFloat": (__spec__.parent, "search"),
    "NonNegativeInt": (__spec__.parent, "embeddings"),
    "NotRequired": (__spec__.parent, "dataclasses"),
    "Path": (__spec__.parent, "aliases"),
    "PathLike": (__spec__.parent, "aliases"),
    "PositiveInt": (__spec__.parent, "delimiter"),
    "PrivateAttr": (__spec__.parent, "dataclasses"),
    "Provider": (__spec__.parent, "embeddings"),
    "ProviderCategory": (__spec__.parent, "provider"),
    "ProviderEnvVars": (__spec__.parent, "env"),
    "PydanticOmit": (__spec__.parent, "sentinel"),
    "QueryResult": (__spec__.parent, "embeddings"),
    "Required": (__spec__.parent, "delimiter"),
    "RerankingModelName": (__spec__.parent, "aliases"),
    "Role": (__spec__.parent, "aliases"),
    "RootedRoot": (__spec__.parent, "models"),
    "RootModel": (__spec__.parent, "models"),
    "SearchResult": (__spec__.parent, "search"),
    "SearchStrategy": (__spec__.parent, "search"),
    "Self": (__spec__.parent, "dataclasses"),
    "Sentinel": (__spec__.parent, "sentinel"),
    "SentinelName": (__spec__.parent, "aliases"),
    "SentinelNameT": (__spec__.parent, "aliases"),
    "Sequence": (__spec__.parent, "dataclasses"),
    "SerializationKwargs": (__spec__.parent, "dataclasses"),
    "ServiceCard": (__spec__.parent, "service_cards"),
    "ServiceMetadata": (__spec__.parent, "service_cards"),
    "SettingsConfigDict": (__spec__.parent, "settings_model"),
    "SparseEmbedding": (__spec__.parent, "embeddings"),
    "StrategizedQuery": (__spec__.parent, "search"),
    "ThingName": (__spec__.parent, "aliases"),
    "TimingStatisticsDict": (__spec__.parent, "statistics"),
    "TypeAdapter": (__spec__.parent, "dataclasses"),
    "TypedDict": (__spec__.parent, "dataclasses"),
    "Unpack": (__spec__.parent, "dataclasses"),
    "Unset": (__spec__.parent, "sentinel"),
    "ValuesView": (__spec__.parent, "dictview"),
    "VariableInfo": (__spec__.parent, "env"),
    "abc": (__spec__.parent, "models"),
    "add_enum_alias": (__spec__.parent, "utils"),
    "add_enum_member": (__spec__.parent, "utils"),
    "asyncio": (__spec__.parent, "service_cards"),
    "auto": (__spec__.parent, "enum"),
    "cache": (__spec__.parent, "service_cards"),
    "cached_property": (__spec__.parent, "dataclasses"),
    "cast": (__spec__.parent, "dataclasses"),
    "clean_sentinel_from_schema": (__spec__.parent, "models"),
    "computed_field": (__spec__.parent, "enum"),
    "contextlib": (__spec__.parent, "enum"),
    "core_schema": (__spec__.parent, "sentinel"),
    "dataclass": (__spec__.parent, "dataclasses"),
    "defaultdict": (__spec__.parent, "service_cards"),
    "generate_field_title": (__spec__.parent, "dataclasses"),
    "generate_title": (__spec__.parent, "dataclasses"),
    "get_categories": (__spec__.parent, "provider"),
    "get_default_provider_import_for_category": (__spec__.parent, "provider"),
    "get_local_only_provider_members": (__spec__.parent, "service_cards"),
    "get_local_only_providers": (__spec__.parent, "service_cards"),
    "get_openai_provider_members": (__spec__.parent, "service_cards"),
    "get_openai_providers": (__spec__.parent, "service_cards"),
    "get_provider_capabilities_map": (__spec__.parent, "service_cards"),
    "get_provider_category_sdk_clients_for_provider": (__spec__.parent, "service_cards"),
    "get_provider_clients": (__spec__.parent, "service_cards"),
    "get_provider_literals": (__spec__.parent, "service_cards"),
    "get_providers_for_category": (__spec__.parent, "service_cards"),
    "get_sdk_client": (__spec__.parent, "service_cards"),
    "get_sdk_client_map": (__spec__.parent, "service_cards"),
    "get_service_card": (__spec__.parent, "service_cards"),
    "get_service_cards": (__spec__.parent, "service_cards"),
    "get_sometimes_local_provider_members": (__spec__.parent, "service_cards"),
    "get_sometimes_local_providers": (__spec__.parent, "service_cards"),
    "has_package": (__spec__.parent, "service_cards"),
    "os": (__spec__.parent, "provider"),
    "overload": (__spec__.parent, "service_cards"),
    "override": (__spec__.parent, "embeddings"),
    "platform": (__spec__.parent, "utils"),
    "re": (__spec__.parent, "service_cards"),
    "SDKClient": (__spec__.parent, "provider"),
    "service_card_factory": (__spec__.parent, "service_cards"),
    "set_relative_path": (__spec__.parent, "search"),
    "textcase": (__spec__.parent, "delimiter"),
    "unique": (__spec__.parent, "enum"),
    "UUID7": (__spec__.parent, "embeddings"),
    "UUID7Hex": (__spec__.parent, "aliases"),
    "UUID7HexT": (__spec__.parent, "aliases"),
})

__getattr__ = create_late_getattr(_dynamic_imports, globals(), __name__)

__all__ = (
    "BASEDMODEL_CONFIG",
    "DATACLASS_CONFIG",
    "DEFAULT_BASE_SETTINGS_CONFIG",
    "FILTERED_KEYS",
    "FROZEN_BASEDMODEL_CONFIG",
    "LANGUAGE_TO_FAMILY",
    "MISSING",
    "TYPE_CHECKING",
    "UNSET",
    "UUID7",
    "AfterValidator",
    "Annotated",
    "AnonymityConversion",
    "Any",
    "AnyUrl",
    "BaseCodeWeaverSettings",
    "BaseDataclassEnum",
    "BaseEnum",
    "BaseEnumData",
    "BaseModel",
    "BaseSettings",
    "BasedModel",
    "BlakeHashKey",
    "BlakeKey",
    "CallHookTimingDict",
    "Callable",
    "CategoryKey",
    "CategoryName",
    "CategoryNameT",
    "ChunkEmbeddings",
    "CodeChunk",
    "CodeWeaverSparseEmbedding",
    "ComputedFieldInfo",
    "ConfigDict",
    "Coroutine",
    "DataType",
    "DataclassSerializationMixin",
    "DelimiterDict",
    "DelimiterKind",
    "DelimiterPattern",
    "DeserializationKwargs",
    "DevToolName",
    "DevToolNameT",
    "DictView",
    "DirectoryName",
    "DirectoryNameT",
    "DirectoryPath",
    "DirectoryPathT",
    "DiscoveredFile",
    "DontGenerateJsonSchema",
    "DynamicClassAttribute",
    "EmbeddingBatchInfo",
    "EmbeddingKind",
    "EmbeddingModelName",
    "EmbeddingModelNameT",
    "Enum",
    "EnvFormat",
    "EnvVarInfo",
    "Field",
    "FieldInfo",
    "FileExt",
    "FileExtensionT",
    "FileGlob",
    "FileGlobT",
    "FileName",
    "FileNameT",
    "FilePath",
    "FilePathT",
    "FilteredCallable",
    "FilteredKey",
    "FilteredKeyT",
    "FilteredReturn",
    "FrameType",
    "GenerateJsonSchema",
    "Generator",
    "GetCoreSchemaHandler",
    "GetJsonSchemaHandler",
    "GetPydanticSchema",
    "HttpRequestsDict",
    "IncEx",
    "ItemsView",
    "Iterable",
    "Iterator",
    "JsonSchemaValue",
    "KeysView",
    "LanguageFamily",
    "LanguageName",
    "LanguageNameT",
    "LineStrategy",
    "Literal",
    "LiteralProvider",
    "LiteralProviderCategory",
    "LiteralProviderCategoryType",
    "LiteralProviderType",
    "LiteralSDKClient",
    "LiteralSDKClientType",
    "LiteralString",
    "LiteralStringT",
    "LlmToolName",
    "LlmToolNameT",
    "Mapping",
    "MappingProxyType",
    "McpComponentRequests",
    "McpComponentTimingDict",
    "McpOperationRequests",
    "McpTimingDict",
    "Metadata",
    "Missing",
    "ModelName",
    "ModelNameT",
    "NamedTuple",
    "NewType",
    "NonNegativeFloat",
    "NonNegativeInt",
    "NotRequired",
    "OperationsKey",
    "Path",
    "PathLike",
    "PositiveInt",
    "PrivateAttr",
    "Provider",
    "ProviderCategory",
    "ProviderCategoryLiteralString",
    "ProviderEnvVars",
    "ProviderLiteralString",
    "PydanticOmit",
    "QueryResult",
    "RawEmbeddingVectors",
    "RequestKind",
    "Required",
    "RerankingModelName",
    "RerankingModelNameT",
    "ResourceUri",
    "Role",
    "RoleT",
    "RootModel",
    "RootedRoot",
    "SDKClient",
    "SDKClientLiteralString",
    "SearchResult",
    "SearchStrategy",
    "Self",
    "Sentinel",
    "SentinelName",
    "SentinelNameT",
    "Sequence",
    "SerializationKwargs",
    "ServiceCard",
    "ServiceMetadata",
    "SettingsConfigDict",
    "SparseEmbedding",
    "StoredEmbeddingVectors",
    "StrategizedQuery",
    "SummaryKey",
    "ThingName",
    "ThingNameT",
    "ThingOrCategoryNameT",
    "TimingStatisticsDict",
    "ToolOrPromptName",
    "TypeAdapter",
    "TypedDict",
    "UUID7Hex",
    "UUID7HexT",
    "Unpack",
    "Unset",
    "ValuesView",
    "VariableInfo",
    "abc",
    "add_enum_alias",
    "add_enum_member",
    "asyncio",
    "auto",
    "cache",
    "cached_property",
    "cast",
    "clean_sentinel_from_schema",
    "computed_field",
    "contextlib",
    "core_schema",
    "dataclass",
    "defaultdict",
    "generate_field_title",
    "generate_title",
    "get_categories",
    "get_default_provider_import_for_category",
    "get_local_only_provider_members",
    "get_local_only_providers",
    "get_openai_provider_members",
    "get_openai_providers",
    "get_provider_capabilities_map",
    "get_provider_category_sdk_clients_for_provider",
    "get_provider_clients",
    "get_provider_literals",
    "get_providers_for_category",
    "get_sdk_client",
    "get_sdk_client_map",
    "get_service_card",
    "get_service_cards",
    "get_sometimes_local_provider_members",
    "get_sometimes_local_providers",
    "has_package",
    "os",
    "overload",
    "override",
    "platform",
    "re",
    "service_card_factory",
    "set_relative_path",
    "textcase",
    "unique",
)


def __dir__() -> list[str]:
    """List available attributes for the package."""
    return list(__all__)
